include::../../variables.adoc[]
= {PRODUCT_NAME} Permission System

One of the main focuses when working with any kind of data in the enterprise environment is the data integrity and security, especially when working with sensitive information.
{PRODUCT_NAME} takes this seriously and defines a powerful permission system that allows you to control access to any resource, being an application or a single module field.

{PRODUCT_NAME} is based on users and user roles, where a single user can be a member of multiple roles, where each role defines its own set of access control.

[NOTE]
====
Resource level permissions are described in detail in the following sections.
This section merely outlines the system.
====

Each permission can be in one of the following states:

Inherit::
    To use the value that was defined under the "Everyone" virtual role,
Allow::
    To allow the role to perform the operation over a specified resource,
Deny::
    To deny the role to perform the operation over a specified resource.

[IMPORTANT]
====
It's good practice to limit system users a much as possible to avoid potential security breaches.
====
