include::../variables.adoc[]

= {APP_AUTOMATION}

Main component, responsible for {PRODUCT_NAME} automation is {APP_AUTOMATION}.
It's a Node.js application responsible for processing, serving, executing and compiling (transpiling and bundling) of automation scripts.

It allows developers to write custom scripts and components that can modify default behaviour, change user interface and add extra capabilities to {PRODUCT_NAME}.

These automation scripts are written in JavaScript and executed in a save, containerised environment, but as with any system, automation scripts can cause unwanted complications if misused or left open for modification by users who may do harm, willingly or otherwise.
You (or whoever will configure this system) is responsible for making sure scripts are written in a way that do not cause problems to users or the underlying system running them.


== Terminology

Extension::
    Collection of automation scripts

Script or Automation Script::
    Combination of code, triggers, description, label.
    There is usually one automation script per file by convention and readability.

Client scripts::
    Are always executed inside a client (browser)
    These scripts can be considered more flexible in terms of interaction and the ability to modify the user interface.

Server scripts::
    Are always executed on the backend (server).
    These scripts can be considered more secure and stable.

Triggers or Automation Triggers::
    Set of rules, constraints and options that help {APP_AUTOMATION} and it's implementations reference a specific event type (like `beforeUpdate`), resource type (like `compose:record`).

Resource Type::
    Predefined list of well-known types: `compose`, `compose:record`, `messaging:message`, `system:user`, …
    Resource types also determine input data for execution script.

Event Type::
    Each resource type comes with the set of event types ( `onManual`, `beforeUpdate`, `afterDelete`, `beforeUpdate`, `onRequest`, `onLogin`)
    Event types are prefixed with `on` or `before` and `after` (`on...` is always single and `before...`/`after...` always come in pairs).

Trigger constraints::
    Constraints vary by resource type and help to filter list of scripts or configure the scheduling system (deferred scripts)

Trigger weight::
    When registering in the eventbus (client or server side) scripts are executed order configured through triggers via weight.
    Scripts with the same weight are ordered by name (alphabetically) - not name of the script file but full path

User interface properties (UIProps)::
    Help with placement, label and look of automation button on user interface

Explicitly triggered or manual scripts::
    When user clicks on a button to execute a specific script (`onManual`)

Implicitly triggered scripts::
    When a set of matching scripts are executed as a result of some action (record is updated, user signs in, ...)

Deferred or scheduled scripts::
    When script is triggered on a certain date and time (`onTimestamp`) or on configured interval (`onInterval`).

Eventbus::
    Event handling system inside client web applications and on the server (2 independent systems with very similar behaviour)
    When event is dispatched through eventbus it looks for a registered handler and runs it.

UIHooks::
    Handles scripts that can be triggered explicitly (onManual) in form of buttons.
    These buttons are then automatically placed in the various UI slots in the client app (login screen, list of users, etc...)



== Security context

Script can be configured to be executed with security context of the user triggering the event or with security context of a predefined user.

.Example scenario:
* User creates a Client record in Compose. This triggers a script that create a new user.
User creation is only allowed to administrators and script can be ran with privileges of an administrator


Events that are not triggered directly by authenticated user

@todo combination of resource and event types require defined user - any event that is not triggered


== {APP_AUTOMATION} server

{APP_AUTOMATION} is a Node.js server running in the background.
{PRODUCT_NAME} server connects to it via gRPC protocol to get list of scripts and executes them.

.Responsible for:
1. Scanning configured search paths (`config.extensions.searchPaths`) for scripts and dependency definition files (`package.json`)
2. To load and inspect each found script, parse triggers, record errors and prepare a final list of valid and invalid (containing errors) scripts
3. Run dependency management tool (`yarn`) to load all extension depenencies
4. Run file change watchers that rebuild list of scripts
5. Run frontend JavaScript compiler (WebPack) that bundles all frontend scripts
6. Run gRPC server that serves list of scripts, bundles and executes server-scripts upon request.

.Not responsible for:
1. Trigger and/or event matching
2. Interval/scheduled/deferred script triggering


== Directory structure, files and naming conventions

=== Server scripts
`/server-scripts/<path-to-script.js>`

You can structure your scripts under `/server-scripts` as deep as you want.

=== Client scripts:

`/client-scripts/<bundle-name>/<path-to-script.js>`

You can structure your scripts under `/client-scripts` as deep as you want.

Bundle name represents one of the web applications in the {PRODUCT_NAME} suite that utilize the automation wiht client scripts.
All scripts that belong to an application must be grouped in a subdirectory (admin, auth, compose, messaging).


=== Extensions, search paths and overriding

{APP_AUTOMATION} supports multiple search paths: you can provide different locations where {APP_AUTOMATION} can look for scripts.

By default, {APP_AUTOMATION} is configured with 2 search paths: `./usr/*` and `./usr`.
This setting allows you to stack multiple extensions in one location along with custom set of scripts.

Corredor cuts off the base path (part of search-path) to enable:

 a. easier migration of scripts to another location (different path on the server)
 b. ability to override scripts in the following search-paths

Ability to override also opens the possibility of unwanted behaviour. To avoid this, we recommend that
name of the extension is repeated in the path under scripts:

.Example:
```
./usr/crm/server-scripts/crm/Case/SetLabel.js
./usr/crm/client-scripts/compose/crm/Account/SetAddress.js
```

Path in the example, follows pattern where extension name is repeated once again under the scripts directory to create
unique path: `/server-scripts/crm/Case/SetLabel.js` and `/client-scripts/compose/crm/Account/SetAddress.js` respectively.

With this, developer can add a new script in `./usr/server-scripts/Case/SetLabel.js` without interfering with `crm` extension
or add `./usr/server-scripts/crm/Case/SetLabel.js` when she wants to fully override the script from the `crm` extension.

{APP_AUTOMATION} itself does not know (by design) about extensions other than through additional directories in the path to script.


=== Script tests

`.../<path-to-script.test.js>`

Automation script tests should be located next to each script, using '.test.js' suffix (i.e: `foo.js` should have `foo.test.js` for tests).

. Some recommendations from {PRODUCT_NAME} engineering team:
 - Add at least one basic test per automation script
 - Write your scripts in way that you can add unit tests where external resources can be replaced with mocks.
   This way your tests can be executed fast and without changing the actual data.


== Scenarios

How automation works

. When {APP_AUTOMATION} server starts, it
.. scans all search paths from config and load all scripts
.. scans all package.json in all search paths and install all additional packages
.. runs file-change watchers for script reloading
.. runs file-change watchers for package.json

. When {PRODUCT_NAME} server starts, it
.. connects to {APP_AUTOMATION} (via gRPC) and loads all server and client scripts
.. creates event handlers from server scripts' triggers and registers them in the EventBus
.. configures scheduler to trigger both `onTimestamp` and `onInterval` events once per minute at the minute

. When scheduling system on {PRODUCT_NAME} server ticks (once per minute), it
.. dispatches event through EventBus
.. checks for registered events and their constraints are compatible
.. requests from {APP_AUTOMATION} to execute the compatible (matching) script

. When {PRODUCT_NAME} web application loads in a browser, it
.. loads appropriate bundle from {PRODUCT_NAME} system API
.. registers client scripts from the bundle in the UIHooks and EventBus system on client

. When user clicks on an automation button (explicitly triggered *client* script) provided via UIHooks system or configured on compose's page-block, it
.. generates event from the given configuration and button clicked
.. passes generated event and script name from the button to eventbus
.. it runs the registered handler (never more than one) that executes the script in the browser context (client-side)

. When user clicks on an automation button (explicitly triggered *server* script), it
.. generates event from the given configuration and button clicked
.. passes generated event and script name from the button to eventbus
.. it runs the registered handler (never more than one) that sends event and any arguments to the server via REST API and from there to the {APP_AUTOMATION} server via gRPC

. When user indirectly runs automation script via some action in the *client* app (implicitly triggered *client* scripts), it
.. raises a specific event (`onSomething`, `beforeSomethingElse`, `afterSomethingElse`) and dispatches it through eventbus
.. executes all matching event handlers (and subsequently, scripts) in the browser context (client-side)

. When user indirectly runs automation script via some action on the *server* (implicitly triggered *server* scripts)
.. raises a specific event (`onSomething`, `beforeSomethingElse`, `afterSomethingElse`) and dispatches it through eventbus
.. executes all matching event handlers (and subsequently, scripts)

. When request is sent to `/sink` endpoint
.. it searches for all registered handlers for `onRequest` event and executes it

