include::ROOT:partial$variables.adoc[]

= API clients

*API clients* define an SDK to work with {PRODUCT_NAME} API.
They are provided in the *execution context* (here: `exec(args, ctx)` -- see <<script-execution>>).

.Available {PRODUCT_NAME} API clients:
* https://github.com/cortezaproject/corteza-js/blob/2020.12.x/src/api-clients/system.ts[System]
* https://github.com/cortezaproject/corteza-js/blob/2020.12.x/src/api-clients/messaging.ts[Messaging]
* https://github.com/cortezaproject/corteza-js/blob/2020.12.x/src/api-clients/compose.ts[Compose]
* https://github.com/cortezaproject/corteza-js/blob/2020.12.x/src/api-clients/federation.ts[Federation]

[TIP]
====
*All API operations* are achievable via these clients.
====

[NOTE]
====
*DevNote* extract methods here?
====

The API clients simplify the process of interacting with our API.
The source resides in the https://github.com/cortezaproject/corteza-js/tree/2020.12.x/src/api-clients[corteza-js] repository, and available under `apiClients` in the https://www.npmjs.com/package/@cortezaproject/corteza-js[NPM package].

* `apiClients.system` provides a client to work with *the core system*
* `apiClients.compose` provides a client to work with *compose*
* `apiClients.messaging` provides a client to work with *messaging*
* `apiClients.federation` provides a client to work with *federation*

The API clients handle all of the annoying little details, such as proper error handling, authentication, request headers, and response type casting.

[NOTE]
====
Currently, we only provide JavaScript API clients to cover our use-cases.
Additional language will be covered if need be.
====
