include::ROOT:partial$variables.adoc[]

= Templates
:description: Templates allow you to define the generic structure of a document (such as a welcome email message or a quote PDF) which is then converted into an actual document based on the provided data.

Templates allow you to define the generic structure of a document (such as a welcome email message or a quote PDF) which is then converted into an actual document based on the provided data.

If you wish to learn more about a specific topic, refer to the subsections under menu:Integrator Guide[Templates].

== Creating a template

Templates are created and managed in the {PRODUCT_NAME} {APP_NAME_ADMIN}.

Navigate to the menu:System[Templates] and click on the btn:[New] button in the top-right corner.

Enter the basic information; short name, handle, description, and template type.
The template type determines the format of the template and implicitly implies what document types the template can render to.

A partial template is used as part of another template (for example; a generic header or a footer) and can not be rendered on it's own.
The template can be converted from and to a partial template.

Click on the btn:[Submit] button to prepare your template.

After you submit the base parameters, three new sections will appear.

[cols="1s,5a"]
|===

| [#templates-toolbox]#<<templates-toolbox,Toolbox>>#
|
The toolbox provides snippets for the most common operations, HTML template sample, and partial inclusion samples.

| [#templates-content]#<<templates-content,Template content>>#
|
The template content editor provides a simple code editor to edit your template.
The HTML template editor implements syntax highlighting and some other useful tools.

| [#templates-preview]#<<templates-preview,Preview>>#
|
The preview section allows you to test how your templates will look like when rendered into an actual document.

[IMPORTANT]
====
Refer to the xref:templates/pdf.adoc[] section to setup PDF rendering.
====

|===

== The content

[NOTE]
====
Advanced users are welcome to checkout the https://golang.org/pkg/text/template/[plain text template full reference], the https://golang.org/pkg/html/template/[html template full reference], and the https://masterminds.github.io/sprig/[extended function docs].
====

Let's start by copying the default HTML sample from the toolbox.

[source,html]
----
<!DOCTYPE html>
<html>
<head>
  <meta charset='utf-8'>
  <meta http-equiv='X-UA-Compatible' content='IE=edge'>
  <title>Title</title>
  <meta name='viewport' content='width=device-width, initial-scale=1'>
</head>
<body>
  <h1>Hello, world!</h1>
</body>
</html>
----

If you don't need any dynamic content (different name for different contacts) you can stop.
The above template is valid and can already be used.

If you need dynamic content, we need to cover a few more topics.

=== Value interpolation

Value interpolation allows you to define some placeholder that is then replaced with an actual value when the template is rendered.

In our case, this placeholder looks like this:

[source]
----
{{.name}}
----

The above placeholder will be replaced by the value under the `name` property from the provided `value` object.

Let's look at some examples.
Each example firstly defines the `value` object and then the placeholder.

.Example with a basic property:
[source]
----
{
  "name": "Jane"
}

{{.name}}
----

.Example with a nested property:
[source]
----
{
  "contact": {
    "details": {
      "name": "Jane"
    }
  }
}

{{.contact.details.name}}
----

A complete example would look like this:

.The provided data:
[source,json]
----
{
  "contact": {
    "details": {
      "firstName": "Jane",
      "lastName": "Doe"
    }
  }
}
----

.The template:
[source,html]
----
<!DOCTYPE html>
<html>
<head>
  <meta charset='utf-8'>
  <meta http-equiv='X-UA-Compatible' content='IE=edge'>
  <title>Title</title>
  <meta name='viewport' content='width=device-width, initial-scale=1'>
</head>
<body>
  <h1>Hello, {{.contact.details.firstName}} {{.contact.details.lastName}}!</h1>
</body>
</html>
----

=== Conditional rendering

Conditional rendering allows you to show or hide sections of the rendered document based on the input parameters.

.`if` statement:
[source]
----
{{if condition}}
  The condition was true.
{{end}}
----

.`if-else` statement:
[source]
----
{{if condition}}
  The condition was true.
{{else}}
  The condition was false.
{{end}}
----

.`if-else if-else` statement:
[source]
----
{{if condition}}
  The condition was true.
{{else if condition}}
  The other condition was true.
{{else}}
  Neither conditions were true.
{{end}}
----

The `condition` part is an expression that returns a single boolean value.
An example of an expression:

[source]
----
{{if .lead.cost > 1000}}
  The lead {{.lead.name}} was expensive!
{{end}}
----

.Logic operators:
[cols="1s,5a"]
|===

| [#tpl-syntax-and]#<<tpl-syntax-and,AND>>#
|
* *syntax*: `a && b`
* *notes*: Results as truthy if both `a` and `b` evaluate to `true`.

| [#tpl-syntax-or]#<<tpl-syntax-or,OR>>#
|
* *syntax*: `a \|\| b`
* *notes*: Results as truthy if either `a` or `b` evaluates to `true`.

| [#tpl-syntax-not]#<<tpl-syntax-not,NOT>>#
|
* *syntax*: `!a`
* *notes*: Results as truthy if `a` is `false` and vice-versa.

| [#tpl-syntax-eq]#<<tpl-syntax-eq,Equal>>#
|
* *syntax*: `a == b`
* *notes*: Results as truthy if `a` is equal to `b`.

| [#tpl-syntax-neq]#<<tpl-syntax-neq,Not equal>>#
|
* *syntax*: `a != b`
* *notes*: Results as truthy if `a` is not equal to `b`.

| [#tpl-syntax-lt]#<<tpl-syntax-lt,Less then>>#
|
* *syntax*: `a < b`
* *notes*: Results as truthy if `a` is less then `b`.

| [#tpl-syntax-gt]#<<tpl-syntax-gt,Greater then>>#
|
* *syntax*: `a > b`
* *notes*: Results as truthy if `a` is greater then `b`.

| [#tpl-syntax-let]#<<tpl-syntax-let,Less equal then>>#
|
* *syntax*: `a \<= b`
* *notes*: Results as truthy if `a` is less or equal to `b`.

| [#tpl-syntax-get]#<<tpl-syntax-get,Greater equal then>>#
|
* *syntax*: `a >= b`
* *notes*: Results as truthy if `a` is greater or equal to `b`.

|===

=== Handling lists

Our templates make it quite easy to work with lists of items.
For example, you would like to generate a quote with lots of line items.

The syntax for iterating over a list looks like this:

[source]
----
{{range .listOfItems}} 
  {{.itemName}}; {{.itemCost}}$
{{end}}
----

If you prefer to specify what variable the current item is stored into, use this syntax:

[source]
----
{{range $index, $item := .ListOfItems}}
  {{$item.itemName}}; {{$item.itemCost}}$
{{end}}
----

=== Using functions

Sometimes you will need to do some further processing the the data before it is rendered to the document.

Some lighter processing can be handled directly by the template engine.
More complex processing should be handled by the code that is requesting to render the template.

.A function is called like this:
[source]
----
{{functionName arg1 arg2 ... argN}}
----

The passed argument can be a constant or a property from the provided data.

Functions can also be chained.
When two functions are chained, the output of the left function is passed into the argument of the right function.

[source]
----
{{funcA | funcB | ... | funcN}}
----

.Most common function reference:
[cols="1s,5a"]
|===

| [#tpl-syntax-fref-len]#<<tpl-syntax-fref-len,Length of>>#
|
* *syntax*: `{{len listOfThings}}`
* *notes*: returns the number of items in the given `listOfThings`.

| [#tpl-syntax-fref-printf]#<<tpl-syntax-fref-printf,Format string>>#
|
* *syntax*: `{{printf "pattern goes here" arg1 arg2 ... argn}}`
* *notes*: returns the formatted string, following the provided pattern using the values provided as arguments.

| [#tpl-syntax-fref-inlineRemote]#<<tpl-syntax-fref-inlineRemote,Inline remote file>>#
|
* *syntax*: `{{inlineRemote "url goes here"}}`
* *notes*: returns the base64 encoded file denoted by the URL.
The string is formatted in the form of `data:\{mime-type};base64,\{encoded remote file}`.
Useful when attaching images to PDF documents.

| [#tpl-syntax-fref-trim]#<<tpl-syntax-fref-trim,Trim string>>#
|
* *syntax*: `{{trim "string goes here"}}`
* *notes*: removes any spaces from the start/end of the provided string.

| [#tpl-syntax-fref-trimSuffix]#<<tpl-syntax-fref-trimSuffix,Trim suffix from a string>>#
|
* *syntax*: `{{trimSuffix "suffix to remove here" "string goes here"}}`
* *notes*: removes the suffix from the given string.

| [#tpl-syntax-fref-trimPrefix]#<<tpl-syntax-fref-trimPrefix,Trim prefix from a string>>#
|
* *syntax*: `{{trimPrefix "prefix to remove here" "string goes here"}}`
* *notes*: removes the prefix from the given string.

| [#tpl-syntax-fref-upper]#<<tpl-syntax-fref-upper,To uppercase>>#
|
* *syntax*: `{{upper "string goes here"}}`
* *notes*: converts string to upper case.

| [#tpl-syntax-fref-lower]#<<tpl-syntax-fref-lower,To lowercase>>#
|
* *syntax*: `{{lower "string goes here"}}`
* *notes*: converts string to lower case.

|===

=== Using partials

Partials allow you to keep your documents consistent by using common headers and footers.
Partials can also be useful when displaying {PRODUCT_NAME}s' resources, such as displaying a record in a table.

.Partials are included like so:
[source]
----
{{template "partial_handle"}}
----

The `partial_handle` is the handle you used when you defined the partial.
For example:

[source]
----
{{template "email_general_header"}}
----

If your partial needs to access some data that was provided to the current template (the one that uses the partial), you need to provide the second argument to the partial inclusion process.

[source]
----
{{template "email_general_header" .property.to.pass}}
----

For example, if our data looks like this:

[source,json]
----
{
  "contact": {
    "values": {...}
  },
  "account": {
    "values": {...}
  }
}
----

If you want to pass the `contact` to the partial, you would include your partial like so:

[source]
----
{{template "partial_handle" .contact}}
----

If you wanted to pass all of the data to your partial, you would include your partial like so:

[source]
----
{{template "partial_handle" .}}
----

You would access the `contact` in your partial like so:

[source]
----
{{/* In case of the first example */}}
Hello {{.values.FirstName}}

{{/* In case of the second example */}}
Hello {{.contact.values.LastName}} of the {{.account.values.Name}}
----

// .Another interesting example is a partial that displays a record in a table:
// [source,html]
// ----
// <!-- handle: record_table_generic -->
// <table width="800" cellspacing="0" cellpadding="0" border="0">
//   <thead>
//     <tr>
//       <th>Field</th>
//       <th>Value</th>
//     </tr>
//   </thead>
//   <tbody>
// {{range $key, $value := .values}}
//     <tr>
//       <td>{{ $key }}</td>
// {{if $value }}
//       <td>{{ $value }}</td>
// {{else}}
//       <td>&nbsp;</td>
// {{end}}
//     </tr>
// {{end}}
    
//   </tbody>
// </table>
// ----

// The above example iterates over the `values` of the provided record and displays the key-value pair in the table.
// You would use the `record_table_generic` partial like so:

// [source,html]
// ----
// <h2 style="color: #568ba2;text-align: center;">
//   Record as a table example:
// </h2>

// {{template "record_table_generic" .account }}
// ----

// Note the `.account` at the end.
// This tells the template engine to use the value of the `account` parameter as the base object in the partial.

== The preview

The preview section at the bottom of the page allows you to check how your documents will look like once the template is rendered.

The input box should contain a valid JSON object (render payload) with two root properties; `variables` and `options`:

[source,json]
----
{
  "variables": {},<1>
  "options": {}<2>
}
----
<1> The `variables` parameter defines what data will be available when rendering the document.
The structure is not defined.
<2> The `options` parameter defines the rendering options and is currently only available for PDFs.

.An example of the render payload:
[source,json]
----
{
  "variables": {
    "param1": "value1",
    "param2": {
      "nestedParam1": "value2"
    }
  },
  "options": {
    "documentSize": "A4",
    "contentScale": "1",
    "orientation": "portrait",
    "margin": "0.3"
  }
}
----

.Complete render payload reference:
[cols="1s,5a"]
|===

| [#tpl-render-variables]#<<tpl-render-variables,`variables`>>#
|
* *type*: `Object<any>`
* *description*: the variables you wish to apply to the template.
For example, if you wish `{{testing}}` to work, you must pass `{"variables": {"testing": "some value"}}`.

| [#tpl-render-options_marginBottom]#<<tpl-render-options_marginBottom,`options.marginBottom`>>#
|
PDF only.

* *type*: `string< float; 0 >= n; inches >`
* *description*: controls the margin on the bottom of the page.

| [#tpl-render-options_marginLeft]#<<tpl-render-options_marginLeft,`options.marginLeft`>>#
|
PDF only.

* *type*: `string< float; 0 >= n; inches >`
* *description*: controls the margin on the left of the page.

| [#tpl-render-options_marginRight]#<<tpl-render-options_marginRight,`options.marginRight`>>#
|
PDF only.

* *type*: `string< float; 0 >= n; inches >`
* *description*: controls the margin on the right of the page.

| [#tpl-render-options_marginTop]#<<tpl-render-options_marginTop,`options.marginTop`>>#
|
PDF only.

* *type*: `string< float; 0 >= n; inches >`
* *description*: controls the margin on the top of the page.

| [#tpl-render-options_marginY]#<<tpl-render-options_marginY,`options.marginY`>>#
|
PDF only.

* *type*: `string< float; 0 >= n; inches >`
* *description*: controls the margin on the top and bottom of the page.

| [#tpl-render-options_marginX]#<<tpl-render-options_marginX,`options.marginX`>>#
|
PDF only.

* *type*: `string< float; 0 >= n; inches >`
* *description*: controls the margin on the left and right of the page.

| [#tpl-render-options_margin]#<<tpl-render-options_margin,`options.margin`>>#
|
PDF only.

* *type*: `string< float; 0 >= n; inches >`
* *description*: controls the margin on the left, right, top, and bottom of the page.

| [#tpl-render-options_documentSize]#<<tpl-render-options_documentSize,`options.documentSize`>>#
|
PDF only.

* *type*: `string<A0...A10, B0...B10, C0...C10, ANSI A, ANSI B, ANSI C, ANSI D, ANSI E, junior legal, letter, legal, tabloid>`
* *description*: The size of the document following the ISO216 standard for the A, B, and C series; ANSI standard for ANSI A, B, C, and D; and NA standards for the last few.

| [#tpl-render-options_documentWidth]#<<tpl-render-options_documentWidth,`options.documentWidth`>>#
|
PDF only.

* *type*: `string< float; 0 >= n; inches >`
* *description*: specifies the document width if none of the presets fit your needs.

| [#tpl-render-options_documentHeight]#<<tpl-render-options_documentHeight,`options.documentHeight`>>#
|
PDF only.

* *type*: `string< float; 0 >= n; inches >`
* *description*: specifies the document height if none of the presets fit your needs.

| [#tpl-render-options_contentScale]#<<tpl-render-options_contentScale,`options.contentScale`>>#
|
PDF only.

* *type*: `string< float; 0 >= n >`
* *description*: at what scale the document should be rendered; bigger number => bigger content.

[NOTE]
====
PDF documents are limited to `0 >= n \<= 8`
====

| [#tpl-render-options_orientation]#<<tpl-render-options_orientation,`options.orientation`>>#
|
PDF only.

* *type*: `string<landscape,portrait>`
* *description*: what orientation to render the document in.

|===
