include::ROOT:partial$variables.adoc[]

= Delaying and scheduling workflows

Another amazing feature of a workflow is that it allows you to schedule or delay its execution.
This can be a powerful tool when working with external services that throttle their API usage or when we want to perform some task in an interval, such as monthly subscription renewal.

To achieve this, we provide a delay step image:workflow/delay.svg[width=20px] and a deferred trigger image:workflow/trigger.svg[width=20px].

== Delay step

The delay step image:workflow/delay.svg[width=20px] allows you to explicitly pause the workflows' execution for a set period of time.

[CAUTION]
====
The delay step can cause the workflow to time out.
====

This type of delaying is common when working with APIs that throttle their access.
To examplify; let's say that the API allows 10 calls per minute and we wish to fetch 100 items.
We could do something like the following:

image:workflow/delay-example.svg[]

[NOTE]
====
If you want to wait for an action performed by a user (such as a confirmation), use a xref:workflows/index.adoc#user-interaction[prompt step] instead.
====

== Scheduling execution

Execution scheduling is performed by configuring the trigger image:workflow/trigger.svg[width=20px] to run in an <<deferred-interval,interval>> or at a specific <<deferred-timestamp,timestamp>>.

[cols="1s,5a"]
|===

| [#deferred-interval]#<<deferred-interval,Interval>>#
|
Performing a task in an interval can be a powerful tool as it allows you to define an interval in which the workflow executes.

A good example is a subscription service where it is necessary to renew the subscriptions of the clients once a month.
We define an interval that would execute the workflow each day, determine what clients need to be renewed that day and renew them.

image:workflow/interval-example.svg[]

[WARNING]
====
The form of the above example should not be used in production.
The actual workflow should implement error handling, transaction logging, and email notifications.
====

An interval is defined by specifying the resource as a system, and the event as an interval in the trigger configuration (click on the configuration icon image:workflow/cog.svg[width=20px]).

The interval is defined as a https://en.wikipedia.org/wiki/Cron[chron expression] and can be as flexible as you could ever want it to be.
You can also use https://crontab.guru/[this amazing tool] to verify that your expressions are valid.

.Common cron examples:
* every hour at minute 0: `0 * * * *`
* every 30 minutes (0 and 30): `0/30 * * * *`
* every day at the start of the day: `0 0 * * *`
* every month at the start of month: `0 0 1 * *`

[TIP]
====
You can define multiple intervals under the same trigger.
====

| [#deferred-timestamp]#<<deferred-timestamp,Timestamp>>#
|
Performing a task at a specific date and time can be another powerful tool in your toolbox as it allows you to define exactly when an action should be performed.

To illustrate; we've just received a new client that requested a series of deadlines where they would like to see the current progress.
We could define a scheduled workflow that is executed at each one of the timestamps.
The workflow would aggregate all of the completed tickets into an email and send it off to the client.

image:workflow/schedule-example.svg[]

A timestamps is defined in the https://en.wikipedia.org/wiki/ISO_8601[ISO 8601, `YYYY-MM-DDThh:mm:ssZ` format].

[TIP]
====
You can define multiple timestamps under the same trigger.
====

|===
