include::ROOT:partial$variables.adoc[]

= Data types

All of the data inside a workflow is *typed* in order to provide a robust development environment.

[cols="2s,1,5a"]
|===
| Type | Primitive | Description

| [#datatype-boolean]#<<datatype-boolean,Boolean>>#
| Yes
|
A `Boolean` indicates wether a variable is truthy (`true`) or faulty (`false`).

| [#datatype-datetime]#<<datatype-datetime,DateTime>>#
| Yes
|
A `DateTime` contains an absolute temporal value.
A `DateTime` can easily be manipulated using xref:expressions.adoc#datetime[date-time functions].

| [#datatype-duration]#<<datatype-duration,Duration>>#
| Yes
|
A `Duration` contains a relative temporal value.
A `Duration` is usually used in combination with <<datatype-datetime,DateTime>> values to calculate offsets.

| [#datatype-float]#<<datatype-float,Float>>#
| Yes
|
A `Float` is a 64bit floating point number following the https://en.wikipedia.org/wiki/IEEE_754[IEEE 754] standard.

| [#datatype-integer]#<<datatype-integer,Integer>>#
| Yes
|
An `Integer` is a 64bit signed integer.

| [#datatype-unsignedinteger]#<<datatype-unsignedinteger,UnsignedInteger>>#
| Yes
|
An `UnsignedInteger` is a 64bit unsigned integer.

| [#datatype-string]#<<datatype-string,String>>#
| Yes
|
A `String` is a string.

| [#datatype-id]#<<datatype-id,ID>>#
| Yes
|
An `ID` is a system assigned unique identifier for all system resources and should not be assigned or manipulated manually.
An `ID` is a 64bit unsigned integer.

| [#datatype-handle]#<<datatype-handle,Handle>>#
| Yes
|
A `Handle` is a human-friendly resource identifier.
Most {PRODUCT_NAME} resources (such as namespaces and modules) allow you to define a unique identifier that can be used instead of its system assigned <<datatype-id,ID>>.

// ---

| [#datatype-array]#<<datatype-array,Array>>#
| No
|
An `Array` contains a list of items, such as a list of users, records or modules.

| [#datatype-reader]#<<datatype-reader,Reader>>#
| No
|
A `Reader` represents a data stream (such as a file or a blob) that can be read or iterated over using the stream iterator.

[IMPORTANT]
====
A `Reader` can only be read once.
If you need to use it multiple times you will need to cache the initial output.
====

| [#datatype-kv]#<<datatype-kv,KV>># @todo type ref
| No
|
A `KV` is a hashmap that maps `String` values to `String` keys.

| [#datatype-kvv]#<<datatype-kvv,KVV>># @todo type ref
| No
|
A `KVV` is a hashmap that maps a set of `String` values to `String` keys.

// ---

| [#datatype-template]#<<datatype-template,Template>># @todo type ref
| No
|
A `Template` contains a template that can be used by the rendering engine.

| [#datatype-document]#<<datatype-document,Document>># @todo type ref
| No
|
A `Document` is a rendered <<datatype-template,Template>> using <<datatype-renderoptions,RenderOptions>> and <<datatype-rendervariables,RenderVariables>>.

| [#datatype-renderoptions]#<<datatype-renderoptions,RenderOptions>># @todo type ref
| No
|
`RenderOptions` define how a <<datatype-template,Template>> should be rendered into a <<datatype-document,Document>>.

| [#datatype-rendervariables]#<<datatype-rendervariables,RenderVariables>># @todo type ref
| No
|
`RenderVariables` define what data the <<datatype-template,Template>> can use to produce a <<datatype-document,Document>>.

| [#datatype-emailmessage]#<<datatype-emailmessage,EmailMessage>># @todo type ref
| No
|
An `EmailMessage` represents an email that will be sent to the recipients.
The `EmailMessage` type should not be constructed or interacted with directly.
Use the predefined functions to manipulate it's contents.

| [#datatype-role]#<<datatype-role,Role>># @todo type ref
| No
|
A `Role` contains a system role.

| [#datatype-user]#<<datatype-user,User>># @todo type ref
| No
|
A `User` contains a system user.

// ---

| [#datatype-composemodule]#<<datatype-composemodule,ComposeModule>># @todo type ref
| No
|
A `ComposeModule` contains a {APP_NAME_COMPOSE} module.
The `ComposeModule` type is mostly used when updating module fields or creating new records.

| [#datatype-composenamespace]#<<datatype-composenamespace,ComposeNamespace>># @todo type ref
| No
|
A `ComposeNamespace` contains a {APP_NAME_COMPOSE} namespace.
The `ComposeNamespace` type is mostly used when interacting with namespace specific {APP_NAME_COMPOSE} resources.

| [#datatype-composerecord]#<<datatype-composerecord,ComposeRecord>># @todo type ref
| No
|

A `ComposeRecords` contains a {APP_NAME_COMPOSE} record.
The `ComposeRecords` type is mostly used when interacting with {APP_NAME_COMPOSE} records, such as changing their values or converting them into email notifications.

| [#datatype-composerecordvalues]#<<datatype-composerecordvalues,ComposeRecordValues>># @todo type ref
| No
|
A `ComposeRecordValues` contains a set of {PRODUCT_NAME} record values.
This type is usually not used on it's own but in the combination with <<datatype-composerecord,ComposeRecord>>.

|===
