include::../../variables.adoc[]

= {PRODUCT_NAME} with Docker Compose

== Set up Docker

If Docker is already set up on the machine where you want to use {PRODUCT_NAME}, you can skip this section.
If you are using a Docker version below 18.0, I strongly encourage you to update.

.If you're not sure whether you have Docker, open your console or terminal and enter:
----
docker -v
----

If the response is "command not found," download and install a Docker community edition for https://www.docker.com/products/docker-desktop[desktop] or https://hub.docker.com/search?offering=community&type=edition[server or cloud] that fits your environment.

- https://docs.docker.com/install/#server[Docker installation guide]
- https://docs.docker.com/compose/install/[Docker Compose installation guide]


== Configuration files

Very base {PRODUCT_NAME} service configuration for Docker Compose consists of one or two files:
obligatory `docker-compose.yaml` and `.env` file.

=== Environment file (.env)

The format for environment files is simple and clean with one `KEY=VALUE` per line.
File usually has the name `.env` and is placed in the same directory as an application.
In Docker Compose context it is placed in the same directory as `docker-compose.yaml` configuration file.

.Environment file is used on three levels:
. Configuring Docker Compose itself.
  Implicit, as `.env` file in the same directory as `docker-compose.yaml`)
. Utilize values for docker-compose configuration.
  Implicit, as `.env` file in the same directory as `docker-compose.yaml`)
. Passed to configured services.
  Environment file(s) must be explicitly referenced by each service (`env_file: [ .env ]`)
  You can use `.env` or one or more environment files.
  See <<Delaying API execution>>.

[source,dotenv]
----
# Docker images version <1>
VERSION=latest <2>
----
<1> Comment line
<2> Key and value


=== docker-compose.yaml file

This file describes service, network and storage configuration in a human and machine readable format.

Full Docker Compose file reference documentation is available on https://docs.docker.com/compose/compose-file/[docs.docker.com].

[NOTE]
====
YAML (a recursive acronym for "YAML Ain't Markup Language") is a human-readable data-serialization language.
It is commonly used for configuration files and in applications where data is being stored or transmitted.
====

Environmental variables from `.env` can be utilized to make `docker-compose.yaml` file more compact, modular and simpler to change.
You can define a variable (like `VERSION`) and then use it inside yaml file (as $\{VERSION\}`).
