include::../../variables.adoc[]
= Nginx Proxy

NOTE: Nginx Proxy setup is not needed for local testing.
Instructions from <<Basic setup for local demo>> are enough to get local demo up & running.

https://github.com/jwilder/nginx-proxy[Nginx Proxy] (docker image `jwilder/nginx-proxy`) is auto-configurable reverse-proxy that routes traffic from your public IP to containers on the host
https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion[LetsEncrypt Nginx Proxy Companion] (docker image `jrcs/letsencrypt-nginx-proxy-companion`) handles the automated creation, renewal and use of Let's Encrypt certificates for proxyed Docker containers.

WARNING: In the following instructions, we assume you don't have anything similar set up on your current environment. If you have other means to provide traffic forwarding and/or SSL certificate handling, proceed with caution!

Please see https://github.com/jwilder/nginx-proxy[Nginx Proxy] and https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion[LetsEncrypt Nginx Proxy Companion] Github pages to

.How it works & benefits
. Both images mount /var/run/docker.sock (read-only) and listen to docker events (when containers start or stop)
. Containers (like {PRODUCT_NAME} server, and fronted application) that are exposed publicly no longer have to publish their ports on public IP
. No complicated firewall or network forwarding rules are needed
. Containers MUST (also) be on the same network as `nginx-proxy` (in the examples we're using network named `proxy`)
. Nginx Proxy detects `VIRTUAL_HOST` on each container that comes online.
  Then it auto-generates configuration, reloads itself and starts forwarding HTTP traffic to that container
. LetsEncrypt companion detects `LETSENCRYPT_HOST` and starts certificate creation process with LE.
  It also reconfigures nginx-proxy, adds certificates and enables redirection from HTTP to HTTPS

.`docker-compose.yaml`
[source,yaml]
----
include::example$docker-compose/nginx-proxy/docker-compose.yaml[]
----

.Add `custom.conf` Nginx configuration file next to `docker-compose.yaml`
[source]
----
include::example$docker-compose/nginx-proxy/custom.conf[]
----

.Start both services
[source,shell]
----
docker-compose up -d
----

.Running `docker-compose ps` should produce something like:
[source,shell]
[%autofit]
----
include::example$docker-compose/nginx-proxy/output-ps.txt[]
----
