include::../../variables.adoc[]
= Production deployment

This example describes production-ready deployment.
It depends on running nginx-proxy service (see <<Nginx Proxy>>)

This demo uses 2 example domains: `your-demo.example.tld` and `api.your-demo.example.tld`.
You should configure your DNS, add 2 hosts and point them to the IP address (A record) or hostname (CNAME record) of the server you're using for Corteza deployment.

.`.env`
[source,dotenv]
----
include::example$docker-compose/production/env.txt[]
----

.`docker-compose.yaml`
[source,yaml]
----
include::example$docker-compose/production/docker-compose.yaml[]
----

Create an empty directory, with `.env` and `docker-compose.yaml` files and copy contents from the examples above.
Some operating systems do not like files that start with a dot so make sure `.env` file is properly named.

[WARNING]
====
We advise against merging/mixing Corteza and `nginx-proxy` in the same directory.

It can be done but requires some experience with Docker Compose.
====

Make sure your nginx-proxy service is running before running.
If nginx-proxy service is not started or you changed your configuration somehow, you might get error like:

----
ERROR: Network proxy declared as external, but could not be found. Please create the network manually using `docker network create proxy` and try again.
----

Inspect your configuration files and compare them with ones provied in this documentation.


.Start all services (database, server, corredor, webapp)
[source,shell]
----
docker-compose up -d
----

.Running `docker-compose ps` should produce something like:
[source,shell]
----
include::example$docker-compose/production/output-ps.txt[]
----

You can see 4 services up and running.
Your services should soon (under a couple of minutes) be available on the configured domains.

Direct your browser to `http://your-demo.example.tld`.
On first visit, you should be redirected to `/auth` where you can login, sign up, etc.

Create your account through the sign-up form.
{PRODUCT_NAME} detects if the database is empty and auto-promotes first user to administration role.

.Stopping and removing containers and date (do not ask for confirmation, stop containers if running and remove volumes)
[source,shell]
----
docker-compose rm --force --stop -v
----

Other useful docker-compose commands:

.View container output (logs) and follow output and output 20 lines from each service
[source,shell]
----
docker-compose logs --follow --tail 20
----
