include::../../variables.adoc[]
= Corredor Server

Environmental variables used by Corredor and API Server when connected to and communicating with Corredor.

[cols="m,m,"]
|===
|Type|Default value|Description

3+| CORREDOR_ADDR
| string
| corredor:80
| This setting is used by both, Corredor and API Server.

For Corredor server: where is server listening on

For API server: where can Corredor server be accessed.

_Used by Corredor and API server._

3+| CORREDOR_ENABLED
| bool
| false
| This is a setting for API server, will Corredor be used for server automation?

_Used by Corredor and API server._

3+| CORREDOR_MAX_BACKOFF_DELAY
| duration
| 1m
| Connection timeout (from API server to Corredor)

_Used by API server._

3+| CORREDOR_API_BASE_URL_COMPOSE
| string
|
| Location of the compose API (example: `{API_COMPOSE_BASE_URL}`)

_Used by API server._

3+| CORREDOR_API_BASE_URL_MESSAGING
| string
|
| Location of the messagign API (example: `{API_MESSAGING_BASE_URL}`)

_Used by API server._

3+| CORREDOR_API_BASE_URL_SYSTEM
| string
|
| Location of the system API (example: `{API_SYSTEM_BASE_URL}`)

_Used by API server._

3+| CORREDOR_LOG_ENABLED
| boolean
| corredor
| This setting is used by both, Corredor and API Server.

For Corredor service: where is service listening on (gRPC)

For API server: where can Corredor service be accessed.

_Used by Corredor and API server._

3+| CORREDOR_LOG_LEVEL
| bool
| false
| If set to true, API server will log communication with Corredor and Corredor will log incoming requests.

_Used by Corredor and API server._

3+| CORREDOR_LOG_LEVEL
| string
| info
| Defaults to `trace` when `CORREDOR_DEBUG` is `true`, defines amount of log information outputed.

_Used by Corredor and API server._

3+| CORREDOR_LOG_PRETTY
| boolean
| false
| Are events logged in one-line JSON or formatted to ease development?

_Used by Corredor._

3+| CORREDOR_DEBUG
| boolean
| false
| Corredor will log even more information

_Used by Corredor._
|===
