= Nodes

Federation of the data occurs between at least two servers (from here on reffered as nodes). A *node* can supply - _expose_ records
to other nodes or it can act as a destination node and fetch data into the mapped modules from originating node. 

For nodes to successfuly transfer data between Corteza instances, they need to be successfuly paired. The pairing is started on any of 
the nodes with adding necessary info about the destination node, providing at least the url of the federated node and contact info.

Once the node is added in administration, the generated url is provided to the administrators and an invitation email can be sent to the destination contact.

[NOTE]
====
No data is shared on this step yet as the pairing needs to be confirmed on destination node also.
====

The destination administrator needs to use the generated link that was sent via the invite and create a new node from the generated url. 

Once that is done, the originating node's administrators will receive a confirmation email that will prompt them to accept the pairing process. Once that is approved, the node pairing is done and the next process (specifying data to be federated) can begin.
