= Setting up federation in Corteza

.The basic principle of data federation in Corteza is based on 3 phases:
 - node pairing
 - field mapping
 - data synchronisation

== Node pairing

[#federation:node:pair]
.Adding a node:
. Click on *_new_* link in the node administration via *_Federation > Nodes > New_*
. Fill the destination node's information
. Submit

.Sending invitation:
. Click on *_Generate Federation Link_*
. Insert contact email (invitation will be sent) or copy generated url

[WARNING]
====
Generated url includes a secure token, so the federation link must be sent to the other party via a secure channel
====

.Receiving invitation:
. Click on *_Pair Federation Node_* and use the received federation link

[NOTE]
====
The process needs to be performed manually on the destination node to accomodate the highest levels of security. The pairing will begin after inserting
the federation link and should be instantaneous.
====

=== Confirming federation

.The confirmation of the handshake process:
. Click on the warning icon and the pairing will be confirmed

[NOTE]
====
This step needs to be done on the origin server, so that all the tokens and users are exchanged successfuly
====

