include::../../variables.adoc[]

= Modules

A *module stores and shapes* your data (records).
The data within a module is *specific to the namespace* -- that data *cannot* be accessed *from other namespaces*.

[TIP]
====
.Relational database correlation:
* module ~= *table*
* module field ~= *attribute*
* record ~= *entity*
====

[TIP]
====
{PRODUCT_NAME} {APP_NAME_COMPOSE} supports *multi-value fields*, which removes the need of simple _pivot_ tables.
====

[IMPORTANT]
====
When exporting *multi-value fields* into the *CSV format*, only the *first value* is exported.
====

== Module definition guidelines

Module name::
    The module name should be in *PascalCase* with spaces allowed, it should be *short* and *descriptive*, with *no special characters* except for `:` (colon), `-` (dash), `_` (underscore), `/` (forward slash) and `\` (backwards slash).

Module handle::
    The module handle should be in *snake_case*, it should be *short* and *descriptive*, with *no special* characters.

[IMPORTANT]
====
.The provided handle must:
include::ROOT:partial$handle-constraints.adoc[]
====

== Module field definition guidelines

Field name::
    The module field name should be in *snake_case*, it should be *short* and *descriptive*, with *no special characters*.

[IMPORTANT]
====
.The provided name must:
include::ROOT:partial$handle-constraints.adoc[]
====

Field title::
    The maximum module field *title length* is *64 characters*.
    There are no other restrictions.

Type::
    The module *field type* defines the *type of the stored data*.
    Make sure to *use appropriate types*.

== Create a module

.To create a new module:
. navigate to the {PRODUCT_NAME} {APP_NAME_COMPOSE} page and enter the namespace you wish to edit,
. click on the "Admin panel" in the top right corner,
. navigate to the "Modules" subpage,
. enter the module name and press the "Create" button,
. provide the module handle and save the changes.

[IMPORTANT]
====
You can only define permissions for existing modules.
After you save the module, the option becomes available.
====

== Importing modules

[IMPORTANT]
====
The current *module importing system* is unable to resolve *relations between different modules* via record fields.
References must be *fixed manually* after the system finishes *with the import*.
====

[NOTE]
====
Currently, only the JSON format is supported.
====

.To import modules:
. navigate to the {PRODUCT_NAME} {APP_NAME_COMPOSE} page and enter the namespace you wish to edit,
. click on the "Admin panel" in the top right corner,
. navigate to the "Modules" subpage,
. find the "Import module(s)" section on the top of the page,
. click on the "Browse" button and select the JSON file containing module definitions,
. click on the "Import" button,
. select on the modules you wish to import and press the "Import" button.

== Editing a module

.To edit an existing module:
. navigate to the {PRODUCT_NAME} {APP_NAME_COMPOSE} page and enter the namespace you wish to edit,
. click on the "Admin panel" in the top right corner,
. navigate to the "Modules" subpage,
. click on the edit icon next to the module you wish to edit,
. update the data and save the changes.

== Deleting a module

.To delete an existing module:
. navigate to the {PRODUCT_NAME} {APP_NAME_COMPOSE} page and enter the namespace you wish to edit,
. click on the "Admin panel" in the top right corner,
. navigate to the "Modules" subpage,
. click on the edit icon next to the module you wish to edit,
. click on the "Delete" button on the bottom of the page and confirm the action.

== Adding module fields

.To add a new module field:
. navigate to the {PRODUCT_NAME} {APP_NAME_COMPOSE} page and enter the namespace you wish to edit,
. click on the "Admin panel" in the top right corner,
. navigate to the "Modules" subpage,
. click on the edit icon next to the module you wish to edit,
. click on the "+ Add new field" button,
. configure the field as you see fit and save the changes (see <<compose-module-field-properties>>).

== Editing module fields

[IMPORTANT]
====
If the module *contains records*, the editing *interface is limited*.
If you wish to change the *disabled properties*, we suggest you create a *new field* instead.
====

.To edit an existing field:
. Navigate to the {PRODUCT_NAME} {APP_NAME_COMPOSE} page and enter the namespace you wish to edit,
. click on the "Admin panel" in the top right corner,
. navigate to the "Modules" subpage,
. click on the edit icon next to the module you wish to edit,
. configure the field as you see fit and save changes (see <<compose-module-field-properties>>).

== Deleting a module field

[IMPORTANT]
====
* When deleting *existing fields*, the change will *not* take effect unless you *explicitly save* the changes.
* When deleting *new fields*, the changes take effect *immediately*.
====

.To delete an existing field:
. navigate to the {PRODUCT_NAME} {APP_NAME_COMPOSE} page and enter the namespace you wish to edit,
. click on the "Admin panel" in the top right corner,
. navigate to the "Modules" subpage,
. click on the edit icon next to the module you wish to edit,
. click on the trashcan icon next to the field you wish to delete and save changes.

[#compose-module-field-properties]
== Module field properties

Name::
    *The name for the field*; defines how the values are stored.
    The name is *not visible to the user* if you've provided the title.

[IMPORTANT]
====
.The provided name must:
include::ROOT:partial$handle-constraints.adoc[]
====

Title::
    *A human-friendly label* shown when interacting with the data.
    It should be *short*, *descriptive* and *limited to 64 characters*.
    No other restrictions apply.

Type::
    The module *field type* defines the *type of the stored data*.
    Make sure to *use appropriate types*.

Multi value:: 
    *Multi value fields* allow you to store *multiple entries* under the *same field*.
    This removes the need for simple _pivot tables_.

[IMPORTANT]
====
When exporting *multi-value fields* into the *CSV format*, only the *first value* is exported.
====

Required::
    *The required flag* makes the field *mandatory* for the end-user when creating or editing a record.

Private::
    *The private flag* marks the data as *sensitive*; such as name, email, or telephone number.
    This helps make your namespace *compliant with privacy regulations*, such as GDPR.

== Module field types

[TIP]
====
Access *additional configuration options*, by pressing on the *wrench icon* next to the field type.
====

=== Checkbox (Y/N)

The *checkbox field type* represents a *true/false* (yes/no) vale; *a boolean*.
When editing, the field is a checkbox; when viewing, it's the value label.

.Additional configurations:
* *true/false label*: the *label to show* when the value is true or false.

=== Date and time

The *date and time field type* represents a *temporal value* (date and/or time); *a timestamp*.
When editing, the field is a date-time picker; when viewing, it's a text string.

.Additional configurations:
* *date only*: omit the time part and only use the date,
* *time only*: omit the date part and only use the time,
* *past values only*: only allow past values,
* *future value only*: only allow future values,
* *output relative value*: show the value relative to now,
* *custom output format*: custom output date format.

[NOTE]
====
See https://momentjs.com/docs/#/displaying/format/[Moment.js format] for available date-time formatting.
====

=== Email

The *email field type* represents an *email address* (the field has some built-in value validation).
When editing, the field is an email input box; when viewing, it's either a link or a text string.

.Additional configurations:
* *don't turn email into a link*: keep the link as plain text.

[IMPORTANT]
====
The email is *stored as plain text* regardless of the configuration options.
The email is *converted* to a link *before it is shown* on the user interface.
====

=== Select / dropdown

The *select / dropdown field type* represents a *text value* that is limited to the specified set of options.
When editing, the field is a native dropdown; when viewing, it's a text string.

.Additional configurations:
* *Options*: a set of *label/value pairs* of the *available options*.
The *value* part defines how the data is *stored internally*; the *label* part describes how the *data is presented* to the user (defaults to the value).
* *Multiple value input type*: specify how multiple values are selected.

=== Number

The *number field type* represents a *numerical value*.
When editing, the field is a number input; when viewing, it's a formatted text string.

[NOTE]
====
The same field can store *both full* and *fractional numbers*.
====

.Additional configurations:
* *prefix*: specify the prefix, such as `$`,
* *suffix*: specify the suffix, such as `USD/h`,
* *precision*: specify the number precision (maximum is 6),
* *format*: specify the display format.

[NOTE]
====
See https://numeraljs.com/#format[Numeral.js format] for available number formatting.
====

=== Record

The *record field type* represents a *reference to another record*.
When editing, the field is a searchable dropdown select field; when editing, it's a clickable link.

[IMPORTANT]
====
You can only reference records *in the same namespace*.
====

.Additional configurations:
* *module*: specify what module this field will be linked to,
* *record label field*: specify what field should be used when showing the linked record,
* *query fields on search*: specify the fields that should be included in the search,
* * pre-filter records*: specify the pre-filtering.

=== String

The *string field type* represents a *text string value*.
When editing, the fields are either regular text input or a rich-text input; when viewing, it's a formatted text string.

.Additional configurations:
* *multi-line*: specify that the value can span over multiple lines,
* *use rich text editor*: use the rich text editor instead of the simple plain text editor.

=== URL

The *URL field type* represents a *URL value* (the field has some built-in value validation).
When editing, the field is an URL input box; when viewing, it's either a link or a text string.

.Additional configurations:
* *trim # from the URL*: specify that the fragment should be ignored (the thing after the `#`),
* *trim ? from the URL*: specify that the query should be ignored (the thing after the `?`),
* *only allow SSL (HTTPS) URLs*: specify that only secure URL's can be provided,
* *don't turn URL into a link*: keep the URL as a plain text value.

[TIP]
====
The above configurations can help you *sanitize user input* with no additional code required.
====

[IMPORTANT]
====
The URL is *stored as plain text* regardless of the configuration options.
The URL is *converted* to a link *before it is shown* on the user interface.
====

=== User

The *user field type* represents a *reference to a user*.
When editing, the field is a searchable dropdown; when viewing its a text string (the registered name).

.Additional configurations:
* *preset with current user*: default to the user that created/updated the record,
* *multiple value input type*: determine how multiple values are selected.

=== File upload

The *file field type* represents a *reference to a file* uploaded to the record.
When editing, the field is a file uploader; when viewing, it's one of the configured displays.

.Additional configurations:
* *view mode*: specify how the files are presented when viewing the value.

== Permissions for all modules

include::ROOT:partial$permissions/compose-modules.adoc[]

== Permissions for a specific module

include::ROOT:partial$permissions/compose-module-specific.adoc[]

== Permissions for all module fields

include::ROOT:partial$permissions/compose-module-fields.adoc[]

== Permissions for a specific module field

include::ROOT:partial$permissions/compose-module-field-specific.adoc[]
