include::../../variables.adoc[]

= Namespaces

A *namespace* is the *root* of your *{APP_NAME_COMPOSE}* application, as it *encapsulates the components* that make up a *specific application*.
For example, *CRM related things* go under the *CRM namespace*; *call centre things* go under the *call centre namespace*.

[TIP]
====
A namespace can be thought of as a *schema* in a relational database.
The schema encapsulates modules, their attributes, and entities.
====

== Create a namespace

.To create a new namespace:
. navigate to the {PRODUCT_NAME} {APP_NAME_COMPOSE} page,
. click on the "Create namespace" button at the bottom of the page,
. provide all the requested data (see <<compose-namespaces-properties,namespace properties>>),
. press the "Save" or "Save and close" button.

[IMPORTANT]
====
You can only define permissions for existing namespaces.
====

[#compose-namespaces-edit]
== Edit a namespace

.To edit an existing namespace:
. navigate to the {PRODUCT_NAME} {APP_NAME_COMPOSE} page,
. hover over the namespace you wish to edit,
. press on the edit icon,
. provide all the requested data (see <<compose-namespaces-properties,namespace properties>>),
. press the "Save" or "Save and close" button.

== Delete a namespace

[TIP]
====
Not sure if the namespace could be *used in the future*?
You can just <<compose-namespaces-edit,*disable the namespace*>>.
====

.To delete an existing namespace:
. navigate to the {PRODUCT_NAME} {APP_NAME_COMPOSE} page,
. hover over the namespace you wish to delete,
. press on the edit icon,
. press and confirm the "Delete" option.

[#compose-namespaces-properties]
== Namespace properties

Full namespace name::
    *The name of your application*, which will is visible in the {APP_NAME_COMPOSE} Namespaces menu.
    Keep your namespace names short and descriptive.

short name::
    *A shortened name* (slug) is used as a human-friendly identifier within the system.
    You can use the *short name* instead of the namespace ID (that long number) within your *automation scripts* and *URL references*.

[IMPORTANT]
====
.The provided short name must:
include::ROOT:partial$handle-constraints.adoc[]
====

Subtitle::
    *The subtitle* is shown *below the name* of the application in the {APP_NAME_COMPOSE} Namespaces menu.

Namespace description::
    A *longer description* that appears when hovering over the namespace in the {APP_NAME_COMPOSE} Namespaces menu.

Enable namespace::
    The namespace *is shown regardless* of the value; when disabled, you *can not enter* the namespace.

== Permissions for all namespaces

include::ROOT:partial$permissions/compose-namespaces.adoc[]

== Permissions for a specific namespace

include::ROOT:partial$permissions/compose-namespace-specific.adoc[]
