= Glossary

== Node pairing

[IMPORTANT]
====
Before we pair the two nodes, we are unable to determine what node is the source and what node is the destination.
To avoid confusion, we use _node A_ and _node B_ when referring to the two nodes.
====

Node URI::
    The URI that identifies a federation node.

Node A::
    Node A is the node that initializes the process of creating a federated network with another node (node B).

Node B::
    Node B is the node that wishes to join a federated network, initialized by node A.

NodeID A::
    NodeID A is the node A identifier.

NodeID B::
    NodeID B is the node B identifier.

Token A::
    Token A is the authentication token used to access protected resources on node A.

Token B::
    Token B is the authentication token used to access protected resources on node B.

== Node sync

Origin node::
    The *origin node* is the node that *shares the data* to the other node.
    If node A requests data from node B, node B is the origin, as it contains the data.

Destination node::
    The *destination node* is the node that *receives the data* from the origin node.
    If node A requests data from node B, node A is the destination as it receives the data.

== Federated node

Node status::
    Node status defines the current status of the federated node.
    Can be one of the following:

    * *pairing*: the node is in the pairing process,
    * *paired*: the nodes were successfully paired,
    * *failed*: the node was unable to pair.

Structure sync status::
    Structure sync status defines the current status of the federation node structure syncing.
    Can be one of the following:

    * *syncing*: the node is currently syncing structures from the origin node,
    * *synced*: the node has successfully finished syncing,
    * *failed*: there was an error while syncing.

Data sync status::
    Data sync status defines the current status of the federated node data syncing.
    Can be one of the following:

    * *syncing*: the node is currently syncing data from the origin node,
    * *synced*: the node has successfully finished syncing,
    * *failed*: there was an error while syncing.
