include::../../variables.adoc[]

[#federation]
= {PRODUCT_NAME} {APP_NAME_FEDERATION}

.An abstract overview over the entire federation system.
[plantuml,federation-overview,svg,role=sequence]
----
@startuml
skinparam ParticipantPadding 50
participant "Node A\n(Origin Node)" as NodeA
participant "Node B\n(Destination Node)" as NodeB

== Node pairing ==
NodeA <-> NodeB: Pair nodes
note over NodeA, NodeB: The nodes exchange identity and authentication credentials via a node handshake
...
== Structure syncing ==
NodeA -> NodeA: Expose structures
note over NodeA
Origin node determines what structures
it wishes to expose to the destination node.
end note
NodeA -> NodeB: Structure sync

NodeB -> NodeB: Module mapping
note over NodeB
Destination node determines what origin fields
should map to what destination fields.
end note
...
== Data syncing ==
NodeA -> NodeB: Data sync

@enduml
----

Node pairing::
    The process of establishing a federated network between two nodes.
    After they are paired, they are able to securely exchange data.
    Refer to <<federation:node-pair>> and <<federation:security:authentication>> for details.

Structure syncing::
    The process of determining what structures on the origin node (the one that contains the data), is exposed to it's destination node (the one that wishes to access the data).
    The origin node has full control over what data the destination node is allowed to access.
    This can be as simple as allowing access to only specific modules; and as complex as allowing access to only specific module fields.
    Refer to <<federation:structure-sync>> and <<federation:security:access-control>> for details.

Data syncing::
    The process of updating data on the destination node, based on the updated data source.
    The destination node has the ability to determine what field from the origin node maps into what field in the destination node.
    Refer to <<federation:data-sync>> for details.

:leveloffset: +1

include::glossary.adoc[]

include::security.adoc[]

include::logging.adoc[]

include::node_pair.adoc[]

include::structure_sync.adoc[]

include::data_sync.adoc[]

include::api/index.adoc[]

:leveloffset: -1

