[#federation:structure-sync]
= Syncing structures

The process of determining what structures on the origin node, is exposed to it's destination node.
The origin node has full control over what data the destination node is allowed to access.
This can be as simple as allowing access to only specific modules; and as complex as allowing access to only specific module fields.

[IMPORTANT]
====
The two nodes must be paired prior to this.
See <<federation:node-pair, Node pairing>>.
====

== Exposing structures

Firstly, in order to perform any data sharing, the origin node must define what structures (in our case modules and fields) the destination node can access.
This can be performed via the Corteza Low-Code administration panel, or directly via the API.

[NOTE]
====
Besides the module itself, the origin node must also specify what fields the destination node is allowed to access.
====

=== API

==== Expose module

include::api/structure_sync__add_module_to_federation.adoc[]

==== See exposed module

include::api/structure_sync__list_exposed_module.adoc[]

==== Remove exposed module

include::api/structure_sync__remove_module_federation.adoc[]

==== Change exposed module fields

include::api/structure_sync__change_sharing_fields.adoc[]

