include::../../variables.adoc[]

= About

https://www.docusign.com/[DocuSign] is a service that allows our clients to sign documents, such as quotes and contracts online.

The extension implements 3 main components:

The data model::
    the data model required by the extension in order for it to work,

Authentication::
    DocuSign's OAuth2 authentication flow to authorize {PRODUCT_NAME} to access resources connected to your account,

Document signature::
    A set of automation scripts that allow us to send the document into signing, cancel the pending document and check for the signature status.

[IMPORTANT]
====
DocuSign is fairly strict in the terms of when your credentials can be used in production.
====

== Required token scopes

signature::
    This scope allows the token to perform most document related operations, such as sending the document to be signed, canceling the document, ...

extended::
    This scope allows us to request new refresh tokens with a full lifetime of ~30days.
