include::ROOT:partial$variables.adoc[]

= Federated Nodes
:page-aliases: 2024.9@administrator-guide:federation/nodes.adoc

A *federated node* is an independent *{PRODUCT_NAME} instance* with the {APP_NAME_FEDERATION} feature enabled. In a federated network, each node operates autonomously but can connect with other nodes to securely exchange information.

A node can expose data to its destination nodes (acting as an *origin*), or consume shared data from its origin nodes (acting as a *destination*).

[NOTE]
====
A node can act as both an origin and a destination simultaneously.
====

Before any data can be exchanged, the instances must establish a secure connection through the <<node-pairing,node pairing>> process.

[#node-pairing]
== Node pairing

.Node pairing flow outline:
. the origin node <<node-pairing-register,registers a destination node>>,
. the origin node <<node-pairing-invite,sends an invite>> to the destination node,
. the destination node accepts the invite, either <<node-pairing-accept-invite,via email>> or <<node-pairing-accept-invite-manual,manually>>,
. the origin node <<node-pairing-handshake-accept,accepts the handshake request>> sent by the destination node.

[NOTE]
====
You can initiate the node pairing process from any node.
====

.[#node-pairing-register]#<<node-pairing-register,To register a new node (Origin Node):>>#
. navigate to the {PRODUCT_NAME} {APP_NAME_ADMIN},
. click on *Nodes* under *Federation* in the navigation drawer,
. click the btn:[New] button,
. provide the requested data regarding the node you wish to connect to,
. press the btn:[Submit] button.

.[#node-pairing-invite]#<<node-pairing-invite,To send the invitation (Origin Node):>>#
. navigate to the {PRODUCT_NAME} {APP_NAME_ADMIN},
. click on *Nodes* under *Federation* in the navigation drawer,
. click on the node to which you want to send an invitation,
. click the btn:[Generate Federation Link] button and either:
** copy the invitation URL, or
** insert the contact email where the invite should be sent.

[WARNING]
====
The generated invite URL includes a secure OTT (One-Time Token), so ensure you send it over a secure channel.
====

.[#node-pairing-accept-invite]#<<node-pairing-accept-invite,To accept the email invitation (Destination Node):>>#
. click the btn:[Pair Federation Node] link in the email to open the pairing page,
. enter the received URL and confirm.

.[#node-pairing-accept-invite-manual]#<<node-pairing-accept-invite-manual,To accept the invitation manually (Destination Node):>>#
. navigate to the {PRODUCT_NAME} {APP_NAME_ADMIN},
. click on *Nodes* under *Federation* in the navigation drawer,
. click the btn:[Edit] button,
. enter the received URL and confirm.

[NOTE]
====
Node pairing will not proceed until the pairing URL is inserted and the handshake request is accepted by the origin node.
====

.[#node-pairing-handshake-accept]#<<node-pairing-handshake-accept,To accept the node pair handshake request (Origin Node):>>#
. navigate to the {PRODUCT_NAME} {APP_NAME_ADMIN},
. click on *Nodes* under *Federation* in the navigation drawer,
. click on the node you wish to accept the request for,
. click the warning icon to confirm the request.

[IMPORTANT]
====
Remember that this final step is done on the *origin server* (the one that initiated the handshake).
====
