include::ROOT:partial$variables.adoc[]

= Data Synchronization
:page-aliases: 2024.9@administrator-guide:federation/share-data.adoc

Once two nodes have successfully completed the <<node-pairing,node pairing>> process, you can begin sharing data between them.

[NOTE]
====
Shared modules are automatically created by the {APP_NAME_FEDERATION} system and cannot be manually removed or updated.
====

[#expose-module]
== Sharing data (Origin Node)

An origin node shares data by defining which modules and fields a specific paired destination node is allowed to access.

[NOTE]
====
You can only share data with nodes that have been successfully paired.
====

.To share a new module from the Origin Node:
. navigate to {PRODUCT_NAME} {APP_NAME_COMPOSE},
. enter the namespace administration area,
. navigate to the *Modules* sub-page,
. click the edit icon next to the module you want to share,
. click on *Federation Settings*,
. go to the *Expose* tab,
. select the destination node you want to share the module with,
. select the specific fields you want to expose to that node,
. save the changes.

[TIP]
====
To speed up configuration, you can duplicate settings from another node by selecting the desired node from the *Copy settings from* dropdown.
====

.A screenshot showing the module sharing interface.
[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "federation/expose-module.png",
    "alias": "federation-expose-module",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 545,
    "y": 10,
    "w": 850,
    "h": 450
  },
  "annotations": []
}
----

[#module-mapping]
== Consume shared data (Destination Node)

A destination node consumes shared data from its paired origin node. The destination node defines which modules it wants to access and how the remote values map to the local destination module.

[NOTE]
====
You can only consume data from nodes that have been successfully paired.
====

.To consume data on the Destination Node:
. navigate to {PRODUCT_NAME} {APP_NAME_COMPOSE},
. enter the namespace administration area,
. navigate to the *Modules* sub-page,
. click the edit icon next to the local module where you want to consume the data,
. click on *Federation Settings*,
. go to the *Map* tab,
. select the origin node you want to consume data from,
. map the shared remote fields to your local module fields,
. save the changes.

.A screenshot showing the module mapping interface.
[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "federation/map-module.png",
    "alias": "federation-map-module",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 545,
    "y": 10,
    "w": 850,
    "h": 450
  },
  "annotations": []
}
----
