include::ROOT:partial$variables.adoc[]

[cols="2s,1,5a"]
|===
| Type | Primitive | Description

| [#datatype-any]#<<datatype-any,Any>>#
| N/A
|
A variable of type `Any` does not perform any type checks and can store anything.
The use of this is not recommended, but it can be used.

| [#datatype-vars]#<<datatype-vars,Vars>>#
| No
|
Identical to <<datatype-kv,`KV`>> but used for complex structures.

| [#datatype-boolean]#<<datatype-boolean,Boolean>>#
| Yes
|
A `Boolean` indicates wether a variable is truthy (`true`) or faulty (`false`).

| [#datatype-datetime]#<<datatype-datetime,DateTime>>#
| Yes
|
A `DateTime` contains an absolute temporal value.
A `DateTime` can easily be manipulated using xref:expr/fnc-reference.adoc#datetime[date-time functions].

| [#datatype-duration]#<<datatype-duration,Duration>>#
| Yes
|
A `Duration` variable contains a relative temporal value.
It is usually used in combination with <<datatype-datetime,DateTime>> values to calculate offsets.

| [#datatype-float]#<<datatype-float,Float>>#
| Yes
|
A `Float` is a 64bit floating point number following the https://en.wikipedia.org/wiki/IEEE_754[IEEE 754] standard.

| [#datatype-integer]#<<datatype-integer,Integer>>#
| Yes
|
An `Integer` is a 64bit signed integer; range `-9223372036854775808` through `9223372036854775807`.

| [#datatype-unsignedinteger]#<<datatype-unsignedinteger,UnsignedInteger>>#
| Yes
|
An `UnsignedInteger` is a 64bit unsigned integer; range `0` through `18446744073709551615`.

| [#datatype-string]#<<datatype-string,String>>#
| Yes
|
A `String` variable contains a text (a string).

| [#datatype-id]#<<datatype-id,ID>>#
| Yes
|
An `ID` is a system assigned unique identifier for all system resources and should not be assigned or manipulated manually.
An `ID` is a 64bit unsigned integer; range `0` through `18446744073709551615`.
//Editor's note: Should not be assigned or manipulated manually or cannot be assigned or manipulated manually? is the possibility of manually applied changes there?

| [#datatype-handle]#<<datatype-handle,Handle>>#
| Yes
|
A `Handle` is a user-friendly resource identifier.
Most {PRODUCT_NAME} resources (such as namespaces and modules) allow you to define a unique identifier that can be used instead of its system assigned <<datatype-id,ID>>.

The value must be an empty string or a string matching the following regular expression: `/^[A-Za-z][0-9A-Za-z_\-.]*[A-Za-z0-9]$/`.

// ---

| [#datatype-array]#<<datatype-array,Array>>#
| No
|
An `Array` contains a list of items, such as a list of users, records or modules.

| [#datatype-reader]#<<datatype-reader,Reader>>#
| No
|
A `Reader` represents a data stream (such as a file or a blob) that can be read or iterated over using the stream iterator.

[IMPORTANT]
====
A `Reader` can only be read once.
If you need to use it multiple times you will need to cache the initial output.
====

| [#datatype-kv]#<<datatype-kv,KV>>#
| No
|
A `KV` is a hashmap that maps `String` values to `String` keys.

| [#datatype-kvv]#<<datatype-kvv,KVV>>#
| No
|
A `KVV` is a hashmap that maps a set of `String` values to `String` keys.

// ---

| [#datatype-template]#<<datatype-template,Template>>#
| No
|
A `Template` contains a template that can be used by the rendering engine.

| [#datatype-document]#<<datatype-document,Document>>#
| No
|
A `Document` is a rendered <<datatype-template,Template>>.
It uses <<datatype-renderoptions,RenderOptions>> and <<datatype-rendervariables,RenderVariables>> in order to produce a document.

| [#datatype-renderoptions]#<<datatype-renderoptions,RenderOptions>>#
| No
|
`RenderOptions` define how a <<datatype-template,Template>> should be rendered into a <<datatype-document,Document>>.

| [#datatype-rendervariables]#<<datatype-rendervariables,RenderVariables>>#
| No
|
`RenderVariables` define what data the <<datatype-template,Template>> can use to produce a <<datatype-document,Document>>.

| [#datatype-emailmessage]#<<datatype-emailmessage,EmailMessage>>#
| No
|
An `EmailMessage` represents an email that is to be sent to the recipients.
The `EmailMessage` type should not be constructed or interacted with directly.
It is suggested you use the predefined functions to manipulate it's contents.

[CAUTION]
====
A new `EmailMessage` must be initialized using the `Email builder` function.
====

| [#datatype-role]#<<datatype-role,Role>>#
| No
|
A `Role` contains a system role.

| [#datatype-user]#<<datatype-user,User>>#
| No
|
A `User` contains a system user.

// ---

| [#datatype-composemodule]#<<datatype-composemodule,ComposeModule>>#
| No
|
A `ComposeModule` contains a {APP_NAME_COMPOSE} module.
The `ComposeModule` type is mostly used when updating module fields or creating new records.

| [#datatype-composenamespace]#<<datatype-composenamespace,ComposeNamespace>>#
| No
|
A `ComposeNamespace` contains a {APP_NAME_COMPOSE} namespace.
The `ComposeNamespace` type is mostly used when interacting with namespace specific {APP_NAME_COMPOSE} resources.

| [#datatype-composerecord]#<<datatype-composerecord,ComposeRecord>>#
| No
|

A `ComposeRecords` contains a {APP_NAME_COMPOSE} record.
The `ComposeRecords` type is mostly used when interacting with {APP_NAME_COMPOSE} records, such as changing their values or converting them into email notifications.

[CAUTION]
====
A new `ComposeRecord` must be initialized using the `Compose record maker` function.
====

| [#datatype-composerecordvalues]#<<datatype-composerecordvalues,ComposeRecordValues>>#
| No
|
A `ComposeRecordValues` contains a set of {PRODUCT_NAME} record values.
This type is usually not used on it's own but in the combination with <<datatype-composerecord,ComposeRecord>>.

|===

[#object-reference]
= Object reference

include::generated:partial$expr-types.gen.adoc[]
