include::ROOT:partial$variables.adoc[]

= Platform Developer Guide

The platform developer guide covers the process of developing on the core {PRODUCT_NAME} platform components.

The guide is designed for the core {PRODUCT_NAME} maintainers as well as open source contributors.

In case you wish to learn more about low-code app development, refer to the xref:integrator-guide:index.adoc[]

== GitHub repositories

The core {PRODUCT_NAME} codebase is located in the {GIT_MONOREPO_LINK}[`corteza` monorepo].
The monorepo includes the server, the web applications, NPM packages, and Discovery.
{PRODUCT_NAME} {APP_AUTOMATION} can be found in it's own {GIT_REPO_LINK_PREFIX}corteza-server-corredor[repository]

== Component diagram

[NOTE]
====
*DevNote* @todo make nice diagram
====

== Contribution checklist

All contributors should follow the contribution checklist to help maintain consistency and order as the project grows.

.The below table outlines the contribution checklist items:
[cols="1s,5a"]
|===
| [#contribution-checklist-implement]#<<contribution-checklist-implement,Implement>>#
|
Implement the bug fix, feature, or general improvement based on the GitHub issue tracker or own observations.

.The implementation should be consistent with the rest of the component:
* xref:corteza-server/index.adoc[{PRODUCT_NAME} server]
* xref:web-applications/index.adoc[Web applications]
* xref:corteza-js/index.adoc[corteza-js]
* xref:corteza-vue/index.adoc[corteza-vue]
* xref:documentation/index.adoc[documentation]

[NOTE]
====
*DevNote* add reference to the indexer when it is available
====

*External contributors* must submit their addition as a pull request which must be reviewed by a core contributor.

*Core contributors* may provide their addition directly to the version branches, but should still request peer reviews for larger modifications.

| [#contribution-checklist-test]#<<contribution-checklist-test,Test>>#
|
Define all of the required tests; unit, integration, and manual testing.
Any addition to the project should define at least the basic unit and integration tests to help assure system stability and ease future development.

[NOTE]
====
*DevNote* add reference to testing guidelines
====

| [#contribution-checklist-document]#<<contribution-checklist-document,Document>>#
|
Document your work so other contributors, low-code platform developers, and end-users know about your addition.

Refer to the xref:documentation/index.adoc[documentation documentation] for details regarding producing documentation.

|===

== Where to next

To learn more on how to setup and develop for each component, refer to xref:corteza-server/index.adoc[{PRODUCT_NAME} server], xref:web-applications/index.adoc[Web applications], xref:corteza-js/index.adoc[corteza-js], or xref:corteza-vue/index.adoc[corteza-vue].

To learn more about our release cycle and how we release the product (how the code is compiled and how images are built), refer to the xref:release-cycle/index.adoc[release cycle] documentation.

To learn how to contribute to the documentation, refer to the xref:documentation/index.adoc[documentation documentation].
