include::ROOT:partial$variables.adoc[]

= Local Webapp Setup

== API endpoint

{PRODUCT_NAME} web applications connect with the API via the REST interface.
The location of the API is specified in the `public/config.js` file.
The exact request URL is generated by the underlying API client that the web application uses.

[source,js]
----
window.CortezaAPI = '$API_DOMAIN'
----

== Authentication endpoint

=== Explicitly defined

{PRODUCT_NAME} web applications authenticate using an OAuth2 flow.
//N's note: authenticate what? The user, the account, the ...?
The location of the authentication provider can be defined in the `public/config.js` file.

[source,js]
----
window.CortezaAuth = '$API_DOMAIN/auth'
----

=== Implicitly defined

If the authentication endpoint is *not explicitly set*, it is generated using the `CortezaAPI` parameter.

* `CortezaAPI` endpoint is explicitly set and ends with `/api`; the `/api` suffix is replaced with `/auth` and implicitly used as `CortezaAuth`.
* `CortezaAPI` endpoint is explicitly set and does not end with `/api`; the `/auth` suffix is appended to the `CortezaAPI` value and implicitly used as `CortezaAuth`.

As mentioned in the API file, you are able to add new endpoints in order to rebuild definitions; you can combine implicit and explicit settings.

.Examples
|===
| Description | CortezaAPI | CortezaAuth

| Setting both endpoints explicitly
//N's note: referring to Adding new endpoints in api.adoc? It might be worth mentioning that there can be 2 endpoints. If I understand this correctly, my attempt should work, if not, add the fact onto this page wherever appropriate (or give me more info on it and I'll do it).
| `window.CortezaAPI = '{API_DOMAIN}'`
| `window.CortezaAuth = '{API_DOMAIN}/auth'`

| Setting CortezaAPI only
| `window.CortezaAPI = '{API_DOMAIN}/custom'`
| `window.CortezaAuth = '{API_DOMAIN}/custom/auth'`

| Setting CortezaAPI with auto set
| `window.CortezaAPI = '{API_DOMAIN}/api'`
| `window.CortezaAuth = '{API_DOMAIN}/auth'`
|===

[NOTE]
====
Refer to the xref:devops-guide:configuration/server.adoc[*server configuration*] section for more detail.
====

//Nika's note: specify what the lines in 13 and 25 are (in case they are shown in what the reader sees)
