include::ROOT:partial$variables.adoc[]

= Local Webapp Setup

== API endpoint

{PRODUCT_NAME} web applications connect with the API via the REST interface.
The location of the API is specified in the `public/config.js` file.
The exact request URL is generated by the underlying API client that the web application uses.

[source,js]
----
window.CortezaAPI = '$API_DOMAIN'
----

== Authentication endpoint

=== Defined explicitly

{PRODUCT_NAME} web applications authenticate using an OAuth2 flow.
The location of the authentication provider can be defined in the `public/config.js` file.

[source,js]
----
window.CortezaAuth = '$API_DOMAIN/auth'
----

=== Defined implicitly

If the authentication endpoint is *not* explicitly set, it is generated using the `CortezaAPI` parameter.

* `CortezaAPI` endpoint is explicitly set and ends with `/api`: the `/api` suffix is replaced with `/auth` and implicitly used as `CortezaAuth`.
* `CortezaAPI` endpoint is explicitly set and does not end with `/api`: the `/auth` is suffix is appended to the `CortezaAPI` value and implicitly used as `CortezaAuth`.

.Examples
|===
| Description | CortezaAPI | CortezaAuth

| Setting both endpoints explicitly.
| `window.CortezaAPI = '{API_DOMAIN}'`
| `window.CortezaAuth = '{API_DOMAIN}/auth'`

| Setting only CortezaAPI.
| `window.CortezaAPI = '{API_DOMAIN}/custom'`
| `window.CortezaAuth = '{API_DOMAIN}/custom/auth'`

| Setting CortezaAPI with auto set
| `window.CortezaAPI = '{API_DOMAIN}/api'`
| `window.CortezaAuth = '{API_DOMAIN}/auth'`
|===

[NOTE]
====
Refer to the xref:devops-guide:configuration/server.adoc[*server configuration*] section for more details.
====
