include::../../../variables.adoc[]
= {PRODUCT_NAME} Command Line Interface (CLI)

{PRODUCT_NAME} comes with command line interface tool. With it, you can manually or automatically change applications settings,
add users, roles, and run the API. You are using the same binary that can start the backend service and the API.

.Depending on built flavour, you can use a different entry:
- Microservice build produce `corteza-server-system`, `corteza-server-messaging` and `corteza-server-compose`
- Monolith build produces `corteza-server` binary with system, messaging, compose subcommands

== Using the CLI tool

IMPORTANT: At least basic https://docs.docker.com/engine/docker-overview/[Docker] and https://docs.docker.com/compose/[Docker Compose] knowledge is required for most {PRODUCT_NAME} setup and management.

.Executing with Docker Compose (when service is started)
[source]
----
docker-compose exec <service name> help
----

.Executing with docker (when container is running)
[source]
----
docker exec -it <container name> help
----

.Running with Docker Compose (when service is not started)
[source]
----
docker run -it --rm <container name> help
----

.Executing with Docker (when container is not running)
[source]
----
docker run -it --rm [docker run options] <container name> help
----

NOTE: Running and executing with Docker Compose should be easier and simpler because all required options and settings
for container are packed in the Docker Compose project configuration file (`docker-compose.yaml`)

include::cli-commands.adoc[]
