include::../../../variables.adoc[]
= Delaying API execution

With `WAIT_FOR*` Delaying API execution, waiting for external (HTTP) services.

This might aid you in complex setup where another service should be running and accessible before {PRODUCT_NAME} is ready.



[cols="m,m,"]
|===
|Type|Default value|Description

3+| WAIT_FOR
| duration
| 0
| Delays API startup for the amount of time specified (10s, 2m...).

This delay happens before service (WAIT_FOR_SERVICES) probing.

3+| WAIT_FOR_STATUS_PAGE
| bool
| true
| Show temporary status web page.

3+| WAIT_FOR_SERVICES
| string
|
| Space delimited list of hosts and/or URLs to probe.
Host format: `host` or `host:443` (port will default to 80).

Services are probed in parallel.

3+| WAIT_FOR_SERVICES_TIMEOUT
| duration
| 1m
| Max time for each service probe.

3+| WAIT_FOR_SERVICES_PROBE_TIMEOUT
| duration
| 30s
| Timeout for each service probe.

3+| WAIT_FOR_SERVICES_PROBE_INTERVAL
| duration
| 5s
| Interval between service probes.
|===
