include::ROOT:partial$variables.adoc[]

= Automation scripts
:description: An automation script is a piece of code that lets you implement custom business logic. Automation scripts are written in plain JavaScript with support for node packages.
:keywords: business logic, automation, automation scripts, {PRODUCT_NAME}

An automation script (further referred to as script) is a piece of code that allows you to implement custom business logic.
Automation scripts are written in plain JavaScript with the support for node packages.

[IMPORTANT]
====
As of xref:ROOT:changelog/202103.adoc[], with the introduction of workflows, automation scripts are disabled by default.
====

Take a look at our samples (menu:Low-Code Platform Developer Guide[Automation scripts,Samples]) and <<sample-project,the sample project>> to get started.

[TIP]
====
See whether you can implement your logic using xref:automation/workflows/index.adoc[].
A workflow is able to xref:automation/workflows/automation-scripts.adoc[execute automation scripts]
====

There are two categories of automation scripts; *server scripts* and *client scripts*.

[cols="1a,5a"]
|===
| [#automation-scripts-server]#<<automation-scripts-server,Server scripts>>#
| Server scripts are executed in the *{PRODUCT_NAME} {APP_AUTOMATION} server*.

.Use server scripts when:
* working with *sensitive data*,
* communicating with *external APIs*,
* it *shouldn't be possible for the script to be interrupted* by the user.

.Examples of usage:
* *create additional records* based on the current data,
* *send email* notifications,
* run *statistic analysis*.

| [#automation-scripts-client]#<<automation-scripts-client,Client scripts>>#
| Client scripts are executed in the client's browser (user agent).

.Use client scripts when:
* you need to *interact with the user*,
* are performing *data validation*,
* *inserting* default *values*.

.Examples of usage:
* *prompt the user* to confirm the form submission,
* *validate the form* submitted by the user,
* *redirect the user* after they've submitted the form,
* open an external webpage.

[IMPORTANT]
====
Client scripts are less secure as they run in the users browser.
Any baked-in credentials are easily accessible, the execution is easily terminated.
====
|===

Which one should you use?
If you need to interact with the user (show notification, request confirmations), use *client scripts*, elsewhere use *server scripts*.

== File structure

To start writing automation scripts, you must first define the appropriate file structure.

.The three main parts:
. `package.json` defines metadata as well as your dependencies.
. `/server-scripts` contains a set of automation scripts that are executed on the {APP_AUTOMATION} server.
. `/client-scripts` contains a set of automation scripts that will be executed inside the web application.
** Each sub-directory inside `/client-scripts` defines a bundle.
When a web application loads, it fetches the bundle that is assigned to it (this is done automtically).

Both `/server-scripts` and `/client-scripts` assume that all underlying files are automation scripts with valid signatures.
When defining a file with utility functions, move it under `/shared` or define a `/util` (or similar) at the root of the project.


.An example filestructure containing all of the available parts:
[source,text]
----
package.json
...
/server-scripts
  ...
/client-scripts
  /admin
      ...
  /compose 
      ...
  /shared
      ...
----

`...` indicates that you are free to structure your files as you see fit.
We do recommend you group your automation scripts based on their content, for example, scripts working with leads should go under the `/Lead` directory.

`/admin` and `/compose` contain scripts specific to each web application (as discussed earlier).

`/shared` contains code that client scripts can reuse.

== Automation script

[CAUTION]
====
It is only possible to define one automation script per file.
====

.This is how a valid automation script looks like:
[source,js]
----
{
  // A short label describing this script
  label: '...',

  // A longer description of what it does. Don\'t go over board.
  description: '...',

  // This controls script-level security, such as the invoking user.
  // We cover some details a bit later.
  security: {...},

  // This function returns a list of triggers that specify when the script should be ran.
  // We cover some details a bit later.
  triggers: (t) {...},

  // This is the code that is ran when the script is executed.
  // We cover some details a bit later.
  exec: (args, ctx) {...};
}
----

.You can use this template to cover most cases of usage:
[source,js]
----
include::example$server-script-sample/implicit-generic.js[]
----

[NOTE]
====
See xref:automation/automation-scripts/samples/server-scripts/index.adoc[server script samples], and xref:automation/automation-scripts/samples/client-scripts/index.adoc[client script samples] for more.
====

=== Execution arguments

Execution arguments (the `args` parameter of the <<automation-script-signature,`exec` function>>) contain the core data that your logic is able to work with.
The data differs based on the event that triggered the automation script.
To examplify; user related events define what user is involved, while record related events define the involved record and the module.

[NOTE]
====
Refer to xref:automation/automation-scripts/references/resource-events.adoc[] for a complete reference of what data each event exposes.
====

[IMPORTANT]
====
Arguments to a client-script are provided via *references* to the original objects, meaning that *any change* to the argument parameter *reflects* back to the original object.

Arguments to a server-script are provided as *a copy* of the original object, meaning that the changes are *not reflected* on the original object.
====

[#execution-context]
=== Execution context

Execution context (the `ctx` parameter of the <<automation-script-signature,`exec` function>>) contains contextual information and utilities that can be used within script execution.
The context between all of the events is static.

.Execution of context parameters:
[cols="1m,5a"]
|===
| [#context-console]#<<context-console,ctx.console>>#
|
The `console` parameter defines a logger.

[NOTE]
====
When executing client scripts, this is the built-in `window.console`; when executing server secripts, this is a `Pino` logger.
====

| [#context-log]#<<context-log,ctx.log>>#
|
`ctx.log` is an alias for <<context-console,`ctx.console`>>

| [#context-authuser]#<<context-authuser,ctx.$authUser>>#
|
`$authUser` is a reference to the xref:automation/automation-scripts/index.adoc#involing-user[invoking user].

| [#context-systemapi]#<<context-systemapi,ctx.SystemAPI>>#
|
`SystemAPI` is the {PRODUCT_NAME} API client.

| [#context-composeapi]#<<context-composeapi,ctx.ComposeAPI>>#
|
`ComposeAPI` is the {PRODUCT_NAME} {APP_NAME_COMPOSE} API client.

| [#context-system]#<<context-system,ctx.System>>#
|
`System` defines a set of helper methods to work with the core system

| [#context-compose]#<<context-compose,ctx.Compose>>#
|
`Compose` defines a set of helper methods to work with {PRODUCT_NAME} {APP_NAME_COMPOSE} resources.

| [#context-composeui]#<<context-composeui,ctx.ComposeUI>>#
|
`ComposeUI` defines a set of helper methods to work with {PRODUCT_NAME} {APP_NAME_COMPOSE} user interface.

| [#context-frontendbaseurl]#<<context-frontendbaseurl,ctx.frontendBaseURL>>#
|
`frontendBaseURL` defines the base URL address that the front-end web applications are running.
This is useful when generating URL addresses that point to the {PRODUCT_NAME} applications (such as a link to the newly created lead).

|===

=== Execution result

Refer to the xref:automation/execution-flow-details.adoc[execution flow details] sub-section for details on how the execution result affects the system.

[NOTE]
====
*DevNote* document iterators and their special `Aborted` error

[source,js]
----
exec (args, ctx) {
  throw new Error('Aborted')
  // OR
  return false
}
----
====

[cols="2s,5a"]
|===
| [#exec-result-terminate]#<<exec-result-terminate,The execution is terminated>>#
|
The automation script is *terminated* when an error occurs.
This normally causes the original operation to also terminate.

.An example:
[source,js]
----
export default {
  trigger (t) {...}

  exec (args, ctx) {
    throw new Error('Oh no, something went wrong')
  }
}
----

| [#exec-result-unknown]#<<exec-result-unknown,The execution is successful>>#
|
In any other cases the automation script is *successful*.
The returned value is a zero value, if it is either `null` or `undefined`.

.An example:
[source,js]
----
export default {
  trigger (t) {...}

  exec ({ $record }, ctx) {
    return $record
  }
}
----
|===

== Automation triggers

Automation triggers (further referred to as triggers) control the timing of the execution of a specific automation script.
[IMPORTANT]
====
Automation triggers are evaluated in an isolated context that doesn't allow any external data (variables or imports).

.This will not work:
[source,js]
----
const MOD_NAME = 'Contact'

export default {
  triggers ({ on }) {
    return on('manual')
      .for(MOD_NAME) // 👈 we're referencing the constant here
  },
  exec (args, ctx) {...},
}
----
====

.The three main parts of a trigger:
. an event that specifies what system events the trigger reacts to,
. a <<trigger-define-resource,resource>> that specifies what system resource the trigger reacts for,
. a <<trigger-define-constraint,constraint>> that specifies how the event needs be presented as in order for the trigger to react.

.Available trigger types:
[cols="1a,5a"]
|===
| [#trigger-type-explicit]#<<trigger-type-explicit,Explicit>>#
| These are *explicitly triggered* by pressing a *button*.

Use explicit triggers when you wish to *manually initiate an action*, for example an OAuth authentication flow, redirection to an external resource, or data export.

| [#trigger-type-implicit]#<<trigger-type-implicit,Implicit>>#
| These are *implicitly triggered* and based on *system events*.

Use implicit triggers when you wish for an action to be *automatically performed* when triggered by another action or process; such as sending an email when you register a new user or adding a changelog entry when the content changes.

Refer to xref:automation/automation-scripts/references/resource-events.adoc[resources and events] for a complete list of events you can listen for.

| [#trigger-type-deferred]#<<trigger-type-deferred,Deferred>>#
|
[IMPORTANT]
====
Deferred triggers can only be used in server scripts and require explicit security context.
====

The system triggers these *at a certain point in the future*; either *periodically* (define with *cron expressions*), or *at a timestamp* (use *ISO 8601*, `YYYY-MM-DDThh:mm:ssZ` format).


Use deferred triggers when you want an action to *periodically repeat* or *be performed at a certain point in the future*. Examples of such use are  recurring payments or sending holiday newsletters to your subscribers.

[NOTE]
====
The scheduler acts *once per minute*, therefore that is the maximum accuracy {PRODUCT_NAME} supports.
====

| [#trigger-type-sink]#<<trigger-type-sink,Sink>>#
|
[IMPORTANT]
====
Sink triggers can only be used in server scripts and require explicit security context.
====
These are triggered by the system *when it receives a request*; either *HTTP* or *email*.

Use sink triggers when you want to *respond to requests*; such as *webhooks for external services* or *custom API endpoints*, f1or example *capturing data from external forms*, *tracking external document changes*, and *capturing payments*.

[NOTE]
====
It is recommended you use the REST API interface whenever possible.
====
|===

[#trigger-define-resource]
=== Defining a resource

To define what resource the trigger should react for (such as module, user, role), we use the conveniently named `.for('resource:goes:here')` method.

.An example of specifying a resource:
[source,js]
----
triggers ({ before }) {
  return before('create', 'update')
    // This will trigger for a compose record resource
    .for('compose:record')
},
----

Refer to xref:automation/automation-scripts/references/resource-events.adoc[resources and events] for a complete list of available resources and supported events.

[#trigger-define-constraint]
=== Defining a constraint

[NOTE]
====
Refer to xref:automation/automation-scripts/references/resource-constraints/index.adoc[resource constraints] for a list of available constraint properties for each resource.
====

To define how an event should be presented as (such as the module name, user email, role handle), we use the `.where(property, operator, value)` method or a variation of it.

.To elaborate:
* When applying two arguments to the method, the first one specifies the *property* and the second one specifies the *value*.
The default <<constraint-operator-eq,equality operator>> is used.
* When specifying three arguments to the method, the first one specifies the *property*, the second one specifies the <<trigger-comparison-operators,comparison *operator*>> and the third one specifies the *value*.

.An example of chaining constraints:
[source,js]
----
triggers ({ before }) {
  return before('create', 'update')
    .for('compose:record')
    .where('module', 'Lead')
    .where('namespace', 'crm')
},
----

[#trigger-comparison-operators]
.Available comparison operators:
[cols="1s,5a"]
|===
| [#constraint-operator-eq]#<<constraint-operator-eq,Equals (default)>>#
|
* `eq`
* `=`
* `==`
* `===`

| [#constraint-operator-neq]#<<constraint-operator-neq,Not equals>>#
|
* `not eq`
* `ne`
* `!=`
* `!==`

| [#constraint-operator-prt]#<<constraint-operator-prt,Partial equals>>#
|
* `like`

.Supported wildcards:
* *one or more characters*: `%`, `*`,
* *one character*: `_`, `?`.

| [#constraint-operator-nprt]#<<constraint-operator-nprt,Partial not equals>>#
|
* `not like`

.Supported wildcards:
* *one or more characters*: `%`, `*`,
* *one character*: `_`, `?`.

| [#constraint-operator-regex]#<<constraint-operator-regex,Regex equals>>#
|
* `~`

| [#constraint-operator-nregex]#<<constraint-operator-nregex,Regex not equals>>#
|
* `!~`

|===

=== Conventions

[cols="2s,5a"]
|===
| [#trigger-destructuring]#<<trigger-destructuring,Use object destructuring>>#
|
Object destructuring helps you shorten the code.

.Example:
[source,js]
----
// Instead of using:
triggers (t) {
  return t.after('create')
    .for('compose:record')
    .where('module', 'super_secret_module')
},

// you can do:
triggers ({ after }) { // 👈 this thing
  return after('create')
    .for('compose:record')
    .where('module', 'super_secret_module')
},
----

| [#constrained-constraints]#<<constrained-constraints,Use constraints>>#
|
Loose constraints may lead to unwanted side effects such as running the script when a record in a different namespace is created.

.Example:
[source,js]
----
// Instead of using:
triggers (t) {
  return t.after('create')
    .for('compose:record')
    .where('module', 'super_secret_module')
},

// you should do:
triggers ({ after }) {
  return after('create')
    .for('compose:record')
    .where('module', 'super_secret_module')
    .where('namespace', 'super_secret_namespace') // 👈 this thing
},
----


|===

== Security context

[#involing-user]
=== The invoking user

[IMPORTANT]
====
*Deferred* and *sink* scripts require you to specify the security context as the invoker is not known.
====

The invoking user is a person who performes an action that triggers the script execution.
To examplify; you press a button, therefore you are the invoking user.

By specifying the invoking user, the automation script may access some resources that the actual invoking user may not have access to, such as personal client information.

[CAUTION]
====
You are only able to set the invoking user for server scripts.
====

.An example of defining an invoking user:
[source,js]
----
export default {
  trigger (t) {...}

  security: 'some-user-identifier-here',

  exec (args, ctx) {...}
}
----

You can use the user's handle, email or ID as the user identifier.
We suggest you use an email or a handle.

[TIP]
====
It is a good idea to create a new system user the purpose of which is that of script execution wherever that is needed.
====

=== Allowing and denying script execution

Security context lets you prevent specific users from performing specific operations. Each user is attributed a role that specifies the degree of control they can operate with.
To examplify; you can prevent regular users from signing documents or sending quotes.

.Use these properties when defining the context:
* `allow` specifies which roles are permitted to access the automation script,
* `deny` specifies which roles are not permitted to access the automation script,

[IMPORTANT]
====
This is only available for explicit scripts.
It is ignored for any other script types
====

.An example of permitting access:
[source,js]
----
export default {
  trigger (t) {...}

  security: {
    allow: ['administrator', 'superuser'],
  },

  exec (args, ctx) {...}
}
----

.An example of denying access:
[source,js]
----
export default {
  trigger (t) {...}

  security: {
    deny: ['client', 'lead'],
  },

  exec (args, ctx) {...}
}
----

[#sample-project]
== An example setup

.The file structure (the sources are listed below):
[source,text]
----
/ .gitignore
/ .eslintrc.js
/ .mocharc.js
/ package.json

/ server-scripts
    / Sample.js
    / Sample.test.js
    / ...
/ client-scripts
    / ....
----

.gitignore:
[source,gitignore]
----
include::example$testing-setup/dotgitignore.txt[]
----

.eslintrc.js:
[source,js]
----
include::example$testing-setup/doteslintrc.js[]
----

.mocharc.js:
[source,js]
----
include::example$testing-setup/dotmocharc.js[]
----

.package.json:
[source,json]
----
include::example$testing-setup/package.json[]
----

.Sample.js
[source,js]
----
include::example$testing-setup/server-scripts/example/Sample.js[]
----

[TIP]
====
Pay attention to the following part:

[source,js]
----
// vv this line here vv
/* istanbul ignore next */
trigger ({ before }) {
  return before('create')
},
----

`istanbul ignore next` excludes the following function from the coverage report.
====

.Sample.test.js
[source,js]
----
include::example$testing-setup/server-scripts/example/Sample.test.js[]
----

.The above `package.json` defines three scripts:
* `lint` lints the code using the default ES6 standard (can be configured; see https://eslint.org/docs/rules/[here]),
* `test:unit` runs unit tests defined inside `.test.js` files (can be configured in the `.mocharc.js` file),
* `test:unit:cc` runs unit tests with code coverage.

[NOTE]
====
The code coverage report gets generated into the `coverage` directory.
For a HTML report inspect the `coverage/lcov-report` directory.

Usually the https://www.npmjs.com/package/http-server[http-server] package is used to help with this, but a simple "Open in <browser name here>" suffices.

[source,bash]
----
`http-server coverage/lcov-report`
----
====
