version: '3.5'

services:
  server:
    image: cortezaproject/corteza-server:2020.12.0-rc.2
    restart: on-failure
    depends_on: [ corredor ]
    # Direct your browser to http://localhost:18080
    ports: [ "127.0.0.1:18080:80" ]
    environment:
      HTTP_WEBAPP_ENABLED: "true"
      ACTIONLOG_ENABLED: "false"

  corredor:
    image: cortezaproject/corteza-server-corredor:2020.12.0-rc.2
    restart: on-failure
    environment:
      # Set template to use http and server API directly over internal docker network
      CORREDOR_EXEC_CSERVERS_API_BASEURL_TEMPLATE: "http://server/{service}"
