Corteza technical and user documentation
========================================

- link:src/overview/index.adoc[Overview]
- link:src/releases/index.adoc[Releases]
- link:src/user/index.adoc[User manual]
- link:src/extdev/index.adoc[Extending and customization]
- link:src/maint/index.adoc[Maintainer's manual]
- link:src/coredev/index.adoc[Core developer's documentation]
- link:src/manage/index.adoc[System management]


== Authoring

Documentatio n is written in https://asciidoctor.org/docs/what-is-asciidoc/[AsciiDoc] format and processed with https://asciidoctor.org/[AsciiDoctor]

Before you start, be sure you are familiar with https://asciidoctor.org/docs/asciidoc-writers-guide/[syntax and formatting] rules of AsciiDoc format.

.https://asciidoctor.org/docs/asciidoc-recommended-practices/[Rules to follow]:
* One sentance per line.
* Atx-style section titles

_and other recomended practices from the linked page_


=== Structure

Documentation is divided into 6 major chapters:

 * overview
 * releases
 * user manual
 * extending
 * maintainer
 * core developer
 * system management

=== Building manually

This repository contains a handy shell script, a wrapper around https://github.com/asciidoctor/docker-asciidoctor[asciidoctor docker container].
There is also a Makefile with shortcuts for building individual major chapters as HTML.

.Get *asciidoctor* command line tool help through provided docker image/container:
[source]
----
./asciidoctor.sh asciidoctor -h
----

.Build all chapters as HTML (and put them under `dist/` folder)
[source]
----
make html
----

.Build user manual chapter as HTML (and put it under `dist/user` folder)
[source]
----
make html.user
----
