include::ROOT:partial$variables.adoc[]

= Corteza Vue

The http://github.com/cortezaproject/corteza-vue[`corteza-vue`] package provides the common Vue-specific logic that should be accessible by any Vue-based web application.

The most common use cases for the `corteza-vue` package include the authentication and the API client plugins.

[NOTE]
====
Refer to the xref:release-cycle/core-repos.adoc[] for details regarding the release process.
====

== Development setup

=== Fork the `corteza-vue` repository

[CAUTION]
====
Core contributors should skip this part.
====

. go to the {GIT_REPO_LINK_PREFIX}-vue repository
. click on the btn:[Fork] button in the top right corner and follow the instructions on the screen.

=== Clone the repository

.Using the CLI:
. open the CLI
. navigate to your working folder
. run the `git clone git@github.com:$YOUR_USERNAME_HERE/corteza-vue.git` command

=== Assure dependencies

[CAUTION]
====
When using modified versions of the `corteza-js`, make sure to link it using `yarn link @cortezaproject/corteza-js`.
====

Run the `yarn` command to assure that all of the packages are present and up to date.

=== Build the bundle

Run the `yarn build` command to build a fresh bundle.
The optional `-w` flag will automatically rebuild the bundle when changes occur.

== Linking the package

Run the `yarn link` command to make this package linkable using the `yarn link @cortezaproject/corteza-vue` command.
