version: '2.1'

services:
  db:
    image: percona:8.0
    networks: [ internal ]
    environment:
      # To be picked up by percona image when creating the database
      # Must match with DB_DSN settings inside .env
      MYSQL_DATABASE:      corteza
      MYSQL_USER:          corteza
      MYSQL_PASSWORD:      change-me
      MYSQL_ROOT_PASSWORD: change-me-too
#    volumes: [ "./data/db:/var/lib/mysql" ] # use local fs
#    volumes: [ "db:/var/lib/mysql" ]        # use internal docker volume
    healthcheck: { test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"], timeout: 20s, retries: 10 }
    restart: on-failure

  server:
    image: cortezaproject/corteza-server:${VERSION}
    env_file: [ .env ]
    depends_on: { db: {condition: service_healthy}}
    networks: [ proxy, internal ]
    environment:
      VIRTUAL_HOST:     api.${DOMAIN}
      LETSENCRYPT_HOST: api.${DOMAIN}
#    volumes: [ "./data/server:/data" ] # use local fs
#    volumes: [ "server-data:/data" ]        # use internal docker volume
    restart: on-failure

  webapp:
    image: cortezaproject/corteza-webapp:${VERSION}
    networks: [ proxy ]
    environment:
      MONOLITH_API:     "true"
      VIRTUAL_HOST:     ${DOMAIN}
      LETSENCRYPT_HOST: ${DOMAIN}
    restart: on-failure

networks: { internal: {}, proxy: { external: true } }

#volumes: { db: {}, server-data: {} }
