= REST API Request life cycle

== HTTP request handling

[plantuml,api-request-life-cycle,svg]
----
@startuml
skinparam ParticipantPadding 20
skinparam BoxPadding 200
skinparam SequenceArrowThickness 2
skinparam RoundCorner 10

Server     -> Handler: HTTP Request
activate Handler
Handler    -> Controller: Request params
activate Controller
Controller -> Handler: Response payload
deactivate Controller
Handler    -> Server: HTTP Response
deactivate Handler

@enduml
----

Corteza uses standard Go's HTTP servers and handlers with https://github.com/go-chi/chi[chi] to handle request routing

Handlers, routes and request processing code is generated from `*/rest.yaml` definitions.

[NOTE]
====
Home-brew format is currently used for API definitions.
We're using https://github.com/cortezaproject/openapi3-converter[a tool] to create basic OpenAPI 3.0 definitions that is then used for API documentation (navigate to `/docs` on your Corteza server deployment)
====

Handlers read and normalise request data into *request* structures and pass them on to controllers.
Controllers are functions, that handle request and route it forward to internal service, formatting the final output.

[NOTE]
====
Controllers were initial developed to solve CRUD operations.
Further development of Corteza platform outgrew that, so you can notice some peculiar patterns (returning http.HandlerFunc functions from handlers for instance)
====

When controller completes the request, handler packs the response payload into JSON.


== A typical path from controller to store for CRUD-like requests

When request is processed in a handler there is (usually) one service function/action that is executed.

. Service action params are initialized
. Related resources (if any) are loaded (and read permissions for these resources are checked)
. Operation (read, create, update, ...) permissions are checked
. Appropriate change or lookup is done in the data store
. Results are returned to the caller

Service action ::
  All services (records, modules, users, ...) have all possible actions (and errors) defined.
  This make action (audit) logging clearer.

Related resources::
  For example: modules and namespaces for records

== Plans for the future
* Remove home-brew API definitions and replace it with OpenAPI 3
* Better support for update and partial update requests (PUT/PATCH); at the moment it's not consistant how and where the update occurs, there are permission check conflicts (user updating the resource also needs read permissions) due to slightly misaligned implementation.
