= Authentication and authorization

Corteza supports OAuth2 protocols and can act as an OAuth2 server and, optionally as an OAuth2 client.
This allows two ways how users can authenticate: using internal (local) and/or external credentials.

[TIP]
====
If you want to fully understand what is going under the hood of Corteza Auth and how OAuth 2.0 protocols work, please read https://oauth.net/2.
====

== Rationale behind this architecture:

* OAuth2 is a proven and well accepted authentication standard.
* We wanted to open Corteza for integrations and use with different applications
* Data security and access control is important but should not stand it the way of pleasant user experience
* It should fit well into existing RBAC security model
* Users should know what system to trust and where is safe to enter their credentials
* Modification of Corteza Auth UI should be trivial

== Terminology

The User::
    _In OAuth2 terminology this is a **resource owner**_
    Users will authenticate themselves and authorize client on the authorization server

Corteza Auth::
    _In OAuth2 terminology this is a **authorization server**_
    Authenticates users, authorizes clients and issues access tokens.
    At the moment, Corteza Auth runs side-by-side with Corteza API server.

Corteza API::
    _In OAuth2 terminology this is a **resource server**_
    To use Corteza API users need access tokens.
    At the moment, Corteza API runs side-by-side with Corteza Auth server.

Client, Auth Client, Third-Party Application::
    Each application that users are using to interact with Corteza API.
    These applications need to be registered inside Corteza as clients.

Local credentials::
    User's email and password

External identity providers::
    Well known identity providers as Google, LinkedIn, GitHub, LinkedIn or anyone that supports OpenID Connect (OIDC) protocol.

Security context::
    List of roles that user is using when performing actions on Corteza API.
    Roles are collected from user's role membership info and modified by Client security rules by removing prohibited, unpermitted roles and adding forced ones.

== Corteza Auth server

Enables users to give access but not their credentials to clients and applications ther are using.
This happens through secure exchange of credentials, codes, secrets and tokens.

After a **successful authentication** with local credentials or through an external provider and **authorization** of user's client application an **access token** is issued and can be used for communication with the Corteza API.

These access tokens are short-lived and must be frequently refreshed.
This is done by client that automatically and in intervals updates access (and refresh) tokens with refresh tokens.

[NOTE]
====
User's session on Corteza Auth is separated from the access tokens granted to application.
It can be reused when doing a authorization of the 2nd client and each client's access token can be revoked independently.

This is also true in reverse: logging out Corteza Auth without explicitly removing authorized clients will not have
any effect on the preauthorized clients.
====

== Authentication with local credentials

Local credentials require users to provide their email and password.
It is are enabled by default and is very configurable.

.Administrators can control weather users can
 - log-in,
 - sign-up (register),
 - if email confirmation (after sign-up) is needed, and
 - if passwords can be reset (forgot password flow)

[TIP]
====
All these settings can be set via admin panel.
They are effective immediately without server restart.
====

== Authentication through external identity provider

To enable a particular external identity providers, Corteza must be registered there to obtain ID, key or secret.
In that context, Corteza acts as third-party application.

[TIP]
====
External providers can be added, configured, disabled via admin panel.
They are effective immediately without server restart.
====

== Applications or authentication clients

Clients offer a high-level access-control on use and accessing resources over the API.

. Combination of client ID and secret
. List of scopes to limit client use of different areas of the API server
. List of redirection URIs that can be used with authorization_code grant
. Trusted flag to force users to confirm authentication
. Client validity from-to date and time
. Manipulation of user's role membership with list of allowed, denied and forced roles

[IMPORTANT]
====
We strongly advise you to create a separate Client *for each application* you integrate with.
Especially when you do not have full and complete control.
This way you always keep full access control on what and how is Corteza used and can quickly disable or otherwise remove privileges in case of abuse or security incident.
====

=== Permission to authorize a client

Corteza is using it's internal RBAC system to control if user (as a member of a certain role) can authorize the client.
When system is provisioned in a way that any user (through everyone role) can authorize any client.

=== Role membership manipulation in more detail

When authorizing a specific client, user's role membership can be manipulated.

This feature was created to allow more fine-grained control on what can users do or can not do when using a specific client.

Permitted roles::
    When at least one role is added, only those roles are added to user's security context.

Prohibited roles::
    If user is member of ar role on the prohibited list, that role is removed from user's security context.

Forced roles::
    These roles are always added to user's security context, even if he's not a member prior authorizing the client.
    Please keep in mind that this is a very powerful feature
    You can accidentally allow destructive or deny essential privileges to users

When client is authorized and user's the security context is modified through allowed/denied/forced roles all standard RBAC rules apply.

=== Default client

Corteza is configured with default client that enables Corteza's own web application to streamline the authentication for the selected client.

This way, we're saved from passing client's ID to web applications and to provide server-side OAuth2 proxy to authorize requests.

== Corteza Auth server protection and other security features

First above all, use HTTPS with valid SSL certificates.

Authentication forms and endpoints are by default protected against brute-force and cross-site request attacks.
You can also set your own secrets for JWT, CSRF and cookie value encryption.

Different expiration durations can be set on sessions temporary and permanent sessions to support your organization's security policies.

[IMPORTANT]
====
If any of the secrets are changed users will receive various warnings and will get logged-out.
====

Please see xref:ROOT:dev-ops-guide/server-configuration/index.adoc#_authentication[full list of options].
[NOTE]
====
All these options require server restart.
====

== Client authorization troubleshooting list

.Things to check when authentication is not working (unordered)
* Client's ID and secret must match
* At least one of client's redirect URIs must match (by prefix)
* Client's grant flow must match
* Client's scope must match (requested group of scopes must intersect with scopes on the client)
* User authorizing the client must be member of a role that can authorize the client
* User must be valid (confirmed email, unsuspended, undeleted)

== Common authorization flow with Corteza Auth
[plantuml,common-auth-flow,svg]
----
@startuml
|User|
:User starts authentication flow;
|Client application|
:Asks client application for link to \n**Corteza Auth** authorization server;
|Authorization server|
if (Verify redirect URI parameter) then
    |User|
    #darkred:Failed:\nInvalid redirect URI;
    stop
endif

|Authorization server|
:Present authentication\noptions for user;
|User|
:Authenticates by using local credentials\nor selecting one of the\nexternal identity provider;
|Authorization server|
if (Verify credentials) then
    |User|
    #darkred:Failed:\nInvalid credentials;
    stop
endif

|Authorization server|
if (Can user authorize this client) then
    |User|
    #darkred:Failed:\nNo permissions to authorize this client;
    stop
endif

|Authorization server|
if (Is user valid) then
    |User|
    #darkred:Failed:\nInvalid user\n(eg: unverified email);
    stop
endif

|Authorization server|
if (Is client trusted) then
    |User|
    :Prompt user\nto authorize this client;
endif

|Authorization server|
:Generate authorization code;
|Client application|
:Receive authorization code;
->exchange code for token;
|Authorization server|
:Generate access\nand refresh tokens;
|Client application|
#green:Store tokens;
stop;
@enduml
----

== Future improvements

* 2-factor authentication
* more fine-grain scopes
* per-client allow/deny list of IP addresses
* per-client access and refresh token expiration control
* per-client refresh token use
* per-client credentials use (only local-login, require 2fa, only login via specific provider)
