= Authorization client configuration examples

There are no limitations on how Corteza is used.
It can be integrated with a different system.
You can build a dedicated interface, might that be a desktop, web or a mobile application.
Each this interface, application, system is a "client" for Corteza and for each client we need some level of access control.

We strongly recommend you create separated authentication clients for each such integration to minimize security risks and maximize access control and usage overview.


== Using Corteza as authentication backend

You use an internal web email application that supports authentication via OAuth2/OIDC you can use Corteza.

Create new auth client and allow access o user's profile.
No need to access the whole API.

You can mark client as "trusted" to skip extra step where users need go through extra client authorization screen.

Make sure client is enabled and that there are no permitted, forbidden or forced roles.

=== Limiting access to a subset of users

If not configured otherwise, all users can authorize all clients.
In other words all users can use all clients for logging in.

You can limit that and create special roles and assign members to it.
When the role is ready open permission settings for thar auth client and set appropriate allow/deny combinations to "Authorize client" operation.
This will effectively prevent all users that are not members of groups that this permission.


== Using Corteza as central point for your application

You have your own specialised applications that allow users to use a dedicated user interface.
Create new auth client that allows users to login via corteza and to use it's API.

You can forbid certain roles when this client is used (e.g. Admin).
This will effectively remove listed roles from user's security context when logged-in on that client.

== Using multiple Corteza instances

When you use multiple Corteza instances to support your business you can use one for authentication central point and configure others to use the central one as identity provider (external auth provider) via OIDC protocol.
