# Compose Record Values internals


[plantuml,diagram-name-here,svg,role=sink-request]
----
@startuml
skinparam ParticipantPadding 20
skinparam BoxPadding 200
skinparam SequenceArrowThickness 2
skinparam RoundCorner 10

participant "Input"
participant "Sanitizer"
participant "Validator"
participant "Formatter"
participant "Store"
participant "Output"

activate Input
activate Sanitizer
activate Validator
activate Formatter
activate Store
activate Output

Input -> Sanitizer:
Sanitizer -> Validator:
Validator -> Formatter:
Formatter -> Store:
Store -> Output:

@enduml
----

## Data input and output (REST JSON API)
Incoming and outgoing data is always encoded in *string*.
Even unsigned 64-bit integer values are encoded as *strings*.
Main reason for this architectural design decision are JavaScript type system limitations that prevent us to types beyond 64-bit integers without additional libraries.

## Data store
Record values are currently using vertical data structure where all values are internally encoded either as *unsigned 64-bit integer* (uint64) or *string*.
Integers are used to store IDs of referenced data like other records, files, users and strings are used for all other field types.

## Sanitizers
. Makes sure all data is present and properly ordered (in case of multi-value fields)
. Makes sure there is no extra data (not defined in module fields)
. Converts string inputs of certain field types:
  * `record`, `file`, `user` (reference values) need to be unsigned 64-bit integers encoded in string
  * `boolean` field using `^(t(rue)?|y(es)?|1)$` regular expression
  * `number` field is parsed into decimal number (`float`) with max-precision from field options is used
  * `datetime` field values are parsed into internal time value accordingly to field options (date, time or date+time).

### Supported date-time parsing formats (in order):
* Date only
** `2006-01-02`
** `02 Jan 06`
** `Monday, 02-Jan-06`
** `Mon, 02 Jan 2006`
** `2006/_1/_2`
* Time only
** `15:04:05`
** `15:04`
** `15:04:05Z07:00`
** `15:04:05 MST`
** `15:04:05 -0700`
** `15:04 MST`
** `15:04Z07:00`
** `15:04 -0700`
** `3:04PM`
* Date and time:
** `2006-01-02T15:04:05Z07:00`
** `Mon, 02 Jan 2006 15:04:05 -0700`
** `Mon, 02 Jan 2006 15:04:05 MST`
** `Monday, 02-Jan-06 15:04:05 MST`
** `02 Jan 06 15:04 -0700`
** `02 Jan 06 15:04 MST`
** `Mon Jan 02 15:04:05 -0700 2006`
** `Mon Jan 02 15:04:05 -0700 2006`
** `Mon Jan _2 15:04:05 2006`
** `2006/_1/_2 15:04:05`
** `2006/_1/_2 15:04`

### Validator
This step does not have any effect on the value but it ensures that certain field types actually store valid values.
For example: ensure that `email` field type holds a valid email value.

### Formatters
Ensures all types are properly formatted and ready to storage, depending on the field type.

Referenced values (of `record`, `file`, `user`) are not subject of this.
In the current store implementation with vertical data structure, references are stored in a separated numeric column.

. Formatting rules per field types
* `boolean`
** false values are stored as empty strings
** true values are stored as `"1"` (string with value "1")
* `datetime`
** when date+time, value is stored in ISO 8601 (RFC3339) format (`2006-01-02T15:04:05Z07:00`)
** when date-only, value is stored in `YYYY-MM-DD` format (`2006-01-02`)
** when time-only, value is stored in `HH:mm:ss` (24h) format (`15:04:05`)

## Future plans
* use typed values instead of strings internally
* improved value input and output processing through store encoders/decoders
* support for real database tables (or other store-type equivalents) for improved performance and consistency
