# Executing corredor server scripts from workflow

## Intro
Automation can sometimes be overly complex, or it needs special logic that are hard implement through workflows.
With a "Corredor automation script executor" function step any of the server-scripts in the Corredor can be called. Workflow can then serve to prepare arguments for the script and to collect results from it.

## Preparing the Corredor server script

Place your scripts that will be invoked from the workflow as you would any other server script, inside `server-scripts` directory.
Add triggers definition and exec function and optionally, describe it with label and description fields.

./server-scripts/invoked-from-the-workflow.js
[source,javascript]
----
export default {
  label: 'Called From Workflow',
  description: 'This script will be called from workflow function',
  triggers ({ on }) {
    /**
     * Due to how corredor scripting system is designed right now,
     * triggers still need to be defined; even if script is
     * executed explicitly from the workflow
     */
    return on('manual').for('system')
  },

  exec (args, { logger }) {
    logger.info('success')
  }
}
----

[NOTE]
====
Even though, script will be executed explicitly from workflow minimum trigger definition is still needed.
====


When the script is ready you can navigate your browser to administration panel under "Automation"/"Corredor Scripts" to see the list of recognized scripts.
Find the script in the list and copy the reference to the script.
For the example above, reference would be `/server-scripts/invoked-from-the-workflow.js:default`.
This reference will be used to tell workflow function which script to execute.

If script is not listed, verify if triggers are defined correctly and that there are no syntax errors in the script.
Check the Corredor server logs if there are any related errors when script is loaded and parsed.


## Minimum workflow definition

To execute the Corredor script, you need to add the function step and select the "Corredor automation script executor" function. Place your script reference under script argument.

To test run the workflow add a trigger and connect it to the function step.
These two steps are enough to run the script.
Inspect your corredor log to see if "success" string is logged.

## Custom arguments for the Corredor script

In order to pass arguments to the script we need to prepare them in the workflow.
Add an expression step between the trigger and function from the previous example.

.Expressions
[source]
----
scriptArgs          (Vars)
scriptArgs.from     (Boolean) = false
scriptArgs.workflow (String)  = "some string"
----

First line defines an empty Vars variable and 2nd and 3rd set `a` and `workflow` keys with values.

When expression step is ready, modify the function step and add `scriptArgs` to the `args` argument.

Then modify the automation script like the following example:

./server-scripts/invoked-from-the-workflow.js
[source,javascript]
----
export default {
  // ...

  exec (args, { logger }) {
    // unpack arguments
    const { from, workflow } = args

    // log all arguments
    logger.info('these are the special arguments we received', { from, workflow })
  }
}
----

When testing the script, you should see the log line with the values from the workflow.


## Collecting results from the script

When arguments are returned from the script you can collect them by setting them to the target variable.

./server-scripts/invoked-from-the-workflow.js
[source,javascript]
----
export default {
  // ...

  exec (args, { logger }) {
    logger.info('returning some values from the script')
    return {
      a: 123,
      b: true
    }
  }
}
----

Example above would return results in form of Vars with 2 keys: `a` and `b`.

[NOTE]
====
Standard corredor script rules for return values apply.
If script returns `false` we consider this as "Abort" signal -- workflow execution will result in an error.

To allow workflow to successfuly parse the values returned from the script, make sure you return an object.
====
