include::ROOT:partial$variables.adoc[]

= Accessing {PRODUCT_NAME}
:keywords: API, {PRODUCT_NAME} API, {PRODUCT_NAME}
:description: Learn how to access {PRODUCT_NAME} using it's API-centric design

{PRODUCT_NAME} separates the back-end business logic and the front-end user interface by defining an API that the clients (web applications and other custom applications) can access.

{PRODUCT_NAME} is API-centric, meaning that everything can be done via an API endpoint.

[#authentication]
== Authentication

{PRODUCT_NAME} uses bearer JWT tokens when authenticating HTTP requests.

[WARNING]
====
JWT tokens grant access to your system, so treat them as login credentials.
====

=== Obtaining Access Tokens

Before you can obtain the access token, you need to define an *auth client*, and a *system user*.
You can use an existing user (such as yourself), or create a dedicated user.

[CAUTION]
====
Make sure that the system user has sufficient roles to be able to access resources which you wish to access.
====

Create a new auth client with the `client_credentials` grant type.
Insert the ID of the selected user under the "Impersonate user" (the user that is mentioned above).

[IMPORTANT]
====
Make sure that you are using {PRODUCT_NAME} xref:ROOT:changelog/202103.adoc#p2021_3_4[2021.3.4] or any subsequent versions.
====

If the user's ID is not set or is not valid, an `Error: "auth client security configuration invalid"` error is returned.

.Use the following cURL request example to fetch the access token:
[source,bash]
----
curl -X POST $CORTEZA_URL/auth/oauth2/token \
     -d grant_type=client_credentials \
     -d scope=api \
     -u <client id>:<client secret>
----

.An example of the cURL request:
[source,bash]
----
curl -X POST $CORTEZA_URL/auth/oauth2/token \
     -d grant_type=client_credentials \
     -d scope=api \
     -u 229978909641277628:sMVVcYpXE6bOUm6gG0sJGKmDOzEgkYyhvKyrmcU9fGY8M4GhLd90lThZDxUUFLC9
----

.An example response object:
[source,json]
----
{
  "access_token": "ey...MsLA",
  "expires_in": 7200,
  "refresh_token_expires_in": 0,
  "scope": "api",
  "sub": "229974909641277121",
  "token_type": "Bearer"
}
----

[CAUTION]
====
The above token expires after two hours; make sure to fetch a new one when necessary.
====

=== Using Access Tokens

Each HTTP request to a *protected resource* must provide the bearer JWT token in the `authorization` header.

.Unauthorized requests yield an error response of:
[source,json]
----
{
  "error": {
    "message": "Unauthorized"
  }
}
----

.An example cURL with authentication:
[source,bash]
----
curl "$CORTEZA_URL" \
  -H 'accept: application/json, text/plain, */*' \
  -H "authorization: Bearer $JWT";
----

.An example cURL without authentication:
[source,bash]
----
curl "$CORTEZA_URL" \
  -H 'accept: application/json, text/plain, */*';
----

// @todo update/assure the bellow list
//
// Most of the endpoints exposed by {PRODUCT_NAME} are protected except for the ones listed in the table below.

// .System endpoints with alternative request authentication:
// [cols="1m,5a"]
// |===
// | Endpoint | Other authentication methods

// | `GET /attachment/\{kind}/\{attachmentID}/original/\{name}`
// | System generated signature.

// | `GET /attachment/\{kind}/\{attachmentID}/preview.\{ext}`
// | System generated signature.

// // ----

// | `GET /auth/`
// | None.

// | `GET /auth/check`
// | None.

// | `POST /auth/exchange`
// | None.

// | `GET /auth/logout`
// | None.

// | `POST /auth/internal/login`
// | None.

// | `POST /auth/internal/signup`
// | None.

// | `POST /auth/internal/request-password-reset`
// | None.

// | `POST /auth/internal/exchange-password-reset-token`
// | System generated password reset token.

// | `POST /auth/internal/reset-password`
// | System generated password reset token.

// | `POST /auth/internal/confirm-email`
// | System generated token.

// // ----

// | `* /sink/*`
// | System generated sink signature.

// |===

.{PRODUCT_NAME} {APP_NAME_COMPOSE} endpoints with alternative request authentication:
[cols="1m,5a"]
|===
| Endpoint | Other authentication methods

| `GET /namespace/\{namespaceID}/attachment/\{kind}/\{attachmentID}/original/\{name}`
| System generated signature.

| `GET /namespace/\{namespaceID}/attachment/\{kind}/\{attachmentID}/preview.\{ext}`
| System generated signature.

|===

.{PRODUCT_NAME} {APP_NAME_FEDERATION} endpoints with alternative request authentication:
[cols="1m,5a"]
|===
| Endpoint | Other authentication methods

| `POST /nodes/\{nodeID}/handshake`
| System generated OTT token.

|===

[#api-endpoints]
== Endpoints

Each {PRODUCT_NAME} instance ships with a built-in API reference that is accessible on the `/docs` endpoint of your {PRODUCT_NAME} API.

[NOTE]
====
If you are using a *different sub-domain* for your API (two separate Docker containers for web app and API), the URL should look something like `https://api.$BASE_URL/docs`.

If you are using *the same domain* for your API (a single Docker container for web app and API), the URL should look something like `https://$BASE_URL/api/docs`.
====
//Editor's note: you could add a hyperlink to the word "this" - like you do oin some other instances.

Here endpoints used for debugging and maintenance are covered.
Refer to the built-in API reference for the complete list of available endpoints.

[TIP]
====
You can use https://latest.cortezaproject.org/api/docs/[community instance] API reference.
====

In addition to the API reference mentioned above, these are the system-level endpoints that need to be explicitly enabled.
They can be enabled for development or debugging but should be disabled when running in production.

.System-level Endpoints:
[cols="1m,5a"]
|===
| Option | Endpoints

| HTTP_ENABLE_DEBUG_ROUTE
|
* `/__profiler` provides server runtime profiling data in the format expected by the pprof visualization tool.
* `/__routes` provides a list of all registered routes.
* `/__eventbus` presents a list of all registered automation script triggers.
* `/__corredor` presents a list of all registered automation scripts.

| HTTP_ENABLE_VERSION_ROUTE
|
* `/version` shows the build time and the {PRODUCT_NAME} version.

| HTTP_ENABLE_HEALTHCHECK_ROUTE
|
* `/healthcheck` performs and displays the system health check.

|===

[#response-format]
== Response Data Format

{PRODUCT_NAME} implements three different response formats based on what you are trying to do, and based on the status.

[IMPORTANT]
====
Error responses use the status code 200 OK, instead of the standard 4xx/5xx -- legacy reasons.
Our API clients cover this case and throw correct errors.
====

.The different response formats:
[cols="2a,5a"]
|===
| [#response-single-items]#<<response-single-items,Working with single items>>#
|

When working with single items, the item (or its status) is provided in the response object.

.Example:
[source,json]
----
{
  "response": {...}
}
----

| [#response-multiple-items]#<<response-multiple-items,Working with multiple items>>#
|

When working with multiple items, the list of items is provided in the response array along with the filter object.

.Example:
[source,json]
----
{
  "response": {
    "filter": {...},
    "set": [...]
  }
}
----

[NOTE]
====
The structure of the `filter` property differs based on the resource.
In general, it specifies what filters were applied to the responding set.
====

| [#response-errors]#<<response-errors,Encountered an error>>#
|

When an error occurs, the error message is provided under the `error.message` property.

.Example:
[source,json]
----
{
  "error": {
    "message": "..."
  }
}
----

When you enable error tracing via the `HTTP_ERROR_TRACING` environment variable, the additional error contexts are provided in the `stack` and `wrap` properties.
This can be useful for debugging but should be turned off in production.

.Example:
[source,json]
----
{
  "error": {
    "message": "...",
    "stack": [...],
    "wrap": {...}
  }
}
----

|===
