include::../../variables.adoc[]

= Contacts

This page gives a 360 degree overview of a single contact. It shows contact data, related cases and all emails sent.

== Contact data

Each account can have one or multiple contacts.
They are identified by name and email, which is found under "Personal Data".
Other optional personal fields include title, phone number and social media profiles.
The Twitter field automatically populates the Twitter feed on the right.

The "Contact Address" block contains the account name and address, and the "Other Information" shows the contact owner (an agent), Do Not Call and Email Opt Out values and an optional long description.
The sales agent has to check if an contact has opted out for calls and emails before contacting.

== Related cases

The "Cases related to this Contact" block shows all cases where the contact is selected in the "Case Details" block.
The list shows a summary of each case (case number, status, priority, subject, time, cost and creation date) and it's ordered by date.
The list is searchable and filterable, and allows adding new case records.

When using the "+Add new record" button to create a new case for this contact, the contact field in the "Case Details" block is automatically populated.

== Emails

All emails sent to a contact are shown in chronological order in this list.
The content of the email is shown directly in the list.

