include::ROOT:partial$variables.adoc[]

= `2022.3.0`

*Released on*: TBD

.[#2022_3_0-added]#<<2022_3_0-added,Added:>>#
* Added additional development tools for nicer user experience; step configuration preview on hover ({WEBAPP_WORKFLOW_COMMIT_BASE}b017702[`b017702`] {WEBAPP_WORKFLOW_COMMIT_BASE}6e2a4be[`6e2a4be`] {WEBAPP_WORKFLOW_COMMIT_BASE}51d1f9e[`51d1f9e`]), additional help labels ({WEBAPP_WORKFLOW_COMMIT_BASE}214c973[`214c973`]), and a predefined HTTP method select ({SERVER_COMMIT_BASE}5e59bbab2[`5e59bbab2`]).
* Added additional workflow prompts to redirect to a record create page ({WEBAPP_VUE_COMMIT_BASE}a021552[`a021552`] {WEBAPP_VUE_COMMIT_BASE}c1fe4ff[`c1fe4ff`]) and to allow record selection ({WEBAPP_VUE_COMMIT_BASE}aba32e6[`aba32e6`]).
* Added additional support in workflows for paging over {APP_NAME_COMPOSE} records (https://github.com/cortezaproject/corteza-server/pull/336[`#336`]).
* Added default workflow step labels when no custom label is provided ({WEBAPP_WORKFLOW_COMMIT_BASE}3854ddd[`3854ddd`]).
* Added xref:2022.3@devops-guide:troubleshooting/web-console.adoc[web console] -- a user interface for inspecting and troubleshooting server-side issues (https://github.com/cortezaproject/corteza-server/pull/327[`#327`], {SERVER_COMMIT_BASE}7fa5e43d0[`7fa5e43d0`], {SERVER_COMMIT_BASE}f66ab4550[`f66ab4550`], {SERVER_COMMIT_BASE}9eca65595[`9eca65595`], {SERVER_COMMIT_BASE}f291cde93[`f291cde93`]).
* Added API endpoints with a landing page and 404 pages ({SERVER_COMMIT_BASE}a81f35d5a[`a81f35d5a`]).
* Added additional configuration for page configuration ({SERVER_COMMIT_BASE}b478b3777[`b478b3777`]) and general UI, sidebar, and top bar settings ({SERVER_COMMIT_BASE}f69751190[`f69751190`], {WEBAPP_COMPOSE_COMMIT_BASE}a2dd9fe5[`a2dd9fe5`], {SERVER_COMMIT_BASE}eb583a339[`eb583a339`], {SERVER_COMMIT_BASE}c558ece3b[`c558ece3b`], {SERVER_COMMIT_BASE}2b6026182[`2b6026182`], {WEBAPP_ADMIN_COMMIT_BASE}bed4f1b[`bed4f1b`], {WEBAPP_WORKFLOW_COMMIT_BASE}6134d9b[`6134d9b`], {WEBAPP_REPORTER_COMMIT_BASE}314d1d1[`314d1d1`], {WEBAPP_VUE_COMMIT_BASE}2659085[`2659085`], {WEBAPP_VUE_COMMIT_BASE}97dea83[`97dea83`], {WEBAPP_VUE_COMMIT_BASE}e4f2977[`e4f2977`]).
* Added support for record page editing the same way as list pages can be edited ({WEBAPP_COMPOSE_COMMIT_BASE}8bb77988[`8bb77988`]).
* Added an "open in new tab" option for links defined in the rich text editors ({WEBAPP_VUE_COMMIT_BASE}e4fddb3[`e4fddb3`]).
* Added additional import export capabilities by adding a user import and export to the {PRODUCT_NAME} {APP_NAME_ADMIN} ({SERVER_COMMIT_BASE}9142c7b5a[`9142c7b5a`], {WEBAPP_ADMIN_COMMIT_BASE}84f86bb[`84f86bb`], {WEBAPP_ADMIN_COMMIT_BASE}89f4aab[`89f4aab`], {WEBAPP_JS_COMMIT_BASE}2b04d79[`2b04d79`]); as well as including access control and resource translations to the existing namespace export ({SERVER_COMMIT_BASE}8e679bf97[`8e679bf97`]).
* Added xref:2022.3@integrator-guide:discovery/index.adoc[{PRODUCT_NAME} {APP_NAME_DISCOVERY}] -- a search engine for your data ({SERVER_COMMIT_BASE}7bde98697[`7bde98697`], {SERVER_COMMIT_BASE}84f918a1d[`84f918a1d`], {SERVER_COMMIT_BASE}d384db951[`d384db951`], {SERVER_COMMIT_BASE}4e3d5dd00[`4e3d5dd00`], {SERVER_COMMIT_BASE}b6ff0f921[`b6ff0f921`], {WEBAPP_COMPOSE_COMMIT_BASE}ed1122d6[`ed1122d6`]).
* Added delete strategy for {APP_NAME_COMPOSE} pages when the page has nested child pages ({SERVER_COMMIT_BASE}691481424[`691481424`], {WEBAPP_COMPOSE_COMMIT_BASE}efb45ff8[`efb45ff8`]).
* Added improvements to resource searching and filtering by adding support for date/time only fields ({SERVER_COMMIT_BASE}640a90c20[`640a90c20`]) as well as introducing fuzzy searching to some resources ({WEBAPP_VUE_COMMIT_BASE}03a6f7c[`03a6f7c`], {WEBAPP_COMPOSE_COMMIT_BASE}4f28578e[`4f28578e`], {WEBAPP_WORKFLOW_COMMIT_BASE}29b71da[`29b71da`], {WEBAPP_VUE_COMMIT_BASE}8500f61[`8500f61`]).
* Added support for `Record` fields to query based on a nested `Record` field, limited to *1 level* ({WEBAPP_COMPOSE_COMMIT_BASE}155e6b12[`155e6b12`], {WEBAPP_JS_COMMIT_BASE}eb4c911[`eb4c911`]).
* Added support for multiple presort definitions on record lists ({WEBAPP_COMPOSE_COMMIT_BASE}80f3ad47[`80f3ad47`]).
* Added support to define custom clientID and scope when generating JWT tokens from the CLI ({SERVER_COMMIT_BASE}957e70056[`957e70056`]).
* Added integration between {APP_NAME_REPORTER} and {APP_NAME_COMPOSE} by introducing the xref:2022.3@integrator-guide:compose-configuration/page-blocks.adoc#page-block-report[reporter page block] to show report data on {APP_NAME_COMPOSE} pages ({WEBAPP_COMPOSE_COMMIT_BASE}89664b8a[`89664b8a`], {WEBAPP_REPORTER_COMMIT_BASE}7201f70[`7201f70`], {WEBAPP_JS_COMMIT_BASE}b4667c5[`b4667c5`], {WEBAPP_VUE_COMMIT_BASE}a0b8913[`a0b8913`]).
* Added a new xref:2022.3@integrator-guide:compose-configuration/field-types.adoc#field-type-geometry[`Geometry` field] to store geo location, primarily for use with {APP_NAME_DISCOVERY} ({WEBAPP_COMPOSE_COMMIT_BASE}cb3ac6c2[`cb3ac6c2`], {WEBAPP_JS_COMMIT_BASE}3f56b79[`3f56b79`], {WEBAPP_JS_COMMIT_BASE}2a12fc0[`2a12fc0`]).
* Added support to hide selected roles from the permission list ({WEBAPP_ADMIN_COMMIT_BASE}5bdc3e9[`5bdc3e9`]).
* Added additional media styling for nicer PDF output ({WEBAPP_COMPOSE_COMMIT_BASE}908ba673[`908ba673`]).
* Added Integration gateway profiler ({SERVER_COMMIT_BASE}9a7f6f90[`9a7f6f90`], {WEBAPP_ADMIN_COMMIT_BASE}cbd7ab45[`cbd7ab45`]).

//
//

.[#2022_3_0-changed]#<<2022_3_0-changed,Changed:>>#
* Changed auth templates to use general assets ({SERVER_COMMIT_BASE}43ddaf1e5[`43ddaf1e5`]).
* Changed packages to use the more recent versions, more notably `jwx goth`, and `jwt` ({SERVER_COMMIT_BASE}6eda39f3a[`6eda39f3a`]) as well as switching to `go 1.17` ({SERVER_COMMIT_BASE}2d90fe4e9[`2d90fe4e9`]).
* Changed `onTimestamp` workflow triggers to use the new date time component ({WEBAPP_WORKFLOW_COMMIT_BASE}e18230b[`e18230b`]).
* Changed the expression workflow step to show the add button on the bottom of the list rather then on top ({WEBAPP_WORKFLOW_COMMIT_BASE}b16cb39[`b16cb39`]).
* Changed the workflow step configurator sidebar to use faster transitions for nicer user experience ({WEBAPP_WORKFLOW_COMMIT_BASE}642d3e2[`642d3e2`]).
* Changed the workflow error and delay steps to use expressions instead of constant values ({WEBAPP_WORKFLOW_COMMIT_BASE}5754544[`5754544`], {WEBAPP_WORKFLOW_COMMIT_BASE}9ad29f7[`9ad29f7`]).
* Changed the reports to display users with a user-friendly identifier (name, email, ...) instead of the system user ID ({SERVER_COMMIT_BASE}506a92d2c[`506a92d2c`], {SERVER_COMMIT_BASE}ac6e7332a[`ac6e7332a`]).
* Changed the stack trace log level to "dpanic" ({SERVER_COMMIT_BASE}3f7755cd0[`3f7755cd0`]).
* Changed PageBuilder positioning to avoid toolbar with icons appearing below the Block's title and description ({WEBAPP_COMPOSE_COMMIT_BASE}667a9b0[`667a9b0`]).
* Changed the {APP_NAME_COMPOSE} record list by defining a default limit and a maximum limit to prevent the server from getting overwhelmed ({SERVER_COMMIT_BASE}9e5fd42d4[`9e5fd42d4`]).
* Changed the {APP_NAME_COMPOSE} admin panel side navigation to show the resources in a tree representation for easier overview and access ({WEBAPP_COMPOSE_COMMIT_BASE}14968080[`14968080`], {WEBAPP_COMPOSE_COMMIT_BASE}81e1c340[`81e1c340`], {WEBAPP_VUE_COMMIT_BASE}8262db5[`8262db5`]).
* Changed user display to fall back to user handle before the user ID ({WEBAPP_JS_COMMIT_BASE}d1238b1[`d1238b1`]).
* Changed {APP_NAME_COMPOSE} expression reference to redirect to the documentation ({WEBAPP_COMPOSE_COMMIT_BASE}67834a52[`67834a52`]).
* Changed inline record list editing to work on list pages instead of only record pages ({WEBAPP_COMPOSE_COMMIT_BASE}6d070b62[`6d070b62`]).
* Changed the Integration Gateway request processing using automation workflows by defining more flexible interfaces to access the data (https://github.com/cortezaproject/corteza-server/pull/324[`#324`], {SERVER_COMMIT_BASE}460646d45[`460646d45`]).
* General UI changes ({WEBAPP_COMPOSE_COMMIT_BASE}1b33bad3[`1b33bad3`], {WEBAPP_COMPOSE_COMMIT_BASE}c6bf400b[`c6bf400b`], {WEBAPP_COMPOSE_COMMIT_BASE}31d33048[`31d33048`], {WEBAPP_COMPOSE_COMMIT_BASE}1c0ec5ae[`1c0ec5ae`], {WEBAPP_COMPOSE_COMMIT_BASE}ab987f3d[`ab987f3d`], {WEBAPP_ADMIN_COMMIT_BASE}feed8f0[`feed8f0`], {WEBAPP_ADMIN_COMMIT_BASE}4f0e67b[`4f0e67b`]), tweaked responsive design ({WEBAPP_COMPOSE_COMMIT_BASE}e7cfa97c[`e7cfa97c`]), hiding/disabling buttons when they shouldn't be available ({WEBAPP_COMPOSE_COMMIT_BASE}36195451[`36195451`], {WEBAPP_COMPOSE_COMMIT_BASE}59c797b8[`59c797b8`]), changed visual assets ({WEBAPP_COMPOSE_COMMIT_BASE}f5b09bf5[`f5b09bf5`], {WEBAPP_WORKFLOW_COMMIT_BASE}5c72c30[`5c72c30`]).
* Changed the action log layout to match other log lists ({WEBAPP_ADMIN_COMMIT_BASE}f96062e[`f96062e`]).
* Changed funnel charts to be more configurable ({WEBAPP_COMPOSE_COMMIT_BASE}dd28baec[`dd28baec`], {WEBAPP_JS_COMMIT_BASE}4d0eafb[`4d0eafb`]).

//
//

.[#2022_3_0-removed]#<<2022_3_0-removed,Removed:>>#

//
//

.[#2022_3_0-fixed]#<<2022_3_0-fixed,Fixed:>>#
* Fixed SQLite data loss caused by mid-use session disconnect ({SERVER_COMMIT_BASE}23c7f357f[`23c7f357f`]).
* Fixed invalid session lifetime when a user signs up; was set to zero ({SERVER_COMMIT_BASE}f53463a32[`f53463a32`]).
* Fixed external authentication provider removal issues ({SERVER_COMMIT_BASE}74b3ddf94[`74b3ddf94`]).
* Fixed improper user-id claim parsing ({SERVER_COMMIT_BASE}6c7d89a92[`6c7d89a92`]).
* Fixed exported auth asset serving for non-development modes ({SERVER_COMMIT_BASE}dfe19c4c3[`dfe19c4c3`]).
* Fixed overflowing workflow step labels ({WEBAPP_WORKFLOW_COMMIT_BASE}e424627[`e424627`]).
* Fixed premature workflow execution termination caused by parallel delay steps ({SERVER_COMMIT_BASE}4fd0ddfaa[`4fd0ddfaa`]).
* Fixed improper workflow event management by manually removing event listeners ({WEBAPP_WORKFLOW_COMMIT_BASE}deb301f[`deb301f`]), properly destroying instances ({WEBAPP_WORKFLOW_COMMIT_BASE}a192b4a[`a192b4a`]), and making the `ctrl+s` key binding work more reliably ({WEBAPP_WORKFLOW_COMMIT_BASE}faa25d1[`faa25d1`]).
* Fixed workflow configurator side panel not allowing to open paths ({WEBAPP_WORKFLOW_COMMIT_BASE}8e0148f[`8e0148f`]).
* Fixed improper actionlog metadata type encoding/decoding ({SERVER_COMMIT_BASE}e833796aa[`e833796aa`]).
* Fixed invalid system configuration procedure where default settings potentially got omitted ({SERVER_COMMIT_BASE}7fd719364[`7fd719364`]).
* Fixed system panic caused by websockets ({SERVER_COMMIT_BASE}f76b94e74[`f76b94e74`]).
* Fixed report name conflicts with system values ({SERVER_COMMIT_BASE}ab8668955[`ab8668955`]) and missing values on the PostgreSQL database ({SERVER_COMMIT_BASE}cd15f3eaf[`cd15f3eaf`]).
* Fixed reporter including deleted namespaces in report output ({SERVER_COMMIT_BASE}908008eba[`908008eba`]).
* Fixed display elements not rendering when switching between different reports ({WEBAPP_REPORTER_COMMIT_BASE}24d163a[`24d163a`]).
* Fixed missing locale HTTP headers when making requests from the reporter web application ({WEBAPP_REPORTER_COMMIT_BASE}8215602[`8215602`]).
* Fixed reporter table display element raising errors if no data is available ({WEBAPP_VUE_COMMIT_BASE}d2b0ad0[`d2b0ad0`]).
* Fixed missing module field resource translations ({SERVER_COMMIT_BASE}e9dfe8254[`e9dfe8254`]).
* Fixed improper empty resource translation handling by soft-deleting the value instead of omitting the change ({SERVER_COMMIT_BASE}631811929[`631811929`]).
* Fixed improper resource translation updating and handling for {APP_NAME_COMPOSE} pages and modules ({WEBAPP_COMPOSE_COMMIT_BASE}c24d7160[`c24d7160`]).
* Fix the number of records to be exported in ExporterModal ({WEBAPP_COMPOSE_COMMIT_BASE}8f5f2c3[`8f5f2c3`]).
* Fixed Right-To-Left detection to work based on current user language ({WEBAPP_COMPOSE_COMMIT_BASE}30cc4eb7[`30cc4eb7`], {WEBAPP_ADMIN_COMMIT_BASE}c882464[`c882464`]).
* Fixed filtering for time and date only `DateTime` fields ({WEBAPP_COMPOSE_COMMIT_BASE}a755b984[`a755b984`], {WEBAPP_COMPOSE_COMMIT_BASE}6ab98c52[`6ab98c52`], {WEBAPP_COMPOSE_COMMIT_BASE}a755b984[`a755b984`]).
* Fixed automation button removal for unconfigured buttons in the record list page block configurator ({WEBAPP_COMPOSE_COMMIT_BASE}7a7307b6[`7a7307b6`]).
* Fixed record organizer, changed prefilter evaluation ({WEBAPP_COMPOSE_COMMIT_BASE}74b047de[`74b047de`], {WEBAPP_COMPOSE_COMMIT_BASE}2ea20d86[`2ea20d86`]) and added additional record source evaluation ({WEBAPP_COMPOSE_COMMIT_BASE}5cbefcb8[`5cbefcb8`]).
* Fixed record list filtering by properly handling `Boolean` values ({WEBAPP_COMPOSE_COMMIT_BASE}43a1d3cf[`43a1d3cf`]), added missing system fields ({WEBAPP_COMPOSE_COMMIT_BASE}67e7f4fa[`67e7f4fa`], {WEBAPP_COMPOSE_COMMIT_BASE}7cae2b0b[`7cae2b0b`]), tweaked internal logic ({WEBAPP_COMPOSE_COMMIT_BASE}f11def50[`f11def50`], {WEBAPP_COMPOSE_COMMIT_BASE}751c589b[`751c589b`]), fixing improper field kind handling ({WEBAPP_COMPOSE_COMMIT_BASE}1082cf73[`1082cf73`]), and adding a fallback to the equality operator ({WEBAPP_COMPOSE_COMMIT_BASE}b5ee8752[`b5ee8752`]).
* Fixed settings not applying when they are updated and saved ({WEBAPP_ADMIN_COMMIT_BASE}7f5eebe[`7f5eebe`]).
* Fixed timeout issues in http request workflow function ({SERVER_COMMIT_BASE}6620b6ea[`6620b6ea`]).
* Fixed queue name matching on workflow onMessage event ({SERVER_COMMIT_BASE}465e8ffe[`465e8ffe`]).

.[#2022_3_0-security]#<<2022_3_0-security,Security:>>#
* Replaced `dgrijalva/jwt-go` with `lestrrat-go/jwx`, refactored the JWT handling implementation ({SERVER_COMMIT_BASE}59ec77e20[`59ec77e20`], {SERVER_COMMIT_BASE}46675080f[`46675080f`]), token issuer ({SERVER_COMMIT_BASE}6c3bef075[`6c3bef075`]), and moved token validation to earlier stages ({SERVER_COMMIT_BASE}53dd7cc29[`53dd7cc29`]) for a safer, more robust and configurable implementation.
* Added token validation and identity decoding for websockets ({SERVER_COMMIT_BASE}f9c8066e2[`f9c8066e2`]).
* Added missing roles to impersonated user JWT tokens ({SERVER_COMMIT_BASE}ab805f007[`ab805f007`]).
* Tweaked CORS settings ({SERVER_COMMIT_BASE}9fe21dd8c[`9fe21dd8c`]).
* Added sanitization for workflow labels to avoid potential XSS ({WEBAPP_WORKFLOW_COMMIT_BASE}82d8f23[`82d8f23`]).

//
//

.[#2022_3_0-development]#<<2022_3_0-development,Development:>>#
* Refactored and improved the code generator by introducing cuelang ({SERVER_COMMIT_BASE}725f7e9e2[`725f7e9e2`]), refactored old codegeneration to the new facility ({SERVER_COMMIT_BASE}a035e6106[`a035e6106`], {SERVER_COMMIT_BASE}3bddce4d3[`3bddce4d3`], {SERVER_COMMIT_BASE}d103d60a3[`d103d60a3`], {SERVER_COMMIT_BASE}d09b037e8[`d09b037e8`]).
* Added `.env.example` generator ({SERVER_COMMIT_BASE}80d9b466a[`80d9b466a`]).
* Fixed `pinio` version mismatch between `corteza-js` and `corteza-vue` ({WEBAPP_JS_COMMIT_BASE}a8c46b9[`a8c46b9`], {WEBAPP_VUE_COMMIT_BASE}a8f5e24[`a8f5e24`]).
* Tweaked Envoy to properly handle user email lookups ({SERVER_COMMIT_BASE}d841aad13[`d841aad13`]), expanded resource definition for easier state access ({SERVER_COMMIT_BASE}da1828642[`da1828642`]), and removed potential import cycles ({SERVER_COMMIT_BASE}bc1550938[`bc1550938`]), and general improvements ({WEBAPP_COMPOSE_COMMIT_BASE}f5a93caa[`f5a93caa`], {WEBAPP_COMPOSE_COMMIT_BASE}7bb22d96[`7bb22d96`]).
* Improved HTTP server startup ({SERVER_COMMIT_BASE}d74239c73[`d74239c73`]).
* Cleaned up the store interface ({SERVER_COMMIT_BASE}1949782cc[`1949782cc`]).
* Added additional identifiers for report resources ({SERVER_COMMIT_BASE}330a332fd[`330a332fd`]).
* Defined a general component to be used with item selection such as module fields and chart columns ({WEBAPP_COMPOSE_COMMIT_BASE}c3c2d5d6[`c3c2d5d6`], {WEBAPP_COMPOSE_COMMIT_BASE}e4a93e78[`e4a93e78`], {WEBAPP_COMPOSE_COMMIT_BASE}0b39fcc8[`0b39fcc8`], {WEBAPP_REPORTER_COMMIT_BASE}02b7cb9[`02b7cb9`], {WEBAPP_VUE_COMMIT_BASE}bd02931[`bd02931`]).
* Define a generic reusable chart container ({WEBAPP_VUE_COMMIT_BASE}afc6d15[`afc6d15`]).
* Update date fields with the `CDateInput` component ({WEBAPP_COMPOSE_COMMIT_BASE}d65b2c41[`d65b2c41`], {WEBAPP_COMPOSE_COMMIT_BASE}594b6ea5[`594b6ea5`], {WEBAPP_COMPOSE_COMMIT_BASE}f5690fa6[`f5690fa6`]).
* Updated workflow prompt definition structure for more flexibility ({WEBAPP_VUE_COMMIT_BASE}fe8645c[`fe8645c`], {WEBAPP_VUE_COMMIT_BASE}180271f[`180271f`]).
