= Access Control

Corteza's access control is a powerful tool that restricts access based on  roles(RBAC-role based access control) of individual users within an enterprise. This ensures users can only access information they need to do their jobs and prevents them from accessing information that doesn't pertain to them.

[IMPORTANT]
The core principle is to allocate enough access for an employee to do their job.

//The corteza RBAC has a feature rich interface that not only allows the adminstartor to review users but also combine their variouis roles.

== What is Role-Based Access Control?

Role-based access control (RBAC) helps you manage who has access to resources, what they can do with those resources, and what areas they have access to.

Corteza RBAC has many features, such as access to an operating system limited to specified functions, including generating, altering, or viewing a file. You can ensure the security of a company's essential data and mission-critical applications with RBAC. 

Three primary rules are defined for RBAC:

1. Role assignment: A subject can exercise a permission only if the subject has selected or been assigned a role.

2. Role authorization: A subject's active role must be authorized for the subject. With rule 1 above, this rule ensures that users can take on only roles for which they are authorized.

3. Permission authorization: A subject can exercise a permission only if the permission is authorized for the subject's active role. With rules 1 and 2, this rule ensures that users can exercise only permissions for which they are authorized.

=== Features of Corteza RBAC System

* Review users and their asssigned permissions.
* Permissions of a role Authenticated are editable.
* combination of roles.
* Low code administrator permissions are evaluated


=== Use cases

* Through RBAC, you can control what end-users can do at board and granular levels. You can designate whether the user is an administrator or standard user, and align roles and permissions based on the user's position in the organization. 

* If the employee's job changes, you may need to add and/or remove them for their current role group.

* By adding a user to a role group, the user has access to all the permissions of that group. If they are removed, access becomes restricted. Users can also be assigned temporary access to certain data or programs to complete a task and be removed after.

