include::../../variables.adoc[]
= {PRODUCT_NAME} Command Line Interface (CLI) ⛏

{PRODUCT_NAME} comes with command line interface tool. With it, you can manually or automatically change applications settings,
add users, roles, and run the API. You are using the same binary that can start the backend service and the API.

.Depending on built flavour, you can use a different entry:
- Microservice build produce `corteza-server-system`, `corteza-server-messaging` and `corteza-server-compose`
- Monolith build produces `corteza-server` binary with system, messaging, compose subcommands

== Using the CLI tool

IMPORTANT: At least basic https://docs.docker.com/engine/docker-overview/[Docker] and https://docs.docker.com/compose/[Docker Compose] knowledge is required for most {PRODUCT_NAME} setup and management.

.Executing with Docker Compose (when service is started)
[source]
----
docker-compose exec <service name> help
----

.Executing with docker (when container is running)
[source]
----
docker exec -it <container name> help
----

.Running with Docker Compose (when service is not started)
[source]
----
docker run -it --rm <container name> help
----

.Executing with Docker (when container is not running)
[source]
----
docker run -it --rm [docker run options] <container name> help
----

NOTE: Running and executing with Docker Compose should be easier and simpler because all required options and settings
for container are packed in the Docker Compose project configuration file (`docker-compose.yaml`)


.System subcommands
2+|auth
|auto-discovery
|Auto discovers new OIDC client

.Generates new JWT for a user
[source,shell,subs=attributes]
----
{CLI_CMD_SYSTEM} auth auto-discovery [name] [url] [flags]

Flags:
      --enable            Enable this provider and external auth
  -h, --help              help for auto-discovery
      --skip-validation   Skip validation
----

.Sends samples of all authentication notification to specified receipient
[source,shell,subs=attributes]
----
{CLI_CMD_SYSTEM} auth test-notifications [recipient]
----


provision
Command provision Wraps 2 sub-commands:

configuration Creates roles, channels, namespaces,
migrate-database Run database migration scripts
Both these commands are automatically executed when you run serve-api command after the database is connected and before initialization. This behavior can be changed with env variables.

You can prevent auto-provision on startup with PROVISION_CONFIGURATION=false.

System specific commands & sub-commands
Command	Subcommand
auth	auto-discovery	Auto discovers new OIDC client
auth	jwt	Generates new JWT for a user
auth	test-notifications	Sends samples of all authentication notification to recipient
roles	useradd	Add user to role
settings	delete	Set value (raw JSON) for a specific key
settings	get	Get value (raw JSON) for a specific key
settings	import	Import settings as JSON from stdin or file
settings	list	List all
settings	set	Set value (raw JSON) for a specific key
users	add	Add new user
users	list	List users
users	password	Change user's password
See help (--help) under each (sub) command for details about additional flags and arguments.
