include::../../variables.adoc[]
= Email automation: processing inbound email ⛏

{PRODUCT_NAME} supports email automation and processing of incoming email messages.
This can be achieved through local email service like <<postfix>> or 3rd party provider that forward received emails through webhooks.

.Flow:
 . Email is received by internal or external system
 . Email is forwarded to sink API endpoint
 . {PRODUCT_NAME} sink service extracts header and body data from received email
 . onReceive triggers are filtered for a match (trigger can be configured to match specific headers like sender or subject)
 . Automation script is called

== Preparing (signing) sink URL

Signing the URL (the sign=... parameter and value) is created as a combination of all parameters and Corteza's secret string.
This signature should be kept secret as it is effectively same as password that allows access to Corteza.

.Example:
[source,shell script,subs=attributes]
----
{CLI_CMD_SYSTEM} sink signature --method POST --origin postfix --content-type email
----

.Command will output a line that looks like this:
[source]
----
/sink?content-type=email&expires=&method=POST&origin=postfix&sign=6280d530ae74f1f9c55e4dd362c9ef2094221287
----

.Parameters:
|===
|Parameter|Description

|method
|must match the request method

|origin
|arbitrary string, can be used to describe

|content-type
|used to set the processor for the data inputed

|expires
|can be used to sign link with expiration date.
|===

.Validation
[source,shell,subs=attributes]
----
echo "
From: <sender@cortezaproject.org>
To: <test@corteza.domain.tld>
Subject: hello
Message-ID: <1234@local.machine.example>

Ola Corteza!
" | curl -i --data-binary @- "{API_SYSTEM_BASE_URL}/sink?content-type=email&expires=&method=POST&origin=postfix&sign=6280d530ae74f1f9c55e4dd362c9ef2094221287'"
----

This command must return `200 OK` response.
