include::../../variables.adoc[]
= Provisioning ⛏

Provisioning is step after server is started and API becomes available.
It allows you to directly influence how a fresh {PRODUCT_NAME} instance is configured on first run.
This entire process can be disabled by setting env. variables `PROVISION_MIGRATE_DATABASE` and `PROVISION_CONFIGURATION` to `false`.

.Control provisioning procedure
[cols="m,m,"]
|===
|Type|Default value|Description

3+| PROVISION_MIGRATE_DATABASE
| boolean
| true
| Controls if database migration (creation of tables, changes of schema between versions) should be done before each service is started.

It's recommended to keep this setting on.
Disabling it on a running server prevents migration between version udpates

3+| PROVISION_CONFIGURATION
| boolean
| true
| Runs various auto-setup procedures and creates resources:

- creates default permission rules and roles
- default channels are created
- default applications are created
- compose resources (namespaces, modules, charts,...)
- settings auto-discovery
|===

.Provision authentication settings:
[cols="m,m,"]
|===
|Type|Default value|Description

3+| PROVISION_SETTINGS_AUTH_EXTERNAL_ENABLED
3+| auth.external.enabled
| boolean
| true
| Is OAuth2 enabled or disabled

OAuth2 flow redirection URL.
3+| PROVISION_SETTINGS_AUTH_EXTERNAL_REDIRECT_URL
3+| auth.external.redirect-url
| string
|
| searches env-variables (`DOMAIN`, `LETSENCRYPT_HOST`, `VIRTUAL_HOST`, `HOSTNAME`, `HOST`)
and uses additional info (monolith, api-base-url) to calculate the value


3+| PROVISION_SETTINGS_AUTH_EXTERNAL_SESSION_STORE_SECRET
3+| auth.external.session-store-secret
| string
| _random 64 char string_
| generated 64 char long string if missing.

Is session cookie "secure" flag used (if yes, cookie can only be access over HTTPS).
3+| PROVISION_SETTINGS_AUTH_EXTERNAL_SESSION_STORE_SECURE
3+| auth.external.session-store-secure
| bool
| false
| If HTTPS is used for external auth redirection url, value is set to true.


3+| PROVISION_SETTINGS_AUTH_FRONTEND_URL_BASE
3+| auth.frontend.url.base
| string
|
| Where the frontend SPA is located. Serves as base for generating other `auth.frontend.url...` variables.


3+| PROVISION_SETTINGS_AUTH_FRONTEND_URL_PASSWORD_RESET
3+| auth.frontend.url.password-reset
| string
|
| Where the frontend SPA is located, the password reset form.


Where the frontend SPA is located, password email confirmation page.
3+| PROVISION_SETTINGS_AUTH_FRONTEND_URL_EMAIL_CONFIRMATION
3+| auth.frontend.url.email-confirmation
| string
| `auth.frontend.url.base` is used as base URL
|

3+| PROVISION_SETTINGS_AUTH_FRONTEND_URL_REDIRECT
3+| auth.frontend.url.redirect
| string
|
| Where the frontend SPA is located. User will be redirected here on successful external authentication.
Auto discovery uses `auth.frontend.url.base` as base URL

3+| PROVISION_SETTINGS_AUTH_EMAIL_FROM_ADDRESS
3+| auth.mail.from-address
| string
| to-be-configured@example.tld
| Email address used for sending auth emails (password reset, email confirmation)

Name used for sending auth emails (password reset, email confirmation)
3+| PROVISION_SETTINGS_AUTH_EMAIL_FROM_NAME
3+| auth.mail.from-name
| string
|
| Corteza Team (to-be-configured)

Is internal auth enabled? Enable this to allow users to use all (enabled)
internal features (sign-up, log in....)
3+| auth.internal.signup
3+| PROVISION_SETTINGS_AUTH_INTERNAL_ENABLED
| boolean
| true
|

3+| PROVISION_SETTINGS_AUTH_INTERNAL_SIGNUP_ENABLED
3+| auth.internal.signup.enabled
| boolean
| true
| Is internal sign-up enabled? Enable this to allow users to register if you do not have external authentication providers.

3+| PROVISION_SETTINGS_AUTH_INTERNAL_SIGNUP_EMAIL_CONFIRMATION_REQUIRED
3+| auth.internal.signup-email-confirmation-required
| boolean
| false
| Is email confirmation required for internal sign-ups?
Enabled on auto-discovery if server has email capabilities (`SMTP_HOST` variable is set)


3+| PROVISION_SETTINGS_AUTH_INTERNAL_PASSWORD_RESET_ENABLED
3+| auth.internal.password-reset.enabled
| boolean
| false
| Is password reset enabled for internal account?
Auto-discovery enables this if server has email capabilities (`SMTP_HOST` variable is set)
|===


.Provision OIDC providers:
[cols="m,m,"]
|===
|Type|Default value|Description

3+| PROVISION_OIDC_PROVIDER
| string
|
| Registers all given providers on start.
Provide a list of space delimited provider pairs (`<name> <provider-url>` or
`<name> <provider-url> <name-2> <provider-url-2>`).

The provider is auto-discovered only if it does not exist (match by name).

Also, make sure that your redirect URL (`auth.external.redirect-url`) is properly.
and `PROVISION_SETTINGS_AUTH_EXTERNAL_REDIRECT_URL`.

3+| PROVISION_SETTINGS_AUTH_EXTERNAL_REDIRECT_URL
| string
|
| Sets value for `auth.external.redirect-url` setting.

This should be set to: `{API_SYSTEM_BASE_URL}/auth/external/%s/callback`
|===

.Provision other external provider
[cols="m,m,"]
|===
|Type|Default value|Description

3+| PROVISION_SETTINGS_AUTH_EXTERNAL_GITHUB
| string
|
| Github's app credentials: `<key> <secret>`

3+| PROVISION_SETTINGS_AUTH_EXTERNAL_FACEBOOK
| string
|
| Facebook's app credentials: `<key> <secret>`

3+| PROVISION_SETTINGS_AUTH_EXTERNAL_GPLUS
| string
|
| Google's app credentials: `<key> <secret>`

3+| PROVISION_SETTINGS_AUTH_EXTERNAL_LINKEDIN
| string
|
| LinkedIn's app credentials: `<key> <secret>`

3+| PROVISION_SETTINGS_AUTH_EXTERNAL_OIDC
| string
|
| OIDC provider settings `<name> <issuer> <key> <secret>`
|===
