include::../../variables.adoc[]

[#facility-webApp]
= Web Application

The last important bit of the automation system is the web application.
The web application implements a small subset of {PRODUCT_NAME} server's automation system features that allow script listing and their execution.
The main purpose of this system is to provide the ability to interact with the user from inside automation scripts.

[IMPORTANT]
====
Since client scripts are executed in the browser, they are considered less secure.
These scripts should **not** work with any sensitive data such as authentication tokens, API credentials, personal data filtering, ...
====

== Main responsibilities

. Fetching and registration of automation scripts provided by {app_automation} server via {PRODUCT_NAME} server,
. registration of automation triggers on the system event bus,
. execution of automation scripts based on implicit/explicit events.


[#ext-facility-webEventBus]
== Event bus

In order to implement a powerful and flexible automation system, we have decided to base it around an event bus.
With the help of an event bus, we are able to trivially handle any combination of automation scripts in a unified, robust manner.

[IMPORTANT]
====
Client side event bus and server side event bus **are not** the same, so both should receive equal attention when reading.
====

=== Client script trigger registration

Firstly we need to register client scripts on the event bus, so they can listen and respond to dispatched events.
The flow is as follows:

. fetch the bundled automation scripts for the given service,
. for each trigger of every automation script:
.. prepare a generic execution function,
.. register the trigger with the execution function on the event bus.

=== Explicit server script trigger registration

Secondly we need to register explicit server scripts (manual server scripts).
The flow is as follows:

. fetch available automation scripts, excluding non explicit and non server script entries,
. for each trigger of every automation script:
.. prepare an execution function that invokes the {PRODUCT_NAME} server via API client libraries,
.. register the trigger with the execution function on the event bus.

=== Event handling and script execution

Finally we discuss event dispatching, handling and script execution.
Events are dispatched over the event bus and executed synchronously.

There is a slight difference between event validation when it comes to implicit and explicit scripts.

If the script name is provided::
    when the script name is provided, it is assumed, that we are invoking an **explicit** script.
    In this case, the event type **must** be defined as manual (`'onManual'`),

If the script name is not provided::
    when the script name is not provided, it is assumed, that we are invoking **implicit** script(s).
    In this case, the event type **must not** be defined as manual (`'onManual'`).

Other than that, the flow is as follows:

. validate the event,
. filter triggers based on the provided event,
. for each available trigger:
.. prepare context and payload,
.. execute the automation with the above generated meta,
.. handle possible errors.

When it comes to automation script execution, there is a small deviation between {APP_AUTOMATION} server and web application.
When the automation script is executed inside the web application, it's resources are provided by reference and therefore any changes made to the resource is reflected through the rest of the pipeline without the need of explicit return statements.
For some resources, such as records, the changes are also reflected on the UI.

[#ext-facility-csuihooks]
== UI hooks

A UI hook represents a UI component (usually a button), that is able to invoke an explicit automation script, being a client or server script.
UI hooks solely provide component definition (script name, element type, design, labels, ...) and it's up to the user interface to render the component and dispatch the event when needed.
