include::ROOT:partial$variables.adoc[]

= System Requirements

== Supported Clients

[IMPORTANT]
====
{PRODUCT_NAME} doesn't support older browsers.
If you wish to do so, you may build your own Docker containers with custom build procedures.
====

.{PRODUCT_NAME} supports the following clients:
[cols=","]
|===
|Client |Version

|Chrome| v78+
|Firefox| v68+
|Safari| v12+
|Edge| v44+
|iOS| iPhone 5s devices and later with iOS 12+
|Android| Android 7+
|===

== Server Operating System

Any Docker-compatible operating system is supported. 

[NOTE]
====
We recommend a Linux-based operating system, preferably Ubuntu LTS.
====

== Docker

The minimum Docker Engine version is 1.12.x

== HTTP Server

You should place the API and the web applications behind a firewall or an HTTP reverse proxy.
The reverse proxy is responsible for traffic forwarding to {PRODUCT_NAME} services and https://en.wikipedia.org/wiki/TLS_termination_proxy[SSL termination].

[NOTE]
====
Most of the popular HTTP servers support this.
====

The documentation provides configurations guides for https://github.com/nginxproxy/nginx-proxy[Nginx Reverse Proxy] and the https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion[LetsEncrypt nginx-proxy companion].

[NOTE]
====
It isn't obligatory to use Nginx; you can use the HTTP server you are most familiar with.

Use provided examples for Nginx as a reference on how to configure it.
====

== Database

It is recommended to use the https://hub.docker.com/_/postgres[PostgreSQL] 13, either native on the host or provided via Docker.

[NOTE]
====
{PRODUCT_NAME} also supports MySQL for which we recommend https://hub.docker.com/_/percona[Percona Server for MySQL] 8.x.
====

== Hardware

|===
| Number of Users | Processor      | Memory
|    1 - 500      |  1 vCPU/cores  |  2 GB RAM
|  500 - 1000     |  2 vCPU/cores  |  4 GB RAM
| 1000 - 2000     |  4 vCPU/cores  |  8 GB RAM
| 2000 - 5000     |  8 vCPU/cores  | 16 GB RAM
| 5000+           | 16 vCPU/cores  | 32 GB RAM
|===

== Storage

.Estimated storage per user per month:
[cols="m,,"]
|===
|Volume|Description|Recommended Storage

| Low volume
| *{APP_NAME_COMPOSE}*: creating plain-text records (without file upload).
| 5 MB/user/month

|Medium volume
| *{APP_NAME_COMPOSE}*: attaching documents to records.
| 25 MB/user/month

| High volume
| *{APP_NAME_COMPOSE}*: attaching a high number of documents to records daily.
| 100 MB/user/month

|===

.For the annual storage calculation you will need:
* Base storage (operating system and core components) of 10 GB,
* recommended storage per user per month based on the matrix above (multiplied by 12 to get the yearly amount),
* average number of users in a year,
* apply a safety factor; we recommend at least 2.0.

.The formula:
----
total = (nr. of users * recommended storage * 12 * safety factor) + base storage
----

.Example calculation for 30 medium usage users:
----
Recommended storage = (30 * 25 MB * 12 * 2) + 10 GB = 28 GB / year
----

== Network

Depending on your configuration, {PRODUCT_NAME} may need some access to outside services.

If you intend to use any email communication; such as sending confirmation emails, password reset emails, or sending emails from automation scripts; you must configure your SMTP servers to be accessible.

If you enable federation, the nodes ({PRODUCT_NAME} instances) must be *visible and allow traffic* between them on the designated HTTP ports.

If you enable OAuth2 or OIDC sign-up or access external services via automation scripts, you should allow HTTP traffic.

== Domain and Hostname

For the most common and effortless setup, we recommend using a {PRODUCT_NAME} docker image that contains web applications and an API server (all-in-one), and both are served from the same domain.

Alternatively, if needed, the setup could be split into two; the web application and the API server would be hosted separately. 

[NOTE]
====
If you decide on a split setup, {PRODUCT_NAME} does not require different domains for its services.
You can use different hosts or subdomains and point them to each service.
To exemplify; you can use `web.example.tld` for your web applications and `api.example.tld` for your API.
====

== HTTPS/SSL Certificates

{PRODUCT_NAME} supports any SSL certificate from all certificate authorities (CA).
You can use any existing or new SSL certificate from any commercial SSL certificate provider or self-signed.

We use https://en.wikipedia.org/wiki/Let's_Encrypt[Let's Encrypt].

[NOTE]
====
If you aren't using any other HTTP server, we highly recommend using the use of https://github.com/nginxproxy/nginx-proxy[Nginx Reverse Proxy] and https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion[LetsEncrypt companion container for nginx-proxy].

It is an automated and the simplest way to secure {PRODUCT_NAME} or any other web application you host.
====
