include::ROOT:partial$variables.adoc[]

= The Security Model
:page-aliases: 2023.9@administrator-guide:access-control/index.adoc
:keywords: security model, access control
:description: Learn how to configure your security model to conform to your business requirements

{PRODUCT_NAME} defines a https://en.wikipedia.org/wiki/Role-based_access_control[RBAC] access control facility.
RBAC uses the <<glossary-role,*roles*>> of the given <<glossary-user,*user*>> to determine whether they have access to a given <<glossary-resource,*resource*>>.

[NOTE]
====
Most of the {PRODUCT_NAME} resources allow you to define which xref:security-model/roles.adoc[roles] are allowed to access the resource.
Locate the btn:[permissions] button in the user interface in order to manage the resource.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "security-model/general-permissions-button.png",
    "alias": "security-model-general-permissions-button",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 320,
    "y": 0,
    "h": 550,
    "w": 1600
  },
  "focus": {
    "x": 1466,
    "y": 80,
    "h": 31,
    "w": 206
  },
  "annotations": [{
    "kind": "box",
    "x": 1536,
    "y": 80,
    "w": 134,
    "h": 30
  }]
}
----

Refer to xref:security-model/references/operations.adoc[] for the complete reference of available RBAC rules.
====

{PRODUCT_NAME}'s RBAC facility uses a "flat design" which removes role hierarchy (two roles can not explicitly define a parent/child relationship).

<<role-type-ctx,*Context role membership*>> allows you to dynamically assign users to roles based on the defined set of rules.

[IMPORTANT]
====
While access control for specific records is supported, access control for particular fields of particular records is not.

You can bypass this limitation by using <<role-type-ctx,context role membership>> and module filed rules.
====

== Access Evaluation Flow

When access is evaluated, the system collects all users' roles and RBAC rules as a part of the security context.
The order of rule evaluation is based on <<ac-role-importance,*role importance*>> and <<ac-resource-specificity,*resource specificity*>>.

[CAUTION]
====
If a user is a member of a bypass role, *all operations are permitted* without any restrictions.
====

.Access evaluation flow:
. If any rule defines an explicit *deny*, the evaluation results with *deny*.
. If at least one rule defines an explicit *allow*, the evaluation results with *allow*.
. If there are no explicit allow or deny rules on the current level, the evaluation continues to the next set of rules based on role importance.
. If the evaluation cannot find an explicit allow or deny rules, the evaluation results with *deny*.

[#ac-role-importance]
=== Role Importance

Role importance defines the order in which roles and their corresponding rules are evaluated.

.Role importance for authenticated users:
. bypass roles,
. context roles,
. common roles,
. authenticated roles.

.Role importance for unauthenticated users:
. anonymous roles.

[#ac-resource-specificity]
=== Resource Specificity

Resource specificity defines the order in which rules for the corresponding resources are evaluated.
Resource specificity is defined based on _how specific  this rule is to this resource_.

As an example, a rule that allows users to create records on the account module in the CRM namespace is more specific than the rule just on the CRM namespace.

[TIP]
====
Such specificity allows you to deny access to all but one resource of the given type.
To exemplify; you could deny access to all namespaces and allow access to just one namespace.
====

== Role Types

[NOTE]
====
A list of bypass, authenticated, and anonymous roles is provided in the system configuration and can not be changed at runtime.
Refer to xref:devops-guide:access-control/index.adoc[DevOps guide] for details on how this can be done.

These roles can not be modified or renamed.

.If you wish to alter the roles, you can either:
* temporarily change the role list, edit the roles, revert the role list changes,
* change the provision scripts to supply the required names at the initial {PRODUCT_NAME} run.
====

[#role-type-bypass]
=== Bypass

Bypass roles allow their members unlimited access to {PRODUCT_NAME} with no permission checking.

Out of the box, {PRODUCT_NAME} defines the default bypass role named "Super administrator".
Your system administrator can xref:devops-guide:access-control/index.adoc[change the set of bypass roles] in the `.env` file.
The roles that are defined as authenticated have restricted editing options.

[#role-type-common]
=== Common Roles

Common roles are any additional roles defined in the administration panel, such as a CRM admin and application builder.

[#role-type-ctx]
=== Contextual Roles

[NOTE]
====
You can not use contextual roles within auth clients, nor can they define an explicit member list.
Contextual roles are assigned to users based on the operation and the context.
====

Contextual roles define a series of xref:integrator-guide:/expr/index.adoc[*expressions*], which determine when the role is assigned to the user based on the operations' context.

Each role can define an expression for each resource type.
Each role can only use a resource type once.

[IMPORTANT]
====
Contextual roles are hidden from resource permission screens if the role does not define an expression for that resource.
For example, a record specific role is not shown on the module permission screen.
====

For example, a certain case of use would allow us to use contextual roles to permit resources owners to perform operations they normally wouldn't have, such as editing and deleting said resources.

Refer to the xref:security-model/references/contextual-role-parameters.adoc[] for details.

.Contextual roles are currently supported for:
* records,
* workflows,
* auth clients.

[#role-type-authenticated]
=== Authenticated

Authenticated roles are *implicit*, meaning that users can not explicitly be set as role members.

Out of the box, {PRODUCT_NAME} defines the default authenticated role named "Authenticated".
Your system administrator can xref:devops-guide:access-control/index.adoc[change the set of authenticated roles] in the `.env` file.
The roles that are defined as authenticated have restricted editing options.

If the user is authenticated with {PRODUCT_NAME} when they are accessing a resource, the system additionally assigns them authenticated roles.

[#role-type-anonymous]
=== Anonymous

Anonymous roles are *implicit*, meaning that users can not explicitly be set as role members.

Out of the box, {PRODUCT_NAME} defines the default anonymous role named "Anonymous".
Your system administrator can xref:devops-guide:access-control/index.adoc[change the set of anonymous roles] in the `.env` file.
The roles that are defined as anonymous have restricted editing options.

If the user is *not* authenticated with {PRODUCT_NAME} when they are accessing a resource, the system additionally assigns them anonymous roles.

== Important Notes

=== System Setup

{PRODUCT_NAME} defines a series of system role types: bypass, authenticated, and anonymous.
System role types are defined on the server configuration level, and *cannot* be changed directly through the user interface.

If a role is assigned to one of the system role types, the editing is restricted.
If the role is somehow removed or changed to the extent where the system can not identify it, the system should refuse to start.

.The rationale behind such restrictions:
* The configuration affects the RBAC facility and its setup process.
* Systems that work with access tokens need to be aware of such changes.
* The security model on this level rarely changes, and the change is drastic when it does.

=== Bypass RBAC Roles

If a role is assigned as a bypass, it may *not* appear as any other role type.
In the occasion where this is not the case, the system will refuse to start.

[IMPORTANT]
====
Only members of the bypass role may manage the membership of the bypass role.
====

Bypass roles can be listed on auth clients as permitted or prohibited roles but are *silently ignored* when defined under forced roles.

=== Authenticated and Anonymous

Authenticated and anonymous roles may not appear in any auth client security role lists (the allowed, denied, and forced roles) and are silently ignored.

== Glossary

[cols="1s,5a"]
|===
| [#glossary-user]#<<glossary-user,A user>>#
|
A user is an entity that is accessing {PRODUCT_NAME}.
A user can be a member of security roles and cannot get permissions directly without an assigned role.

| [#glossary-role]#<<glossary-role,A role>>#
|
A role represents a set of users and a set of permissions over resources.

{PRODUCT_NAME}'s RBAC implementation defines a flat structure that removes role hierarchy (two roles can not explicitly specify a parent/child relationship).

| [#glossary-access]#<<glossary-access,Access>>#
|
Defines if the rule permits (`allow`) or denies (`deny`).

| [#glossary-resource]#<<glossary-resource,A resource>>#
|
A structured piece of information stored within {PRODUCT_NAME} that we may or may not control access to.
Each resource belongs to a component and has a unique type.

| [#glossary-resource-type]#<<glossary-resource-type,A resource type>>#
|
A resource type defines the structure of information within the {PRODUCT_NAME} component.

| [#glossary-operation]#<<glossary-operation,Operation>>#
|
Defines what operation the given RBAC rule defines access to.

| [#glossary-rbac-rule]#<<glossary-rbac-rule,RBAC rule>>#
|
A RBAC rule combines *operation*, *role*, *access*, and *resource*.
It defines what someone can (or can not) do on one or more resources inside {PRODUCT_NAME}.

| [#glossary-security-session]#<<glossary-security-session,Security session>>#
|
A security session is created when a user requests to access {PRODUCT_NAME}.

|===
