include::ROOT:partial$variables.adoc[]

= Permission Evaluation

The permission evaluation feature allows administrators to check which actions or operations can be performed by a user or a combination of roles.
The evaluation entails comparing the different roles assigned to a user to determine the user's ability to perform the various operations within a resource.

[NOTE]
====
xref:access-control/index.adoc[{PRODUCT_NAME} RBAC] uses the roles of the given user to determine if they have access to a given resource.
====

== How to evaluate applied permissions

[NOTE]
====
Most of the {PRODUCT_NAME} resources allow you to define which xref:access-control/roles.adoc[roles] are allowed to access the resource.
Locate the btn:[permissions] button in the user interface in order to manage the resource.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "security-model/access-control/general-permissions-button.png",
    "alias": "general-permissions-button",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 320,
    "y": 0,
    "h": 550,
    "w": 1600
  },
  "focus": {
    "x": 1466,
    "y": 80,
    "h": 31,
    "w": 206
  },
  "annotations": [{
    "kind": "box",
    "x": 1536,
    "y": 80,
    "w": 134,
    "h": 30
  }]
}
----
====

1. Navigate to the resource of choice, and click the [btn:[permissions].

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "security-model/access-control/permission-button-page.png",
    "alias": "new-user",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "annotations": [{
    "kind": "box",
    "padding": "xs",
    "x": 1535,
    "y": 75,
    "w": 130,
    "h": 42
  }]
}
----

2.Click the *[add +]* button.
An evaluation window appears with two dropdown options, the *[select role(s)]* and *[search or select user]*.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "security-model/access-control/add-role.png",
    "alias": "add-role",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "annotations": [{
    "kind": "box",
    "padding": "xs",
    "x": 765,
    "y": 150,
    "w": 750,
    "h": 80
}]
}
----

3.Click on the *[select roles]* or the *[select user]* dropdown and select a role or a user to evaluate.
Only one of two options can be applied.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "security-model/access-control/eval-permission.png",
    "alias": "eval-permission.png",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "focus": {
    "padding": "xs",
    "x": 604,
    "y": 320,
    "w": 1232,
    "h": 684
  },
  "annotations": [{
    "kind": "box",
    "x": 600,
    "y": 330,
    "w": 735,
    "h": 270
  }]
}
----

Click on the btn:[save] button.
[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "security-model/access-control/save-evaluation-permission.png",
    "alias": "save-evaluation-permission",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "focus": {
    "padding": "xs",
    "x": 344,
    "y": 42,
    "w": 1232,
    "h": 630
  },
  "annotations": [{
    "kind": "box",
    "x": 1150,
    "y": 613,
    "w": 193,
    "h": 38
  }]
}
----

4.If you chose role evaluation in step 3, repeat the step again, choosing a different role in order to evaluate the permissions applied to the different roles.

.The screenshot shows an overview of permissions appied on the roles being evaluated.
[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "security-model/access-control/save-eval.png",
    "alias": "save-eval",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "annotations": []
}
----

== Permission Evaluation on Resource Components 

Corteza has three major resource components, namely;
*System*, *compose* and *automation* components.
Each resource component has operations that are performed in it.

[IMPORTANT]
====
Permissions to the various operations within a component resource are subject to the roles assigned to a user.
====

Permissions can be evaluated by selecting a combination of roles or a particular user.

Follow these steps to access and evaluate the system, compose and automation permissions.

1.Navigate to your {PRODUCT_NAME} instance *{LOCAL_HOSTNAME}* and click the *[Admin area]* application.

A new screen showing you all of the available components will appear. Each component has a btn:[permissions] button.

2.Click on the btn:[permissions] button on either system, compose or the automation component. A new screen appears that displays a list of all the available operations within a component.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "security-model/access-control/system-permissions-button.png",
    "alias": "system-permissions-button.png",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  
  "annotations": [{
    "kind": "box",
    "padding": "xs",
    "x": 15,
    "y": 480,
    "w": 110,
    "h": 32
}]
}
----

3.Click on the *[add +]* button.
An evaluation window appears with two dropdown options.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "security-model/access-control/system-permissions-add-button.png",
    "alias": "system-permissions-add-button.png",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  
  "annotations": [{
    "kind": "box",
    "padding": "xs",
    "x": 640,
    "y": 150,
    "w": 1190,
    "h": 125
}]
}
----

4.Click on the *[evaluate]* button and then click on the *[select roles]* or the *[select user]* dropdown and select a role or a user to evaluate.
Only one of two options can be applied.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "security-model/access-control/evaluate-permissions.png",
    "alias": "user-create",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "annotations": [{
    "kind": "box",
    "x": 770,
    "y": 510,
    "w": 380,
    "h": 140
  }]
}
----

Click on the btn:[save] button.
[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "security-model/access-control/save-eval-permission.png",
    "alias": "save-eval-permission-button",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "focus": {
    "padding": "xs",
    "x": 344,
    "y": 45,
    "w": 1232,
    "h": 630
  },
  "annotations": [{
    "kind": "box",
    "x": 1150,
    "y": 613,
    "w": 193,
    "h": 38
  }]
}
----

5.If you chose role evaluation in step 4, repeat the step again, choosing a different role in order to evaluate the permissions applied to the different roles.

.The screenshot shows an overview of permissions applied on the roles being evaluated.
[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "security-model/access-control/system-evaluated-permissions.png",
    "alias": "system-evaluated-permissions.png",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  
  "annotations": []
}
----






