include::ROOT:partial$variables.adoc[]

= Role Management
:page-aliases: 2023.3@administrator-guide:roles.adoc
:keywords: security model, roles, role management
:description: Learn how to create and manage the roles your users can be part of


A role is a security group which may or may not have access to specific user interfaces or system resources based on your xref:security-model/index.adoc[security model].

A role can have a series of xref:security-model/users.adoc[users] who are provided with the security model defined by the given role.

== The User Interface

The role management user interface resides in the xref:index.adoc#webapp-admin[{PRODUCT_NAME} {APP_NAME_ADMIN}] web application, under menu:system[roles].

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "security-model/roles/list.png",
    "alias": "security-model-roles-list-index",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "annotations": [{
    "kind": "box",
    "padding": "xs",
    "x": 16,
    "y": 180,
    "w": 288,
    "h": 37
  }]
}
----

== Tips and Tricks

=== Modular Design

[NOTE]
====
*DevNote* @todo
====

== Listing Roles

.To list current system roles:
. Navigate to menu:system[roles],
. optionally insert the filtering parameters.
. The list refreshes automatically.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "security-model/roles/list.png",
    "alias": "security-model-roles-list",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 321,
    "y": 0,
    "w": 1599,
    "h": 960
  },
  "annotations": []
}
----

== Creating Roles

[IMPORTANT]
====
You can only define permissions for existing roles.
====

.To create a new role:
. Navigate to menu:system[roles],
. click on the btn:[new] button,
. insert the parameters for the new role,
. press the btn:[submit] button.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "security-model/roles/create.png",
    "alias": "security-model-roles-create",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 321,
    "y": 0,
    "w": 1599,
    "h": 460
  },
  "annotations": []
}
----

== Editing Roles

.To edit an existing role:
. Navigate to menu:system[roles],
. click on the btn:[edit] button next to the role you wish to edit,
. update the parameters for the updated role,
. press the btn:[submit] button.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "security-model/roles/edit.png",
    "alias": "security-model-roles-edit-index",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 321,
    "y": 0,
    "w": 1599,
    "h": 660
  },
  "annotations": []
}
----

[#archiving-roles]
== Archiving Roles

.To archive an existing role:
. Navigate to menu:system[roles],
. click on the btn:[edit] button next to the role you wish to archive,
. click and confirm the btn:[archive] button.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "security-model/roles/edit.png",
    "alias": "security-model-roles-edit-archive",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 321,
    "y": 0,
    "w": 1599,
    "h": 660
  },
  "annotations": [{
    "kind": "box",
    "padding": "sm",
    "y": 499,
    "x": 672,
    "w": 86,
    "h": 32
  }]
}
----

== Deleting Roles

[TIP]
====
Instead of deleting roles, you can <<archiving-roles,archive the role>>.
====

.To delete an existing role:
. Navigate to menu:system[roles],
. click on the btn:[edit] button next to the role you wish to delete,
. click and confirm the btn:[delete] button.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "security-model/roles/edit.png",
    "alias": "security-model-roles-edit-delete",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 321,
    "y": 0,
    "w": 1599,
    "h": 660
  },
  "annotations": [{
    "kind": "box",
    "padding": "sm",
    "y": 499,
    "x": 586,
    "w": 77,
    "h": 32
  }]
}
----

== Cloning Role Permissions

.To clone the role's permissions to another role:
. Navigate to menu:system[roles],
. click on the btn:[clone permissions] button,
. select the roles you wish to clone the permissions to,
. press the btn:[clone] button.

.The screenshot shows the clone permissions button.
[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "security-model/roles/clone-permissions-button.png",
    "alias": "security-model-roles-clone-permissions-button",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "annotations": [{
    "kind": "box",
    "x": 1498,
    "y": 90,
    "w": 165,
    "h": 35
  }]
}
----

.The screenshot shows clone permissions to dialog, to select roles for cloning permission to.
[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "security-model/roles/clone-permissions.png",
    "alias": "security-model-roles-clone-permissions",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "annotations": [{
    "kind": "box",
    "x": 710,
    "y": 410,
    "w": 500,
    "h": 260
  }]
}
----
