include::../../variables.adoc[]

= Create a namespace

To enter {PRODUCT_NAME} {APP_NAME_COMPOSE}, first, you need to enter {PRODUCT_NAME}. Once you're inside {PRODUCT_NAME}, you have several options for opening {PRODUCT_NAME} {APP_NAME_COMPOSE}:

== Open {PRODUCT_NAME} {APP_NAME_COMPOSE}

* Open it in a new tab by clicking on the + button close to the top of the page, which opens the application menu;
* Open it in a new panel by selecting the grid icon on the top right (the icon with four squares); or
* Open it in a new window by selecting open in a new window when hovering over the {APP_NAME_COMPOSE} icon in the application menu.

The first thing you see is the {PRODUCT_NAME} {APP_NAME_COMPOSE} Namespaces menu.
This shows all the applications you have installed (if any) and an option to create new applications.

NOTE: If you cannot see {PRODUCT_NAME} {APP_NAME_COMPOSE}, your existing applications, or the Create a new namespace button, you might not have the permissions you need.
In this case, contact the administrator of your {PRODUCT_NAME} platform.

== Create an application

Each {APP_NAME_COMPOSE} application lives in its own unique namespace.
This feature allows you to have an unlimited number of {PRODUCT_NAME} {APP_NAME_COMPOSE} applications.

To create a new application, you need to fill out the following fields:

* *Full namespace name (mandatory)*: The name of your application, which will be shown in the {APP_NAME_COMPOSE} Namespaces menu.
This name does not have to be unique, but it's best practice to give each application a unique and descriptive name.
For example: Donations.
* *Subtitle (optional)*: The subtitle is shown below the name of the application in the {APP_NAME_COMPOSE} Namespaces menu.
For example: Donor Management for the Development Department.
* *Namespace description (optional)*: A longer description that appears when hovering over the namespace in the {APP_NAME_COMPOSE} Namespaces menu.
For example: In this Donations application, our organization tracks contributors and contributions.
* *Slug (mandatory)*: A short name for the namespace that is used in the URL.
It's best to only use letters, numbers, and characters like the dash or underscore.
For example: donation-management.
* *Enabled (mandatory in order to enter the application)*: By checking the Enabled checkbox, the application will be available in the {APP_NAME_COMPOSE} Namespaces menu.
* *Set namespace permissions (optional)*: By clicking on Set namespace permissions, you can define the access permissions to the namespace for each role.
Other access permissions for your application will be created later because they depend on the type of application you build.

Try it out by following these steps to create an example namespace to manage donations.

* First, click on the Create namespace button.
It's the last block on the {PRODUCT_NAME} {APP_NAME_COMPOSE} Namespaces menu.
This opens the Create namespace form. 
* For the donation application, fill in the following data:
{PRODUCT_NAME}_createdonationnamespace.png
* Hit Save and close. You've created an application in {PRODUCT_NAME}!
