include::ROOT:partial$variables.adoc[]

= Evaluate applied permissions

xref:access-control/index.adoc[{PRODUCT_NAME} RBAC] uses the roles of the given user to determine if they have access to a given resource.
This is achieved by comparing the permissions associated with different roles available to the user.

Therefore one can evaluate the permissions applied to a particular user by listing the actions permitted in different roles.

== How to evaluate applied permissions

[NOTE]
====
Most of the {PRODUCT_NAME} resources allow you to define which xref:access-control/roles.adoc[roles] are allowed to access the resource.
Locate the btn:[permissions] button in the user interface in order to manage the resource.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "access-control/general-permissions-button.png",
    "alias": "general-permissions-button",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 320,
    "y": 0,
    "h": 550,
    "w": 1600
  },
  "focus": {
    "x": 1466,
    "y": 80,
    "h": 31,
    "w": 206
  },
  "annotations": [{
    "kind": "box",
    "x": 1536,
    "y": 80,
    "w": 134,
    "h": 30
  }]
}
----
====

1.Navigate to the resource of choice, click the [btn:[permissions].

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "access-control/permission-button-page.png",
    "alias": "new-user",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "annotations": [{
    "kind": "box",
    "padding": "xs",
    "x": 1535,
    "y": 75,
    "w": 130,
    "h": 42
  }]
}
----

2.Click the *[add +]* button to evaluate applied permissions. An evaluation window appears with the *[select role(s)]* and *[search or select user]* dropdowns.
You can only use one of the two options per time.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "access-control/add-role.png",
    "alias": "add-role",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "annotations": [{
    "kind": "box",
    "padding": "xs",
    "x": 765,
    "y": 150,
    "w": 750,
    "h": 80
}]
}
----

3.Click the *[select roles]* dropdown and select a role or  the  *[select user]* dropdown to choose a user.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "access-control/eval-permission.png",
    "alias": "user-create",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "annotations": []
}
----

4.Click the *[save & close]* button.
[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "access-control/add-role-button.png",
    "alias": "user-create",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "annotations": []
}
----

5.Repeat the steps again choosing a different role on step 3 and 4 respectively inorder to evaluate  the different permissions applied on a role.
[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "access-control/save-eval.png",
    "alias": "save-eval",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "annotations": []
}
----

