include::ROOT:partial$variables.adoc[][]

= Contacts

The Contacts page is accessible by clicking on the menu:Accounts[Contacts] in the main navigation bar on the top of the screen.

A contact belongs to an account, and we can think of them as employees for a specific company that we are allowed to contact.

== Add a new contact

. Navigate to the menu:Accounts[Contacts],
. click on the btn:[+ Add] button to open the form,
. populate the data and press the btn:[Save] button on the bottom right corner.

== Key parts of a contact

[IMPORTANT]
====
A contact has two particular fields that indicate how and if we can contact them:

* Do Not Call,
* Email Opt Out.

The agent should check these fields before trying to make any contact.
====

Personal Data::
    Here we store the essential information regarding contacts, such as their name, title, phone, and email.

Contact Address::
    Here we store their contact address if we need to generate any quotes, send packages or dispatch maintainers.

Contact Twitter Feed::
    Here we can keep track of the contact's latest updates via Twitter.

Cases related to this Contact::
    Here we store the cases that are related to the contact; either created by them, or they are responsible for.

Emails::
    Here we store the emails that we sent to the contact, presented in chronological order.
    These are usually generated based on cases.

== Add a case for a contact

. Navigate to the menu:Accounts[Contacts,select account],
. scroll down to the "cases" page block,
. click on the btn:[+ Add] button to open the form,
. populate the data and press the btn:[Save] button on the bottom right corner.

[NOTE]
====
Refer to xref:service-solution/index.adoc#cases[the cases section] for additional details.
====
