include::ROOT:partial$variables.adoc[][]

= Contacts

The Contacts page is accessible by clicking on the menu:Accounts[Contacts] in the main navigation bar on the top of the screen.

A contact belongs to an account; you can think of them as employees for a specific company that you are allowed to contact.

== The addition of a new contact

. Navigate to the menu:Accounts[Contacts],
. click on the btn:[+ Add] button to open the form,
. populate the data and press the btn:[Save] button in the bottom right corner.

== The key parts of a contact

[IMPORTANT]
====
A contact has two particular elements that indicate how and if you can contact them:

* Do Not Call,
* Email Opt Out.

The agent should check these fields before trying to make any contact.
====

Personal Data::
    Here the essential information regarding contacts, such as their name, title, phone, and email are stored.

Contact Address::
    Here their contact address (if it is necessary to generate any quotes, send packages or dispatch maintainers) are stored.

Contact Twitter Feed::
    Here you can keep track of the contact's latest updates via Twitter. 
//Nika's note: Only Twitter?

Cases related to this Contact::
    Here the cases that are related to the contact; either created by the contact, or those which it are responsible for are stored.

Emails::
    Here, in chronological order, the emails that you have previously sent to the contact are stored.
    These are usually generated based on cases.

== The addition of a case for a contact

. Navigate to the menu:Accounts[Contacts,select account],
. scroll down to the "cases" page block,
. click on the btn:[+ Add] button to open the form,
. populate the data and press the btn:[Save] button in the bottom right corner.

[NOTE]
====
Refer to xref:service-solution/index.adoc#cases[the cases section] for additional details.
====
