include::ROOT:partial$variables.adoc[][]

= Departments

The Departments page is accessible by clicking on the menu:Departments[] in the main navigation bar on the top of the screen.

Companies usually consist of multiple departments that may have different costs when performing their tasks.
One hour support by the service department is not the same as one hour support by R&D.
This allows the system to calculate the cost of a particular case automatically.

[NOTE]
====
A department is not directly assigned to a case, but rather its update.
This allows multiple departments to work on the same case.
====

== The addition of a department

. Navigate to the menu:Departments[],
. click on the btn:[+ Add] button to open the form,
. populate the data and press the btn:[Save] button in the bottom right corner.

== The key parts of a department

Department details::
    Here the essential information regarding a department, such as its name, list of employees, and it's hourly cost are stored.

Total time and cost of department related to work on cases::
    Here you can see some quick statistics regarding total consumed times and the total cost of the department.
    The system calculates this, so that you don't have to worry about this.

Case updates related to the department::
    Here you can see all of the case updates that are assigned to this department.
    This can help us determine what department has the most significant load so you can properly adjust our business process.

[IMPORTANT]
====
Changing the hourly cost of a department only affects new entries.
Old entries and their costs remain untouched unless they are updated.
====
