include::ROOT:partial$variables.adoc[][]

= Knowledge base

[IMPORTANT]
====
We use "KB" as a shortened notation to reference the knowledge base.
====

The Knowledge Base page is accessible by clicking on the "Knowledge Base" in the main navigation bar on the top of the screen.

The knowledge base stores various information regarding your products, services and other so the agents can solve cases faster without the need for experts.

== Key parts of a knowledge base entry

Details::
    Here we store the essential information regarding the entry, such as the type, related product, description, its status and some other metadata.

Cases with this KB Item as Solution::
    Here we see all the cases that we solved with the help of this entry.
    This helps us distinguish good entries from the bad ones to improve our knowledge base.
    It also allows other agents to solve similar cases much faster.

== Add a new knowledge base entry

. Press on the "+ Add" button on the top of the list,
. fill out the data,
. press "Save" in the bottom right corner.

[NOTE]
====
The ID gets calculated by the system.
====

== Tips for improving quality

Implement reviews::
    We can use the status field of the entry to indicate if it needs to be reviewed by an expert, or if it's accepted or rejected.
