include::ROOT:partial$variables.adoc[]

= Products

The Products page is accessible by clicking on the menu:Products[] section in the main navigation bar on the top of the screen.

A product can be a physical or a software product, as well as a service provided by your company.
Products allow you to keep track of how much turnover a specific product or a product family provides.
You also get an overview of all cases for a specific product.

== Adding a product

. Navigate to the menu:Products[],
. click on the btn:[+ Add] button to open the form,
. populate the data and press the btn:[Save] button in the bottom right corner.

== The key parts of a product

Product Description::
    Here the essential information regarding the product, such as it's product code, name, family and optionally an entitlement template are stored.

[TIP]
====
You can use entitlement templates to automate the creation of more common entitlements, such as a hardware warranty for a product.
====

Case totals::
    Here the total time and cost that a specific product has required so far can be seen.
    The system calculates these fields, so there is no need to worry about that!

Cases related to this product::
    Here you can find all the cases created for the product.
    It can help us identify the most problematic products and the most common issues.

Entitlements for this product::
    Here you can find all of the entitlements created for this product.

Knowledge Base items related to this product::
    The knowledge base allows us to provide some information regarding the product, so our support agents can provide quality answers without the need for experts.

[NOTE]
====
The knowledge base is accessible from the case creation screen.
====
