include::../../variables.adoc[]

= Products

The Products page is accessible by clicking on the "Products" in the main navigation bar on the top of the screen.

A product can be a physical or a software product, as well as a service provided by your company.
Products allow you to keep track of how much service a specific product or product family provides.
We also get an overview of all cases for a specific product.

== Key parts of a product

Product Description::
    Here we store the essential information regarding the product, such as it's product code, name, family and optionally an entitlement template.

[TIP]
====
We can use entitlement templates to automate the creation of more common entitlements, such as a hardware warranty for a product.
====

Cases totals::
    Here we see the total time and cost that a specific product has required so far.
    The system calculates these fields, so we don't need to worry about that!

Cases related to this product::
    Here we find all the cases that we created for the product.
    It can help us identify the most problematic products and the most common issues.

Entitlements for this product::
    Here we find all of the entitlements that we created for this product.

Knowledge Base items related to this product::
    The knowledge base allows us to provide some information regarding the product, so our support agents can provide quality answers without the need for experts.

[NOTE]
====
The knowledge base is accessible from the case creation screen.
====
