include::ROOT:partial$variables.adoc[][]

= Campaigns

The Campaigns page is accessible by clicking on the "Campaigns" in the main navigation bar on the top of the screen.

A campaign is a planned marketing project that you want to manage and keep track of from within the CRM.
This allows you to analyze different business strategies and analyze which one is most effective.

A campaign can be anything from a simple newsletter, seminar, conference, or any other type of marketing initiative.

Leads, contacts, accounts and opportunities are related to campaigns, as *campaign members*.
The campaign - opportunity relationship allows you to calculate values such as the ROI (Return Of Investment) based on the campaign cost and expected revenue.

To calculate the ROI, you need to insert the cost of the campaign.
The CRM creates the numbers that compare the costs to the value of the won opportunities.

[NOTE]
====
Campaign results are automatically updated. 
====

[TIP]
====
Try to add campaigns to all your leads.
Upon lead conversion, the campaigns are mapped to the account and opportunity, allowing you to define the ROI of your lead generation activities.
====
