include::ROOT:partial$variables.adoc[][]

= Cases

The Cases page is accessible by clicking on the menu:Mode[Cases] in the main navigation bar on the top of the screen.

The {PRODUCT_NAME} CRM implements a simplified case management tool.
It allows you to keep track of various customer complaints, disputes or similar.

[IMPORTANT]
====
The CRM and the xref:service-solution/index.adoc[Service Solution] do not share data.
====

Cases can be linked to accounts, contacts products or even to other cases.
//Nika's note: contacts products? The products of contacts -> contact's, if it is meant as a plural, remove the "s" in contacts

You can define who is part of the case, what role they have, keep track of the progress, assign tasks and add notes.

[NOTE]
====
You can store a resolved case as a "Solution".
Solutions help you to solve similar (future) cases with ease.
====

== The addition of a new case

. Navigate to the menu:More[Cases],
. click on the btn:[+ Add] button to open the form,
. populate the data and press the btn:[Save] button on the bottom right corner.

== The marking of the case as "in progress"

. Navigate to the menu:More[Cases,select a case],
. click on the btn:[Set Case status to Working].

== The marking of the case as "closed"

. Navigate to the menu:More[Cases,select a case],
. click on the btn:[Set Case status to Closed].

== Sharing the progress to the contact

. Navigate to the menu:More[Cases,select a case],
. click on the btn:[Inform the contact via email of the Case solution].
