include::ROOT:partial$variables.adoc[][]

= Leads

The Leads page is accessible by clicking on the "Leads" in the main navigation bar on the top of the screen.

[NOTE]
====
There are three pages dedicated to leads -- one main page and two subpages.
They all show leads but with different filtering.

* *Leads* shows all of the leads in the system,
* *All New Leads* shows only the leads that have the `New` status,
* *My Leads* shows only the leads that are assigned to you.
====

A *lead* or a prospect is an individual who *might become your customer*, but currently is not.
They are usually converted into *accounts*, *contacts* and *opportunities*.

== Add a new lead

[NOTE]
====
A new lead can be added from either one of the subpages.
====

. Click on the "+ Add" button to open up the form,
. populate the data and press the "Save" button on the bottom right corner.

[TIP]
====
The rating field is incredibly helpful as it allows you to see which leads are qualified as good leads.
====

The typical process of handling a lead after it is inserted in the system is for the assigned salesperson to follow up on the lead.
This salesperson can contact, and further qualify the lead.

[TIP]
====
Try to retrieve as much relevant lead data as possible.
It will help you create interesting charts, such as leads per country or leads per industry.
====

[TIP]
====
Fill in the lead's personal or company twitter profile.
This allows you to see, directly in the lead record, a list of latest tweets from that profile.
====

[TIP]
====
You can create notes, events and tasks for a lead.
====

== Converting the lead

A lead should be converted when there is a sales opportunity.

You have two options:

Convert this lead into an Account::
    This creates an account and a contact for the lead.
    Use it when a lead shows some interest but its not exactly clear what the sales opportunity will look like.

Convert this lead into an Account and Opportunity::
    This creates an account, contact and an opportunity for the lead.
    Use it when a lead shows interest, and we already have enough info about the sales opportunity.

[TIP]
====
When a lead is converted, the generated Contact is set as the primary contact for the account.
====

== Tips for determining a lead rating

If a lead *shows commercial interest*, such as a request for pricing and the lead's *location matches the region your business targets*, this lead could be considered a *5 star lead*.

If a lead *performed some additional interactions*, such as going through a demo, they could be considered a *3 star lead*.

If a lead *contacted* you regarding, but it's clear that there is no explicit business intention, it can be considered a *0 star* or a *1 star* lead.
