include::ROOT:partial$variables.adoc[][]

= Leads

The Leads page is accessible by clicking on the menu:Leads[] in the main navigation bar on the top of the screen.

A *lead or a prospect* is an individual who *might become your customer*, but currently is not.
They are usually converted into accounts, contacts and opportunities.

.There are three pages dedicated to leads:
* menu:Leads[] shows all of the leads in the system,
* menu:All New Leads[] shows only the leads that have the `New` status,
* menu:My Leads[] shows only the leads that are assigned to you.

The typical process of handling a lead after it is inserted in the system is for the assigned salesperson to follow up on the lead.
This salesperson can contact, and further qualify the lead.

== Add a new lead

. Navigate to the menu:Leads[],
. click on the btn:[+ Add] button to open the form,
. populate the data and press the btn:[Save] button on the bottom right corner.

[TIP]
====
The rating field allows you to see which leads are qualified as good leads.
====

[TIP]
====
Try to retrieve as much relevant lead data as possible.
It will help you create interesting charts, such as leads per country or leads per industry.
====

[TIP]
====
Fill in the lead's personal or company twitter profile.
This allows you to see, directly in the lead record, a list of latest tweets from that profile.
====

[TIP]
====
You can create notes, events and tasks for a lead.
====

[#lead-convert]
== Converting the lead

A lead should be converted when there is a sales opportunity.

[NOTE]
====
When a lead is converted, the generated Contact is set as the primary contact for the account.
====

.You have two options:
* [#lead-convert-account]#<<lead-convert-account,Convert the lead into an account>># when a lead shows some interest but its not exactly clear what the sales opportunity will look like.
This conversion creates an account and a contact for the lead.
To use this conversion navigate to menu:Lead[select a lead] and click on the btn:[Convert this Lead into an Account] button.
* [#lead-convert-account_opp]#<<lead-convert-account,Convert the lead into an account and opportunity>># when a lead shows some interest, and we already have enough info about the sales opportunity.
This conversion creates an account, a contact and an opportunity for this lead.
To use this conversion navigate to menu:Lead[select a lead] and click on the btn:[Convert this Lead into an Account and Opportunity] button.

== Tips for determining a lead rating

If a lead *shows commercial interest*, such as a request for pricing and the lead's *location matches the region your business targets*, this lead could be considered a *5 star lead*.

If a lead *performed some additional interactions*, such as going through a demo, they could be considered a *3 star lead*.

If a lead *contacted* you regarding, but it's clear that there is no explicit business intention, it can be considered a *0 star* or a *1 star* lead.
