include::ROOT:partial$variables.adoc[]

= Opportunities

The Opportunities page is accessible by clicking on the menu:Opportunities[] section in the main navigation bar on the top of the screen.

An account can be created either manually, or by <<account-new-opportunity,generating it from an account>>.

When generating an opportunity for a given account, you indicate that you have uncovered a potential future sale and thus potential revenue.

An *opportunity name* should be short and descriptive in order to identify what the opportunity is about quickly.
to illustrate; "300 licenses" is a good example as it is short and straight to the point.

The default close date is set to one month after the opportunity is created (can be configured with <<settings,settings>>).

The *stage* field allows you to identify what stage a given opportunity is in.
When you create an opportunity, it is set to *Qualification*.
Once correctly qualified, you can move it to *Proposal* (or to *Need Analysis*, if more analysis is needed).
The last few steps are *Negotiation*, followed by *Closed Won* or *Closed Lost*.

[TIP]
====
Use the Contact Roles block to create a clear overview of the people related to the opportunity, including the contact data and role.
====

== Adding a new opportunity manually

. Navigate to the menu:Opportunities[],
. click on the btn:[+ Add] button to open the form,
. populate the data and press the btn:[Save] button on the bottom right corner.

== Adding products and updating amounts

. Navigate to the menu:Opportunities[select an opportunity],
. select a price book,
. add products by clicking on the btn:[+ Add] button in the "products" block,
. click on the btn:[Update prices of Products by applying the selected Price Book and inserted discounts] button,
. press the btn:[Save] button on the bottom right corner.

[IMPORTANT]
====
You only have to insert the quantity and optionally the discount for a product.
Other fields are filled in automatically.
====

[NOTE]
====
You can overwrite the list price of the product by inserting a different sales price manually.
====

[#opportunity-generate-quote]
== Generating a quote for the opportunity

. Navigate to the menu:Opportunities[select an opportunity],
. click on the btn:[Create a new Quote for this opportunity] button.

== Tips for the qualification of leads

.It is useful to reflect upon the following data:
* *budget*: check whether there is a budget,
* *authority*: check if you are able to communicate with the decision-makers,
* *need*: check if there is an actual need for the product/service,
* *timeline*: check on what timeline the product/service needs to be delivered or implemented, and if this timeline is compatible with your capabilities,
* *competition*: check with whom you are competing.
