include::../../variables.adoc[]

= Opportunities

The Opportunities page is accessible by clicking on the "Opportunities" in the main navigation bar on the top of the screen.

When you generate an opportunity for a given account, you indicate that you have uncovered a potential future sale and thus potential revenue.

An *opportunity name* should be short and descriptive to identify what the opportunity is about quickly.
For example, "300 licenses" is a good example, as it is short and straight to the point.

The close date is set to one month after the opportunity is created.

[NOTE]
====
The close date determination is configurable via the settings.
====

The "stage" field allows you to identify what stage a given opportunity is in.
When you create an opportunity, it is set to "Qualification".
Once correctly qualified, you can move it to "Proposal" (or to "Need Analysis", if more analysis is needed).
The last few steps are "Negotiation", followed by "Closed Won" or "Closed Lost".

You can generate Quotes for an opportunity, and add notes, events and tasks.

[TIP]
====
Use the "Contact Roles" block to create a clear overview of the people related to the opportunity, including their contact data and role.
====

== How to add products to an opportunity and automaticaly update the total amount

The typical process is:

. Select a price book. You can have multiple price books in your organisation, offering different prices for the same product, depending on region and client organization type.
. Add a products. Note that you will only have to insert the quantity, and optionally "Discount". Other fields will be filled in automatically
. Click on the button "Update prices of Products by applying the selected Price Book and inserted discounts"

[NOTE]
====
You can overwrite the list price of the product by inserting a different sales price manually.
====

[TIP]
====
You can edit the list of products directly when you are in the editing mode of the opportunity record. This is faster then adding products one by one.
====

== Tips for qualifying leads

.It is useful to figure out the following data:
* *Budget*: Check if there is actually a budget,
* *Authority*: Check if you are talking to or being able to get through to the decision-makers,
* *Need*: Check if there is an actual need for the product/service,
* *Timeline*: Check by when the product/service needs to be delivered or implemented, and if this timeline makes sense,
* *Competition*: Check whom you are competing with.