include::ROOT:partial$variables.adoc[][]

= Quotes

The Quotes page is accessible by clicking on the menu:Quotes[] in the main navigation bar on the top of the screen.

A quote can be created either manually, or by <<opportunity-generate-quote,generating it from an opportunity>>.
An opportunity can have multiple quotes.
A quote allows you to complete the payment and thus charge the customer.

[IMPORTANT]
====
{PRODUCT_NAME} does not implement a payment mechanism. You should use an external provider.
====

Products in an opportunity are inserted as quote line items.

Quote *bill to*, *quote to* and *ship to* information are retrieved from the related account.

== The manual addition of a new quote

. Navigate to the menu:Quotes[],
. click on the btn:[+ Add] button to open the form,
. populate the data and press the btn:[Save] button in the bottom right corner.

== Sending the quote to a primary contact

. Navigate to the menu:Opportunities[select an opportunity],
. click on the btn:[Send this Quote via email to the primary contact] button.

== Sending the quote to a custom contact

. Navigate to the menu:Opportunities[select an opportunity],
. click on the btn:[Send this Quote to a custom email] button,
. insert the email address into the requested prompt window and press btn:[Submit].
