= Resource labelling

// https://github.com/cortezaproject/corteza-docs/pull/110/files
// The developer-guide was already updated.
// The integrator-guide should be updated when our webapps implement this.

[NOTE]
====
See the POC pull request https://github.com/cortezaproject/corteza-server/pull/112[#112].
The POC already covers most of the bits defined in this RFC.
====

Resource labelling equips *internal {PRODUCT_NAME} resources* with arbitrary key-value labels that provide *more flexibility* when performing operations over these labels.

.Example use cases:
* Categorization/taxonomy,
* resource grouping without the need for forced handle format to ensure prefix-based filtering,
* data migration ID references,
* marking federated resources,
* {APP_AUTOMATION} resource preloading,
* marking dependencies for automation scripts, workflows.

[IMPORTANT]
====
{PRODUCT_NAME} {APP_NAME_MESSAGING} resources *will not* support this feature.
====

== Label structure

Resource labels define a simple structure of:

[source,text]
----
{KEY}: {VALUE}
----

`{KEY}`::
    Label key is *a simple `string`* value that conforms to `^[A-Za-z][0-9A-Za-z_\-.]\*[A-Za-z0-9]$` and is limited to 512 characters.
    Keys are *unique per specific resources* (a module can define only a single label with the key of `{KEY}`) and are simple strings.
    This limitation simplifies the underlying systems, and it makes it less prone to abuse.

`{VALUE}`::
    The label value is a regular `string` value that doesn't put in place any particular value validations or constraints.

== Label usage

Labels can be used *by majority of {PRODUCT_NAME} resources* as long as it defines the proper facility for *assigning labels* and *label based retrieving*.

[TIP]
====
{PRODUCT_NAME} defines a dedicated package (`pkg/label`) that knows how to perform the core operations over labels.
Other services can trivially include the package into the request cycle.
====

.Supported resources:
. Users
. Roles
. Compose namespace
. Compose page
. Compose chart
. Compose module
. Compose module field
. Compose record


=== Assigning labels

.The resource *must cover* these cases when an additional `label` parameter is provided:
* If the parameter is *not provided*, *no* label *modifications* are performed.
* If the parameter *is provided* and *empty*, *remove all labels* from the given *resource*.
* If the parameter *is provided* and is *not empty*, *remove missing* labels and *add new labels*.

=== Retrieving resources

[NOTE]
====
When we query over resources that support labels and already define some labels, do we always want to return those labels?
Should we only return labels when we perform some operation over labels or when explicitly requested?
Does this make sense?
====

.The resource supports the following filtering operations:
* Filtering *by label existence*; check if *label with the given key* exists.
* Filtering *by label !existence*; check if *label with the given key does not* exist.
* Filtering by label *with a specific value*; check if *both* label *key and value* exist.

== Access control

All label access control falls under access control of the resource holding the labels.
Read access fall under resource's `read` operation.
Managing access (create, update, delete) fall under resource's `create` or `update` operation.

== Label store

Label store is generic and can be used by any {PRODUCT_NAME} resource using labels.
See the list of supported resouces in <<_label_usage>>.

.Resource labels store definition.
[cols="1s,1l,3a"]
|===
|Field |Type |Description

|Kind | string| Specifies the *kind of the resource* this label belongs to.
|ResourceID | uint64| Specifies the ID of the resource this label belongs to.
|Name | string| Specifies the key part of the label.
|Value | string| Specifies the value part of the label.
|===

[NOTE]
====
The primary key is *constructed* from `Kind`, `ResourceID`, and `Name` fields.
====

== Resource and label deleting

When resource is deleted a soft-delete is preformed in most cases.
For simplicity, on implementation level and for use, labels do not support soft delete.
When resource is deleted, all connected labels stay stored and available in case resource is restored later.
