include::../../variables.adoc[]

= Contacts

The Contacts page is accessible by clicking on the "Contacts" under the "Accounts" dropdown in the main navigation bar on the top of the screen.

Contacts belong to accounts, and we can think of them as employees for a specific company that we are allowed to contact.

== Key parts of a contact

[IMPORTANT]
====
A contact has two particular fields that indicate how and if we can contact them:

* Do Not Call,
* Email Opt Out.

The agent should check these fields before trying to make any contact.
====

Personal Data::
    Here we store the essential information regarding contacts, such as their name, title, phone, and email.

Contact Address::
    Here we store their contact address if we need to generate any quotes, send packages or dispatch maintainers.

Contact Twitter Feed::
    Here we can keep track of the contact's latest updates via Twitter.

Cases related to this Contact::
    Here we store the cases that are related to the contact; either created by them, or they are responsible for.

Emails::
    Here we store the emails that we sent to the contact, presented in chronological order.
    These are usually generated based on cases.

[TIP]
====
We can use this outside of cases, for example, to notify the client that their subscription expires soon.
====

== Add a case for a contact

. Open a contact you wish to create a case for,
. click on the "+ Add" button on top of the "Cases related to this Contact" list,
. fill out the data,
. press "Save" on the bottom right corner.

[NOTE]
====
Refer to xref:ROOT:end-user-guide/service-solution/index.adoc#cases[the cases section] for additional details.
====

== Add an email for a contact

[NOTE]
====
Emails are usually generated from a case and not directly as shown here.
====

. Open a contact you wish to create an email for,
. click on the "+ Add" button on top of the Emails list,
. fill out the data,
. press "Save" on the bottom right corner.
