include::../../variables.adoc[]

= Email templates

The Email Templates page is accessible by clicking on the "Email Templates" under the "Settings" dropdown in the main navigation bar on the top of the screen.

Email templates help us speed up the process of contacting our clients by prefilling the more common information and let us fine-tune the last few details, specific to the client.

== Key parts of an email template

Template::
    Here we store the essential parts of the template, such as its name, description, subject and the body content.
    We can use placeholders to speedup the process of designing an email (more on this in the below section).

Template is used in following emails::
    Here we can see all the emails that are using this template.
    We can use this to distinguish the more popular templates to help us design better templates in the future.

== Placeholders

[NOTE]
====
We can use placeholders in both the subject and the body.
====

We can use the following placeholders (take note of the `\{\{  \}\}` -- this indicates a placeholder).

.Placeholders for getting data of the case:
* `{{Case.Number}}`
* `{{Case.Subject}}`
* `{{Case.Status}}`
* `{{Case.ContactName}}`
* `{{Case.ContactTitle}}`
* `{{Case.ContactEmail}}`
* `{{Case.ContactPhone}}`
* `{{Case.Escalated}}`
* `{{Case.Category}}`
* `{{Case.CloseDate}}`
* `{{Case.Priority}}`
* `{{Case.Description}}`
* `{{Case.TotalTime}}`
* `{{Case.TotalCost}}`

.Placeholders for getting data of the contact:
* `{\{Contact.FirstName}}`
* `{\{Contact.LastName}}`
* `{\{Contact.Title}}`
* `{\{Contact.Phone}}`
* `{\{Contact.Email}}`
* `{\{Contact.Twitter}}`
* `{\{Contact.Facebook}}`
* `{\{Contact.LinkedIn}}`
* `{\{Contact.MailingStreet}}`
* `{\{Contact.MailingCity}}`
* `{\{Contact.MailingState}}`
* `{\{Contact.MailingPostalCode}}`
* `{\{Contact.MailingCountry}}`
* `{\{Contact.DoNotCall}}`
* `{\{Contact.HasOptedOutOfEmail}}`

== Example subject

[source,text]
----
Case: [{{Case.Number}}] "{{Case.Subject}}"
----

== Example body

[source,text]
----
Dear {{Contact.FirstName}},

We are contacting you concerning the case "{{Case.Subject}}".

...ADD_REASON_FOR_CONTACT_HERE...

Kind regards,

The service team
----
