include::ROOT:partial$variables.adoc[]

= Web Applications

The web applications are written in https://vuejs.org/[Vue.js] and provide the user interface to interact with the entire system.

The core web applications are located inside the {GIT_MONOREPO_LINK}[`corteza`] monorepo under `client/web`.

Communication between the {PRODUCT_NAME} server and web applications is done using the REST API and web sockets.

== Development setup

=== Fork the {PRODUCT_NAME} web application

[NOTE]
====
Core contributors should skip this part.
====

. go to the {GIT_MONOREPO_LINK} repository
. click on the btn:[Fork] button in the top right corner and follow the instructions on the screen.

=== Clone the repository

.Using the CLI:
. open the CLI
. navigate to your working folder
. run the `git clone git@github.com:cortezaproject/corteza.git` command

[TIP]
====
Refer to the repository if you wish to use an alternative method.
====

=== Configure the environment

.Inside your web application directory:
. run `cp public/config.example.js public/config.js` for _Linux_, or in `public` folder run `copy config.example.js config.js` for _Windows_
. open the `config.js` file using VIM, Nano, or any other editor and modify the configuration as you see fit

=== Set the API

.Define the API in the `public/config.js` by setting:
[source,js]
----
window.CortezaAPI = '$BASE_URL'
----

The `$BASE_URL` parameter is the location of your {PRODUCT_NAME} server.
If you are running the server on http://localhost:80, then the value should be `http://localhost:80/api`.

=== Set the authentication API

{PRODUCT_NAME} web applications authenticate the user using an OAuth2 flow.

This part can be skipped when using the same {PRODUCT_NAME} server for authentication and processing.
The web application will generate the authentication endpoints based on the `CortezaAPI` parameter.

.Define the authentication API in the `public/config.js` by setting:
[source,js]
----
window.CortezaAuth = '$BASE_URL/auth'
----

=== Assure dependencies

[CAUTION]
====
When using modified versions of `corteza-js` and `corteza-vue`, make sure to link them using `yarn link @cortezaproject/corteza-js` and `yarn link @cortezaproject/corteza-vue`.
====

Run the `yarn` command to assure that all of the packages are present and up to date.

See the `package.json` file for the supported Node.js versions.

=== Run the web application

Run the `yarn serve` command to start the web application.
You can use an optional `--port $POST` flag to specify what port it should run on.
