= DRAFT 3


= Record list filtering

Corteza provides an advanced filtering mechanism that allows you to easily filter your record by any field type, string, number, datetime


== Integration

=== Location

To use the record list filtering you need to import a `<record-list-filter>` component located in `Common\RecordListFilter.vue` in (https://github.com/cortezaproject/corteza-compose) repository


=== Usage

The `<record-list-filter>` component requires several parameters to be passed to it upon initialization

* 'selectedField' is the field you want to be passed as default field name
* 'namespace' corteza namespace object
* 'module' corteza module object
* 'recordListFilter' is the field which will contain your filter result

[source,js]
----
<record-list-filter
    :selectedField="field.moduleField"
    :namespace="namespace"
    :module="recordListModule"
    :recordListFilter="recordListFilter"
    @filter="onFilter"
/>
----

== Sql query parsing

The output of a `<record-list-filter>` component is an object array which is passed down to `queryToFilter` function located in `src\lib\record-filter.js` where it is combined with sorting parameters, and a search filter converted into a sql query. 

[source,js]
----
import { queryToFilter } from 'corteza-webapp-compose/src/lib/record-filter'
----


=== Extending the filter component

You can extend the filter component by adding your own custom fields or components to the record list filtering.

