include::ROOT:partial$variables.adoc[]

= Multi-image Discovery with PostgreSQL
:page-noindex: true

[NOTE]
====
Currently Corteza Discovery is tested on a running production servers in combination with PostgreSQL database, but should work with the latest MySQL versions.
Beside the `server` and `db` containers, there should be also the indexer (`opensearch-node`) and the searcher (`discovery`) running.
====

[CAUTION]
====
If your {APP_NAME_DISCOVERY} is not working, try restarting the `discovery` service.
There is a known issue with order of execution and health check reporting which may cause the service to fail for you.
====

== Configuration Files

.`docker-compose.yaml`
[source,yaml]
----
include::example$deploy/prod-discovery-pgsql/docker-compose.yaml[]
----

.`.env`
[source,env]
----
include::example$deploy/prod-discovery-pgsql/env-example.txt[]
----

[#integration-configuration]


== Preparing {PRODUCT_NAME}

{PRODUCT_NAME} {APP_NAME_DISCOVERY} is a stand alone application, independent from the rest of the {PRODUCT_NAME} system.
In order to make {APP_NAME_DISCOVERY} functional, you must *grant access* by creating an *auth client* along with *a user* and *a role*.

[IMPORTANT]
====
Access control defines what data the {APP_NAME_DISCOVERY} indexer has access to.
====

=== Indexer Role

Firstly define a new role for the {APP_NAME_DISCOVERY} indexer to use.
Open the {PRODUCT_NAME} {APP_NAME_ADMIN} web application and navigate to menu:System[Roles].
Click on the *New* button, fill in the parameters and click on the *Submit* button.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "discovery/role.png",
    "alias": "discovery-role",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 312,
    "y": 102,
    "w": 1313,
    "h": 544
  }
}
----

[#indexer-user]
=== Indexer User

Next, define a new user that the {APP_NAME_DISCOVERY} indexer should identify as.
In the {PRODUCT_NAME} {APP_NAME_ADMIN} web application navigate to menu:System[Users].
Click on the *New* button and fill in the parameters and click on the *Submit* button.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "discovery/user.png",
    "alias": "discovery-user",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 360,
    "y": 105,
    "w": 1233,
    "h": 521
  },
  "annotations": []
}
----

After you save the user, assign them the role you've created earlier.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "discovery/user-membership.png",
    "alias": "discovery-user-membership",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 372,
    "y": 319,
    "w": 1156,
    "h": 245
  },
  "annotations": []
}
----

=== Indexer Auth Client

Lastly, define an auth client that the {APP_NAME_DISCOVERY} indexer should use to authenticate with {PRODUCT_NAME}.

[NOTE]
====
Since authentication between two systems is being performed, you should to use the `client_credentials` grant type.
====

In the {PRODUCT_NAME} {APP_NAME_ADMIN} web application navigate to menu:System[Auth Clients].
Click on the *New* button and fill in the basic parameters; make sure you select the `client_credentials` grant type and check the `allow client access to Corteza Discovery API on behalf of user`.
Select the previously created user in the `impersonate user` input and click on the *Submit* button.

[NOTE]
====
It is recommended you define a new auth client for a new external application instead of reusing existing ones.
====

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "discovery/auth-client.png",
    "alias": "discovery-auth-client",
    "w": 1916,
    "h": 985
  },
  "view": {
    "x": 527,
    "y": 104,
    "w": 1151,
    "h": 732
  },
  "annotations": []
}
----