include::ROOT:partial$variables.adoc[]
include::ROOT:partial$icons.adoc[]

= Style Guide
:page-aliases: 2024.9@automation/workflows/organizing-workflows.adoc, 2024.9@automation/workflows/style-guide-best-practices.adoc
:keywords: automation, style guide, designing workflows
:description: Learn how you should structure your workflows for consistency and ease of maintenance

Workflows are based on and inherit the base rules from the BPMN 2.0 standard.
We define some additional rules to help keep workflows consistent.

== Follow the KISS principle

The Keep It Simple, Stupid principle indicates that your workflows should not be needlessly overcomplicated.
Over-engineering usually reduces clarity and introduces more failure points.

To exemplify, instead of using a gateway to set a `Boolean` variable to the correct value, write an expression that evaluates the desired value.

.The screenshot outlines an over-engineered version.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "automation/workflows/styleguide/simple-gateway.png",
    "alias": "automation-workflows-styleguide-simple-gateway.png",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 164,
    "y": 286,
    "w": 691,
    "h": 430
  },
   "annotations": []
}
----

.The screenshot outlines a simplified version.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "automation/workflows/styleguide/simple-expression.png",
    "alias": "automation-workflows-styleguide-simple-expression.png",
    "w": 1920,
    "h": 1080
  },
   "view": {
    "x": 1030,
    "y": 1,
    "w": 889,
    "h": 600
  },

   "annotations": []
}
----

[CAUTION]
====
Most operations can be transformed into expressions but at the cost of clarity.
If a simplification causes the clarity to decrease, you should choose to avoid it.
====

[TIP]
====
Larger complex operations can be replaced by xref:automation/workflows/automation-scripts.adoc[automation scripts].
====

== Avoid crossing connectors

When working with larger workflows, crossing connectors may mislead and confuse the reader.
Workflow steps define many anchor points to help you achieve this.

.An example of crossing connectors:

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "automation/workflows/styleguide/connectors-nok.png",
    "alias": "automation-workflows-styleguide-connectors-nok.png",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 78,
    "y": 156,
    "w": 1295,
    "h": 389
  },
   "annotations": []
}
----

.An example of corrected, non-crossing connectors:

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "automation/workflows/styleguide/connectors-ok.png",
    "alias": "automation-workflows-styleguide-connectors-ok.png",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 78,
    "y": 155,
    "w": 1295,
    "h": 303
  },
   "annotations": []
}
----

[TIP]
====
A connector defines a series of anchor points that you may use to adjust the flow of the connector.
The anchor points become available when you click on the connector.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "automation/workflows/styleguide/connector-anchors.png",
    "alias": "automation-workflows-styleguide-connector-anchors.png",
    "w": 1920,
    "h": 1080
  },
    "view": {
    "x": 188,
    "y": 290,
    "w": 996,
    "h": 373
  },
   "annotations": []
}
----

====

== Step labels

All workflow steps should have a short label that outlines the core of the step.
To exemplify, an expression that calculates the sales commissions is best to be labelled as "Calculate sales commissions".

A *trigger* label should state the resource and the trigger type.
This allows the reader to understand when the trigger is executed without reading the configuration.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "automation/workflows/styleguide/label-trigger.png",
    "alias": "automation-workflows-styleguide-label-trigger.png",
    "w": 1920,
    "h": 1080
  },
    "view": {
    "x": 325,
    "y": 335,
    "w": 629,
    "h": 360
  },
   "annotations": []
}
----

A *gateway* label should state the question that determines the output.
The output path labels should state the answer to the question of the corresponding gateway.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "automation/workflows/styleguide/label-gateway.png",
    "alias": "automation-workflows-styleguide-label-gateway.png",
    "w": 1920,
    "h": 1080
  },
   "view": {
    "x": 192,
    "y": 228,
    "w": 725,
    "h": 517
  },
  "annotations": []
}
----

The *function* label should contain the verb and the subject of the function.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "automation/workflows/styleguide/label-function.png",
    "alias": "automation-workflows-styleguide-label-function.png",
    "w": 1920,
    "h": 1080
  },
   "view": {
    "x": 193,
    "y": 280,
    "w": 361,
    "h": 206
  },
   "annotations": []
}
----

== Coherent layouts

The initial integration usually consists of multiple workflows which can be extended and added in the future.
A consistent layout increases consistency and coherence.

.Here are some tips:
* the flow should go from top-left to bottom-right,
* group the related steps,
* align the steps with the grid,
* keep the layout symmetric as it is generally easier to understand.

== Use swimlanes to organize your workflows

You can use the *swimlane* {ICON_WORKFLOW_SWIMLANE} visual element to organize your workflows.

In smaller workflows that perform simple, singular operations (such as notifying administrator about a client sign-up or logging changes) swimlanes do not make much sense and may even reduce the clarity.

For larger projects however, swimlanes can be an orderly addition as they help you visually group smaller steps into larger operations and thus allow you to understand what a specific part of the workflow does.

.The screenshot shows the refactored workflow with swimlanes to group operations.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "automation/workflows/styleguide/swimlane.png",
    "alias": "automation-workflows-styleguide-swimlane.png",
    "w": 1920,
    "h": 1080
  },
    "view": {
    "x": 100,
    "y": 86,
    "w": 1026,
    "h": 945
  },
  "annotations": []
}
----

