include::ROOT:partial$variables.adoc[]
include::ROOT:partial$icons.adoc[]

= Testing and Debugging Workflows
:keywords: automation, workflows, testing, debugging
:description: Learn how to test and debug your workflows

[#testing]
== Testing

Testing is a powerful and essential component of any project.

[CAUTION]
====
The testing approach mentioned below doesn't sandbox your data in any way.
Any changes performed by the workflow are reflected in the system.
====

Let us look at an example.
You want to implement a workflow that calculates the cost of a newly created lead.
The cost of the lead is sent as an email to the administrator.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "automation/workflows/testing-debugging/manual-test-play.png",
    "alias": "automation-workflows-testing-debugging-manual-test-play.png",
    "w": 978,
    "h": 145
  },
  "view": {},
   "annotations": []
}
----

To test the workflow, click on the play icon {ICON_WORKFLOW_PLAY} in the top right corner of the trigger.
Only saved and valid workflows can be run.

A pop-up asking for the initial scope appears.
The initial scope is data passed to the workflow to perform an operation.

[NOTE]
====
The initial scope depends on the resource and event type.
====

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "automation/workflows/testing-debugging/manual-test-load-resources.png",
    "alias": "automation-workflows-testing-debugging-manual-test-load-resources.png",
    "w": 745,
    "h": 705
  },
  "view": {},
   "annotations": []
}
----

Insert the required parameters and click on the btn:[Load and Configure] button to set the initial scope.
Any missing parameters are automatically added as the empty value of that type.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "automation/workflows/testing-debugging/manual-test-configure-resources.png",
    "alias": "automation-workflows-testing-debugging-manual-test-configure-resources.png",
    "w": 743,
    "h": 690
  },
  "view": {},
   "annotations": []
}
----

The last step allows you to change the variables of the initial scope before test running the workflow.
Click on the btn:[Run Workflow] to run the workflow, or on the btb:[Back] button to return to the previous screen.

When a workflow is manually run, you see a green outline that indicates the execution path based on the provided input.
If any of the steps fail to execute successfully, they are be marked with a red outline.
If there is no error handling, the manual execution is also terminated.

.An example of a successful test:

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "automation/workflows/testing-debugging/manual-test-run-ok.png",
    "alias": "automation-workflows-testing-debugging-manual-test-run-ok.png",
    "w": 1012,
    "h": 146
  },
  "view": {},
   "annotations": []
}
----

.An example of a failed test:

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "automation/workflows/testing-debugging/manual-test-run-nok.png",
    "alias": "automation-workflows-testing-debugging-manual-test-run-nok.png",
    "w": 1397,
    "h": 288
  },
  "view": {},
   "annotations": []
}
----

In some cases, your workflows may implement steps that should only run in production, such as client charging, mass email notifications, and similar.
We can mock this path of execution by defining a `testing` flag at the beginning.
Before you reach the "in production only" steps, you should use an exclusive gateway to carry out distinctive handling, such as logging a message or using a <<debug-step,debug step {ICON_WORKFLOW_DEBUG}>>.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "automation/workflows/testing-debugging/manual-test-special.png",
    "alias": "automation-workflows-testing-debugging-manual-test-special.png",
    "w": 1370,
    "h": 399
  },
  "view": {},
   "annotations": []
}
----

When you run the workflow after that step, you should see something like the below example:

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "automation/workflows/testing-debugging/manual-test-special-ok.png",
    "alias": "automation-workflows-testing-debugging-manual-test-special-ok.png",
    "w": 1371,
    "h": 438
  },
  "view": {},
   "annotations": []
}
----

== Debugging

Knowing how to debug a specific tool or software can save you a lot of time if you encounter an issue.

[#debug-step]
=== The debugging step

The debugging step {ICON_WORKFLOW_DEBUG} allows you to inspect the contents of the scope it resides in.

The debugging step uses the logger configured by the server and it is not visible in the workflow editor itself.

.A simple example:

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "automation/workflows/testing-debugging/debug-example-simple.png",
    "alias": "automation-workflows-testing-debugging-debug-example-simple.png",
    "w": 829,
    "h": 144
  },
  "view": {},
   "annotations": []
}
----

=== Test result context

When you <<testing,run a manual test>> for the workflow you might notice an icon in the bottom right corner of the step.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "automation/workflows/testing-debugging/debug-stepctx.png",
    "alias": "automation-workflows-testing-debugging-debug-stepctx.png",
    "w": 325,
    "h": 143
  },
  "view": {},
   "annotations": []
}
----
When you hover over the icon you see the important information regarding the steps' execution.

If you hover over a successful step (step with a green outline), you see the duration of the execution.
Knowing the duration of the execution can help you pinpoint any system bottlenecks.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "automation/workflows/testing-debugging/debug-stepctx-ok.png",
    "alias": "automation-workflows-testing-debugging-debug-stepctx-ok.png",
    "w": 434,
    "h": 184
  },
  "view": {},
   "annotations": []
}
----

If you hover over a failed step (step with a red outline), you see the duration of the execution and the encountered error.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "automation/workflows/testing-debugging/debug-stepctx-nok.png",
    "alias": "automation-workflows-testing-debugging-debug-stepctx-nok.png",
    "w": 1127,
    "h": 159
  },
  "view": {},
   "annotations": []
}
----
