= Evaluate applied permissions

Corteza RBAC uses the roles of the given user to determine if they have access to a given resource.

Therefore a user can evaluate the permissions applied to a particular user by listing  the actions that are allowed in different roles.

== How to evaluate applied permissions

1. Once you're logged into corteza, click the *[admin area]* card

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "access-control/permission-admin-area.png",
    "alias": "admin-area",
    "w": 516,
    "h": 353
  },
  "view": {},
  "annotations": [{
    "kind": "box",
    "x": 135,
    "y": 145,
    "w": 43,
    "h": 43
  }]
}
----
2.Click on *[Roles]* button to see a list of all availabe roles 

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "access-control/permission-role-page.png",
    "alias": "roles-page",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "annotations": [{
    "kind": "box",
    "padding": "xs",
    "x": 16,
    "y": 180,
    "w": 288,
    "h": 37
  }]
}
----
 
3.Click the *[permissions button]*.
[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "access-control/permission-button-page.png",
    "alias": "new-user",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "annotations": [{
    "kind": "box",
    "padding": "xs",
    "x": 1535,
    "y": 75,
    "w": 130,
    "h": 42
  }]
}
----

4.Click the *[add +]* button to evaluate applied permissions

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "access-control/add-role.png",
    "alias": "add-role",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "annotations": [{
    "kind": "box",
    "padding": "xs",
    "x": 765,
    "y": 150,
    "w": 750,
    "h": 80
}]
}
----


5.Click the *[select roles]* dropdown and select a role or the *[select user]* to choose a user.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "access-control/eval-permission.png",
    "alias": "user-create",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "annotations": []
}
----

6.Click the *[save & close]* button.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "access-control/add-role-button.png",
    "alias": "user-create",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "annotations": []
}
----

7.Repeat the steps again choosing a different role on step 5 and 6 respectively inorder to evaluate  the different permissions applied on a role.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "access-control/save-eval.png",
    "alias": "save-eval",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "annotations": []
}
----

