= Permissions

A permission is what is needed to execute/access an resource. Permissions are assigned to roles, and resources require a set of permissions.

[IMPORTANT]
A set of permissions can be tailored for each role to meet its particular needs and is inherited by all the users who fulfill that role. If the permissions for a role need to be changed, those changes are similarly passed on to the users or members of that role


Permissions control who has access to what on a network and even what level of permission they have. Administrators, for example, will have access to all folders or files, and they grant access to those resources to others. Those permissions might be to only read a file, but not edit it, or they may include edit access as well. Permissions are typically granted based on the role a person plays inside a company.

== Access rights

Each role has explicit access rights determine what operations  that a user can perform on particular corteza resource. For example, the access rights on a security account can determine whether the user or role has the right to create items, delete items, or to push items through a workflow.

Each access right has one of three possible settings. They are:

* Allow – grants the associated access rights for the selected account.

* Deny – denies the associated access right for the selected account.

* Inherit – The Inheritance access right is a setting that determines whether an item can inherit its ancestors' access rights for a specific item resource.

=== The Inheritance access right

The Inheritance access right is a setting that determines whether an item can inherit its ancestors' access rights for a specific item resource.

You can use the Inheritance access right to streamline the process of assigning access rights. In certain situations, this can spare administrators the tedious task of assigning each role explicit access rights to every item in the content tree.

By default, an item inherits the access rights that are assigned to the items that are higher up the content tree (the ancestors). For example, a security administrator can configure the security settings of a single item and all the items that are lower down the content tree (the descendants) automatically inherit the same settings. However, if there is an item that should not inherit any security settings from its ancestors, you can use the Inheritance access right to deny the item the right to inherit the security settings.

