include::ROOT:partial$variables.adoc[]

[NOTE]
====
*DevNote* either provide a TL;DR changelog or link to a detailed changelog.
====

{PRODUCT_NAME} defines a https://en.wikipedia.org/wiki/Role-based_access_control[RBAC] access control facility.
RBAC uses the <<glossary-role,*roles*>> of the given <<glossary-user,*user*>> to determine if they have access to the given <<glossary-resource,*resource*>>.

{PRODUCT_NAME}'s RBAC facility uses a "flat design", which removes role hierarchy (two roles can not explicitly define a parent/child relationship).

<<role-type-ctx,*Context role membership*>> allows you to dynamically assign users to roles based on the defined set of rules.

[IMPORTANT]
====
While access control for specific records is supported, access control for particular fields of particular records is not.

You can bypass this limitation by using <<role-type-ctx,context role membership>> and module filed rules.
====

= Access evaluation flow

[CAUTION]
====
If a user is a member of a bypass role, *all* operations are permitted without any restrictions.
====

When access is evaluated, the system collects all users' roles and RBAC rules (security context).
The order of rule evaluation is based on <<ac-role-importance,*role importance*>> and <<ac-resource-specificity,*resource specificity*>>.

.Access evaluation flow:
. If any rule defines an explicit *deny*, the evaluation results with *deny*.
. If at least one rule defines an explicit *allow*, the evaluation results with *allow*.
. If the current level has no explicit allow or deny, the evaluation continues to the next set of rules based on role importance.
. If the evaluation cannot find an explicit allow or deny, the evaluation results with *deny*.

[#ac-role-importance]
== Role importance

Role importance defines the order in which roles and their corresponding rules are evaluated.

.Role importance for authenticated users:
. bypass roles
. context roles
. common roles
. authenticated roles

.Role importance for authenticated users:
. anonymous roles

[#ac-resource-specificity]
== Resource specificity

Resource specificity defines the order in which rules for the corresponding resources are evaluated.
Resource specificity is defined based on "how specific is this rule to this resource".

As an example, a rule that allows users to create records on the account module in the CRM namespace is more specific than the rule just on the CRM namespace.

[TIP]
====
Such specificity allows you to deny access to all but one resource of the given type.
====

= Role types

A list of bypass, authenticated, and anonymous roles is provided in the system configuration and can not be changed at runtime.
Refer to xref:devops-guide:maintenance/access-control.adoc[DevOps guide] for details on how this can be done

These roles can not be modified or renamed.

.If you wish to alter the roles, you can either:
* temporarily change the role list, edit the roles, revert the role list changes,
* change the provision scripts to supply the required names at the initial {PRODUCT_NAME} run.

[#role-type-bypass]
== Bypass

Bypass roles allow their members unlimited access to {PRODUCT_NAME} with no permission checking.

Out of the box, {PRODUCT_NAME} defines the default bypass role named "Super administrator".
Your system administrator can xref:devops-guide:maintenance/access-control.adoc[change the set of bypass roles] in the `.env` file.
The roles that are defined as authenticated have restricted editing options.

[#role-type-common]
== Common

Common roles are any additional roles defined in the administration panel, such as a CRM admin and application builder.

[#role-type-ctx]
== Contextual

[CAUTION]
====
You can not use contextual roles within auth clients, nor can they define an explicit member list.
Contextual roles are assigned to users based on the operation and the context.
====

Contextual roles define a series of *expressions*, which determine when the role is assigned to the user based on the operations' context.

Each role can define an expression for each resource type.
Each role can only use a resource type once.

[CAUTION]
====
Contextual roles are hidden from resource permission screens if the role does not define an expression for that resource.
For example, a record specific role is not shown on the module permission screen.
====

An example use case would allow us to assign roles to resource owners, which would give them permissions that they shouldn't have over other resources.

Refer to the <<ctx-role-evaluation,ctx-role-evaluation>> for details.

[IMPORTANT]
====
.Contextual roles are currently supported for:
* records
* workflows
* auth clients
====

[#role-type-authenticated]
== Authenticated

Authenticated roles are *implicit*, meaning that users can not explicitly be set as role members.

Out of the box, {PRODUCT_NAME} defines the default authenticated role named "Authenticated".
Your system administrator can xref:devops-guide:maintenance/access-control.adoc[change the set of authenticated roles] in the `.env` file.
The roles that are defined as authenticated have restricted editing options.

If the user is authenticated with {PRODUCT_NAME} when they are accessing a resource, the system additionally assigns them authenticated roles.

[#role-type-anonymous]
== Anonymous

Anonymous roles are *implicit*, meaning that users can not explicitly be set as role members.

Out of the box, {PRODUCT_NAME} defines the default anonymous role named "Anonymous".
Your system administrator can xref:devops-guide:maintenance/access-control.adoc[change the set of anonymous roles] in the `.env` file.
The roles that are defined as anonymous have restricted editing options.

If the user is *not* authenticated with {PRODUCT_NAME} when they are accessing a resource, the system additionally assigns them anonymous roles.

[#ctx-role-evaluation]
= Contextual role evaluation

Refer to xref:integrator-guide:/expr/index.adoc[] for details on writing context role expressions.

If the expression returns `true`, the contextual role is applied.

.Common variables:
[cols="1s,5a"]
|===
| [#ctx-eval-var-general-userID]#<<ctx-eval-var-general-userID,userID>>#
|
The ID of the current user.

|===

== Records

.Records variables:
[cols="1s,5a"]
|===
| [#ctx-eval-var-record-ID]#<<ctx-eval-var-record-ID,resource.ID>>#
|
The ID of the resource.

| [#ctx-eval-var-record-recordID]#<<ctx-eval-var-record-recordID,resource.recordID>>#
|
The ID of the resource; same as <<ctx-eval-var-record-ID,resource.ID>>.

| [#ctx-eval-var-record-moduleID]#<<ctx-eval-var-record-moduleID,resource.moduleID>>#
|
The ID of the related module.

| [#ctx-eval-var-record-labels]#<<ctx-eval-var-record-labels,resource.labels>>#
|
The key-value pair of labels associated with this resource.

| [#ctx-eval-var-record-namespaceID]#<<ctx-eval-var-record-namespaceID,resource.namespaceID>>#
|
The ID of the related namespace.

| [#ctx-eval-var-record-ownedBy]#<<ctx-eval-var-record-ownedBy,resource.ownedBy>>#
|
The userID of the resource owner.

| [#ctx-eval-var-record-createdAt]#<<ctx-eval-var-record-createdAt,resource.createdAt>>#
|
The timestamp of when the resource was created.

| [#ctx-eval-var-record-createdBy]#<<ctx-eval-var-record-createdBy,resource.createdBy>>#
|
The userID of the user that created the resource.

| [#ctx-eval-var-record-updatedAt]#<<ctx-eval-var-record-updatedAt,resource.updatedAt>>#
|
The timestamp of when the resource was last updated.
The parameter is not defined if the resource has not yet been updated.

| [#ctx-eval-var-record-updatedBy]#<<ctx-eval-var-record-updatedBy,resource.updatedBy>>#
|
The userID of the user that last updated the resource.
The parameter will be `0` if the resource has not yet been updated.

| [#ctx-eval-var-record-deletedAt]#<<ctx-eval-var-record-deletedAt,resource.deletedAt>>#
|
The timestamp of when the resource was deleted.
The parameter is not defined if the resource has not been deleted.

| [#ctx-eval-var-record-deletedBy]#<<ctx-eval-var-record-deletedBy,resource.deletedBy>>#
|
The userID of the user that deleted the resource.
The parameter will be `0` if the resource has not been updated.

| [#ctx-eval-var-record-values]#<<ctx-eval-var-record-values,resource.values>>#
|
A set of key-value pairs for the record values defined by the module fields.

[NOTE]
====
If a module field is a multi-value, the corresponding key-value entry will be an array.
====

|===

== Workflows

.Workflows variables:
[cols="1s,5a"]
|===
| [#ctx-eval-var-workflow-ID]#<<ctx-eval-var-workflow-ID,resource.ID>>#
|
The ID of the resource.

| [#ctx-eval-var-workflow-workflowID]#<<ctx-eval-var-workflow-workflowID,resource.workflowID>>#
|
The ID of the resource; same as <<ctx-eval-var-workflow-ID,resource.ID>>.

| [#ctx-eval-var-workflow-labels]#<<ctx-eval-var-workflow-labels,resource.labels>>#
|
The key-value pair of labels associated with this resource.

| [#ctx-eval-var-workflow-ownedBy]#<<ctx-eval-var-workflow-ownedBy,resource.ownedBy>>#
|
The userID of the resource owner.

| [#ctx-eval-var-workflow-createdAt]#<<ctx-eval-var-workflow-createdAt,resource.createdAt>>#
|
The timestamp of when the resource was created.

| [#ctx-eval-var-workflow-createdBy]#<<ctx-eval-var-workflow-createdBy,resource.createdBy>>#
|
The userID of the user that created the resource.

| [#ctx-eval-var-workflow-updatedAt]#<<ctx-eval-var-workflow-updatedAt,resource.updatedAt>>#
|
The timestamp of when the resource was last updated.
The parameter is not defined if the resource has not yet been updated.

| [#ctx-eval-var-workflow-updatedBy]#<<ctx-eval-var-workflow-updatedBy,resource.updatedBy>>#
|
The userID of the user that last updated the resource.
The parameter will be `0` if the resource has not yet been updated.

| [#ctx-eval-var-workflow-deletedAt]#<<ctx-eval-var-workflow-deletedAt,resource.deletedAt>>#
|
The timestamp of when the resource was deleted.
The parameter is not defined if the resource has not been deleted.

| [#ctx-eval-var-workflow-deletedBy]#<<ctx-eval-var-workflow-deletedBy,resource.deletedBy>>#
|
The userID of the user that deleted the resource.
The parameter will be `0` if the resource has not been updated.

|===

== Auth clients

.Auth clients variables:
[cols="1s,5a"]
|===
| [#ctx-eval-var-auth-client-ID]#<<ctx-eval-var-auth-client-ID,resource.ID>>#
|
The ID of the resource.

| [#ctx-eval-var-auth-client-labels]#<<ctx-eval-var-auth-client-labels,resource.labels>>#
|
The key-value pair of labels associated with this resource.

| [#ctx-eval-var-auth-client-scope]#<<ctx-eval-var-auth-client-scope,resource.scope>>#
|
The scope defined by the auth client.

| [#ctx-eval-var-auth-client-validGrant]#<<ctx-eval-var-auth-client-validGrant,resource.validGrant>>#
|
The grant that is supported by the auth client.

| [#ctx-eval-var-auth-client-redirectURI]#<<ctx-eval-var-auth-client-redirectURI,resource.redirectURI>>#
|
The redirect URI for the auth client.

| [#ctx-eval-var-auth-client-trusted]#<<ctx-eval-var-auth-client-trusted,resource.trusted>>#
|
The trust setting of the auth client.

| [#ctx-eval-var-auth-client-enabled]#<<ctx-eval-var-auth-client-enabled,resource.enabled>>#
|
The enabled setting for the auth client.

| [#ctx-eval-var-auth-client-validFrom]#<<ctx-eval-var-auth-client-validFrom,resource.validFrom>>#
|
The timestamp denoting from when the auth client is valid from.

| [#ctx-eval-var-auth-client-expiresAt]#<<ctx-eval-var-auth-client-expiresAt,resource.expiresAt>>#
|
The timestamp denoting when the auth client is no longer valid.

| [#ctx-eval-var-auth-client-ownedBy]#<<ctx-eval-var-auth-client-ownedBy,resource.ownedBy>>#
|
The userID of the resource owner.

| [#ctx-eval-var-auth-client-createdAt]#<<ctx-eval-var-auth-client-createdAt,resource.createdAt>>#
|
The timestamp of when the resource was created.

| [#ctx-eval-var-auth-client-createdBy]#<<ctx-eval-var-auth-client-createdBy,resource.createdBy>>#
|
The userID of the user that created the resource.

| [#ctx-eval-var-auth-client-updatedAt]#<<ctx-eval-var-auth-client-updatedAt,resource.updatedAt>>#
|
The timestamp of when the resource was last updated.
The parameter is not defined if the resource has not yet been updated.

| [#ctx-eval-var-auth-client-updatedBy]#<<ctx-eval-var-auth-client-updatedBy,resource.updatedBy>>#
|
The userID of the user that last updated the resource.
The parameter will be `0` if the resource has not yet been updated.

| [#ctx-eval-var-auth-client-deletedAt]#<<ctx-eval-var-auth-client-deletedAt,resource.deletedAt>>#
|
The timestamp of when the resource was deleted.
The parameter is not defined if the resource has not been deleted.

| [#ctx-eval-var-auth-client-deletedBy]#<<ctx-eval-var-auth-client-deletedBy,resource.deletedBy>>#
|
The userID of the user that deleted the resource.
The parameter will be `0` if the resource has not been updated.

|===

= Important notes

== System setup

{PRODUCT_NAME} defines a series of system role types: bypass, authenticated, and anonymous.
System role types are defined on the server configuration level, and *cannot* be changed directly through the user interface.

If a role is assigned to one of the system role types, the editing is restricted.
If the role was somehow removed or changed to the extent where the system can not identify it, the system would refuse to start.

.The rationale behind such restrictions:
* The configuration affects the RBAC facility and its setup process.
* Systems that work with access tokens need to be aware of such changes.
* The security model on this level rarely changes, and the change is drastic when it does.

== Bypass RBAC roles

If a role is assigned as a bypass, it may *not* appear as any other role type (such as an authenticated or anonymous).
In the case where this is not the case, the system will refuse to start.

Only members of the check-bypass role can modify members of that particular role.

[NOTE]
====
*DevNote* ^ huh?
====

Bypass roles can be listed on auth clients as permitted or prohibited roles but are *silently ignored* when defined under forced roles.

== Authenticated and anonymous

Authenticated and anonymous roles may not appear in any auth client security role lists (the allowed, denied, and forced roles) and are silently ignored.

= Glossary

[cols="1s,5a"]
|===
| [#glossary-user]#<<glossary-user,A user>>#
|
A user is an entity that is accessing {PRODUCT_NAME}.
A user can be a member of security roles and cannot get permissions directly without an assigned role.

| [#glossary-role]#<<glossary-role,A role>>#
|
A role represents a set of users and a set of permissions over resources.

{PRODUCT_NAME}'s RBAC implementation defines a flat structure that removes role hierarchy (two roles can not explicitly specify a parent/child relationship).

| [#glossary-access]#<<glossary-access,Access>>#
|
Defines if the rule permits (`allow`) or denies (`deny`).

| [#glossary-resource]#<<glossary-resource,A resource>>#
|
A structured piece of information stored within {PRODUCT_NAME} that we may or may not control access to.
Each resource belongs to a component and has a unique type.

| [#glossary-resource-type]#<<glossary-resource-type,A resource type>>#
|
A resource type defines the structure of information within the {PRODUCT_NAME} component.

| [#glossary-operation]#<<glossary-operation,Operation>>#
|
Defines what operation the given RBAC rule defines access to.

| [#glossary-rbac-rule]#<<glossary-rbac-rule,RBAC rule>>#
|
A RBAC rule combines *operation*, *role*, *access*, and *resource*.
It defines what someone can (or can not) do on one or more resources inside {PRODUCT_NAME}.

| [#glossary-security-session]#<<glossary-security-session,Security session>>#
|
A security session is created when a user requests to access {PRODUCT_NAME}.

|===
