include::ROOT:partial$variables.adoc[]

= Authentication

== Auth client

An authentication client (an auth client for short) is a facility that allows you to define how an external application can {PRODUCT_NAME} to authenticate and what access the authenticated users may have.

The menu:system[auth clients] user interface allows you to inspect and manage your auth clients.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "auth-client-list.png",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "annotations": [{
    "kind": "box",
    "padding": "xs",
    "x": 16,
    "y": 405,
    "w": 288,
    "h": 37
  }]
}
----

.From there you can:
* List the auth clients created inside your {PRODUCT_NAME} instance.
* create a new auth client by clicking on the btn:[new] button,
* edit an existing auth client by clicking on the btn:[edit] icon next to the auth client,
* manage global auth client permissions by clicking on the btn:[permissions button].

=== Listing auth clients

.To list current system auth clients:
. Navigate to menu:system[auth clients],
. optionally insert the filtering parameters (the list refreshes automatically).

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "auth-client-list.png",
    "alias": "admin-webapp-auth-client-list",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 321,
    "y": 0,
    "w": 1599,
    "h": 430
  },
  "annotations": []
}
----

=== Creating auth clients

[IMPORTANT]
====
Permissions can only be defined on existing auth clients.
====

.To create a new auth client:
. Navigate to menu:system[auth clients],
. click on the btn:[new] button in the top right corner,
. provide the requested data,
. press the btn:[submit] button.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "auth-client-create.png",
    "alias": "admin-webapp-auth-client-create",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 321,
    "y": 0,
    "w": 1599,
    "h": 1080
  },
  "annotations": []
}
----

=== Editing auth clients

.To edit an existing auth client:
. Navigate to menu:system[auth clients],
. click on the btn:[edit] icon next to the auth client you wish to edit,
. update the parameters you wish to change,
. press the btn:[submit] button.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "auth-client-edit.png",
    "alias": "admin-webapp-auth-client-edit",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 321,
    "y": 0,
    "w": 1599,
    "h": 1080
  },
  "annotations": []
}
----

=== Deleting auth clients

.To delete an existing auth client:
. Navigate to menu:system[auth clients],
. click on the btn:[edit] icon next to the auth client you wish to suspend,
. press and confirm the btn:[delete] button.

[IMPORTANT]
====
Default auth clients can not be deleted.
====

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "auth-client-delete.png",
    "alias": "admin-webapp-auth-client-delete",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 321,
    "y": 0,
    "w": 1599,
    "h": 1080
  },
  "annotations": [{
    "kind": "box",
    "x": 586,
    "y": 1033,
    "h": 30,
    "w": 76
  }]
}
----

== Grant types

{PRODUCT_NAME} authentication supports two OAuth2 grant types: authorization code and client credentials.

.Authentication grant types:
[cols="1s,5a"]
|===
| [#auth-client-grant-authorization-code]#<<auth-client-grant-authorization-code,Authorization code>>#
|
The *authorization code* grant type is used to authenticate users with the classic OAuth2 flow.

To enable the grant type, select the "will be used to authenticate users (grant type = authorization_code)" option.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "auth-client-authorization-code.png",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 321,
    "y": 0,
    "w": 1599,
    "h": 1080
  },
  "annotations": [{
    "kind": "box",
    "padding": "sm",
    "x": 855,
    "y": 407,
    "w": 526,
    "h": 19
  }]
}
----

| [#auth-client-grant-client-credentials]#<<auth-client-grant-client-credentials,Client credentials>>#
|
The *client credentials* grant type is the simplified authentication flow, normally used to authenticate machines, such as external services or applications.

[IMPORTANT]
====
Client credentials grant type requires you to populate the "impersonate user" option.
The impersonated user will be used to create the security context of the JWT token.
====

To enable the grant type, select the "will be used to authenticate machines (grant type = client_credentials)" option.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "auth-client-client-credentials.png",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 321,
    "y": 0,
    "w": 1599,
    "h": 1080
  },
  "annotations": [{
    "kind": "box",
    "padding": "sm",
    "x": 855,
    "y": 429,
    "w": 547,
    "h": 19
  }]
}
----

|===

== Defining password constraints

{PRODUCT_NAME} allows you to define custom password constraints which enables you to better conform to your security model.

Password constraints are configured on the {PRODUCT_NAME} {APP_NAME_ADMIN} web application under menu:system[settings] in the "password constraints" section.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "authentication/password-constraints.png",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 321,
    "y": 0,
    "w": 1599,
    "h": 1080
  },
  "focus": {
    "x": 565,
    "y": 355,
    "w": 1108,
    "h": 272,
    "padding": 10
  },
  "annotations": []
}
----

[cols="2s,5a"]
|===
| [#auth-password-constraint-len]#<<auth-password-constraint-len,Minimum length>>#
|
The minimum length parameter allows you to restrict your users from using short, insecure passwords.
You can not set the minimum length below 8.

The maximum password length is not configurable and is set to 256.

| [#auth-password-constraint-numbers]#<<auth-password-constraint-numbers,Minimum number of numbers>>#
|
The minimum number of numbers allows you to require your users to use numerical values in their passwords.
The requirement is disabled if left at 0.

| [#auth-password-constraint-symbols]#<<auth-password-constraint-symbols,Minimum number of special characters>>#
|
The minimum number of special characters allows you to require your users to use special characters in their passwords.
The requirement is disabled if left at 0.

|===

[CAUTION]
====
The `AUTH_PASSWORD_SECURITY` `.env` variable allows you to disable password requirements checking by setting it to `false`.
This is handy for local development where we may not wish to handle complex password constraints.

The option should be *disabled* for any production deployment.
If the password security is disabled, a warning message is displayed in the UI.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "authentication/password-security-disabled.png",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 321,
    "y": 0,
    "w": 1599,
    "h": 1080
  },
  "focus": {
    "x": 565,
    "y": 355,
    "w": 1108,
    "h": 336,
    "padding": 10
  },
  "annotations": [{
    "kind": "box",
    "x": 585,
    "y": 401,
    "w": 1071,
    "h": 48
  }]
}
----
====

== Define session duration

{PRODUCT_NAME} allows you to define how long the access tokens should be considered valid.

.The three `.env` variables to control the authentication session:
[cols="2s,5a"]
|===
| [#auth-sesion-auth_oauth2_access_token_lifetime]#<<auth-sesion-auth_oauth2_access_token_lifetime,AUTH_OAUTH2_ACCESS_TOKEN_LIFETIME>>#
|
The `AUTH_OAUTH2_ACCESS_TOKEN_LIFETIME` `.env` variable allows you to define how long an access token should be valid.

The access token represents the credentials that allow users to access protected resources such as records, users, and workflows.

.An example of limiting the access token to two minutes:
[source,.env]
----
AUTH_OAUTH2_ACCESS_TOKEN_LIFETIME=2m
----

| [#auth-sesion-auth_oauth2_refresh_token_lifetime]#<<auth-sesion-auth_oauth2_refresh_token_lifetime,AUTH_OAUTH2_REFRESH_TOKEN_LIFETIME>>#
|
The `AUTH_OAUTH2_REFRESH_TOKEN_LIFETIME` `.env` variable allows you to define how long a refresh token should be valid.

The refresh token provides a mechanism to generate a new access token when the old one expires, removing the need to re-authenticate the user.

.An example of limiting the refresh token to two minutes:
[source,.env]
----
AUTH_OAUTH2_REFRESH_TOKEN_LIFETIME=2m
----

| [#auth-sesion-auth_session_lifetime]#<<auth-sesion-auth_session_lifetime,AUTH_SESSION_LIFETIME>>#
|
The `AUTH_SESSION_LIFETIME` `.env` variable allows you to define how long the authentication session should be valid.

The authentication session is generated when the user provides their credentials to the *{PRODUCT_NAME} login page*.
The authentication session is independent of access tokens.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "auth-login.png",
    "alias": "auth-login-reg",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "annotations": [{
    "kind": "box",
    "padding": "sm",
    "x": 672,
    "y": 546,
    "h": 40,
    "w": 577
  }]
}
----

.An example of limiting the auth session to two minutes:
[source,.env]
----
AUTH_SESSION_LIFETIME=2m
----

| [#auth-sesion-auth_session_perm_lifetime]#<<auth-sesion-auth_session_perm_lifetime,AUTH_SESSION_PERM_LIFETIME>>#
|
The `AUTH_SESSION_PERM_LIFETIME` `.env` variable allows you to define how long the authentication session should be valid when the btn:[login and remember me] is used.

The authentication session is generated when the user provides their credentials to the *{PRODUCT_NAME} login page*.
The authentication session is independent of access tokens.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "auth-login.png",
    "alias": "auth-login-perm",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "annotations": [{
    "kind": "box",
    "padding": "sm",
    "x": 672,
    "y": 497,
    "h": 42,
    "w": 577
  }]
}
----

.An example of limiting the auth session to two minutes:
[source,.env]
----
AUTH_SESSION_PERM_LIFETIME=2m
----

|===

=== Log out inactive users after two minutes

If you wish to log out inactive users, you need to set all three of the `.env` variables mentioned above.

[source,.env]
----
AUTH_OAUTH2_ACCESS_TOKEN_LIFETIME=2m
AUTH_SESSION_LIFETIME=2m
AUTH_OAUTH2_REFRESH_TOKEN_LIFETIME=2m
----

[IMPORTANT]
====
When the user is considered inactive is determined by the user's browser.
Usually this is when they close the tab/window or when their computer enters rest mode.
====
