include::../pages/variables.adoc[]

= Security

One of the *main focus* when working with data in the enterprise environment is the *data integrity* and *security*.

{PRODUCT_NAME} takes this seriously and defines a *powerful permission system* that allows you to *control access to any resource*, being an application or a single module field.

== Users and Roles

{PRODUCT_NAME} uses *Role-based access control* (RBAC), meaning that we define access control *permissions to roles* (we specify *what roles* are allowed to access *what resources*).

When a *role is assigned to a user*, the user inherits the permissions defined on the roles.

[NOTE]
====
Every user is *automatically a member* of the "*Everyone*" role.
====

[IMPORTANT]
====
The *first registered user* is assigned an "*Administrator*" role.
====

.Each permission rule can be in one of the three states:
* *allow*: the role is *allowed to access* the specified resource.
* *deny*: the role is *not allowed to access* the specified resource.
* *inherit*: the role is *allowed to access* the specific resource when they are permitted to access *all resources of that type*.
The same applies to denying access.
For example:
`Role A` wishes to access `namespace A` with an *inherit* permission.
If `role A` can *access any namespace*, they are allowed access.

[TIP]
====
It's good practice to *limit your users* a much as possible to help *avoid security breaches*.
====

== Access control check flow

.The flow of determining if a role is allowed to perform an operation:
. Can this role perform the requested operation *for a specific resource*?
. Can this role perform the requested operation *for all resource of the given type*?
. Can anyone perform the requested operation *for a specific resource*?
. Can anyone perform the requested operation *for all resource of the given type*?

A *step is negative* when there is a role that is *explicitly denied* access.

A *step is positive* when there is at least one role that is *explicitly allowed* access.

If a *step is undetermined* (inherit), *the checking continues*.
If *all steps are undetermined*, the *system default* is used -- in most cases this is *deny*.

== Modular design

We suggest a *modular role design*, where we define *multiple roles* with a *smaller set* of permissions.
For example:

* **CRM admin**: only provides administration privileges for the CRM,
* **Messaging admin**: only provides administration privileges for the messaging,
* **System admin**: only provides administration privileges for the system.

Then we can easily "stick" these roles together when creating users.

[NOTE]
====
There are no limitations to how many roles we can have, but *don't go overboard*.
Having a new *role for each rule* will be a *nightmare for maintaining*.
====
