include::../pages/variables.adoc[]

= Security

One of the *main focus* when working with data in the enterprise environment is the *data integrity* and *security*.

{PRODUCT_NAME} takes this seriously and defines a *powerful permission system* that allows you to *control access to any resource*, being an application or a single module field.

== Roles

{PRODUCT_NAME} uses *Role-based access control* (RBAC), meaning that we can specify *what roles* are allowed to *access specific resources*.
When a user is *assigned a role*, they automatically *inherit the permissions* defined by the role.

[NOTE]
====
Every user is *automatically a member* of the "*Everyone*" role.
The role is *restricting*.
====

[IMPORTANT]
====
The *first registered user* (usually the one responsible for setting up a {PRODUCT_NAME} instance) is assigned an "*Administrator*" role.
====

.Each permission rule can be in one of the three states:
Allow::
    The role is allowed to access the specified resource.
Deny::
    The role is *not* allowed to access the specified resource.
Inherit::
    The role is allowed to access the specific resource, *if* they are permitted to access *all resources of that type*.
    The same applies to denying access.
    For example:
    `Role A` wishes to access `namespace A` with an *inherit* permission.
    If `role A` can *access any namespace*, they are allowed access.

[TIP]
====
It's good practice to *limit your users* a much as possible to *avoid security breaches*.
====

== Access control check flow

.The flow of determining if a role is allowed to perform an operation:
. Can this role perform the requested operation *for a specific resource*?
. Can this role perform the requested operation *for all resource of the given type*?
. Can anyone perform the requested operation *for a specific resource*?
. Can anyone perform the requested operation *for all resource of the given type*?

A *step is negative* when there is a role that is *explicitly denied* access.

A *step is positive* when there is at least one role that is *explicitly allowed* access.

If a *step is undetermined* (inherit), *the checking continues*.
If *all steps are undetermined*, the *system default* is used -- in most cases this is *deny*.

== Modular approach

We suggest a *modular role design*, where we define *multiple roles* with a *smaller set* of permissions.
For example:

* **CRM admin**: only provides administration privileges for the CRM,
* **Messaging admin**: only provides administration privileges for the messaging,
* **System admin**: only provides administration privileges for the system.

Then we can easily "stick" these roles together when creating users.

[NOTE]
====
There is *no limit* to the number of available roles or to the number of members a role can have.
====
