include::../pages/variables.adoc[]

= Security

One of the *main focus* when working with data in the enterprise environment is the *data integrity* and *security*.

{PRODUCT_NAME} takes this seriously and defines a *powerful permission system* that allows you to *control access to any resource*, being an application or a single module field.

== Users and Roles

{PRODUCT_NAME} uses *Role-based access control* (RBAC), meaning we define access control *permissions to roles* (we specify *what roles* are allowed to access *what resources*).
While users cannot have permissions set to them they can become members of one or more roles.
When a *users becomes members of a role*, they inherit permissions defined on all those roles.
See <<_access_control_check_flow>> for details on how permissions are checked on multiple roles.

[NOTE]
====
Every user is *automatically a member* of the "*Everyone*" role.
====

[IMPORTANT]
====
The *first registered user* in the system is automatically promoted to an "*Administrator*" role.
====

.Each permission rule can be in one of the two access states:
* *allow*: the role is *allowed to access* the specified resource.
* *deny*: the role is *not allowed to access* the specified resource.

[TIP]
====
It's good practice to *limit your users* a much as possible to help *avoid security breaches*.
====

== Access control check flow

When checking if user can perform a specific operation on a resource RBAC rules are checked in the following order:

. Can set of roles perform the requested operation *for a specific resource*?
. Can set of roles perform the requested operation *for all resource of the given type*?
. Can everyone perform the requested operation *for a specific resource*?
. Can everyone perform the requested operation *for all resource of the given type*?

For each step:

. If any of roles (or everyone) in the 1st or 2nd step has been explicitly denied access to operation RBAC short circuits the check and *disallows* the operation.
. If at least one of the roles (or everyone) has an explicit allow RBAC short circuits the check and *allows* the operation.
. Continue with the next step.

If check completes all four steps without an explicit allow or deny, the *system default* is used -- in most cases this is *deny*.

== Modular design

We suggest a *modular role design*, where we define *multiple roles* with a *smaller set* of permissions.
For example:

* **CRM admin**: only provides administration privileges for the CRM,
* **Messaging admin**: only provides administration privileges for the messaging,
* **System admin**: only provides administration privileges for the system.

Then we can easily "stick" these roles together when creating users.

[NOTE]
====
There are no limitations to how many roles we can have, but *don't go overboard*.
Having a new *role for each rule* will be a *nightmare for maintaining*.
====
