include::../../variables.adoc[]

[#docker-compose-demo-mysql-deployment]
= Local {PRODUCT_NAME} demo setup with MySQL database and automation server

The section covers configuration files that are only suitable for a demo on a local environment.
All services are on the same network, ports are bound to the host's network, etc.
We're using a minimum setup with corredor automation server, and MySQL database with persistent storage.

[IMPORTANT]
====
Restarting server gives you a fresh database, and you'll lose all your records, users and uploaded files.
====

[IMPORTANT]
====
This is *not* an optimal setup for a production environment.
====

== Configurations

.`docker-compose.yaml`
[source,yaml]
----
include::ROOT:example$docker-compose/demo-mysql/docker-compose.yaml[]
----

.`.env`
[source,yaml]
----
include::ROOT:example$docker-compose/demo-mysql/env-example.txt[]
----

Create an empty directory with the `docker-compose.yaml` and `.env` files.
You can adjust the provided example configuration files as you see fit.

== Run the services

[source,shell]
----
docker-compose up -d
----

Run this command in the same directory as your `docker-compose.yaml` file.
It will start all services based on the configurations provided in the configuration files.

You can check if everything is running correctly, by executing the `docker-compose ps` command.
The output should be similar to this one:

[source,shell]
----
include::ROOT:example$docker-compose/demo-mysql/output-ps.txt[]
----

You can see 2 services up and running. On a modern machine {PRODUCT_NAME} initializes and configures itself in under 10 seconds.

== Testing the demo

. Direct your browser to http://localhost:18080.
If you used other ports in your configurations, use those.
On your first visit, you should be redirected to the authentication page (`/auth`),
. create your account through the sign-up form.
. check the server version http://localhost:18080/version
. check the server's health http://localhost:18080/healthcheck
. check the API documentation http://localhost:18080/api/docs/

[NOTE]
====
The first user gets automatically promoted to an administrator.
You can add additional users by using the sign-up form or by adding them in the administration panel.
====

[NOTE]
====
With disabled email capabilities (unconfigured `SMTP_*` options) all email sending is offline and with it, email confirmation on sign-up.
====

include::ROOT:partial$deployment/troubleshooting.adoc[]

