include::../../variables.adoc[]

[#setup-production]
= Production setup with MySQL database

The section covers configuration files suitable for production environment.
Services are separated into two networks (internal and proxy) so that database and automation server can not be accessed from the public network.

In example volume is mounted on `server` services to ensure that files can be accessed from the host machine (if needed).


[IMPORTANT]
====
This setup depends on you running the xref:ROOT:dev-ops-guide/deployment/prod-proxy-nginx.adoc[NginX proxy service].
We recommend that you set it up beforehand.

If you prefer and use a different method to forward HTTP traffic to your Docker containers
====


== DNS

This demo uses a dedicated domain: *your-demo.example.tld*.
You need to configure your DNS by adding two hosts and point them to the IP address (A record) or the hostname (CNAME record) of the server you're using for running {PRODUCT_NAME}.

== Configurations

[NOTE]
====
Some of the configuration options in the docker-compose are in-lined for brevity and easier enabling/disabling (commenting-out).
====

[NOTE]
====
Some operating systems do not like files that start with a dot, so make sure `.env` file is properly named.
====

.`.env`
[source,dotenv]
----
include::ROOT:example$docker-compose/prod-pgsql/env-example.txt[]
----

.`docker-compose.yaml`
[source,yaml]
----
include::ROOT:example$docker-compose/prod-pgsql/docker-compose.yaml[]
----

Create an empty directory with the `.env` and `docker-compose.yaml` files.
You can adjust the provided example configuration files as you see fit.

[NOTE]
====
If needed, uncomment and make changes to variables in your `.env` file:

- `DOMAIN`
- `AUTH_JWT_SECRET`
- `SMTP_*`
====

If you uncommented local fs for data persinstance in the `db` and `server` containers, you need to prepare the directories.

.Create directories and change ownership so that containers can write to it:
[source,shell]
----
mkdir -p data/db data/server
chown 1001:1001 data/db
chown 4242:4242 data/server
----

== Run the services

[source,shell]
----
docker-compose up -d
----

Run this command in the same directory as your `docker-compose.yaml` file.
It will start all the services based on the configurations provided in the configuration files.

You can check if everything is running correctly by executing the `docker-compose ps` command.
The output should be similar to this one:

[source,shell]
----
include::ROOT:example$docker-compose/prod-pgsql/output-ps.txt[]
----

You can see four services up and running.

[IMPORTANT]
====
Your services should soon be available on the configured domains in a matter of minutes.
====

== Testing the deployment

. Direct your browser to `http://your-demo.example.tld`.
On your first visit, {PRODUCT_NAME} redirects you to the authentication page (`/auth`),
. create your account through the sign-up form.
. check the server version http://your-demo.example.tld/version
. check the server's health http://your-demo.example.tld/healthcheck
. check the API documentation http://your-demo.example.tld/api/docs/

[NOTE]
====
The first user gets automatically promoted to an administrator.
You can add additional users by using the sign-up form or by adding them in the administration panel.
====

include::ROOT:partial$deployment/troubleshooting.adoc[]
