=== Record list

Record list page blocks are designed to show the data from a specific module -- it's records.
These blocks also provide a way of accessing record pages.

Another important feature is, that record lists support client-side automation scripts.
This feature can be accessed in the "Automation" tab of the page block editor.

These automation scripts will be visible in the header of the page block, when any rows are selected.

==== Definition

Module::
    The module that will be used as a data source,
Hide add record button::
    Hides the "Add" button, hence disabling the ability to add new records,
Prefilter records::
    Enables us to apply additional filtering.
    Filters define a standard SQL syntax and also support dynamic value interpolation.
    Refer to <<admin-compose-page-block-recordlist-examples>> for examples,
Hide search box::
    Disables the search box,
Presort records::
    Enables us to apply additional sorting to the resulted records.
    Sorting defines a standard SQL syntax.
    Refer to <<admin-compose-page-block-recordlist-examples>> for examples,
Hide paging::
    Hides the record list paging section,
Allow records export::
    Enables the record export feature,
Enable record selection::
    Enables record selection by providing a selection checkbox next to each row,
Hide record reminder button::
    Hides the set reminder button,
Hide clone record button::
    Hides the clone record button,
Hide edit record button::
    Hides the edit record button,
Hide view record button::
    Hides the view record button.

[#admin-compose-page-block-recordlist-examples]
==== Examples

[TIP]
====
Record list prefiltering supports value interpolation that is relative to the viewed content, such as a record.
Available variables:

* **record**: current record (when available),
* **recordID**: current record's recordID (when available),
* **ownerID**: current record's owner (when available),
* **userID**: current user's userID.
====

Show only records created this year::
    `YEAR(created_at) = YEAR()`,

Show only records linked to the viewed record::
    `related_contact = ${recordID}`,

Show only active contacts::
    `is_active = '1'`,

Show lost opportunities::
    `status = 'closed/lost'`,

Sort by latest::
    `created_at DESC`

Sort by latest and opportunity stage::
    `created_at DESC, stage DESC`
