include::../variables.adoc[]

= Extensions
:doctype: book

These extensions are *developed and maintained* by the *core {PRODUCT_NAME} team*.
You can use these in *your instances* or *extensions*.

[NOTE]
====
*{PRODUCT_NAME} ships* with the xref:ROOT:extensions/crm/index.adoc[*CRM*], and the xref:ROOT:extensions/service-solution/index.adoc[*Service Solution*] extensions.
====

== CRM (built-in)

The CRM extension implements the xref:ROOT:extensions/crm/index.adoc[*CRM*] application.

== Service Solution (built-in)

The Service Solution extension implements the xref:ROOT:extensions/service-solution/index.adoc[*Service Solution*] application.

// @todo
// == PhoneBurner

// The xref:ROOT:extensions/phone-burner/index.adoc[*PhoneBurner extension*] implements the interaction with the https://www.phoneburner.com/[PhoneBurner] service.

== DocuSign

The xref:ROOT:extensions/docusign/index.adoc[*DocuSign extension*] implements the interaction with the https://www.docusign.com/[DocuSign] service.

== Pexels

The xref:ROOT:extensions/pexels/index.adoc[*Pexels extension*] implements an SDK to interact with the https://www.pexels.com/[Pexles] service.

[IMPORTANT]
====
This is not a {APP_NAME_COMPOSE} extension, but *an SDK*.
====

== Document renderer

The xref:ROOT:extensions/renderer/index.adoc[*renderer*] is an *experimental* document rendering engine.

You can use the https://www.npmjs.com/package/@cortezaproject/corteza-ext-renderer[Node.js module].

[IMPORTANT]
====
This is not a {APP_NAME_COMPOSE} extension, but *a library*.
====
