include::ROOT:partial$variables.adoc[]
include::ROOT:partial$icons.adoc[]

= Sub-workflows
:attachment-path: ../../../_attachments/automation/workflows/scaling/
:keywords: automation, modular, modularity
:description: Learn how to utilize sub-workflows to simplify your business logic

Sub-workflows enable you to define reusable pieces of logic that other workflows can utilize.
You can think of a sub-workflow as a function from classic programming languages.

[TIP]
====
On the list of available workflows, there is an additional sub-workflow inclusion filter option.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "automation/workflows/scaling/sub-wf-list.png",
    "alias": "sub-wf-list",
    "w": 1920,
    "h": 1080
  },
    "view": {
    "x": 411,
    "y": 25,
    "h": 386,
    "w": 1099
  },
  "annotations": [{
    "x": 476,
    "y": 139,
    "w": 263,
    "h": 26
  }]
}
----
====

[#exec-args]
== Execution Arguments

When calling sub-workflows, you can pass an arbitrary execution argument encoded as a `Vars` data type.

Click on the cog {ICON_WORKFLOW_COG} icon on the exec-workflow {ICON_WORKFLOW_EXEC_WORKFLOW} step and locate the "arguments" section.
Any value passed in the `scope` argument will be available in the execution context of the sub-workflow.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "automation/workflows/scaling/main-wf-args.png",
    "alias": "main-wf-args-in",
    "w": 1920,
    "h": 1080
  },
    "view": {
    "x": 1244,
    "y": 1,
    "w": 675,
    "h": 920
  },
  "focus": {
    "x": 1476,
    "y": 16,
    "w": 431,
    "h": 840
  },
  "annotations": [{
    "x": 1481,
    "y": 215,
    "w": 429,
    "h": 284
  }]
}
----

[#exec-results]
== Execution Results

After the sub-workflow is done with its execution, the calling workflow gains access to the sub-workflow's execution scope at the state it finished.

Click on the cog {ICON_WORKFLOW_COG} icon on the exec-workflow {ICON_WORKFLOW_EXEC_WORKFLOW} step and locate the "results" section.
Specify a list of values (and the variable name) you'd like to preserve from the sub-workflow.
The `result` field identifies the variable name in the sub-workflow's state, and the `target` identifies the variable name in the caller's state.

[TIP]
====
There is no limit to the number of values you can access from the sub-workflow's state.
====

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "automation/workflows/scaling/main-wf-args.png",
    "alias": "main-wf-args-out",
    "w": 1920,
    "h": 1080
  },
    "view": {
    "x": 1280,
    "y": 1,
    "w": 639,
    "h": 975
  },
  "focus": {
    "x": 1476,
    "y": 17,
    "w": 431,
    "h": 841
  },
  "annotations": [{
    "x": 1476,
    "y": 549,
    "w": 430,
    "h": 311
  }]
}
----

== Creating Sub-workflows

To create a sub-workflow, navigate to the {APP_NAME_WORKFLOW} web application and create a new workflow.
Tick the btn:[subworkflow] checkbox when configuring the workflow metadata.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "automation/workflows/scaling/sub-wf-create.png",
    "alias": "sub-wf-create",
    "w": 1920,
    "h": 1080
  },
  "view": {},
    "focus": {
    "x": 601,
    "y": 26,
    "w": 718,
    "h": 617
  },
  "annotations": [{
    "x": 614,
    "y": 520,
    "w": 217,
    "h": 35
  }]
}
----

Configure the rest of the workflow as you would with any other workflow.
Refer to xref:automation/workflows/index.adoc[main workflow documentation] for details.

[IMPORTANT]
====
Sub-workflows can not utilize triggers and can not be executed like regular workflows.
====

The following example defines a simple sub-workflow where we log the received value and then prepare a new value for the calling workflow.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "automation/workflows/scaling/sub-wf-example.png",
    "alias": "sub-wf-example",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 551,
    "y": 258,
    "w": 802,
    "h": 281
  },
  "annotations": []
}
----

The link:{attachment-path}sub-wf-example.json[source code] for the sub-workflow example.


== Using Sub-workflows

Sub-workflows are called from _regular_ workflows using the *exec-workflow* {ICON_WORKFLOW_EXEC_WORKFLOW} step.
The *exec-workflow* {ICON_WORKFLOW_EXEC_WORKFLOW} step requires you to specify what workflow you wish to execute (must be a sub-workflow), <<exec-args,execution arguments>>, and <<exec-results,execution results>>.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "automation/workflows/scaling/main-wf-example.png",
    "alias": "main-wf-example",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 104,
    "y": 243,
    "w": 1082,
    "h": 603
  },
  "annotations": [{
    "x": 423,
    "y": 523,
    "w": 263,
    "h": 276
  }]
}
----

The link:{attachment-path}main-wf-example.json[source code] for the workflow example.
