include::../../variables.adoc[]

= Permissions

In {PRODUCT_NAME} {APP_NAME_COMPOSE} you have full control over which role has access to what information.

You can set the following permissions to "Allow", "Inherit" or "Deny":

== All namespaces

In the main namespaces menu you can set the following permissions for all namespaces by clicking on the "lock" icon:

* Read any namespace
* Update any namespace
* Delete any namespace
* Manage any namespace: Allow access to namespace's admin pages
* Create modules under any namespace
* Create charts under any namespace
* Create pages under any namespace
* Create automation scripts under any namespace

== Single namespace

When you enter the edit page of a namespace (via the namespaces menu), you can click on the "lock" icon to set the permissions of a single namespace.
These settings overwrite the ones set in "All namespaces".

* Read namespace "(namespace name)"
* Update namespace "(namespace name)"
* Delete namespace "(namespace name)"
* Manage namespace "(namespace name)": Allow access to namespace's admin pages
* Create modules under namespace "(namespace name)"
* Create charts under namespace "(namespace name)"
* Create pages under namespace "(namespace name)"
* Create automation scripts under namespace "(namespace name)"

== Permissions inside a namespace

After setting permission to an entire namespace, you can further define permissions inside a namespace.
You can define it for:
* Modules
** Fields
* Pages
* Chart
* Automation rules.

To do so, you need to go to the admin area of the namespace.

=== Modules

==== All modules

On the top you can click on the "lock" icon to set permissions for all modules.
You can set the following permissions:

* Read any module
* Update any module
* Delete any module
* Create record of any module
* Read records of any module
* Update records of any module
* Delete records of any module
* Can manage automation triggers on any module

==== Single module

You can set permissions for a single module by clicking on the "lock" icon at the end of the module row.
Like this you can for example hide complete modules for certain roles.
You can define per role the following:

* Read module "(module name)"
* Update module "(module name)"
* Delete module "(module name)"
* Create record of module "(module name)"
* Read record of module "(module name)"
* Update record of module "(module name)"
* Delete record of module "(module name)"
* Can manage automation triggers on module "(module name)"

===== Fields inside a module

If you enter a module, you can define the following permissions per field.
Like this you can create a role that has access to a certain module, but don't not have access to see and/or edit certain fields.

* Read "(field name)" record fields
* Update "(field name)" record fields

=== Pages

==== All pages

On the top you can click on the "lock" icon to set permissions for all pages.
You can set the following permissions:
* Read any page
* Update any page
* Delete any page

==== Single page

Per page you can set the following permissions for a role:

* Read page "(page name)"
* Update page "(page name)"
* Delete page "(page name)"

=== Charts

==== All charts

On the top you can click on the "lock" icon to set permissions for all charts.
You can set the following permissions:
* Read any chart
* Update any chart
* Delete any chart

==== Single chart

Per chart you can set the following permissions for a role:

* Read chart "(chart name)"
* Update chart "(chart name)"
* Delete chart "(chart name)"

=== Automation

==== All scripts

On the top you can click on the "lock" icon to set permissions for all scripts.
You can set the following permissions:
* Read any script
* Update any script
* Delete any script

==== Single script

Per script you can set the following permissions for a role:

* Read script "(script name)"
* Update script "(script name)"
* Delete script "(script name)"
