include::ROOT:partial$variables.adoc[]

= {PRODUCT_NAME} {APP_NAME_DISCOVERY}
:keywords: discovery, search, record searcher, record searching, resource searcher, resource searching, data discovery
:description: Learn how to configure the system to support {PRODUCT_NAME} {APP_NAME_DISCOVERY}

{PRODUCT_NAME} {APP_NAME_DISCOVERY} provides a powerful search engine to interact with your data.
{PRODUCT_NAME} {APP_NAME_DISCOVERY} defines an intuitive interface to search and, in some cases, visualize the data such as geographical metadata.

Refer to the xref:integrator-guide:discovery/index.adoc[menu:Low-Code Platform Developer Guide[{PRODUCT_NAME} {APP_NAME_DISCOVERY}]] to learn how to configure and use {PRODUCT_NAME} {APP_NAME_DISCOVERY}.

== Configuring {PRODUCT_NAME} Server

To enable {PRODUCT_NAME} {APP_NAME_DISCOVERY}, access the Docker container and run the following commands:

[NOTE]
====
To access the Docker container, run the following command:

[source,bash]
----
docker-compose exec server bash
----
====

.Enable {PRODUCT_NAME} {APP_NAME_DISCOVERY} for {APP_NAME_COMPOSE} namespaces:
[source,bash]
----
corteza-server settings set discovery.compose-namespaces.enabled true
----

.Enable {PRODUCT_NAME} {APP_NAME_DISCOVERY} for {APP_NAME_COMPOSE} modules:
[source,bash]
----
corteza-server settings set discovery.compose-modules.enabled true
----

.Enable {PRODUCT_NAME} {APP_NAME_DISCOVERY} for {APP_NAME_COMPOSE} records:
[source,bash]
----
corteza-server settings set discovery.compose-records.enabled true
----

.Enable {PRODUCT_NAME} {APP_NAME_DISCOVERY} for users:
[source,bash]
----
corteza-server settings set discovery.system-users.enabled true
----

.Next, set the following `.env` variables for your {PRODUCT_NAME} server:
[source,env]
----
DISCOVERY_ENABLED=true
DISCOVERY_BASE_URL=your-discovery-server-base-url
# Optional variable for debugging
# DISCOVERY_DEBUG=true
----

[NOTE]
====
For an example of an online deployment, refer to xref:devops-guide:deploy-online/multi-discovery-pgsql.adoc[].
====
