include::ROOT:partial$variables.adoc[]

= {PRODUCT_NAME} {APP_NAME_DISCOVERY}
:keywords: discovery, search, record searcher, record searching, resource searcher, resource searching, data discovery
:description: Learn how to configure the system to support {PRODUCT_NAME} {APP_NAME_DISCOVERY}

{PRODUCT_NAME} {APP_NAME_DISCOVERY} provides a powerful search engine to interact with your data.
{PRODUCT_NAME} {APP_NAME_DISCOVERY} defines an intuitive interface to search and, in some cases, visualizes the data such as geographical metadata.

[NOTE]
====
Refer to xref:examples/deploy-online/multi-discovery-pgsql.adoc[] for an example.
====

Refer to the xref:integrator-guide:discovery/index.adoc[menu:Low-Code Platform Developer Guide[{PRODUCT_NAME} {APP_NAME_DISCOVERY}]] to learn how to configure and use {PRODUCT_NAME} {APP_NAME_DISCOVERY}.

== Configuring {PRODUCT_NAME} Server

To enable {PRODUCT_NAME} {APP_NAME_DISCOVERY}, access the Docker container and run the following commands:

.Enable {PRODUCT_NAME} {APP_NAME_DISCOVERY} for {APP_NAME_COMPOSE} namespaces:
[source,bash]
----
corteza-server settings set discovery.compose-namespaces.enabled true
----

.Enable {PRODUCT_NAME} {APP_NAME_DISCOVERY} for {APP_NAME_COMPOSE} modules:
[source,bash]
----
corteza-server settings set discovery.compose-modules.enabled true
----

.Enable {PRODUCT_NAME} {APP_NAME_DISCOVERY} for {APP_NAME_COMPOSE} records:
[source,bash]
----
corteza-server settings set discovery.compose-records.enabled true
----

.Enable {PRODUCT_NAME} {APP_NAME_DISCOVERY} for users:
[source,bash]
----
corteza-server settings set discovery.system-users.enabled true
----

.Next, set the following `.env` variables for your {PRODUCT_NAME} server:
[source,env]
----
DISCOVERY_ENABLED=true
DISCOVERY_BASE_URL=your-discovery-server-base-url
# Optional variable for debugging
# DISCOVERY_DEBUG=true
----

[NOTE]
====
For an example of an online deployment, refer to xref:examples/deploy-online/multi-discovery-pgsql.adoc[].
====

[NOTE]
====
To access the Docker container, run the following command:

[source,bash]
----
docker-compose exec server bash
----
====

== Configuring {PRODUCT_NAME} {APP_NAME_DISCOVERY} Server

Setup the following env variables:

[source,env]
```
ES_ADDRESS=your-open-search-url
ES_USERNAME=your-open-search-username
ES_PASSWORD=your-open-search-password
ES_SECURE=false
ES_INDEX_INTERVAL=60
CORTEZA_SERVER_BASE_URL=your-corteza-server-url
CORTEZA_SERVER_AUTH_URL=your-corteza-server-url/auth

DISCOVERY_INDEXER_ENABLED=true
DISCOVERY_SEARCHER_ENABLED=true
DISCOVERY_INDEXER_PRIVATE_INDEX_CLIENT_KEY=private-index-client-key
DISCOVERY_INDEXER_PRIVATE_INDEX_CLIENT_SECRET=private-index-client-secret
DISCOVERY_INDEXER_PROTECTED_INDEX_CLIENT_KEY=protected-index-client-key
DISCOVERY_INDEXER_PROTECTED_INDEX_CLIENT_SECRET=protected-index-client-secret
DISCOVERY_INDEXER_PUBLIC_INDEX_CLIENT_KEY=public-index-client-key
DISCOVERY_INDEXER_PUBLIC_INDEX_CLIENT_SECRET=public-index-client-secret

DISCOVERY_SEARCHER_CLIENT_KEY=your-searcher-client-key
DISCOVERY_SEARCHER_CLIENT_SECRET=your-searcher-client-secret
```
