include::ROOT:partial$variables.adoc[]

= {PRODUCT_NAME} Server

https://github.com/cortezaproject/corteza-server[{PRODUCT_NAME} server] is the back-end of the {PRODUCT_NAME} ecosystem.
The core logic is written in GO, using https://pkg.go.dev/github.com/go-chi/chi@v3.3.4+incompatible?utm_source=gopls[go-chi] for the routing.

Communication between the {PRODUCT_NAME} server and web applications is done using the REST API and web sockets.
Communication between back-end services ({PRODUCT_NAME} server and {APP_AUTOMATION}) is done using gRPC.

Non-binary data is handled by the store layer and stored inside a database -- currently MySQL and PostgreSQL.
We will add support for additional databases in the future.

Binary data is handled using minIO and stored either locally or on a supported cloud provider.

== Development setup

[CAUTION]
====
{PRODUCT_NAME} server runs on GO 1.16.
This guide assumes that your GO development environment is already set up on the correct version.
====

=== Fork the {PRODUCT_NAME} server

[CAUTION]
====
Core contributors should skip this part.
====

. go to the {GIT_REPO_LINK_PREFIX}-server repository
. click on the btn:[Fork] button in the top right corner and follow the instructions on the screen.

=== Clone the repository

.Using the CLI:
. open the CLI
. navigate to your working folder
. run the `git clone git@github.com:$YOUR_USERNAME_HERE/corteza-server.git` command

[TIP]
====
Refer to the https://github.com/cortezaproject/corteza-server[repository] if you wish to use an alternative method.
====

=== Configure the environment

.Inside your `corteza-server` directory:
. run `cp .env.example .env`
. open the `.env` file using VIM, Nano, or any other editor and modify the configuration as you see fit

=== Setup data storage

If your work requires persistent storage, make sure that you've set up a supported database engine.
You can run the database either locally or inside a Docker container.
Make sure to change the `DB_DSN=` `.env` variable.

If your work does not require persistent storage (you will work solely using tests), you can skip this step, and the testing framework will use the in-memory SQLite server.
Make sure to remove the `DB_DSN=` `.env` variable.

=== Setup SMTP

For local development, you can use MailHog to log the emails sent from the server.
Run the `make mailhog.up` command to start MailHog.
Alternatively, you can use an actual SMTP provider like Gmail or MailGun.
Make sure to change the `SMTP_*=` `.env` variables.

You can skip this part of your workflow does not require emails.
Make sure to remove the `SMTP_*=` `.env` variables.

=== Serve the web applications

{PRODUCT_NAME} server allows you to serve all of the {PRODUCT_NAME} web applications for cases where you need to quickly test something on a user interface.
Refer to the `corteza-server/webapp/README.adoc` file for details on how to set it up.

[CAUTION]
====
Make sure you've properly set the `HTTP_ADDR` `.env` variable to match your local environment variable, for example `HTTP_ADDR=localhost:80`.
The default `HTTP_ADDR` value is `HTTP_ADDR=localhost:80`.

Port 80 is not available on Windows.
====

[CAUTION]
====
The authentication server uses the `HTTP_ADDR` and `DOMAIN` variables when generating cookies.
The authentication flow will hang if it's not defined.

If the login screen _doesn't do anything_ when you try to login, check if the cookie has the correct domain set.
====

=== Run the server

Run the `make watch` command to start the server.
The server will automatically restart when changes to the code are detected.

[CAUTION]
====
The watcher can be a bit wonky at times.
Manually restart the server if the changes are not getting picked up.
====

=== Run the tests

.There are a handful of commands to run your tests:
* `test.integration` to run integration tests (test files inside `/tests`)
* `test.store` to run store tests (test files inside `/store/tests`)
* `test.all` to run all tests
* `test.unit` to run unit tests
* `test.pkg` to run test files for the `/pkg` directory

[TIP]
====
All commands, but the `test.all` command, accept another `.$WHAT_TO_TEST`.
For example, to only run Compose integration tests, you would run the `make test.integration.compose` command
====

[CAUTION]
====
*Integration testing gotcha:*

To prevent your tests from interacting with your development database, you can define an integration test specific `.env` file inside the `/tests` directory.
There, you can configure a different database or remove it to use the SQLite in-memory database.

*Store testing gotcha:*

The same test suite runs over all supported databases.
If you wish to test for a particular database, you must define the corresponding `DSN` in the root `.env` file.
Refer to the `/store/tests/main_test.go` for details.

See the <<container-db,setup containerized database>> section if you wish to run your test databases in a container.
====

:leveloffset: +1
include::ROOT:partial$setup/containerized-db.adoc[]
:leveloffset: -1

== Setup procedure

The initial procedure is located in the root `app` package which defines orchestration structures to configure, initialize, and start different parts of the system.

[NOTE]
====
CLI commands run boot procedures from the first (setup) to the level required by the command.
====

=== Setup procedure levels

[cols="1s,5a"]
|===
| [#setup-level-setup]#<<setup-level-setup,Setup>>#
|
Configures and initializes low-level components, structures required through the entire lifecycle.

.More notable components:
* *Logging*: root logging facility which supports human (formatting, colors) or machine (JSON) readable formats,
* *health check*: scheduler, email, and {APP_AUTOMATION} checks,
* *sentry*: sentry can be used as an error reporting service (critical routines may use their own error/panic reporting functionalities),
* *email*: an SMTP service for relaying sent email messages,
* *monitoring*: a primitive resource usage logging,
* *scheduler*: a facility that controls interval automation execution,
* *{APP_AUTOMATION}*: a server client for the {APP_AUTOMATION} server.

[NOTE]
====
.When SMTP is disabled (no SMTP host is configured):
* User signup no longer requires email verification,
* password reset is disabled,
* email sending via automation is disabled.
====

| [#setup-level-db]#<<setup-level-db,Store initialization>>#
|
Establishes a connection to the configured database.
The post connection procedures run database migrations to conform the schema to the current version.

| [#setup-level-services]#<<setup-level-services,Service initialization>>#
|
Initializes all of the services as well as RBAC, resource translations, and (if enabled) federation.

| [#setup-level-provision]#<<setup-level-provision,Provision>>#
|
The provision step assures that the initial resources (users, roles, namespaces, ...) are imported from the provision files.

| [#setup-level-activate]#<<setup-level-activate,Activate>>#
|
All of the previously initialized and configured services are started/activated including their watchers.

|===
