include::../variables.adoc[]

= Administrator Guide
:doctype: book

The *administrator guide* will help you maintain the security-related aspects of your applications.

[NOTE]
====
The integrator guide focuses on the *security-related aspects*, like defining roles, setting permissions, and adding users.
If you are interested about developing applications, refer to the xref:ROOT:/integrator-guide/index.adoc[integrator guide].
====

== Overview the security system

xref:ROOT:administrator-guide/security.adoc[*Reviewing the security system*] will provide you with an overview of our *access control* systems.
It will help you define a more *secure application*; better define the *role hierarchy* and *their permission*.

== The administrator panel

The xref:ROOT:administrator-guide/admin-panel/index.adoc[*administrator panel*] provides a quick *overview of the system*, xref:ROOT:administrator-guide/admin-panel/index.adoc#admin-panel-user[*user*] and xref:ROOT:administrator-guide/admin-panel/index.adoc#admin-panel-system-roles[*role*] management, permission and settings overview.

== System administration

See our guides for xref:ROOT:administrator-guide/compose/index.adoc[*{PRODUCT_NAME} {APP_NAME_COMPOSE}*] and xref:ROOT:administrator-guide/messaging/index.adoc[*{PRODUCT_NAME} {APP_NAME_MESSAGING}*] administration.
