include::../variables.adoc[]

= Administrator Guide
:doctype: book

The *administrator guide* will help you perform your administrator role.
We cover everything from *creating and configuring users* to *defining permissions*

[NOTE]
====
If you are interested about *application development*, refer to the xref:ROOT:/integrator-guide/index.adoc[integrator guide].
====

== Overview the security system

xref:ROOT:administrator-guide/security.adoc[*Reviewing the security system*] will provide you with an overview of our *access control* system.
It will help with developing *secure applications* and defining *role hierarchies*.

== The administrator panel

The xref:ROOT:administrator-guide/admin-panel/index.adoc[*administrator panel*] provides a quick *overview of the system*, xref:ROOT:administrator-guide/admin-panel/index.adoc#admin-panel-user[*user*] and xref:ROOT:administrator-guide/admin-panel/index.adoc#admin-panel-role[*role*] management; *permission and settings* overview.

== System administration

See our guides for xref:ROOT:administrator-guide/compose/index.adoc[*{PRODUCT_NAME} {APP_NAME_COMPOSE}*] and xref:ROOT:administrator-guide/messaging/index.adoc[*{PRODUCT_NAME} {APP_NAME_MESSAGING}*] administration.

== {PRODUCT_NAME} {APP_NAME_FEDERATION}

xref:ROOT:administrator-guide/federation/index.adoc[*{PRODUCT_NAME} {APP_NAME_FEDERATION}*] enables different *{PRODUCT_NAME} instances* to establish a *federated network* to *freely and securely* exchange information.
