= Working with record values
:attachment-path: ../../../_attachments/workflow/examples/

The section outlines some tips and tricks you can use when working with records.

== Removing the value

To remove some record value, use an expression step to set the value in question to an empty `Any`.

.The screenshot outlines a basic example of removing record values.
[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "workflow/example-record-values/remove-value.png",
    "alias": "example-record-values_remove-value",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 740,
    "y": 0,
    "w": 1180,
    "h": 482
  },
  "annotations": [{
    "kind": "box-note",
    "padding": "xs",
    "x": 1420,
    "y": 340,
    "w": 490,
    "h": 42
  }]
}
----

You can find the source code for the workflow link:{attachment-path}remove-value.json[here].

== Handling missing values

To use the default value in case the record value does not exist, you need to use the `??` operator.

To exemplify, using `a ?? b` will return `a` if it exists or `b` if it does not.

[NOTE]
====
The below example uses a variable as the default value.
You can use a constant such as `"something string"` or `42`.
====

.The screenshot outlines a basic example of using default values.
[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "workflow/example-record-values/missing-value-default.png",
    "alias": "example-record-values_missing-value-default",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 740,
    "y": 0,
    "w": 1180,
    "h": 1003
  },
  "annotations": [{
    "kind": "box-note",
    "padding": "xs",
    "x": 1420,
    "y": 340,
    "w": 490,
    "h": 576
  }]
}
----

You can find the source code for the workflow link:{attachment-path}missing-value-default.json[here].
