= Working with Records
:attachment-path: ../../../_attachments/automation/workflows/examples/record/
:page-noindex: true

The section outlines some tips and tricks you can use when working with records.

== Checking for existence

In case where you wish to perform some task depending on the existence of records, you can use either of the following approaches.

Both approaches are valid and there is no benefit between using one or the other.
Decide based on your preferences/context.

=== Approach A

When searching for records, tick the `incTotal` option and assign the `total` result value to a variable.

Inside the gateway, check if the `total` value is greater then `0`.

.The screenshot outlines a basic example of checking for existence.
[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "automation/workflows/examples/record/existence-a.png",
    "alias": "automation-workflows-examples-record-existence-a",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 325,
    "y": 97,
    "w": 718,
    "h": 600
  },
  "annotations": []
}
----

You can find the source code for the workflow link:{attachment-path}existence-a.json[here].

=== Approach B

Inside the gateway, check if the `count(items)` value is greater then `0`.

.The screenshot outlines a basic example of checking for existence.
[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "automation/workflows/examples/record/existence-b.png",
    "alias": "automation-workflows-examples-record-existence-b",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 325,
    "y": 97,
    "w": 718,
    "h": 600
  },
  "annotations": []
}
----

You can find the source code for the workflow link:{attachment-path}existence-b.json[here].

== Create or update

When creating the record you need to call the `compose record create` function, and when updating the record, you need to call the `compose record update` function.

[NOTE]
====
Only the highlighted portion performs the create/update check; the rest is boilerplate to get it to the desired state.
====

If you need to call one or the other on-the-fyly, you can use the following approach.
You can use the `record.recordID != "0"` to determine if the record needs to be updated -- the default `recordID` value is `"0"`.

.The screenshot outlines a basic example of checking for existence.
[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "automation/workflows/examples/record/create-update.png",
    "alias": "automation-workflows-examples-record-create-update",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 413,
    "y": 67,
    "w": 837,
    "h": 997
  },
  "annotations": [{
    "kind": "box-note",
    "x": 490,
    "y": 824,
    "w": 680,
    "h": 201
  }]
}
----

You can find the source code for the workflow link:{attachment-path}create-update.json[here].

== Removing the value

To remove some record value, use an expression step to set the value in question to an empty `Any`.

.The screenshot outlines a basic example of removing record values.
[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "automation/workflows/examples/record/remove-value.png",
    "alias": "automation-workflows-examples-record-remove-value",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 740,
    "y": 0,
    "w": 1180,
    "h": 482
  },
  "annotations": [{
    "kind": "box-note",
    "padding": "xs",
    "x": 1420,
    "y": 340,
    "w": 490,
    "h": 42
  }]
}
----

You can find the source code for the workflow link:{attachment-path}remove-value.json[here].

== Handling missing values

To use the default value in case the record value does not exist, you need to use the `??` operator.

To exemplify, using `a ?? b` will return `a` if it exists or `b` if it does not.

[NOTE]
====
The below example uses a variable as the default value.
You can use a constant such as `"something string"` or `42`.
====

.The screenshot outlines a basic example of using default values.
[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "automation/workflows/examples/record/missing-value-default.png",
    "alias": "automation-workflows-examples-record-missing-value-default",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 740,
    "y": 0,
    "w": 1180,
    "h": 1003
  },
  "annotations": [{
    "kind": "box-note",
    "padding": "xs",
    "x": 1420,
    "y": 340,
    "w": 490,
    "h": 576
  }]
}
----

You can find the source code for the workflow link:{attachment-path}missing-value-default.json[here].
