include::../../../variables.adoc[]

= Administration

{PRODUCT_NAME} {APP_NAME_COMPOSE} provides a specialized user interface tailored to administrators.
The interface allows you to manage modules, pages, charts and much more.

To enter the admin area of a namespace, you first need to open the namespace inside {PRODUCT_NAME} {APP_NAME_COMPOSE}.
Once inside, you'll see an "Admin panel" link on the top-right corner.
Click on it to enter the namespace's admin area.

[NOTE]
====
If you cannot see the "Admin panel" link, you might not have the permissions you need.
In this case, contact the administrator of your {PRODUCT_NAME} platform.
====

In the admin area there are three menu items:

* *Modules*: Manage modules associated with the namespace; see <<admin-compose-modules>>,
* *Pages*: Manage pages associated with the namespace; see <<admin-compose-pages>>,
* *Charts*: Manage charts associated with the namespace; see <<admin-compose-charts>>.

The Public pages link takes you back to your namespace.

:leveloffset: +1

include::modules.adoc[]

include::pages/index.adoc[]

include::charts.adoc[]

:leveloffset: -1
