include::ROOT:partial$variables.adoc[]

= Authentication
:page-aliases: administrator-guide:authentication/index.adoc
:keywords: authentication, security, login, configure login
:description: Learn how to configure the {PRODUCT_NAME} authentication flow

{PRODUCT_NAME} implements the OAuth2 authentication protocol, where it can act both as a OAuth2 server and as an OAuth2 client, which allows both internal and external authentications.

Basic authentication parameters are configured on the {PRODUCT_NAME} {APP_NAME_ADMIN} web application under menu:system[settings] in the "authentication" section.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "authentication/config-basic.png",
    "alias": "authentication-config-basic",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 321,
    "y": 0,
    "w": 1599,
    "h": 1080
  },
  "focus": {
    "x": 584,
    "y": 104,
    "w": 1070,
    "h": 239
  },
  "annotations": []
}
----

== Defining Password Constraints

{PRODUCT_NAME} allows you to define custom password constraints.
That enables you to better conform to your security model.

Password constraints are configured on the {PRODUCT_NAME} {APP_NAME_ADMIN} web application under menu:system[settings] in the "Password Constraints" section.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "authentication/password-constraints.png",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 321,
    "y": 0,
    "w": 1599,
    "h": 1080
  },
  "focus": {
    "x": 585,
    "y": 375,
    "w": 1070,
    "h": 234
  },
  "annotations": []
}
----

[cols="2s,5a"]
|===
| [#auth-password-constraint-len]#<<auth-password-constraint-len,Minimum length>>#
|
The minimum length parameter allows you to restrict your users from using short, insecure passwords.
You can not set the minimum length below 8 characters.

The maximum password length is not configurable and is set to 256 characters.

| [#auth-password-constraint-numbers]#<<auth-password-constraint-numbers,Minimum number of numbers>>#
|
The minimum number of numbers allows you to require your users to use numerical characters in their passwords.
The requirement is disabled when the value is left at 0.

| [#auth-password-constraint-symbols]#<<auth-password-constraint-symbols,Minimum number of special characters>>#
|
The minimum number of special characters allows you to require your users to use special characters in their passwords.
The requirement is disabled when the value is left at 0.

|===

[CAUTION]
====
The `AUTH_PASSWORD_SECURITY` `.env` variable allows you to disable password requirements checking by setting it to `false`.
This is handy for local development where you may not wish to handle complex password constraints.

The option should be *disabled* for any production deployment.
If the password security is disabled, a warning message is displayed in the UI.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "authentication/password-security-disabled.png",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 321,
    "y": 0,
    "w": 1599,
    "h": 1080
  },
  "focus": {
    "x": 585,
    "y": 375,
    "w": 1070,
    "h": 234
  },
  "annotations": [{
    "kind": "box",
    "x": 585,
    "y": 401,
    "w": 1071,
    "h": 48
  }]
}
----
====

== Auth Client

An *auth client* offers a high-level access control over the use of {PRODUCT_NAME} API and its resources.
An auth client is what applications use when their users attempt to authenticate.

[TIP]
====
You can use {PRODUCT_NAME} to authenticate third-party applications that support OAuth2/OIDC.
====

Auth clients can be defined in the {PRODUCT_NAME} {APP_NAME_ADMIN} panel, under the menu:system[auth clients] section.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "authentication/auth-client-list.png",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 320,
    "y": 0,
    "w": 1600,
    "h": 480
  },
  "annotations": []
}
----

.From there you can:
* list the auth clients created inside your {PRODUCT_NAME} instance,
* create a new auth client by clicking on the btn:[new] button,
* edit an existing auth client by clicking on the btn:[edit] icon next to the auth client,
* manage global auth client permissions by clicking on the btn:[permissions] button.

=== Base Auth Client Configuration

Base configuration parameters allow you to both identify the auth client, and specify the validity and the scope that the auth client provides.

[TIP]
====
The trusted checkbox removes the final confirmation step when the user authenticates.
====

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "authentication/auth-client-create.png",
    "alias": "authentication-auth-client-create-base",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 320,
    "y": 0,
    "h": 1080,
    "w": 1600
  },
  "annotations": [{
    "kind": "box",
    "x": 585,
    "y": 163,
    "w": 1070,
    "h": 90
  }, {
    "kind": "box",
    "x": 585,
    "y": 383,
    "w": 1070,
    "h": 287
  }]
}
----

[#grant-types]
=== Grant Types

{PRODUCT_NAME} supports two OAuth2 grant types: *authorization code* and *client credentials*.

.Authentication grant types:
[cols="1s,5a"]
|===
| [#auth-client-grant-authorization-code]#<<auth-client-grant-authorization-code,Authorization code>>#
|
The *authorization code* grant type is used to authenticate users with the classic OAuth2 flow.

To enable this grant type, select the "will be used to authenticate users (grant type = authorization_code)" option.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "authentication/auth-client-authorization-code.png",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 321,
    "y": 0,
    "w": 1599,
    "h": 1080
  },
  "focus": {
    "x": 855,
    "y": 406,
    "h": 40,
    "w": 548
  },
  "annotations": [{
    "kind": "box",
    "padding": "sm",
    "x": 855,
    "y": 407,
    "w": 526,
    "h": 19
  }]
}
----

| [#auth-client-grant-client-credentials]#<<auth-client-grant-client-credentials,Client credentials>>#
|
The *client credentials* grant type is the simplified authentication flow.
It is normally used to authenticate systems such as external services or applications.

[IMPORTANT]
====
Client credentials grant type requires you to populate the "impersonate user" option.
The impersonated user will be used to create the security context of the JWT token.
====

To enable this grant type, select the "will be used to authenticate machines (grant type = client_credentials)" option.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "authentication/auth-client-client-credentials.png",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 321,
    "y": 0,
    "w": 1599,
    "h": 1080
  },
  "focus": {
    "x": 855,
    "y": 406,
    "h": 40,
    "w": 548
  },
  "annotations": [{
    "kind": "box",
    "padding": "sm",
    "x": 855,
    "y": 429,
    "w": 547,
    "h": 19
  }]
}
----

|===

[#auth-scope]
=== Authorization Scope

The scope is defined as a series of role memberships that are either *permitted*, *prohibited*, or *forced* on the user when using a specific {PRODUCT_NAME} auth server.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "authentication/auth-client-create.png",
    "alias": "authentication-auth-client-create-scope",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 320,
    "y": 0,
    "h": 1080,
    "w": 1600
  },
  "focus": {
    "x": 585,
    "y": 690,
    "w": 1070,
    "h": 204
  },
  "annotations": []
}
----


[cols="1s,5a"]
|===
| [#auth-scope-permitted]#<<auth-scope-permitted,Permitted roles>>#
| *Permitted roles* define what roles the user is *allowed to have* when authenticating with this client.

| [#auth-scope-prohibited]#<<auth-scope-prohibited,Prohibited roles>>#
| *Prohibited roles* define what roles the user is *not allowed to have* when authenticating with this client.

| [#auth-scope-forced]#<<auth-scope-forced,Forced roles>>#
| *Forced roles* define what roles the user *will have* have when authenticating with this client.
If the user does not have a forced role, a role will be automatically assigned.
|===

== Limit Access

By default, any user can use any auth client.
To limit access to specific auth clients, navigate to the auth client and set the "authorize client" access control rule.

If a specific role does not have the authorize client RBAC rule, the underlying users can not authenticate with the given auth client.

[NOTE]
====
*DevNote* how can I expand on this...
====
