include::ROOT:partial$variables.adoc[]

= Multi-factor Authentication
:page-aliases: administrator-guide:authentication/mfa.adoc
:keywords: authentication, mfa, multi factor authentication
:description: Learn how to configure multi factor authentication

Multi-factor authentication (MFA) provides an extra layer of security for your users.
{PRODUCT_NAME} provides multi-factor authentication via email or via mobile authenticator application.

== Configure MFA

Multi-factor authentication can be enabled in the {PRODUCT_NAME} {APP_NAME_ADMIN} web application under menu:system[authentication, multi-factor authentication].

You can configure *OTP via email* by enabling the allow of the force users to use one-time-password over email option and optionally change the default end time for the OTP.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "authentication/mfa/mfa-settings-admin-configure.png",
    "alias": "authentication-mfa-mfa-settings-admin-configure-email",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "focus": {
    "x": 424,
    "y": 376,
    "w": 1070,
    "h": 487
  },
  "annotations": [{
    "kind": "box",
    "x": 605,
    "y": 406,
    "w": 387,
    "h": 54
  }]
}
----

You can configure *OTP via authenticator app* by enabling the use time based one-time-password (using mobile application) option and change the default issuer displayed in the authenticator app.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "authentication/mfa/mfa-settings-admin-configure.png",
    "alias": "authentication-mfa-mfa-settings-admin-configure-mobile",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "focus": {
    "x": 424,
    "y": 376,
    "w": 1070,
    "h": 487
  },
  "annotations": [{
    "kind": "box",
    "x": 605,
    "y": 556,
    "w": 590,
    "h": 54
  }]
}
----

Next, to enable OTP for a specific user, navigate to menu:system[users] and click on the edit icon next to the user you wish to enable it for.
Navigate to the "multi-factor authentication" section and click on the btn:[enable] button.

.The screenshot outlines the user interface used to enable MFA authentication for a specific user.
[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "authentication/mfa/mfa-enable.png",
    "alias": "authentication-mfa-mfa-enable",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "focus": {
    "x": 426,
    "y": 829,
    "w": 1070,
    "h": 150
  },
  "annotations": [{
    "kind": "box",
    "x": 1414,
    "y": 888,
    "w": 80,
    "h": 30
  }]
}
----

From that point on, when a user attempts to login, they will receive an email with the OTP, which they need to provide before the login is finished.

== Use MFA over email

To use MFA over email, navigate to your profile and click on the "security" tab.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "authentication/mfa/mfa-settings-auth.png",
    "alias": "authentication-mfa-mfa-settings-auth-email",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "annotations": []
}
----

Click on the btn:[configure] button in the "additional security with one-time-password over email" section.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "authentication/mfa/mfa-settings-auth-email-enabled.png",
    "alias": "authentication-mfa-mfa-settings-auth-email-enabled",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "annotations": []
}
----

The next time you login, you will need to confirm the login by entering the OTP sent to your email.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "authentication/mfa/mfa-login-confirm.png",
    "alias": "authentication-mfa-mfa-login-confirm",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "annotations": []
}
----

== Use MFA over the authenticator app

To use MFA over email, navigate to your profile and click on the "security" tab.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "authentication/mfa/mfa-settings-auth.png",
    "alias": "authentication-mfa-mfa-settings-auth-app",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "annotations": []
}
----

Click on the btn:[configure] button in the "additional security with mobile app (time-based one-time-password)" section.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "authentication/mfa/mfa-settings-auth-authenticator-add.png",
    "alias": "authentication-mfa-mfa-settings-auth-authenticator-add",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "annotations": []
}
----

Open up your authenticator app and configure {PRODUCT_NAME} by either scanning the QR code or by manually providing the parameters.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "authentication/mfa/mfa-settings-auth-authenticator-enabled.png",
    "alias": "authentication-mfa-mfa-settings-auth-authenticator-enabled",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "annotations": []
}
----

The next time you login, you will need to confirm the login by entering the OTP generated by your authenticator app.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "authentication/mfa/mfa-login-confirm.png",
    "alias": "authentication-mfa-mfa-login-confirm",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "annotations": []
}
----
