include::ROOT:partial$variables.adoc[]

= Multi-factor Authentication
:page-aliases: 2024.9@administrator-guide:authentication/mfa.adoc
:keywords: authentication, mfa, multi factor authentication
:description: Learn how to configure multi factor authentication

Multi-factor authentication (MFA) provides an extra layer of security for your users.
{PRODUCT_NAME} provides multi-factor authentication via email or via mobile authenticator application.

== Configure MFA

Multi-factor authentication can be enabled in the {PRODUCT_NAME} {APP_NAME_ADMIN} web application under menu:system[authentication, multi-factor authentication].
You can either *allow* or *force* users to receive their OTP (one-time-password) either via their *email* or their *authenticator application*.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "authentication/mfa/mfa-settings-admin-configure.png",
    "alias": "authentication-mfa-mfa-settings-admin-configure-email",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "focus": {
    "x": 572,
    "y": 330,
    "w": 1080,
    "h": 389
  },
  "annotations": [{
    "kind": "box",
    "x": 575,
    "y": 333,
    "w": 1029,
    "h": 46
  }, {
    "kind": "box",
    "x": 575,
    "y": 535,
    "w": 1029,
    "h": 70
  }]
}
----

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "authentication/mfa/mfa-settings-admin-configure.png",
    "alias": "authentication-mfa-mfa-settings-admin-configure-mobile",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "focus": {
    "x": 575,
    "y": 537,
    "w": 1076,
    "h": 340
  },
  "annotations": [{
    "kind": "box",
    "x": 575,
    "y": 535,
    "w": 1029,
    "h": 70
  }]
}
----

Next, to enable OTP for a specific user, navigate to menu:system[users] and click on the "edit" icon next to the user you wish to enable it for.
Navigate to the "multi-factor authentication" section and click on the btn:[enable] button.

.The screenshot outlines the user interface used to enable MFA authentication for a specific user.
[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "authentication/mfa/mfa-enable.png",
    "alias": "authentication-mfa-mfa-enable",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "focus": {
    "x": 575,
    "y": 755,
    "w": 1076,
    "h": 135
  },
  "annotations": [{
    "kind": "box",
    "x": 1570,
    "y": 811,
    "w": 82,
    "h": 32
  }]
}
----

From that point on, when a user attempts to login, they will receive an email with the OTP, which they need to provide before the login is finished.

== Use MFA Over Email

To use MFA over email, navigate to your profile and click on the "security" tab.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "authentication/mfa/mfa-settings-auth.png",
    "alias": "authentication-mfa-mfa-settings-auth-email",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "annotations": []
}
----

Click on the btn:[configure] button in the "additional security with one-time-password over email" section.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "authentication/mfa/mfa-settings-auth-email-enabled.png",
    "alias": "authentication-mfa-mfa-settings-auth-email-enabled",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "annotations": []
}
----

The next time you login, you will need to confirm the login by entering the OTP sent to your email.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "authentication/mfa/mfa-login-confirm.png",
    "alias": "authentication-mfa-mfa-login-confirm",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "annotations": []
}
----

== Use MFA Over the Authenticator App

To use MFA over email, navigate to your profile and click on the "security" tab.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "authentication/mfa/mfa-settings-auth.png",
    "alias": "authentication-mfa-mfa-settings-auth-app",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "annotations": []
}
----

Click on the btn:[configure] button in the "additional security with mobile app (time-based one-time-password)" section.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "authentication/mfa/mfa-settings-auth-authenticator-add.png",
    "alias": "authentication-mfa-mfa-settings-auth-authenticator-add",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "annotations": []
}
----

Open up your authenticator app and configure {PRODUCT_NAME} by either scanning the QR code provided or by manually providing the parameters provided on the authentication screen.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "authentication/mfa/mfa-settings-auth-authenticator-enabled.png",
    "alias": "authentication-mfa-mfa-settings-auth-authenticator-enabled",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "annotations": []
}
----

The next time you login, you will need to confirm the login by entering the OTP generated by your authenticator app.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "authentication/mfa/mfa-login-confirm.png",
    "alias": "authentication-mfa-mfa-login-confirm",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "annotations": []
}
----
