include::../../variables.adoc[]

= Minimal support for SCIM v2

Protocol

{PRODUCT_NAME} supports SCIM protocol to enable and identity provisioning and simplify identity management.

Lib used: https://github.com/imulab/go-scim

== Will not implement:

. https://tools.ietf.org/html/rfc7644#section-2.2[RFC7644 2.2.Anonymous Requests]
. https://tools.ietf.org/html/rfc7644#section-3.4[RFC7644 3.4. Retrieving Resources]
. https://tools.ietf.org/html/rfc7644#section-3.11[RFC7644 3.11. "/Me" Authenticated Subject Alias]
. https://tools.ietf.org/html/rfc7644#section-3.4.3[RFC7644 3.4.3. Querying Resources Using HTTP POST]

== Configuration

|===
|SCIM_ENABLED|bool|`false`
|SCIM_BASE_URL|string|`/scim`
|SCIM_SECRET|string|
|===



== Authentication

Provisioning system must send `Authentication` header with `Bearer <SECRET>` value.
Authentication and secret checking is disabled in development mode.

== Resource mapping

=== User

List of SCIM attributes and how they map to/from {PRODUCT_NAME} user fields.

userName::
  Mapped to `username` field.

name.formatted::
  Mapped to `name` field.

nickName::
    If compatible with handle format (`^[A-Za-z][0-9A-Za-z_\-.]*[A-Za-z0-9]$`), value is used to populate user's `handle` property.
    Incompatible values are silently ignored.

password::
    Password will update internal credentials if it does not match currently active one.
    Expecting cleartext passwords as per https://tools.ietf.org/html/rfc7643#section-9.2[RFC7643 Section 9.2].

emails::
    Due to current limitation of {PRODUCT_NAME}, only one email can be stored.
    Primary email is used. If no emails are marked as primary, first entry is used.

externalId::
    Arbitrary string value that can represent provisioner's user ID can be stored alongside {PRODUCT_NAME} resource.
    When value is stored with `SCIM_externalId` key as label.

groups #TBD#::
    Set of objects with `value` key and string value: `[{"value":"...."}, ...]`.
    Value should contain provisioner group identifier (passed as `externalId`) when creating group.
    Absence of `groups` attribute indicates no update.
    Presence of the attribute forces removal of all memberships that were not provided in the list and joining user to all listed ones.
    If provided `externalId` is not found on any of the provisioned groups, that group is skipped.

=== Provisioning groups

List of SCIM attributes and how they map to/from {PRODUCT_NAME} role fields.

displayName::
    Mapped to `name` field.
    If compatible with handle format (`^[A-Za-z][0-9A-Za-z_\-.]*[A-Za-z0-9]$`), value is used to populate roles's `handle` property.
    Otherwise it sets handle to empty string

externalId::
    Arbitrary string value that can represent provisioner's group ID can be stored alongside {PRODUCT_NAME} resource.
    When value is stored with `SCIM_externalId` key as label.

=== Provisioning role (group) membership

#TODO# When group with `members` or user with `groups` is updated, group membership is changed accordingly.


== Creating

=== User

Resource existence is checked in the following order:

. `externalId` value (if provided)
. `email`

If resource is found, system updates it instead of creating new one.

=== Group

Resource existence is checked in the following order:

. `externalId` value (if provided)
. `name`

If resource is found, system updates it instead of creating new one.


== Updating #TBD#

{PRODUCT_NAME} expects its internal resource IDs to be used when constructing resource update endpoints.
