include::ROOT:partial$variables.adoc[]

= Index Only Specified Namespace
:page-noindex: true

xref:discovery/index.adoc#data-visibility[Data visibility] is controlled with the standard access control facility.
The {APP_NAME_DISCOVERY} indexes everything it currently has access to.

To control data visibility, configure access control rules for the role assigned to the xref:discovery/index.adoc#indexer-user[{APP_NAME_DISCOVERY} indexer user].

In this example we configure {PRODUCT_NAME} {APP_NAME_DISCOVERY} to only index records from the Discovery namespace.

Navigate to the Namespace Management page and click on the btn:[Permissions] button to open up global namespace access control rules.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "discovery/examples/limit-namespace/namespace-manage.png",
    "alias": "discovery-examples-limit-namespace-namespace-manage",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "annotations": [{
    "kind": "box-note",
    "x": 830,
    "y": 72,
    "w": 150,
    "h": 43
  }]
}
----

Select the *Authenticated* role and set the `Read any namespace` rule to `Deny`.
Alternatively, you may set the same rule to Deny for the {APP_NAME_DISCOVERY} indexer role.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "discovery/examples/limit-namespace/namespace-rbac-global.png",
    "alias": "discovery-examples-limit-namespace-namespace-rbac-global",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 365,
    "y": 21,
    "w": 1158,
    "h": 1245
  },
  "annotations": [{
    "kind": "box-note",
    "x": 395,
    "y": 149,
    "w": 366,
    "h": 178
  }]
}
----

Next, click on the btn:[Edit] button for the namespace you wish to allow access to, and click on the btn:[Permissions] button to open up access control rules for the given namespace.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "discovery/examples/limit-namespace/namespace-edit.png",
    "alias": "discovery-examples-limit-namespace-namespace-edit",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 378,
    "y": 62,
    "w": 1186,
    "h": 755
  },
  "annotations": [{
    "kind": "box-note",
    "x": 507,
    "y": 83,
    "h": 163,
    "w": 64
  }]
}
----

Select the *Discoverer* role (the role assigned to the {APP_NAME_DISCOVERY} indexer user) and set the `Read namespace` rule to `Allow`.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "discovery/examples/limit-namespace/namespace-rbac.png",
    "alias": "discovery-examples-limit-namespace-namespace-rbac",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 365,
    "y": 21,
    "w": 1158,
    "h": 1245
  },
  "annotations": [{
    "kind": "box-note",
    "x": 395,
    "y": 149,
    "w": 366,
    "h": 178
  }]
}
----

After the {APP_NAME_DISCOVERY} indexer re-indexes your instance, the search results become limited to the discovery namespace for which the access is allowed.

[IMPORTANT]
====
The {APP_NAME_DISCOVERY} indexer must finish it's re-indexing in order for the changes to take affect.
====

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "discovery/examples/limit-namespace/search-results-limited.png",
    "alias": "discovery-examples-limit-namespace-search-results-limited",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "annotations": [{
    "x": 7,
    "y": 67,
    "h": 306,
    "w": 185
  }]
}
----
