include::ROOT:partial$variables.adoc[]

= Index Only Specified Namespace
:page-noindex: true

xref:discovery/index.adoc#data-visibility[Data visibility] is controlled with the standard access control facility.
The {APP_NAME_DISCOVERY} indexes everything it currently has access to.
To control data visibility, configure access control rules for the role assigned to the xref:discovery/index.adoc#indexer-user[{APP_NAME_DISCOVERY} indexer user].

In this example we will configure {PRODUCT_NAME} {APP_NAME_DISCOVERY} to only index records from the discovery namespace.

Click on the btn:[permissions] button to open up global namespace access control rules.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "discovery/examples/limit-namespace/namespace-list.png",
    "alias": "discovery-examples-limit-namespace-namespace-list",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "annotations": [{
    "kind": "box-note",
    "x": 830,
    "y": 72,
    "w": 150,
    "h": 43
  }]
}
----

Select the *authenticated* role and set the `read any namespace` rule to `deny`.
Alternatively, you can set the same rule to deny for the {APP_NAME_DISCOVERY} indexer role.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "discovery/examples/limit-namespace/namespace-rbac-global.png",
    "alias": "discovery-examples-limit-namespace-namespace-rbac-global",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "annotations": [{
    "kind": "box-note",
    "x": 406,
    "y": 105,
    "w": 255,
    "h": 47
  }, {
    "x": 706,
    "y": 105,
    "w": 556,
    "h": 31
  }]
}
----

Next, click on the btn:[edit] button for the namespace you wish to allow access to and click on the btn:[permissions] button to open up access control rules for the given namespace.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "discovery/examples/limit-namespace/namespace-edit.png",
    "alias": "discovery-examples-limit-namespace-namespace-edit",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "focus": {
    "x": 825,
    "y": 68,
    "h": 44,
    "w": 150
  },
  "annotations": [{
    "x": 825,
    "y": 68,
    "h": 44,
    "w": 150
  }]
}
----

Select the *discoverer* role (the role assigned to the {APP_NAME_DISCOVERY} indexer user) and set the `read namespace` rule to `allow`.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "discovery/examples/limit-namespace/namespace-rbac.png",
    "alias": "discovery-examples-limit-namespace-namespace-rbac",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "annotations": [{
    "x": 406,
    "y": 611,
    "h": 48,
    "w": 256
  }, {
    "x": 705,
    "y": 105,
    "h": 31,
    "w": 613
  }]
}
----

After the {APP_NAME_DISCOVERY} indexer reindexes your instance, the search results become limited to the discovery namespace for which we allowed access to.

[IMPORTANT]
====
The {APP_NAME_DISCOVERY} indexer must finish it's re-indexing in order for the changes to take affect.
====

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "discovery/examples/limit-namespace/search-results-limited.png",
    "alias": "discovery-examples-limit-namespace-search-results-limited",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "annotations": [{
    "x": 16,
    "y": 252,
    "h": 49,
    "w": 288
  }]
}
----
