include::../variables.adoc[]

= {APP_AUTOMATION} server configuration

[IMPORTANT]
====
You can place all configurations into a single `.env` file.
====

{PRODUCT_NAME} {APP_AUTOMATION} server is configured via the environment (`.env`) file.
It allows a quick deploy to another platform, along with fine-tuning the behaviour and enabled features.

[IMPORTANT]
====
The `.env` file is at the root of the application.
In the context of Docker Compose, it is next to the `docker-compose.yaml` file.
====

[TIP]
====
You can use variables defined in the `.env` inside your `docker-compose.yaml` file; for example `$\{VERSION\}`.
====

== Base configuration

These variables control the base {APP_AUTOMATION} server configurations, such as extension search paths, and certificate locations.

[cols="1,2,5a"]
|===
|Type|Default value|Description

3+| *CORREDOR_ADDR*
| `string`
| corredor:80
| This setting is used by both, Corredor and API Server.

For Corredor server: where is server listening on

For API server: where can Corredor server be accessed.

_Used by Corredor and API server._

3+| *CORREDOR_ENABLED*
| `bool`
| false
| This is a setting for API server, will Corredor be used for server automation?

_Used by Corredor and API server._

3+| *CORREDOR_MAX_BACKOFF_DELAY*
| `duration`
| 1m
| Connection timeout (from API server to Corredor)

_Used by API server._

3+| *CORREDOR_EXEC_CSERVERS_API_BASEURL_TEMPLATE*
| string
| https://api.\{host\}/\{service\}
| Location of the Corteza server API.
\{host\} is replaced with value from env variables (in this order: CORREDOR_EXEC_CSERVERS_API_HOST, DOMAIN, HOSTNAME, HOST), \{service\} is replaced dynamically inside Corredor with `compose`, `system` or `messaging`.

_Used by Corredor server._

3+| *CORREDOR_EXEC_CSERVERS_API_HOST*
| string
|
| Hostname used for template

_Used by Corredor server._

3+| *CORREDOR_LOG_ENABLED*
| `boolean`
| corredor
| This setting is used by both, Corredor and API Server.

For Corredor service: where is service listening on (gRPC)

For API server: where can Corredor service be accessed.

_Used by Corredor and API server._

3+| *CORREDOR_LOG_LEVEL*
| `string`
| info
| Defaults to `trace` when `CORREDOR_DEBUG` is `true`, defines amount of log information outputed.

_Used by Corredor and API server._

3+| *CORREDOR_LOG_PRETTY*
| `boolean`
| false
| Are events logged in one-line JSON or formatted to ease development?

_Used by Corredor._

3+| *CORREDOR_DEBUG*
| `boolean`
| false
| Corredor will log even more information.

_Used by Corredor_.

3+| *CORREDOR_EXT_DEPENDENCIES_AUTO_UPDATE*
| boolean
| true
| Corredor will auto update script dependencies found in `package.json` files

_Used by Corredor._

3+| *CORREDOR_EXT_SERVER_SCRIPTS_ENABLED*
| boolean
| true
| Server scripts are enabled

_Used by Corredor._

3+| *CORREDOR_EXT_SERVER_SCRIPTS_WATCH*
| boolean
| true
| Corredor will reload server-scripts on change

_Used by Corredor._

3+| *CORREDOR_EXT_CLIENT_SCRIPTS_ENABLED*
| boolean
| true
| Client scripts are enabled

_Used by Corredor._

3+| *CORREDOR_EXT_CLIENT_SCRIPTS_WATCH*
| boolean
| true
| Corredor will reload client-scripts on change

_Used by Corredor._

|===