include::../variables.adoc[]

[#docker-compose]
= Docker Compose

[NOTE]
====
If you are not planning on using Docker you can skip this section entirely.
====

== Environment setup

[NOTE]
====
If your system already has Docker (we recommend at least version 18.0) and Docker Compose installed, you can safely skip this.

You can checkout your Docker version by entering `docker -v` in your CLI.
====

If you don't have Docker installed, or the version is below the recommended version, download and install a Docker community edition for https://www.docker.com/products/docker-desktop[desktop] or https://hub.docker.com/search?offering=community&type=edition[server or cloud] that fits your environment.

* https://docs.docker.com/install/#server[Docker installation guide],
* https://docs.docker.com/compose/install/[Docker Compose installation guide].

== docker-compose file

The `docker-compose.yaml` file describes the different services, networks and storage configurations, used to configure your Docker containers.
Refer to the https://docs.docker.com/compose/compose-file/[Docker Compose documentation] for a complete reference.

== Some useful Docker Compose commands

=== Stop and remove containers along with their volumes without confirmation

[source,bash]
----
docker-compose rm --force --stop -v
----

=== View container logs

[source,bash]
----
docker-compose logs --follow --tail 20
# You can additionally filter by service; for example:
docker-compose logs --follow --tail 20 server
----

=== Executing with Docker Compose (when service is started)

[source,bash]
----
docker-compose exec <service name> help
----

=== Executing with docker (when a container is running)

[source,bash]
----
docker exec -it <container name> help
----

=== Running with Docker Compose (when service is not started)

[source,bash]
----
docker run -it --rm <container name> help
----

=== Executing with Docker (when container is not running)

[source,bash]
----
docker run -it --rm [docker run options] <container name> help
----

[TIP]
====
Running and executing with Docker Compose should be easier and simpler because all required options and settings
for the container are packed in the `docker-compose.yaml` file.
====
