include::../variables.adoc[]

= DevOps Guide
:doctype: book

The *DevOps guide* will help you through the *deployment and setup process*, so you will know how to *deploy*, *configure*, and *maintain {PRODUCT_NAME}*.

== Structure overview

The xref:ROOT:dev-ops-guide/architecture-overview.adoc[*structure overview*] section provides an outline of our *repositories and how they connect*.

== System requirements

[IMPORTANT]
====
The numbers may *differ for your needs*, but you can still use them as a base.
====

xref:ROOT:dev-ops-guide/system-requirements.adoc[*System requirements*] help you determine the server configuration that best suits your needs.

== {PRODUCT_NAME} demo in your local environment

See our *example setup sections* for a quick step-by-step on how to test {PRODUCT_NAME} on your laptop or workstation.

Refer to the xref:ROOT:dev-ops-guide/docker-compose.adoc[*docker compose*] section, if you need help with Docker.



== Deploying {PRODUCT_NAME} for production

[WARNING]
====
include::ROOT:partial$warnings/sqlite.adoc[]
====

See our *example setup sections* for a quick step-by-step on how to deploy to different environments.
Use the xref:dev-ops-guide/deployment/demo-mysql.adoc[*local MySQL*] for any local development or demonstration.
Use the xref:dev-ops-guide/deployment/prod-pgsql.adoc[*PostgreSQL*] or xref:dev-ops-guide/deployment/prod-mysql.adoc[*MySQL*] setup for any live deployments (*production* or *staging/testing*).

Refer to the xref:ROOT:dev-ops-guide/health-check.adoc[*health check*] section to test your deploy.

Refer to the xref:ROOT:dev-ops-guide/docker-compose.adoc[*docker compose*] section, if you need help with Docker.

See the *configuration* sections (xref:ROOT:dev-ops-guide/server-configuration/index.adoc[*server*] and xref:ROOT:dev-ops-guide/corredor-configuration.adoc[*Corredor server*]) for available *configuration options*.

== Post-deployment bits

Use the xref:ROOT:dev-ops-guide/cli.adoc[*CLI tool*] to perform some base maintenance tasks.

Setup xref:ROOT:dev-ops-guide/backup.adoc[*system backups*].

Allow automation scripts to xref:ROOT:dev-ops-guide/email-relay.adoc[*react to emails*].
