include::../variables.adoc[]

= DevOps Guide
:doctype: book

The *DevOps guide* will help you through the deployment and setup process.
You will know how to *deploy*, *configure*, and *maintain {PRODUCT_NAME}*.

== Structure overview

The xref:ROOT:dev-ops-guide/architecture-overview.adoc[*structure overview*] section provides a quick *overview of our repositories* and how they are *connected*.

== System requirements

[IMPORTANT]
====
The numbers may *differ for your use-case*, but you can still use them as a base.
====

xref:ROOT:dev-ops-guide/system-requirements.adoc[*System requirements*] help you determine the server configuration that best suits your use-case.

== Deploying {PRODUCT_NAME}

See our *example setup sections* for a quick step-by-step on how to deploy to different environments.
Refer to the xref:ROOT:dev-ops-guide/health-check.adoc[*health check*] section to test your deploy.

Use the xref:ROOT:dev-ops-guide/setup-local-demo.adoc[*local setup*] for any local development or demonstration.

Use the xref:ROOT:dev-ops-guide/setup-production.adoc[*production setup*] for any live deployments (*production* or *staging/testing*).

Refer to the xref:ROOT:dev-ops-guide/docker-compose.adoc[*docker compose*] section, if you need help with Docker.

See the *configuration* sections (xref:ROOT:dev-ops-guide/server-configuration/index.adoc[*server*] and xref:ROOT:dev-ops-guide/corredor-configuration.adoc[*Corredor server*]) for available *configuration options*.

== Post-deployment bits

Use the xref:ROOT:dev-ops-guide/cli.adoc[*CLI tool*] to perform some base maintenance tasks.

Setup xref:ROOT:dev-ops-guide/backup.adoc[*system backups*].

Allow automation scripts to xref:ROOT:dev-ops-guide/email-relay.adoc[*respond on emails*].
