include::../variables.adoc[]

[#nginx-proxy]
= Nginx proxy

[NOTE]
====
This is not needed when working on local instances.
Following the xref:ROOT:dev-ops-guide/index.adoc#setup-local-demo[setup local demo section] is enough to get a local instance up and running.
====

[WARNING]
====
We advise against merging/mixing {PRODUCT_NAME} and `nginx-proxy` in the same directory.

It can be done but requires some experience with Docker Compose.
====

[IMPORTANT]
====
The following instructions assume that you *don't* have anything similar setup on your current environment.
If you are using other means of providing traffic forwarding or SSL certificate handling, proceed with caution.
====

[IMPORTANT]
====
Containers *must* be on the same network as `nginx-proxy` (in the examples we're using network named `proxy`).
====

https://github.com/jwilder/nginx-proxy[Nginx Proxy] (docker image `jwilder/nginx-proxy`) is an auto-configurable reverse-proxy that routes traffic from your public IP to Docker containers on the host.

https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion[LetsEncrypt Nginx Proxy Companion] (docker image `jrcs/letsencrypt-nginx-proxy-companion`) automates the process of creating, renewing and using Let's Encrypt certificates for your Docker containers.

.What does this do?
. Both images listen for docker events to detect when containers start or stop,
. Nginx Proxy generates and reloads the configuration, and starts forwarding HTTP traffic to that container based on the `VIRTUAL_HOST`,
. LetsEncrypt companion starts the certificate creation process, reconfigures Nginx Proxy and enables redirection from HTTP to HTTPS based on the `LETSENCRYPT_HOST`.

.What are the benefits?
. Containers (like {PRODUCT_NAME} server, and fronted application) that are exposed publicly no longer have to publish their ports on public IP,
. complicated firewall configurations and network forwarding rules are no longer required.

[#nginx-proxy-config]
== Configurations

.`docker-compose.yaml`
[source,yaml]
----
include::ROOT:example$docker-compose/nginx-proxy/docker-compose.yaml[]
----

.`custom.conf`
[source]
----
include::ROOT:example$docker-compose/nginx-proxy/custom.conf[]
----

[IMPORTANT]
====
`custom.conf` *must* be placed next to `docker-compose.yaml`.
====

== Run the services

[source,shell]
----
docker-compose up -d
----

You can check if everything is running correctly by executing the `docker-compose ps` command.
The output should be similar to this one:

[source,shell]
----
include::ROOT:example$docker-compose/nginx-proxy/output-ps.txt[]
----
