include::../variables.adoc[]

[#setup-local-demo-2c]
= Simplified two-container setup for a local demo

[IMPORTANT]
====
The section covers configuration files that are only suitable for a demo on a local environment.
All services are on the same network, ports are bound to the host's network, etc.
We're using a minimum setup with corredor automation server, no persistent storage using in-memory SQLite3.
Restarting server give you a fresh database.

This is *not* an optimal setup for a production environment.
See xref:ROOT:dev-ops-guide/index.adoc#nginx-proxy[Nginx proxy] and xref:ROOT:dev-ops-guide/index.adoc#setup-production[production setup] guides for a production deploy.
====

== Configurations

.`docker-compose.yaml`
[source,yaml]
----
include::ROOT:example$docker-compose/basic-2c/docker-compose.yaml[]
----

Create an empty directory with the `docker-compose.yaml` file.
You can adjust the provided example configuration files as you see fit.

== Run the services

[source,shell]
----
docker-compose up -d
----

Run this command in the same directory as your `docker-compose.yaml` file.
It will start all services based on the configurations provided in the configuration files.

You can check if everything is running correctly, by executing the `docker-compose ps` command.
The output should be similar to this one:

[source,shell]
----
include::ROOT:example$docker-compose/basic-2c/output-ps.txt[]
----

You can see 2 services up and running.


== Finishing the setup

. Direct your browser to `http://localhost:18080`.
If you used other ports in your configurations, use those.
On your first visit, you should be redirected to the authentication page (`/auth`),
. create your account through the sign-up form.

[NOTE]
====
The first user gets automatically promoted to an administrator.
You can add additional users by using the sign-up form or by adding them in the administration panel.
====

