include::../../../variables.adoc[]

[#admin-adminpanel-compose-permissions]
= Permissions

The permissions interface can be accessed by clicking on the "Permissions" navigation item on the left navigation drawer under the compose item group.

The interface allows you to define permissions for core compose resources, such as access to compose, creating namespaces, editing modules and so on.

[IMPORTANT]
====
To define fine grained access control for specific resources, such as modules and pages, see ...
====

The interface is devised to the following sections:

Compose service::
    The section allows you to control overall access and usage of compose (see <<admin-adminpanel-compose-permissions-compose>>),

Namespaces::
    The section allows you to control namespace related access (see <<admin-adminpanel-compose-permissions-namespace>>),

Modules::
    The section allows you to control module related access (see <<admin-adminpanel-compose-permissions-module>>),

Module fields::
    The section allows you to control module field related access (see <<admin-adminpanel-compose-permissions-modulefield>>),

Charts::
    The section allows you to control chart related access (see <<admin-adminpanel-compose-permissions-chart>>),

Pages::
    The section allows you to control page related access (see <<admin-adminpanel-compose-permissions-page>>),

[#admin-adminpanel-compose-permissions-compose]
== Compose service permissions

Access to compose::
    Determines if the role is allowed to access {PRODUCT_NAME} {APP_NAME_COMPOSE},

Grant permissions on compose service::
    Determines if the role is allowed to manage permissions for {PRODUCT_NAME} {APP_NAME_COMPOSE},

Create namespaces::
    Determines if the role is allowed to create namespaces for {PRODUCT_NAME} {APP_NAME_COMPOSE},

Access all settings::
    Determines if the role is allowed to read any setting for {PRODUCT_NAME} {APP_NAME_COMPOSE},

Manage all settings::
    Determines if the role is allowed to manage any setting for {PRODUCT_NAME} {APP_NAME_COMPOSE}.

[IMPORTANT]
====
If a role doesn't have access to the {PRODUCT_NAME} {APP_NAME_COMPOSE}, they will also *not* be able to access any application defined as a {PRODUCT_NAME} {APP_NAME_COMPOSE} namespace.
====

[#admin-adminpanel-compose-permissions-namespace]
== Namespaces permissions

Access any namespace::
    Determines if the role is allowed to access any {PRODUCT_NAME} {APP_NAME_COMPOSE} namespace,

Update any namespace::
    Determines if the role is allowed to update any {PRODUCT_NAME} {APP_NAME_COMPOSE} namespace,

Delete any namespace::
    Determines if the role is allowed to delete any {PRODUCT_NAME} {APP_NAME_COMPOSE} namespace,

Manage any namespace::
    Determines if the role is allowed to manage any {PRODUCT_NAME} {APP_NAME_COMPOSE} namespace,

Create modules under any namespace::
    Determines if the role is allowed to create modules for any {PRODUCT_NAME} {APP_NAME_COMPOSE} namespace,

Create charts under any namespace::
    Determines if the role is allowed to create charts for any {PRODUCT_NAME} {APP_NAME_COMPOSE} namespace,

Create pages under any namespace::
    Determines if the role is allowed to create pages for any {PRODUCT_NAME} {APP_NAME_COMPOSE} namespace.

[#admin-adminpanel-compose-permissions-module]
== Modules permissions

Read any module::
    Determines if the role is allowed to access any {PRODUCT_NAME} {APP_NAME_COMPOSE} module,

Update any module::
    Determines if the role is allowed to update any {PRODUCT_NAME} {APP_NAME_COMPOSE} module,

Delete any module::
    Determines if the role is allowed to delete any {PRODUCT_NAME} {APP_NAME_COMPOSE} module,

Create record under any module::
    Determines if the role is allowed to create records for any {PRODUCT_NAME} {APP_NAME_COMPOSE} module,

Read records under any module::
    Determines if the role is allowed to access records for any {PRODUCT_NAME} {APP_NAME_COMPOSE} module,

Update records under any module::
    Determines if the role is allowed to update records for any {PRODUCT_NAME} {APP_NAME_COMPOSE} module,

Delete records under any module::
    Determines if the role is allowed to delete records for any {PRODUCT_NAME} {APP_NAME_COMPOSE} module.

[#admin-adminpanel-compose-permissions-modulefield]
== Module fields permissions

Read any module field::
    Determines if the role is allowed to see any {PRODUCT_NAME} {APP_NAME_COMPOSE} module field,

Update any module field::
    Determines if the role is allowed to update any {PRODUCT_NAME} {APP_NAME_COMPOSE} module field.

[#admin-adminpanel-compose-permissions-chart]
== Charts permissions

Read any chart::
    Determines if the role is allowed to see any {PRODUCT_NAME} {APP_NAME_COMPOSE} chart,

Update any chart::
    Determines if the role is allowed to update any {PRODUCT_NAME} {APP_NAME_COMPOSE} chart,

Delete any chart::
    Determines if the role is allowed to delete any {PRODUCT_NAME} {APP_NAME_COMPOSE} chart.

[#admin-adminpanel-compose-permissions-page]
== Pages permissions

Read any page::
    Determines if the role is allowed to see any {PRODUCT_NAME} {APP_NAME_COMPOSE} page,

Update any page::
    Determines if the role is allowed to update any {PRODUCT_NAME} {APP_NAME_COMPOSE} page,

Delete any page::
    Determines if the role is allowed to delete any {PRODUCT_NAME} {APP_NAME_COMPOSE} page.
