include::ROOT:partial$variables.adoc[]

= Upgrade Guide

This guide will help you upgrade your {PRODUCT_NAME} to the newest version in no time!

[IMPORTANT]
====
While there are internal safeguards in place that can prevent data loss or other kinds of disasters, make sure you backup your database before you do an upgrade.
Refer to xref:devops-guide:maintenance/backups.adoc[devops guide on backup procedure] for details.
====

[IMPORTANT]
====
If you are upgrading multiple versions at the same time; for example from 2019.12 to 2020.9; you should follow all the upgrade guides between the two versions.
====

== Recommended steps for {PRODUCT_NAME} upgrade

.Especially before any major version upgrade we recommend that before upgrading your production you either:
- upgrade your staging environment, or
- deploy a temporary environment with a copy of the production database and do a test upgrade there

.Steps to upgrade {PRODUCT_NAME} when deployed with *docker-compose*
. changing image versions in your `docker-compose.yaml` (or  `.env`) file,
. pull new images from docker hub with `docker-compose pull`,
. recreate containers with `docker-compose up -d`.

:leveloffset: +1

include::202109.adoc[]

:leveloffset: -1
