include::ROOT:partial$variables.adoc[]

= Authentication and authorization

{PRODUCT_NAME} implements the OAuth2 authentication protocol.
The {PRODUCT_NAME} server can act both as a OAuth2 server and as an OAuth2 client, allowing both internal and external authentications.

== Terminology

[cols="2s,5a"]
|===
| [#auth-term-user]#<<auth-term-user,The user>>#
|
_In OAuth2 terminology, this is a **resource owner**_.
The user authenticates themselves and authorizes the <<,auth-client,client>> on the authorization server.

| [#auth-term-auth]#<<auth-term-auth,{PRODUCT_NAME} auth server>>#
|
_In OAuth2 terminology this is a **authorization server**_.
The {PRODUCT_NAME} Auth authenticates users, authorizes clients and issues access tokens.

[NOTE]
====
{PRODUCT_NAME} Auth currently runs side-by-side with {PRODUCT_NAME} API server.
====
<
| [#auth-term-api]#<<auth-term-api,{PRODUCT_NAME} API>>#
|
_In OAuth2 terminology, this is a **resource server**_
A client must obtain an access token in order to access the resources on the the {PRODUCT_NAME} API.

[NOTE]
====
{PRODUCT_NAME} Auth currently runs side-by-side with {PRODUCT_NAME} API server.
====

| [#auth-term-client]#<<auth-term-client,Client, Auth Client, Third-Party Application>>#
|
A client is any application that is used to interact with the {PRODUCT_NAME} API.

| [#auth-term-local-credentials]#<<auth-term-local-credentials,Local credentials>>#
|
Local credentials are the email and the password that the user can use to authenticate.

| [#auth-term-external-providers]#<<auth-term-external-providers,External identity providers>>#
|
An external identity provider is any provider that supports the OpenID Connect (OIDC) protocol such as Google, LinkedIn, and GitHub.

| [#auth-term-security-ctx]#<<auth-term-security-ctx,Security context>>#
|
Security context is a set of roles that are assigned to the user when accessing the {PRODUCT_NAME} API.
|===

== Defining external providers

The use of external authentication providers allows your users to use external services (such as Google and GitHub) for authentication purposes.
External providers can be defined in the {PRODUCT_NAME} {APP_NAME_ADMIN} panel, under the menu:System[Settings,External authentication providers].

To enable an external authentication provider you must register {PRODUCT_NAME} server as a client using their interface.
Once you've obtained the user key and secret, you can configure {PRODUCT_NAME} using the admin panel.
External providers become effective immediately without server restart.

== Using {PRODUCT_NAME} as an authentication provider

You can allow external applications to use {PRODUCT_NAME} as an authentication provider.

After a successful authorization with local credentials or an external provider, an *access token* along with a *refresh token* is issued.
This should be done automatically by the client.

[CAUTION]
====
The access token is short lived and should be automatically refreshed.
You can use our https://github.com/cortezaproject/corteza-vue/blob/2021.6.x/src/plugins/auth.ts[corteza-vue plugins/auth] to manage this for you.
====

The session on the {PRODUCT_NAME} Auth is different from the one on the client application.
This separation allows the {PRODUCT_NAME} Auth session to be used when authorizing additional clients.

[CAUTION]
====
Since the authentication sessions between different clients are different, each session must be revoked in order for the user to be, in fact, signed-out.
====

=== Auth clients

An <<auth-term-client,auth client>> offers a high-level access control over the use of {PRODUCT_NAME} API and it's resources.
Auth clients can be defined in the {PRODUCT_NAME} {APP_NAME_ADMIN} panel, under the menu:System[Auth clients].

It is advised that you create a *separate Auth client for each application you wish to integrate with*.
This allows you to have full control over all integrated applications and the clients' scope.

.The Auth client consists of:
. a combination of a client ID and a client secret,
. a list of scopes to limit access based on the used Auth client,
. a list of redirection URIs that can be used with authorization code grant,
. a trusted flag to force users to confirm authentication,
. an Auth client validity based on the date.

[#auth-scope]
=== Authorization scope

The scope is defined as a series of role memberships that are either *permitted*, *prohibited*, or *forced* on the user when using a specific {PRODUCT_NAME} Auth server.

[cols="2s,5a"]
|===
| [#auth-scope-permitted]#<<auth-scope-permitted,Permitted roles>>#
Permitted roles allow you to specify what roles the user is *allowed to have* when accessing the {PRODUCT_NAME} API resources from a specific client.
//Nika's note: swap the bolding, everything but 'allowed to have' is bold. I couldn't find the source of that.

| [#auth-scope-prohibited]#<<auth-scope-prohibited,Prohibited roles>>#
Prohibited roles allow you to specify what roles the user is *not allowed to have* when accessing the {PRODUCT_NAME} API resources from a specific client.

| [#auth-scope-forced]#<<auth-scope-forced,Forced roles>>#
Forced roles allow you to specify what roles the user *must have* when accessing the {PRODUCT_NAME} API resources from a specific client.
If the user does not have a forced role, it will be automatically added.
|===
//Nika's note: I don't see the forced roles in the table in the preview section.
//line 115; specify what 'it' is for the sake of clarity.

=== Notes on security

First and above all, use HTTPS with valid SSL certificates.

Authentication forms and endpoints are protected against brute-force and cross-site request attacks.
You can also set your own secrets for JWT, CSRF and cookie value encryption.

Different expiration durations may be set on sessions temporary and permanent sessions to support your organization's security policies.

[NOTE]
====
If any of the secrets are changed, users will receive various warnings and will get logged-out.
====

Please see the xref:devops-guide:configuration/server.adoc#_authentication[full list of options].
These changes take affect after server restart.

=== Tips for debugging

.Things to check when authentication does not work:
* client's ID and secret must match,
* at least one of client's redirect URIs must match (by prefix),
* client's grant flow must match,
* client's scope must match (requested group of scopes must intersect with scopes on the client),
* user authorizing the client must be a carrier of a role that is able to authorize the client,
* the user must be valid (confirmed email, unsuspended, undeleted).
