include::ROOT:partial$variables.adoc[]

= Troubleshooting
:page-aliases: maintenance/troubleshooting.adoc
:description: These troubleshooting steps help you solve the most common issues we have encountered in the past.
:keywords: dev-ops, DevOps, troubleshooting

In case you are experiencing issues while setting up or using {PRODUCT_NAME} you can use the following tools and knowledge bases to help you resolve your issue.

{PRODUCT_NAME} introduces a xref:troubleshooting/web-console.adoc[] which provides an easy way to access important information such as server logs.
The web console can be used to try and pinpoint what is causing the issue.

If you are unable to resolve the issue, you can reach out to the community on https://forum.cortezaproject.org/[our forum].

== Ports are not available

When running various services on your machine, it's common that the ports are already in use.
You see something like this:

[source]
----
Cannot start service server: Ports are not available: listen tcp 127.0.0.1:18080: bind: address already in use
----

If you see this error, you can change the port number to a number between `1024` and `65535`.
You can also replace the value for `services.server.ports` in `docker-compose.yaml` to `["80"]`, and Docker then picks an available port for you.

[#ws-nginx-connection-fail]
== WebSocket connection failing with Nginx

If the WebSocket connection is failing to establish, you might need to enable Nginx WebSocket proxying.

[NOTE]
====
You can find detailed instructions and further examples in the https://nginx.org/en/docs/http/websocket.html[Nginx documentation].
====

Inside your `nginx.conf` file (by default, it is located inside the `/etc/nginx` directory), add the following lines to the `server` configuration section;

[source]
----
location /api/websocket {
  proxy_pass http://server:80;
  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "Upgrade";
  proxy_set_header Host $host;
}

----
[CAUTION]
====
Make sure to adjust the location if you've defined a custom configuration that affects the base path.
====

== Connection to {APP_AUTOMATION} server

You might see one or more connection refused errors in server container logs (`docker-compose logs -f server`):

[source]
----
{"level":"error","ts":1608125024.4714684,"logger":"corredor","caller":"corredor/service.go:427","msg":"could not load corredor server scripts","error":"rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = \"transport: Error while dialing dial tcp 172.23.0.2:80: connect: connection refused\"","stacktrace":"github.com/cortezaproject/corteza-server/pkg/corredor.(*service).loadServerScripts\n\t/drone/src/pkg/corredor/service.go:427"}
----

If there are a couple of errors when the server is starting up, that's ok.
Sometimes it takes more time to start up {APP_AUTOMATION} server, and {PRODUCT_NAME} server can not yet connect to it.

If the problem persists and you can see {APP_AUTOMATION} state as healthy, verify the changes you might have made to the configuration.

== Network Proxy Declared as External

[source]
----
ERROR: Network proxy declared as external, but could not be found. Please create the network manually using `docker network create proxy` and try again.
----

Make sure your nginx-proxy service is up and running before running {PRODUCT_NAME}.

== Blank Screen on `/auth` With the "state does not match" Error in the Browser Console

The `state does not match` error usually occurs in the development environment or where the {PRODUCT_NAME} server is frequently restarted.

The authentication state, which is carried through the user authentication flow, is not persistent and will perish on server restart.
If the error occurs and persists on the production environment, verify your `AUTH_SESSION_*` `.env` settings (in case you have modified them).

== Stuck on Login Screen After Providing Valid Credentials

Please note that some deployments (like with Docker) might not have all configuration available for valid auto-configuration.
Check what how the cookies are sent in the response headers on login.
//Editor's note: which one is it? How the cookies are sent or what cookies are sent?

_Please note that examples below have an abbreviated session value._

=== Broken Configuration, User is Stuck on Login Screen

[source]
----
set-Cookie:
    session=MTYzODQ...tCLvO_DHhw==;
    Path=/auth;
    Domain=e3a47cb50c17; <1>
    Expires=Sun, 27 Nov 2022 10:13:08 GMT;
    Max-Age=31104000;
    HttpOnly
----
<1> A set of random characters where the domain or hostname should be, represent the Docker container ID (and hostname).
//Editor's note: check for accuracy. In case it is not okay, please expand and clarify.
Setup like this requires `DOMAIN` variable to be set (for example. `DOMAIN=localhost:8080`).
//Editor's note: is what it is set to important?
Do not forget to recreate your server container after the change.

=== Valid Cookie Example

[source]
----
set-Cookie: <1>
    session=MTYzODQ...tCLvO_DHhw==;
    Path=/auth;
    Expires=Sun, 27 Nov 2022 12:58:01 GMT;
    Max-Age=31104000;
    HttpOnly
----
<1> When you provide `DOMAIN` option like instructed in the example above, notice that "Domain" flag on the cookie is missing.
Corteza removes it when you use port in the domain.
//Editor's note: Corteza or {PRODUCT_NAME}? (What's the distinction and where should one or the other be used? - the question has nothing to do with the content here, just for my information :).)

=== Valid Example of a Cookie on a Secure Host

[source]
----
set-cookie:
    session=MTYzODQ...tCLvO_DHhw==;
    Path=/auth;
    Domain=corteza.example.org;
    Expires=Fri, 03 Dec 2021 12:58:46 GMT;
    Max-Age=86400;
    HttpOnly;
    Secure <1>
----
<1> Note the "Secure" cookie flag.
This cookie is sent back to the server only if server is on secure domain (HTTPS).
If you used `HTTP_SSL_TERMINATED` or `LETSENCRYPT_HOST` options, Corteza assumes that it is served on a secured domain.
//Editor's note: Corteza or {PRODUCT_NAME}? 

== Further Troubleshooting

If you continue to have issues with {PRODUCT_NAME}, we encourage you to contact other users on our https://latest.cortezaproject.org[community server].
You'll more than likely find someone who can help you out.
You can also open an issue on our https://github.com/cortezaproject/corteza-server[cortezaproject/corteza-server] GitHub repository.

== SMTP not Working

You can use the `corteza-server auth test-notifications` command to verify that your SMTP configuration is working correctly.
The command sends a test email to the provided email address.

[source,bash]
----
corteza-server auth test-notifications your-email@example.tld
----

Depending on your provider, the email can take different amounts of time to be delivered.
If you can't see the email, make sure to check your spam folder and server logs.

.Connection and authentication errors look like this:
[source]
----
could not send email: dial tcp [::1]:25: connect: connection refused
----
