include::../../variables.adoc[]

= Settings

In the settings page you can set multiple values that are used within Service Cloud as default values.
You will need to enter this page when you have just installed {PRODUCT_NAME} and wish to use Service Cloud.

.Settings fields:
* Next number for a KB item
* Default cost per hour
* Default department for new ticket
* Default time for a case update
* Default support channel id
* Default case link
* Default case email template

== Steps to follow just installed {PRODUCT_NAME} Service Cloud

. When you start using Service Cloud, you first need to enter the "Settings" module.
+
This is done by selecting the Settings item  in the main menu.
. By default there is one line , and you need to click on the "Edit the record" button on the right.
. Select the default department
+
This is used in cases
. Optional: insert a support channel id.
+
In this channel case updates will be inserted.
.. Go to Messaging
.. If you don’t have a channel yet where you want to show Service Cloud updates, create the channel with the (+) button.
.. Get the id of the channel.
+
This can be done by hovering with the mouse over the channel name in the list of channels.
+
For example: 117587018585788420
. Insert the default case link.
+
This will allow clickable links to cases from emails and messages in the channel.

.. To find the link, go to the admin panel.
.. Select “Pages”
.. Copy the link under the “view” icon of the page: Record page for module “Case”. Normally the view icon opens the page, but we are interested in retrieving the exact location.
.. The record page of a case is opened.
+
It will look like: https://LINK-TO-YOUR-INSTANCE/compose/ns/service-cloud/pages/117582846914252804/record/117585622083883012
+
You will need to copy "https://LINK-TO-YOUR-INSTANCE/compose/ns/service-cloud/pages/117582846914252804/record" (so, everything except the last "/" and number), and paste it in the Default case link field.
. And, the last step is to select the default case email template.

Other values are inserted with default values, and you can change them if you like.
