= Encoder layer

The encoding layer converts *internal structures* into some *output form* we wish to have.
It operates over internal resource nodes and converts them into... something.

[NOTE]
====
As the name implies, the encoder layer should only encode the data... *but* it's not limited to this.
In the context of the envoy framework this layer can *perform any operation* over the data; write to the *store*, *file*, *HTTP response*, or even *send an email* alerts.
====

The initial implementation defines a *set of base encoders* that cover our initial plans for a better data import/export system.
Out of the box, it supports *YAML*, *CSV* files and the *{PRODUCT_NAME} store layer*.

[TIP]
====
The loose and straightforward interface definition allows us to define an encoder for anything we might want in the future.
====

The Encoder layer is *allowed* to operate over the *resource nodes* that are *provided* by the upper layer.
The encoder *should not*  have to worry about any data validations or related operations.
It should also *not have to* figure out if the resource should be *created*, *updated*, or *deleted* -- the upper layers should determine this.

The encoder layer should rely on the <<layer-preproc,pre-process>> and the <<layer-validator,validator>> layers that the data is valid and good enough for processing.
