include::../../../variables.adoc[]
= External Authentication

Check the "Enable external authentication" box if you wish to allow your users to register and log in using external providers. Currently, we support Google, Facebook, Github and LinkedIn authentication.

== Google

To enable Google authentication you need to create a client ID:

. Go to https://developers.google.com/identity/sign-in/web/sign-in#before_you_begin[Google Sign-in Guide] and click on "Configure a project" button
. Select and existing project or create a new one
. Set a product name (i.e. {PRODUCT_NAME})
. On "Configure your OAuth client" screen select "Web browser" and paste the URL where your {PRODUCT_NAME} system is running (inlcuding https://)
. Copy and paste both Client ID and Client Secret fields to {PRODUCT_NAME} Admin panel and hit submit

== Facebook

To enable Facebook authentication you need to create Facebook app to receive Client key and Secret:

. Go to https://developers.facebook.com/apps/[Facebook for developers] website, click on "Add a new app" and choose a name of the app (i.e. {PRODUCT_NAME}) or select and existing app
. In the list of available products search for "Facebook Login" and click on "Set Up" button
. Select "Web" platform and paste the URL where your {PRODUCT_NAME} system is running
. Go to "Settings" and then "Basic" in the left sidebar
. Copy and paste "App ID" to "Client key" inside {PRODUCT_NAME} Admin panel
. Copy and paste "App Secret" to "Secret" inside {PRODUCT_NAME} Admin panel and hit Submit

== Github

To enable Github authentication you need to register Github application to get unique Client ID and Client Secret:

. Go to https://github.com/settings/applications/new[this link] and create a new OAuth application
. Copy and paste both Client ID and Client Secret fields to {PRODUCT_NAME} Admin panel and hit submit.

== LinkedIn

To enable LinkedIn authentication you need crete a LinkedIn application:

. Go to https://www.linkedin.com/developers/apps/new[this form], fill out the form and click on "Create app"
. Go to Auth section and copy and paste both Client ID and Client Secret fields to {PRODUCT_NAME} Admin panel and hit submit.
