= Internal Authentication

In this section you can control the following:

- Internal authentication enabled
- Password reset enabled (if unchecked, users won't be able to reset their password)
- Signup email confirmation required (if unchecked, users can log in to the system right after the registration, without confirming their email)
- Signup enabled (if unchecked, admins will add users manually in the Admin panel and nobody will be able to register on their own)

== Authentication Email Settings
In this section you can set:

- Sender email address (i.e. info@company.org)
- Sender name (i.e. Organization Ltd.)`

== Email templates:
Email templates used for authentication purposes are the following:

.Email confirmation HTML template
----
{{.EmailHeaderEn}}
  <h2 style="color: #1397CB;text-align: center;">Confirm your email address</h2>
  <p>Hello,</p>
  <p>Follow <a href="{{ .URL }}" style="color:#1397CB;">this link</a> to confirm your email address.</p>
  <p>You will be logged-in after successful confirmation.</p>
{{.EmailFooterEn}}
----
.Password reset HTML template
----
{{.EmailHeaderEn}}
<h2 style="color: #1397CB;text-align: center;">Reset your password</h2>
<p>Hello,</p>
<p>Follow <a href="{{ .URL }}" style="color:#1397CB;">this link</a> and reset your password.</p>
<p>You will be logged-in after successful reset.</p>
{{.EmailFooterEn}}
----

We recommend using https://codepen.io/[Codepen] or similar browser-based tools to preview the layout of the template before changing the template.

[IMPORTANT]
====
- `{{.EmailHeaderEn}}` has to be at the beginning of each template
- `{{.EmailFooterEn}}` has to be at the end of each template
- `{{ .URL }}` is used as a href parameter for the confirmation link.
====
