include::ROOT:partial$variables.adoc[]

= `2023.9.5`

*Released on*: `2024.03.21`

.[#2023_09_05-added]#<<2023_09_05-added,Added:>>#
* Added the option to access user information from xref:integrator-guide:expressions/type-reference.adoc#objref-user[User values] in pages, charts, and record fields.
The change was added to provide an easier way for the user to access their user data
({CORTEZA_PULL_BASE}1735[`1735`]).
* Added support for User and Record fields to be exported/imported on the record list page block
({CORTEZA_COMMIT_BASE}7fc4ca9[`7fc4ca9`]).
* Added the option to open a link/route/record page in a new tab using {APP_NAME_WORKFLOW} prompts
({CORTEZA_PULL_BASE}1726[`1726`]).

.[#2023_09_05-changed]#<<2023_09_05-changed,Changed:>>#
* Changed the flow of updating values in fields and page blocks to fetch the latest values after an update.
The change was made to ensure fields and blocks are always up to date
({CORTEZA_PULL_BASE}1634[`1634`]).

.[#2023_09_05-removed]#<<2023_09_05-removed,Removed:>>#
* Removed Nylass page block.
The removal was made because Nylass stopped using the functionality implemented in {PRODUCT_NAME}
({CORTEZA_COMMIT_BASE}77169cf[`77169cf`]).

.[#2023_09_05-fixed]#<<2023_09_05-fixed,Fixed:>>#
* Fixed not being able to upload `png` file to an application in {APP_NAME_ADMIN}
({CORTEZA_COMMIT_BASE}0456fe4[`0456fe4`]).
* Fixed not being able to make a copy of predefined CRM namespace
({CORTEZA_COMMIT_BASE}55a827a[`55a827a`], {CORTEZA_PULL_BASE}1729[`1729`]).
* Fixed not being able to add a record in a duplicated CRM namespace because page layout wasn't created when the namespace was cloned
({CORTEZA_PULL_BASE}1717[`1717`]).
* Fixed workflow session list throwing internal errors when using postgres database.
The fix was made properly omitting invalid/blank slices in filters
({CORTEZA_COMMIT_BASE}74031ca[`74031ca`]).
* Fixed prompt submissions always being treated as `Untyped` by running a type resolution step before applying to the scope
({CORTEZA_COMMIT_BASE}772d03e[`772d03e`]).
