include::ROOT:partial$variables.adoc[]

= `2023.9.6`

*Released on*: `2024.04.25`

.[#2023_09_06-added]#<<2023_09_06-added,Added:>>#
* Added `id` system field to user information in {APP_NAME_ADMIN}
({CORTEZA_COMMIT_BASE}d81809c[`d81809c`], {CORTEZA_COMMIT_BASE}14b704f[`14b704f`]).
* Added `cancel` status filter to automation session list in {APP_NAME_ADMIN}
({CORTEZA_COMMIT_BASE}c0d43df[`c0d43df`]).

.[#2023_09_06-changed]#<<2023_09_06-changed,Changed:>>#
* Changed the updating mechanism of charts to trigger when the user creates and updates a chart.
The change was made to keep chart up to date with its latest configuration
({CORTEZA_COMMIT_BASE}ad95e6a[`ad95e6a`]).
* Changed chart tooltip structure to be consistent in {APP_NAME_COMPOSE} and {APP_NAME_REPORTER}.
The change was made to implement a standard across all web applications that use charts
({CORTEZA_COMMIT_BASE}91a7a59[`91a7a59`]).

.[#2023_09_06-fixed]#<<2023_09_06-fixed,Fixed:>>#
* Fixed not being able to filter data by `userID` when viewing a record in a record list using the drill down option
({CORTEZA_COMMIT_BASE}8d2ccea[`8d2ccea`]).
* Fixed not being able to see all users assigned to a role in {APP_NAME_ADMIN}
({CORTEZA_COMMIT_BASE}9cc3a9c[`9cc3a9c`]).
* Fixed record page not loading when navigating to a new record from the create record view
({CORTEZA_COMMIT_BASE}9c07c90[`9c07c90`]).
* Fixed not being able to set the SMTP password in {APP_NAME_ADMIN} because it was removed mistakenly
({CORTEZA_COMMIT_BASE}96a7fd6[`96a7fd6`]).
* Fixed not being able to use drill down on `select`, `record`, and `user` fields
({CORTEZA_COMMIT_BASE}cf8de0f[`cf8de0f`]).
* Fixed double fetching of record list configuration after drill down data is updated
({CORTEZA_COMMIT_BASE}5a4f934[`5a4f934`]).
* Fixed multi-line option not working for module text fields
({CORTEZA_PULL_BASE}1770[`1770`]).
* Fixed duplicate field name causing module configuration issues
({CORTEZA_PULL_BASE}1773[`1773`]).
* Fixed workflow not redirecting the user to the next record after saving the current record
({CORTEZA_PULL_BASE}1775[`1775`]).
* Fixed record id shown instead of label by default
({CORTEZA_PULL_BASE}1776[`1776`]).
* Fixed incorrect boolean labels and value shown in charts
Fixed metric label in tooltips to show the field `title` instead of the field `name`
({CORTEZA_COMMIT_BASE}447e6fa[`447e6fa`]).
* Fixed incorrect record shown when workflow function for fetching the first or the last record is used
({CORTEZA_COMMIT_BASE}7b29b80[`7b29b80`]).
* Fixed incorrect redirecting to record view when a workflow prompt is used
({CORTEZA_COMMIT_BASE}e766b4b[`e766b4b`]).
* Fixed redirecting between record view and record edit mode in {APP_NAME_COMPOSE}
({CORTEZA_COMMIT_BASE}60376b7[`60376b7`]).
