include::ROOT:partial$variables.adoc[]

= Integration Gateway
:keywords: integration gateway, API gateway, custom API, custom endpoints, custom API endpoints, sink alternative
:description: Lean how to define custom API endpoints using the integration gateway

The Integration gateway facility allows you to define custom endpoints that can support custom authentication methods, request validation and rate limiting.

[TIP]
====
Integration gateway serves as an alternative to sink endpoints.
====

These endpoints can be used to define a custom endpoint for incoming webhooks, to process data provided by some external integration, or to proxy requests to another service.

Most of the basic operations can be achieved with the built-in functionality; more advanced operations can be implemented with simple JavaScript code snippets or xref:automation/workflows/index.adoc[workflows].

== Defining a New Endpoint

To define a new endpoint, navigate to your {PRODUCT_NAME} instance (for example http://latest.cortezaproject.org/) and click on the "admin area" application.

.The screenshot shows the app selector and the admin area application.
[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "app-selector.png",
    "alias": "apigw-app-selector-admin",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "focus": {
    "x": 540,
    "y": 463,
    "w": 266,
    "h": 217
  },
  "annotations": []
}
----

In the admin area, navigate to the menu:System[Integration Gateway] sub-page.
From the admin area, you can create and update your endpoints, as well as manage their access control.

.The screenshot shows the route list screen.
[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "api-gw/route-list.png",
    "alias": "api-gw-route-list",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 320,
    "y": 0,
    "w": 1600,
    "h": 450
  },
  "annotations": []
}
----

When you click on the btn:[new] button, a new screen will appear where you need to provide the base parameters of your endpoint.

.The screenshot shows the user interface for creating a new endpoint.
[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "api-gw/route-create.png",
    "alias": "api-gw-route-create",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 320,
    "y": 0,
    "w": 1600,
    "h": 450
  },
  "annotations": []
}
----

* *Endpoint* defines the path for the endpoint,
* *method* defines the HTTP method for the endpoint.

The endpoint will be accessible under `$BASE_URL/api/gateway$YOUR_ENDPOINT`.
To exemplify; the `/test-endpoint` endpoint for the `https://latest.cortezaproject.org` instance is available as `https://latest.cortezaproject.org/api/gateway/test-endpoint`.

[TIP]
====
You can specify different HTTP methods on the same route, but they need to be specified as different endpoints, ie. `*GET* /customer` and `*PUT* /customer` being two different integration gateway endpoints.
====

When you submit the forum, an additional "filter list" section opens below the base parameters.
These filters allow you to validate and process requests, as well as defining the response.

Subsequent sections explore specific filters in more depth; what they do, and how they should be used.

.The screenshot shows the user interface for attaching filters to the endpoint.
[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "api-gw/route-filters.png",
    "alias": "api-gw-route-filters",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 320,
    "y": 0,
    "w": 1600,
    "h": 1080
  },
  "focus": {
    "x": 586,
    "y": 598,
    "w": 1070,
    "h": 295
  },
  "annotations": []
}
----

== Request Validation

Request validation is done by using *prefilters*.
prefilters allow you to validate the request and determine if the given endpoint should process it.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "api-gw/route-filters.png",
    "alias": "api-gw-route-filters-prefilter",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 320,
    "y": 0,
    "w": 1600,
    "h": 1080
  },
  "focus": {
    "x": 586,
    "y": 598,
    "w": 1070,
    "h": 295
  },
  "annotations": [{
    "kind": "box-note",
    "padding": "sm",
    "x": 586,
    "y": 666,
    "w": 110,
    "h": 20
  }]
}
----

[NOTE]
====
It is currently not possible to use the built-in authentication facility to authenticate requests.
This feature will be added in the future.
====

.The list of available prefilters:
[cols="1s,5a"]
|===
| [#filters-prefilter-queryparam]#<<filters-prefilter-queryparam,Query parameters>>#
|
The query parameters prefilter allows you to define a condition which asserts if the request can be processed by this endpoint based on the query parameters.

The query parameters are passed into the expression evaluation engine as they were provided.
To exemplify; the query parameters `?param1=value1&param2=value2` would be referenced as `param1` and `param2` in the expression.

Refer to the xref:expr/index.adoc[expression] reference for details regarding to writing these expressions.

The following example checks whether the given HTTP request defines the `token` query param of `"super-secret-value"`.

.Endpoint definition:
* endpoint: `/test-query`
* method: `GET`
* query parameters prefilter expression: `token == "super-secret-value"`

.An example of an HTTP request that conforms to the filter:
[source,bash]
----
curl -X GET $BASE_URL/api/test-query?token=super-secret-value
----

.An example of an HTTP request that does not conform to the filter:
[source,bash]
----
curl -X GET $BASE_URL/api/test-query?token=some-other-value-i-guessed
----

[CAUTION]
====
Multi-word and multi-value query parameters can not be used currently.
====

| [#filters-prefilter-header]#<<filters-prefilter-header,Header>>#
|
The header prefilter allows you to define a condition which asserts whether the request can be processed by this endpoint based on the request's headers.

All system defined headers are passed into the expression evaluation engine as provided.
User-define headers will automatically be converted into the `snake-case` + `PascalCase` format.
To exemplify; `test-header` becomes `Test-Header` and `test` becomes `Test`.

The following header `test: value` would be referenced as `Test` in the expression.

Refer to the xref:expr/index.adoc[expression] reference for details regarding writing these expressions.

The following example checks if the given HTTP request defines the `Token` header of `"super-secret-value"`.

.Endpoint definition:
* endpoint: `/test-query`
* method: `GET`
* header prefilter expression: `Token == "super-secret-value"`

.An example of an HTTP request that conforms to the filter:
[source,bash]
----
curl -X GET $BASE_URL/api/test-query \
  -H 'Token: super-secret-value'
----

.An example of an HTTP request that does not conform to the filter:
[source,bash]
----
curl -X GET $BASE_URL/api/test-query \
  -H 'Token: some-other-value-i-guessed'
----

[CAUTION]
====
Multi-word and multi-value headers can not be used currently.
====

| [#filters-prefilter-profiler]#<<filters-prefilter-profiler,Profiler>>#
|
The profiler prefilter enables a specific endpoint to gather useful statistics on an incoming route, such as headers, request body, content length, and request URI.

The prefilter can be added after any `Query parameters` or `Header` prefilter in order to enable the request to go through any authentication checks that might exist on a route.

See more on adding a profiler prefilter on the xref:integrator-guide:pages/api-gw/profiler.adoc#profiler-add[profiler page].

|===

== Request Processing

Request processing is done using *processers*.
A processer defines the core business logic that the endpoint performs.
{PRODUCT_NAME} allows you to process arbitrary payloads, such as a structured JSON or a binary attachment.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "api-gw/route-filters.png",
    "alias": "api-gw-route-filters-processer",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 320,
    "y": 0,
    "w": 1600,
    "h": 1080
  },
  "focus": {
    "x": 586,
    "y": 598,
    "w": 1070,
    "h": 295
  },
  "annotations": [{
    "kind": "box-note",
    "padding": "sm",
    "x": 699,
    "y": 666,
    "w": 110,
    "h": 20
  }]
}
----

.A list of available processers:
[cols="1s,5a"]
|===
| [#filters-proc-wfexec]#<<filters-proc-wfexec,Workflow processer>>#
|
The workflow processer allows you to bind a xref:automation/workflows/index.adoc[workflow] to the endpoint.
Refer to the xref:api-gw/workflow-processing.adoc[workflow processing] page for details regarding the interaction.

| [#filters-proc-payloadproc]#<<filters-proc-payloadproc,Payload processer>>#
|
The payload processer allows you to handle the request's payload with the help of JavaScript.

Refer to the xref:api-gw/javascript-processing.adoc[] section for more details.

|===

== Response Preparation

Response preparation is done using *postfilters*.
Postfilters allow you to finalize the request lifecycle depending on the result of the processing.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "api-gw/route-filters.png",
    "alias": "api-gw-route-filters-postfilter",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 320,
    "y": 0,
    "w": 1600,
    "h": 1080
  },
  "focus": {
    "x": 586,
    "y": 598,
    "w": 1070,
    "h": 295
  },
  "annotations": [{
    "kind": "box-note",
    "padding": "sm",
    "x": 817,
    "y": 666,
    "w": 110,
    "h": 20
  }]
}
----

.A list of available postfilters:
[cols="1s,5a"]
|===
| [#filters-postfilter-redirect]#<<filters-postfilter-redirect,Redirection>>#
|
The redirect postfilter enriches the response payload with the required redirect HTTP headers.

| [#filters-postfilter-json]#<<filters-postfilter-json,Default JSON response>>#
|
The JSON response postfilter enriches the response headers with the `application/json` content type and JSON encodes the processing results.

|===

== Debugging

=== System Logs

Enable debug logging in your `.env` file.
Refer to the xref:devops-guide:references/configuration/server.adoc[DevOps guide] for details.

=== Inspecting Docker Logs

By default, {PRODUCT_NAME} logs are accessible via Docker logs.
To access these logs, you need to firstly navigate to the directory where your {PRODUCT_NAME} instance resides in.

.An example of navigating to the {PRODUCT_NAME} instance directory:
[source,bash]
----
cd /opt/deploy/{CORTEZA_INSTANCE}/
----

You can use the `docker-compose logs server` command to access the logs output by the `server`.

[TIP]
====
Refer to the `docker-compose logs` documentation for available flags.
Using `docker-compose logs -f --tail=20 server` will follow the logs (new logs will be appended at the bottom) and limit the output to last 20 logs.
====

.A truncated example of running the log command:
[source,bash]
----
docker-compose logs -f --tail=20 server

server_1  | 12:53:14.862        DEBUG   rbac    rbac/service.go:102     allow delete for corteza::compose:record/245030892240891907/245030893465497603/246932114543603715       {"bypass": [], "context": [], "common": [245030892072923139], "authenticated": [245030891334791171], "anonymous": [], "identity": 250804535289769987, "indexed": 63, "rules": 420}
----

You can also use `grep` or log filtering to show only specific logs.
Refer to the xref:devops-guide:troubleshooting/logging.adoc[DevOps guide] for details regarding logging.

.An example of using `grep` to show only debug logs:
[source,bash]
----
user@server:/opt/deploy/{CORTEZA_INSTANCE}/$ docker-compose logs -f --tail=20 server | grep DEBUG
server_1  | 13:52:29.636        DEBUG   rbac    rbac/service.go:102     allow triggers.manage for corteza::automation:workflow/248229091554160643
Last updated 2021-09-27 18:01:45 +0200
Some content has been disabled in this document
----
