include::ROOT:partial$variables.adoc[]

= Route Profiler
:keywords: integration gateway performance, integration gateway profiling, profiling, performance
:description: Learn how to profile your integration gateway endpoints for debugging and analytics

The *Integration gateway route profiler* simplifies the development and troubleshooting process by allowing you to inspect particular requests in a detailed manner.
Besides development, the profiler can be used to benchmark system performance to help determine potential bottlenecks or to get the general idea of what tye system is capable of.

The profiler was designed in a way that it can be used as a development and debugging tool or as a dashboard to glance over incoming requests.

[IMPORTANT]
====
The profiling results and aggregating stats do not get persisted to the store, so any server restart will restart the profiler itself and consequently remove the gateway requests gathered earlier.
====

[TIP]
====
You can use these benchmarks to determine if you will need to perform some system scaling strategy.
====

== Enabling the Profiler

.There are two ways to use the Integration gateway profiler:
* enabled globally (xref:devops-guide:references/configuration/server.adoc#_apigw_profiler_global[`APIGW_PROFILER_GLOBAL`] `.env` variable)
* enabled specifically per-route (by using profiler prefilter)

[IMPORTANT]
====
The profiler itself is enabled by default, but the global option is disabled, so there will be no requests on the profiler page apart from those that already exist in the Integration gateway and have a profiler prefilter added and enabled.
====

[#profiler-add]
== Configuring The Route Profiler

In order for the profiler to include an integration gateway route, you must explicitly enable it by configuring the *profiler* prefilter.
To add the profiler prefilter to an integration gateway endpoint click on the btn:[add filter] and select the "profiler" from the dropdown list.

[CAUTION]
====
The prefilters are applied in the same order they are defined in, meaning, the profiler applies after all other prefilters defined before it execute.
There is no filter sorting (via drag-drop functionality), so the only way for now it is to remove the other filters and create them in the fashionable order.
====

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "api-gw/profiler/prefilter-select.png",
    "alias": "api-gw-profiler-prefilter-select",
    "w": 1920,
    "h": 1080
  },
      "view": {
    "x": 289,
    "y": 1,
    "w": 1630,
    "h": 1078
  },
  "annotations": [{
    "kind": "box-note",
    "padding": "sm",
    "x": 621,
    "y": 754,
    "w": 94,
    "h": 27
  }, {
    "kind": "box-note",
    "padding": "sm",
    "x": 621,
    "y": 851,
    "w": 161,
    "h": 11
  }]
}
----

In the configuration modal window make sure the enabled option is checked and click on the btn:[save & close] button.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "api-gw/profiler/prefilter-cofigure.png",
    "alias": "api-gw-profiler-prefilter-cofigure",
    "w": 1920,
    "h": 1080
  },
    "view": {},
    "focus": {
    "x": 600,
    "y": 26,
    "w": 720,
    "h": 160
  }
}
----

When the profiler prefilter is added you will see a new *requests list* at the bottom of the page.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "api-gw/profiler/preflter-added.png",
    "alias": "api-gw-profiler-preflter-added",
    "w": 1920,
    "h": 1080
  },
  "view": {},
    "focus": {
    "x": 598,
    "y": 578,
    "w": 1000,
    "h": 490
  },
  "annotations": [{
    "kind": "box",
    "x": 598,
    "y": 885,
    "w": 1000,
    "h": 182
  }]
}
----

[#profile-specific]
== Profiling Specific Routes

To profile a specific route open up the route and scroll to the bottom of the page.
The requests list shows all HTTP requests for the particular integration gateway route which ocurred *after* the profiler prefilter has been added.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "api-gw/profiler/route-profiler.png",
    "alias": "api-gw-profiler-route-profiler",
    "w": 1920,
    "h": 1080
  },
  "view": {},
    "focus": {
    "x": 598,
    "y": 418,
    "w": 1000,
    "h": 648
  }
}
----

To inspect the details of a particular request, click on the btn:[edit] icon at the end of the request entry.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "api-gw/profiler/route-profiler.png",
    "alias": "api-gw-profiler-route-profiler-details-open",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "focus": {
    "x": 599,
    "y": 419,
    "w": 997,
    "h": 647
  },
  "annotations": [{
    "kind": "box-note",
    "x": 1572,
    "y": 583,
    "w": 13,
    "h": 13
  }]
}
----

At the very top of the page you see the *general information*, such as the request ID, HTTP method, response status code, and duration.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "api-gw/profiler/request-details-top.png",
    "alias": "api-gw-profiler-request-details-top-general",
    "w": 1920,
    "h": 1080
  },
  "view": {},
    "focus": {
    "x": 599,
    "y": 73,
    "w": 998,
    "h": 448
  }
}
----

Next up is the list of *request headers* provided with with the HTTP request.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "api-gw/profiler/request-details-bottom.png",
    "alias": "api-gw-profiler-request-details-bottom-headers",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "focus": {
    "x": 599,
    "y": 410,
    "w": 999,
    "h": 230
  }
}
----

Lastly the raw *request payload* provided with the HTTP request.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "api-gw/profiler/request-details-bottom.png",
    "alias": "api-gw-profiler-request-details-bottom-body",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "focus": {
    "x": 598,
    "y": 653,
    "w": 999,
    "h": 414
  }
}
----

== Profiling the System

To see general system performance we offer a system-wide profiler view.
Navigate to menu:system[integration gateway] and click on the btn:[profiler] button in the top right corner.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "api-gw/profiler/route-list.png",
    "alias": "api-gw-profiler-route-list",
    "w": 1920,
    "h": 1080
  },
   "view": {},
   "focus": {
    "x": 605,
    "y": 293,
    "w": 999,
    "h": 774
  },
  "annotations": [{
    "kind": "box-note",
    "x": 735,
    "y": 361,
    "w": 79,
    "h": 37
  }]
}
----

A new screen appears showing you all registered integration gateway routes (only routes with a *profiler prefilter* are displayed) along with their statistics such as average request times and payload size.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "api-gw/profiler/profiler-general.png",
    "alias": "api-gw-profiler-profiler-general",
    "w": 1920,
    "h": 1080
  },
    "view": {
    "x": 289,
    "y": 1,
    "w": 1630,
    "h": 520
  }
}
----

To inspect requests for a particular route, either click on the btn:[edit] icon next to the integration gateway route or follow the instructions <<profile-specific,provided above>>.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "api-gw/profiler/profiler-general.png",
    "alias": "api-gw-profiler-profiler-general-see-specific",
    "w": 1920,
    "h": 1080
  },
    "view": {
    "x": 289,
    "y": 1,
    "w": 1630,
    "h": 520
  },
    "annotations": [{
    "x": 1578,
    "y": 274,
    "w": 13,
    "h": 13
  }]
}
----

When you inspect a particular integration gateway route, a list of all logged requests is shown.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "api-gw/profiler/profiler-general-route.png",
    "alias": "api-gw-profiler-profiler-general-route",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 320,
    "y": 0,
    "h": 830,
    "w": 1600
  }
}
----
