include::ROOT:partial$variables.adoc[]

= Workflow Processing
:attachment-path: ../../examples/api-gw/

When your integration gateway endpoint requires additional processing and the built-in processors do not suffice, you can bind a workflow to the endpoint to handle requests.

To bind a workflow to an integration gateway route, you first need to properly configure the workflow, and then bind it to the route's xref:api-gw/index.adoc#filters-proc-wfexec[workflow processor].

== Workflow Configuration

If you wish for a workflow to be executable by the integration gateway, the workflow must define a proper trigger.

.To configure your workflow:
. Create a new workflow or edit an existent workflow.
Refer to the xref:automation/workflows/index.adoc[workflow documentation] for details.
. Assure that the workflow in question defines a trigger with the resource of `System` and an event of `onManual`.

=== Reading a Request Body via Function

The way the http.Request is wrapped allows us to use it in the JS environment processing function (see more at xref:api-gw/index.adoc[JavaScript processing]) or the function designed specifically for request body content fetching.

.The screenshot shows the base workflow definition via read request body function.
[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "api-gw/wf-request-read-fn.png",
    "alias": "wf-request-read-fn",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "annotations": []
}
----

Find the link:{attachment-path}/wf-request-read-fn.json[workflow] for this example in the hyperlink.

=== Reading a Request Body via JS

.The screenshot shows the base workflow definition via JS function.
[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "api-gw/wf-request-read-js.png",
    "alias": "wf-request-read-js",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "annotations": []
}
----

Find the link:{attachment-path}/wf-request-read-js.json[workflow] for this example in the hyperlink.

.The input Javascript source can be as simple as:
[source,javascript]
----
try {
    return JSON.parse(readRequestBody(input));
} catch (e) {
    return 'could not parse request body: ' + e.message
}
----

.The body that is read could also be used as a `string` and later parsed in the subsequent workflow steps:
[source,javascript]
----
try {
    return readRequestBody(input);
} catch (e) {
    return 'could not read request body: ' + e.message
}
----

== Integration Gateway Route Configuration

.To bind a workflow to the integration gateway endpoint:
. Create a new integration gateway endpoint or edit an existing endpoint.
Refer to the xref:api-gw/index.adoc[integration gateway documentation] for details.
. Add a xref:api-gw/index.adoc#filters-proc-wfexec[workflow processor] to the endpoint.
. Select the workflow you wish to bind from the dropdown in the modal window.
. Confirm the selection and press on the btn:[save] button to update the endpoint.

.The screenshot shows the route configuration with workflow processer added.
[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "api-gw/route-wf.png",
    "alias": "route-wf",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "annotations": []
}
----

.The screenshot shows the workflow processer configuration.
[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "api-gw/route-wf-modal.png",
    "alias": "route-wf-modal",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "annotations": []
}
----

== Testing

To test if the integration gateway route and the workflow are properly interacting, initiate an HTTP request using Postman or any other tool such as cURL.

Refer to the xref:api-gw/index.adoc#apigw-proc-js-example[curl examples] for details.
