include::partial$variables.adoc[]

= {PRODUCT_NAME}
:description: {PRODUCT_NAME} is an open-source, self-hosted Low-Code Development Platform.
:keywords: {PRODUCT_NAME}, documentation, open-source, self-hosted, low-code platform

{PRODUCT_NAME} is an open-source, self-hosted Low-Code Development Platform built upon modern technologies.
{PRODUCT_NAME} is secure with a powerful access control system, allowing fine-grained permission definition.

{PRODUCT_NAME} aims to be *indisputably trustworthy* in its motivations and its approach to design, development and maintenance of the platform.
Organisations should feel that their chosen digital work platform is always *under their control*, always *protected* and continuously *developed in their best interests*.

[NOTE]
====
Questions?
Check out https://{DOMAIN}[our homepage] or https://forum.{DOMAIN}[get in touch with us].
====

== Installing {PRODUCT_NAME}

[WARNING]
====
include::devops-guide:partial$warnings/sqlite.adoc[]
====

The xref:devops-guide:index.adoc[] takes you through the installation process for xref:devops-guide:index.adoc#deploy-offline[demo/development environments] and xref:devops-guide:index.adoc#deploy-online[production-like environments].

The DevOps guide also provides some miscellaneous bits, such as xref:devops-guide:references/configuration/server.adoc[system] and xref:devops-guide:references/configuration/corredor.adoc[{APP_AUTOMATION}] configuration references, additional xref:devops-guide:examples/deploy-offline/index.adoc[offline deployment examples], xref:devops-guide:examples/deploy-online/index.adoc[online deployment examples], xref:devops-guide:maintenance/backups.adoc[data backups], and xref:devops-guide:troubleshooting/index.adoc[troubleshooting].

[NOTE]
====
Out of the box we support any system that can run Docker.
If you wish to deploy {PRODUCT_NAME} elsewhere (for example, bare metal) you will need to compile your own binaries.

*DevNote* add some documentation regarding source compiling.
====

// == Learning {PRODUCT_NAME}

// The xref:end-user-guide:index.adoc[] covers *all {PRODUCT_NAME} applications*, their *features*, and *how to use* them.
// We've designed the application end-user guide to be easily understandable by non-techy people, so you don't need to be a field expert.

// .Here are a few shortcuts:
// * xref:end-user-guide:crm/index.adoc[]
// * xref:end-user-guide:case-management/index.adoc[]
// * xref:end-user-guide:shell/index.adoc[]

== Create with {PRODUCT_NAME}

The xref:integrator-guide:index.adoc[] walks you *through the integration process*; from xref:integrator-guide:security-model/index.adoc[] system to xref:integrator-guide:compose-configuration/index.adoc[], xref:integrator-guide:automation/index.adoc[], xref:integrator-guide:reporting/index.adoc[], and xref:integrator-guide:api-gw/index.adoc[].

The Low-Code platform developer guide also covers xref:integrator-guide:authentication/index.adoc[] and xref:integrator-guide:security-model/index.adoc[]

There are also a bunch of copy-pastable examples, and miscellaneous bits such as xref:integrator-guide:automation/automation-scripts/deploying.adoc[], xref:integrator-guide:automation/automation-scripts/debugging.adoc[automation script debugging] and tips for xref:integrator-guide:accessing-corteza/index.adoc[].

// == Core developers

// Hi -- xref:developer-guide:index.adoc[]

// [NOTE]
// ====
// The platform developer guide should provide enough abstract overview to help you get started.
// The guide is fairly... !complete so feel free to get in touch with us if you're stuck.
// ====

// *DevNode* link the new messaging platform

== Upgrading {PRODUCT_NAME}

[IMPORTANT]
====
When upgrading, you should always firstly go over the xref:ROOT:changelog/index.adoc[] and the xref:upgrade-guide:index.adoc[].

Versions may *not be backwards compatible* and may need some additional work to get setup.
====

To upgrade from `2021.3`, you can use xref:ROOT:changelog/202109/index.adoc[this changelog] and xref:upgrade-guide:index.adoc[this upgrade guide].

You can find all of the changelogs xref:ROOT:changelog/index.adoc[here], and all of the upgrade guides xref:upgrade-guide:index.adoc[here].
