include::../variables.adoc[]

[#gitrepos]
= {PRODUCT_NAME} Git repositories

== Versioning

Product repositories follow https://calver.org/[calendar versioning] and produces release at the end of each session:

- March release (`YYYY.3` or `YY.3`) in 2nd half of March,
- June release (`YYYY.6` or `YY.6`) in 2nd half of June,
- September release (`YYYY.9` or `YY.9`) in 2nd half of September,
- December release (`YYYY.12` or `YY.12`) in 2nd half of December.

.List of product repositories that follow versioning
- {GIT_REPO_LINK_PREFIX}-server[{GIT_REPO_PREFIX}-server]
- {GIT_REPO_LINK_PREFIX}-server-corredor[{GIT_REPO_PREFIX}-server-corredor]
- {GIT_REPO_LINK_PREFIX}-webapp-admin[{GIT_REPO_PREFIX}-webapp-admin]
- {GIT_REPO_LINK_PREFIX}-webapp-compose[{GIT_REPO_PREFIX}-webapp-compose]
- {GIT_REPO_LINK_PREFIX}-webapp-one[{GIT_REPO_PREFIX}-webapp-one]

[#gitbranchs]
== Development and version branches

Product repositories that follow calendar versioning do not have or use common branches (`main`, `master`, `development`)
Instead, we use version branch that holds all changes that are scheduled for a particular release.

For release, scheduled on March 21st 2021, we use `2021.3.x` branch.
These branches are permanent and are used for backporting stability and security patches to older releases.

Branch for next release is opened in the release month (so in December 2019 we already have `2020.3.x`).
Branch for the next release should be then rebased on the branch of the previous release up to the date of the release of the previous branch.

Please mind the trailing zero.

[#gittags]
== Version Tags

Commits in version xref:gitbranchs[branches] are tagged with version tag: `2020.3.0`, `2020.3.0-rc.1`, `2020.3.3`.


[#gitfeatbranchs]
== Feature branches

Development of features can be in versioned (`2021.3.x-feature-foo`) or bare feature branches (`feature-foo`).
Bare feature branches can be used for features without scheduled delivery date.

== Build pipelines

All build pipelines are configured to trigger release builds on tags push.
This means whenever a new tag appears that matches `^20\d{2}\.(3|6|9|12)\..+` pattern a release is build tagged the same version.

