= Prefilter
Provides a way to filter data based on the provided expression or configuration. Based on the selected mode(indicated by the filter icon next to the row) of the prefilter, you can pass in expressions of different complexity for each row.

== Default mode
If you wish to write a simple prefilter you should use the default mode.

First you select the column you wish to filter by, then the operator that will evaluate the expression and last you input the value you wish to evaluate by.
Based on the column type, different operators can be used.

image:reporter/prefilter-default.svg[]

== Expression mode
Although this mode can also perform the tasks of the default mode, it is usually used when you can't achieve the desired filter with the default mode.

You must provide a valid expression that will be evaluated. A list of functions that can be used is found xref:reporter/expr-reference.adoc[here]

.Examples(`Foo` is the name of a column):
* `Foo >= 10`
* `Foo = 'Bar'`

[IMPORTANT]
====
To reference a field, use the field name and not its label.
====

image:reporter/prefilter-expression.svg[]