include::ROOT:partial$variables.adoc[]
include::ROOT:partial$icons.adoc[]

= {PRODUCT_NAME} {APP_NAME_DISCOVERY}
:keywords: discovery, search, record searcher, record searching, resource searcher, resource searching, data discovery
:description: Learn how to configure and use {PRODUCT_NAME} {APP_NAME_DISCOVERY}, a powerful search engine for your data

{PRODUCT_NAME} {APP_NAME_DISCOVERY} provides a powerful search engine to interact with your data.
{PRODUCT_NAME} {APP_NAME_DISCOVERY} defines an intuitive interface to search and, in some cases, visualize the data such as geographical metadata.

Refer to the xref:devops-guide:discovery/index.adoc[menu:DevOps Guide[{PRODUCT_NAME} {APP_NAME_DISCOVERY}]] to learn how to configure the systems.

To access {PRODUCT_NAME} {APP_NAME_DISCOVERY}, navigate to your {PRODUCT_NAME} instance and click on the {APP_NAME_DISCOVERY} application.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "app-selector-discovery.png",
    "alias": "discovery-app-selector",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "focus": {
    "x": 1095,
    "y": 477,
    "w": 278,
    "h": 228
  },
  "annotations": []
}
----

In the {PRODUCT_NAME} {APP_NAME_DISCOVERY} application you are presented with an intuitive user interface where the *general filters* are available on the left side of the screen, a *search box* on the top, and the *search results* just below the search box.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "discovery/search-results.png",
    "alias": "discovery-search-results",
    "w": 1920,
    "h": 1080
  },
  "annotations": []
}
----

== Advanced Querying

To find exactly what you're looking for, apply a general filter.
It is located on the left side of the screen.
Click on the checkbox next to a filter to apply it to the search results.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "discovery/search-results.png",
    "alias": "discovery-search-filtering",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "focus": {
    "x": 0,
    "y": 64,
    "w": 312,
    "h": 320
  }
}
----

You can insert a search query in the input box on the top of the screen to filter over the remaining search results.
The querying tries to find the best results based on the available data and the search term you've provided.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "discovery/search-results.png",
    "alias": "discovery-search-querying",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "focus": {
    "x": 325,
    "y": 0,
    "w": 1600,
    "h": 1080
  }
}
----

=== Visualizing a Geographical Location

If a search result defines a geographical location, it can be visualized on a map.
To visualize search results on a map, click on *{ICON_DISCOVERY_MAP} Show Map* in the top-right corner.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "discovery/search-results.png",
    "alias": "discovery-search-map",
    "w": 1920,
    "h": 1080
  },
  "view": {},
  "focus": {
    "x": 1677,
    "y": 104,
    "w": 133,
    "h": 45
  },
  "annotations": []
}
----

Mappable search results are represented as markers on the map; search results that can not be mapped are omitted from the map but still preserved in search results.
Click on a marker to highlight the corresponding search result in the results list, or hover over a result to see the location on the map.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "discovery/search-results-mapped.png",
    "alias": "discovery-search-results-mapped",
    "w": 1920,
    "h": 1080
  },
  "view": {}
}
----

[#index-configuration]
== Indexing Configuration

[#data-visibility]
=== Data Visibility

*Data visibility* defines *what is indexed* and is controlled by the standard *access control facility*.
The {APP_NAME_DISCOVERY} indexes everything it currently has access to.

To control data visibility, configure *access control rules* for the role you've defined in the xref:devops-guide:examples/deploy-online/multi-discovery-pgsql.adoc[discovery configuration].

Refer to the xref:integrator-guide:discovery/examples/limit-namespace.adoc[example] where the indexer is limited to only show records from a specified namespace.

=== Discovery Settings

[IMPORTANT]
====
Currently, the discovery settings applies to indexer's access to specific fields.
To control entire rows, use <<data-visibility,data visibility>>.
====

Click on the *{ICON_DISCOVERY_ICON} Discovery Settings*  button on the module configuration page to specify which fields to index.

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "discovery/module-discovery.png",
    "alias": "discovery-module-discovery",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 414,
    "y": 60,
    "w": 1409,
    "h": 810
  },
  "focus": {
    "x": 564,
    "y": 84,
    "w": 221,
    "h": 64
  },
  "annotations": []
}
----
Selected fields will be indexed and available for searching.


[IMPORTANT]
====
If no fields are selected, the indexer will index all fields it has access to, based on Data Visibility.
====

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "discovery/discovery-settings.png",
    "alias": "discovery-discovery-settings",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 450,
    "y": 60,
    "w": 950,
    "h": 600
  },
  "focus": {
    "x": 544,
    "y": 18,
    "w": 816,
    "h": 888
  },
  "annotations": []
}
----
