= DRAFT 3


= I18n date,time and number localization

Corteza provides an i18n facility to localize the user date, time and number formatting.

This is achived through ECMAScript Internationalization API, which provides language sensitive string comparison, number formatting, date time and formatting. For date and time forrmating `Intl.DateTimeFormat` format object is used and for number formatting `Intl.NumberFormat` is used.


== Integration

=== Date and time
There are three functions used for date and time formatting which can be found in `src/formatting/datetime.ts` folder in (https://github.com/cortezaproject/corteza-js) 
[source,js]
----
export function fullDateTime (input: DateTimeInput, options: DateTimeFormatOptions = { dateStyle: 'full', timeStyle: 'short' }): string {
  return format(input, options)
}

export function date (input: DateTimeInput, options: DateTimeFormatOptions = { dateStyle: 'short' }): string {
  return format(input, options)
}

export function time (input: DateTimeInput, options: DateTimeFormatOptions = { timeStyle: 'short' }): string {
  return format(input, options)
}
----
=== Number
Number uses a single formatting function which can be found in `src/formatting/number.ts` folder in (https://github.com/cortezaproject/corteza-js) 
[source,js]
----
export function number (input: number, options: Intl.NumberFormatOptions = {}): string {
  return new Intl.NumberFormat(currentLanguage(), options).format(input)
}
----

== Usage

Import formatter `fmt` object from '@cortezaproject/corteza-js library
[source,js]
----
import { fmt } from '@cortezaproject/corteza-js'
----

Use the format date and time functions to format your date and time variables

[source,js]
----
fmt.fullDateTime(sampleDate, optionalDateTimeFormat)
fmt.date(sampleDate, optionalDateTimeFormat)
fmt.time(sampleTime, optionalDateTimeFormat)
----


=== Modify localization

Changing the default localization  can be done in two ways 

** By changing the language in your `browser settings` Corteza will `automatically` change it’s date and time formatting and display it according to your local settings

** Add desired language to the current language function
[source,js]
----
export function currentLanguage (): string|string[] {
  return ['en-US']
}
----

=== Modify formatting

Passing an Intl.DateTimeFormat format objects as a parameter will override default formatting
For example:
[source,js]
----
fmt.fullDateTime(sampleDate, {
        day: "numeric",
        month: "numeric",
        year: "numeric",
        hour: "numeric",
        minute: "numeric",
      })
----
will display all date parameters as numbers
`9/21/2021, 10:53 PM` ("en-US")

=== Custom date and time formatting with Intl.DateTimeFormat

dateStyle

* "full"
* "long"
* "medium"
* "short"

timeStyle

* "full"
* "long"
* "medium"
* "short"

year

* "numeric" (e.g., 2012)
* "2-digit" (e.g., 12)

month

* "numeric" (e.g., 2)
* "2-digit" (e.g., 02)
* "long" (e.g., March)
* "short" (e.g., Mar)
* "narrow" (e.g., M)

day

* "numeric" (e.g., 1)
* "2-digit" (e.g., 01)

minute

* "numeric" 
* "2-digit"

second

* "numeric" 
* "2-digit"