include::ROOT:partial$variables.adoc[]

= `2024.9.7`

*Released on*: `2026.01.14`

.[#2024_09_07-added]#<<2024_09_07-added,Added:>>#
* Added ability to assign namespaces and modules as workflow labels for filtering
({CORTEZA_COMMIT_BASE}57f3983[`57f3983`]).
* Added experimental record drafts feature
({CORTEZA_COMMIT_BASE}6ceafa0[`6ceafa0`]).
* Added option to resolve record references during export
({CORTEZA_COMMIT_BASE}271f8d7[`271f8d7`], {CORTEZA_COMMIT_BASE}b4b42e2[`b4b42e2`]).
* Added step option to number fields
({CORTEZA_COMMIT_BASE}ffa1de9[`ffa1de9`]).
* Added automatic comment input focus when replying
({CORTEZA_COMMIT_BASE}03c1ad3[`03c1ad3`]).
* Added sorting to record revisions
({CORTEZA_COMMIT_BASE}5c2aa28[`5c2aa28`]).
* Added multi-field support for record list parent field options
({CORTEZA_COMMIT_BASE}31de4b7[`31de4b7`]).
* Added ability to mark notifications as unread
({CORTEZA_COMMIT_BASE}f07042f[`f07042f`]).
* Added attachments to comments block
({CORTEZA_COMMIT_BASE}358d7a9[`358d7a9`]).
* Added setting for which fields will be searchable in record list
({CORTEZA_COMMIT_BASE}dd8e7a2[`dd8e7a2`]).
* Added option to hide delete button in record lists
({CORTEZA_COMMIT_BASE}8be2627[`8be2627`]).
* Added option to make record list record click do nothing
({CORTEZA_COMMIT_BASE}3e3db08[`3e3db08`]).

.[#2024_09_07-changed]#<<2024_09_07-changed,Changed:>>#
* Changed improved workflow canvas with scrollability and middle-mouse pan support
({CORTEZA_COMMIT_BASE}3d4e077[`3d4e077`]).
* Changed stay on the same record list page after bulk editing when using full-page navigation
({CORTEZA_COMMIT_BASE}5791c24[`5791c24`]).
* Changed OIDC authentication response to include the sub claim
({CORTEZA_COMMIT_BASE}65da683[`65da683`]).
* Changed all shadows to black no matter the theme
({CORTEZA_COMMIT_BASE}224e675[`224e675`]).

.[#2024_09_07-fixed]#<<2024_09_07-fixed,Fixed:>>#
* Fixed inline record editor not refreshing when adding a new record during creation
({CORTEZA_COMMIT_BASE}4978ae1[`4978ae1`]).
* Fixed authentication handler methods to apply settings updates without requiring a server restart
({CORTEZA_COMMIT_BASE}5e128e6[`5e128e6`]).
* Fixed NULL filtering for multi-value record list filters
({CORTEZA_COMMIT_BASE}7dc429d[`7dc429d`]).
* Fixed record notification modals not opening when clicked on the same page
({CORTEZA_COMMIT_BASE}84877e1[`84877e1`]).
* Fixed rendering issues in the Calendar Agenda view
({CORTEZA_COMMIT_BASE}a3a31d0[`a3a31d0`]).
* Fixed hard break handling in rich text editors which was affecting bullet and numbered list behavior
({CORTEZA_COMMIT_BASE}11c92af[`11c92af`]).
* Fixed module issues tab color not displaying correctly
({CORTEZA_COMMIT_BASE}b3ea6d2[`b3ea6d2`]).
* Fixed string to integer conversion not working correctly for workflow expression function
({CORTEZA_COMMIT_BASE}0fa1be6[`0fa1be6`]).
* Fixed precision loss for uint64 values in revision changes
({CORTEZA_COMMIT_BASE}8464083[`8464083`]).
* Fixed modal notification record not redirecting if on a different namespace
({CORTEZA_COMMIT_BASE}2d2e8f2[`2d2e8f2`]).
* Fixed primary database not displaying in admin
({CORTEZA_COMMIT_BASE}c36d716[`c36d716`]).
* Fixed unfilterable fields showing inline filter button
({CORTEZA_COMMIT_BASE}ae04730[`ae04730`]).
* Fixed file field not triggering unsaved changes
({CORTEZA_COMMIT_BASE}b26a7ba[`b26a7ba`]).
* Fixed no visual gap on automation buttons in record list
({CORTEZA_COMMIT_BASE}6f3ce3e[`6f3ce3e`]).
* Fixed issues with scrolling blocks on mobile
({CORTEZA_COMMIT_BASE}1eea6bc[`1eea6bc`]).
