include::ROOT:partial$variables.adoc[]

= Automation scripts

An automation is a piece of *JavaScript code* that implements some *business logic* and *conforms to* this interface:

[source,ts]
----
export interface Script {
  label?: string;

  description?: string;

  security?: {
    runAs?: string;
    deny: string[];
    allow: string[];
  }|string;

  triggers: Trigger[];

  exec?: ScriptFn;
}
----

[IMPORTANT]
====
One automation script per file.
====

.You can use this template for the most common operations:
[source,js]
----
include::ROOT:example$extensions/server-script-sample/implicit-generic.js[]
----

[NOTE]
====
See xref:ROOT:integrator-guide/samples/server-scripts/index.adoc[server script samples], and xref:ROOT:integrator-guide/samples/client-scripts/index.adoc[client script samples] for more.
====

There are two main categories of automation scripts; *server scripts* and *client scripts*.

[cols="1,5"]
|===
| *Server scripts*
a| These are executed in the *{PRODUCT_NAME} {APP_AUTOMATION} server*.

.Use server scripts when:
* working with *sensitive data*,
* communicating with *external APIs*,
* they *shouldn't be interruptible* by the user.

.Example use cases:
* *create additional records* based on the current data,
* *send email* notifications,
* run *statistic analysis*.

| *Client scripts*
a| These are executed in the client's browser (user agent, if you will).

.Use client scripts when:
* we need to *interact with the user*,
* we are performing *data validation*,
* *inserting* default *values*.

.Example use cases:
* *prompt the user* to confirm the form submission,
* *validate the form* submitted by the user,
* *redirect the user* after they've submitted the form,
* open an external webpage.
|===

*A rule of thumb* -- if we need to interact with the user (show notification, request confirmations), use *client scripts*.
Else, use *server scripts*.

[IMPORTANT]
====
Treat client scripts as *less secure* (you can freely inspect their contents from the browser) and *less reliable* (a user can manually terminate their execution -- closes the page).
====
