include::ROOT:partial$variables.adoc[]

= Modifying built-in scripts

== Modify built-in scripts

If you wish to modify an automation script that is defined by some other extension (such as CRM scripts) you have two options.

=== Create a modified copy

.To modify the extension:
. copy the extension source (*clone* the repository, or *copy* the files),
. modify the source as you see fit,
. deploy your version instead of the original version.

=== Overwrite the scripts

{APP_AUTOMATION} assigns unique names to each automation script.
The name is generated from the file path.

.For example:
[source,bash]
----
# The CRM extension
/ server-scripts
  / crm
    / Lead
      / SetLabel.js
----

The `SetLabel.js` script script is assigned `/server-scripts/crm/Lead/SetLabel.js:default` as the name.

To overwrite the `SetLabel.js` script, you must define a script that will be assigned the same name (essentially has the same path).

.For example:
[source,bash]
----
# The CRM extension
/ package.json
/ node_modules
/ server-scripts
  / crm
    / Lead
      / SetLabel.js # 👈 We're targeting this one
      / AnotherScript.js

# Your extension
/ package.json
/ node_modules
/ server-scripts
  # To overwrite something in the CRM extension
  / crm
    / Lead
      / SetLabel.js # 👈 This version will replace the CRM version

  # The rest of your code goes here
  / extension
    / Lead
      / SomeScript.js
----

[IMPORTANT]
====
For this to work, you must make sure that your extension is *included after* the extension you wish to modify.

.For example:
[source,.env]
----
# This will NOT work; the CRM is included after
CORREDOR_EXT_SEARCH_PATHS="/your-ext:/crm"

# This will work; the CRM is included before
CORREDOR_EXT_SEARCH_PATHS="/crm:/your-ext"
----
====
