include::../../variables.adoc[]

= Channels

A channel contains a set of users and their messages, usually tied to a specific topic, such as project management or sales.

{PRODUCT_NAME} {APP_NAME_MESSAGING} defines three channel types:

* Public channels,
* private channels,
* direct channels,

== Public channels

These channels are visible to all {PRODUCT_NAME} {APP_NAME_MESSAGING} users with correct access rights.
Since they are public they shouldn't contain any sensitive information that could be abused if leaked,

=== Creating public channels

To create a public channel, click on the "+" icon to the right of the "Public channels" in the navigation side panel.
This opens a new interface where you can define:

* **Name**: specifies the channel name, such as Sales or Directors,
* **topic**: specifies the channel topic to give some more insight into what the conversation is about,
* **privacy**: specifies if the channel is private or not,
* **featuring**: when a channel is featured, any user is automatically it's member.
This can be useful when making an introduction channel, such as a Welcome or General channel,
* **members**: specifies the members that should be included immediately.

=== Public channel management

After a channel is created there are a lot of little things that can be performed.
Open the channel by clicking on it, and hover over the three dots on the top right corner of the channel.
The main two options are:

* **Member list**: provides the current list of members in the given channel.
It also provides an interface to add and remove additional members,
* **Edit channel**: opens a channel editor interface.
The interface allows you to edit:
** **Name**: specifies the channel name, such as Sales or Directors,
** **topic**: specifies the channel topic to give some more insight into what the conversation is about,
** **privacy**: specifies if the channel is private or not,
** **featuring**: when a channel is featured, any user is automatically it's member.
This can be useful when making an introduction channel, such as a Welcome or General channel,
** **members**: specifies the channel members,
** **channel actions**: allow you to archive or delete the channel.

== Private channels

These channels are visible only to it's members.
Since they are private they could contain some sensitive information,

=== Creating private channels

To create a private channel, click on the "+" icon to the right of the "Private channels" in the navigation side panel.
This opens a new interface where you can define:

* **Name**: specifies the channel name, such as Sales or Directors,
* **topic**: specifies the channel topic to give some more insight into what the conversation is about,
* **privacy**: specifies if the channel is private or not,
* **featuring**: when a channel is featured, any user is automatically it's member.
This can be useful when making an introduction channel, such as a Welcome or General channel,
* **members**: specifies the members that should be included immediately.

[NOTE]
====
Private channels can also be created from public channels, by changing the privacy option.
====

=== Private channel management

After a channel is created there are a lot of little things that can be performed.
Open the channel by clicking on it, and hover over the three dots on the top right corner of the channel.
The main two options are:

* **Member list**: provides the current list of members in the given channel.
It also provides an interface to add and remove additional members,
* **Edit channel**: opens a channel editor interface.
The interface allows you to edit:
** **Name**: specifies the channel name, such as Sales or Directors,
** **topic**: specifies the channel topic to give some more insight into what the conversation is about,
** **privacy**: specifies if the channel is private or not,
** **featuring**: when a channel is featured, any user is automatically it's member.
This can be useful when making an introduction channel, such as a Welcome or General channel,
** **members**: specifies the channel members,
** **channel actions**: allow you to archive or delete the channel.

== Direct channels

These channels are similar to private channels, since they can not be accessed unless a member, but are designed for smaller number of people, such as a one on one conversations.

=== Creating direct channels

To create a direct channel, click on the "+" icon to the right of the "Direct channels" in the navigation side panel.
This opens a new interface where you can define:

* **Featuring**: when a channel is featured, any user is automatically it's member.
This can be useful when making an introduction channel, such as a Welcome or General channel,
* **members**: specifies the direct channel members.

[IMPORTANT]
====
After a direct channel is created, you can not manage it's users, so make sure that all users are included before creating it.
====

[TIP]
====
When you click on a mentioned user inside a message, it will automatically open a direct channel with that user.
====
