include::../../variables.adoc[]

[#dev-ops-guide:server-configuration]
= Server configuration

Core {PRODUCT_NAME} services are configured via the environment (`.env`) file.
It allows a quick deploy to another platform, along with fine-tuning the system's behaviour and enabled features.

[IMPORTANT]
====
The `.env` file is at the root of the application.
In the context of Docker Compose, it is next to the `docker-compose.yaml` file.
====

.The `.env` file affects three levels:
. Implicit Docker Compose configuration,
. variable substitution in Docker configuration,
. service configuration.

[NOTE]
====
When you are using Docker Compose, you must explicitly reference the environment file for each service in the `docker-compose.yaml` file (`env_file: [.env]`).
====

[TIP]
====
You can use variables defined in the `.env` inside your `docker-compose.yaml` file; for example `$\{VERSION\}`.
====

== Base configuration

These variables control the base {PRODUCT_NAME} configurations, such as the port and the database DSN.

include::env-base.adoc[]

== Security

These variables control security aspects of {PRODUCT_NAME}, such as the JWT token secret and the token lifetime.

include::env-security.adoc[]

== Provisioning

Provisioning allows you to configure a {PRODUCT_NAME} instance when deployed.
It occurs automatically after the {PRODUCT_NAME} server starts.

[IMPORTANT]
====
We recommend you to keep provisioning enabled as it simplifies version updates by updating the database and updating settings.

If you're doing local development or some debugging, you can disable this.
====

include::env-provision-base.adoc[]

=== Provision authentication settings

include::env-provision-auth.adoc[]

=== Provision OIDC providers

include::env-provision-oidc.adoc[]

=== Provision other external provider

include::env-provision-external.adoc[]

== SMTP

include::env-smtp.adoc[]

== Corredor

include::env-corredor.adoc[]

== MinIO

[NOTE]
====
The MinIO integration allows you to replace local storage with cloud storage.
When configured, `STORAGE_PATH` is not needed.
====

include::env-minio.adoc[]

== Debugging

[NOTE]
====
These parameters help in the development and testing process.
When you are deploying to production, these should be disabled to improve performance and reduce storage usage.

You should configure external services such as Sentry or ELK to keep track of logs and error reports.
====

=== Sentry

include::env-debug-sentry.adoc[]

=== Logging

include::env-debug-logging.adoc[]

== Delaying API execution

You can configure these options to defer API execution until another external (HTTP) service is up and running.

[TIP]
====
Delaying API execution can come in handy in complex setups where execution order is important.
====

include::env-wait-for.adoc[]
