include::../../variables.adoc[]

[#server-configuration]
= Server configuration

Core {PRODUCT_NAME} services are configured via the environment (`.env`) file.
It allows a quick deploy to another platform, along with fine-tuning the system's behaviour and enabled features.

[IMPORTANT]
====
The `.env` file is at the root of the application.
In the context of Docker Compose, it is next to the `docker-compose.yaml` file.
====

.The `.env` file affects three levels:
. Implicit Docker Compose configuration,
. variable substitution in Docker configuration,
. service configuration.

[NOTE]
====
When you are using Docker Compose, you must explicitly reference the environment file for each service in the `docker-compose.yaml` file (`env_file: [.env]`).
====

[TIP]
====
You can use variables defined in the `.env` inside your `docker-compose.yaml` file; for example `$\{VERSION\}`.
====

== Base configuration

These variables control the base {PRODUCT_NAME} configurations, such as the port and the database DSN.

:leveloffset: +1
include::option_env_variables_gen.adoc[]
:leveloffset: +-

== Provisioning

Provisioning allows you to configure a {PRODUCT_NAME} instance when deployed.
It occurs automatically after the {PRODUCT_NAME} server starts.

[IMPORTANT]
====
We recommend you to keep provisioning enabled as it simplifies version updates by updating the database and updating settings.

If you're doing local development or some debugging, you can disable this.
====

include::env-provision-base.adoc[]

=== Provision authentication settings

include::env-provision-auth.adoc[]

=== Provision OIDC providers

include::env-provision-oidc.adoc[]

=== Provision other external provider

include::env-provision-external.adoc[]

