include::../../variables.adoc[]

= Federated nodes

A *federated node* is a *{PRODUCT_NAME} instance* (server) with the {APP_NAME_FEDERATION} feature enabled.

A node can *expose data to it's destination* nodes (acts as an origin), or *consume shared data from it's origin* nodes (acts as a destination).

[NOTE]
====
A node can be both *the origin and a destination*.
====

Before we can exchange any data between the nodes, they need to go through the <<node-pairing,node pairing>> process.

[#node-pairing]
== Node pairing

.Node pairing flow outline:
. the origin node <<node-pairing-register,registers a destination node>>,
. the origin node <<node-pairing-invite,sends an invite>> to the destination node,
. the destination node accepts the invite, either <<node-pairing-accept-invite,via email>> or <<node-pairing-accept-invite-manual,via other channel>>,
. the origin node <<node-pairing-handshake-accept,accepts the handshake request>> sent by the destination node.

[NOTE]
====
You can start the node pairing process from any node.
====

.[#node-pairing-register]#<<node-pairing-register,Registering a new node:>>#
. navigate to the {PRODUCT_NAME} {APP_NAME_ADMIN},
. click on the "Nodes" under "Federation" in the navigation drawer,
. click on the "new" button,
. provide the requested data regarding node we wish to connect with,
. press the "Submit" button.

.[#node-pairing-invite]#<<node-pairing-invite,Send the invitation:>>#
. navigate to the {PRODUCT_NAME} {APP_NAME_ADMIN},
. click on the "Nodes" under "Federation" in the navigation drawer,
. click on the node you wish to send the invitation for,
. click on the "Generate Federation Link" button,
** either copy the invitation URL, or
** insert the contact email where the invite should be sent to.

[WARNING]
====
The generated url includes a secure OTT token, so the federation link must be sent to the other party via a secure channel.
====

.[#node-pairing-accept-invite]#<<node-pairing-accept-invite,Accept the email invitation:>>#
. click on the "Pair Federation Node" button,
. enter the received URL and confirm.

[NOTE]
====
The node pairing will not proceed until you insert the pairing URL, and the other party accepts the handshake request.
====

.[#node-pairing-accept-invite-manual]#<<node-pairing-accept-invite-manual,Accept the invitation without email:>>#
. navigate to the {PRODUCT_NAME} {APP_NAME_ADMIN},
. click on the "Nodes" under "Federation" in the navigation drawer,
. click on the ... button, // @todo
. enter the received URL and confirm.

[NOTE]
====
The node pairing will not proceed until you insert the pairing URL, and the other party accepts the handshake request.
====

.[#node-pairing-handshake-accept]#<<node-pairing-handshake-accept,Accept the node pair handshake request:>>#
. navigate to the {PRODUCT_NAME} {APP_NAME_ADMIN},
. click on the "Nodes" under "Federation" in the navigation drawer,
. click on the node you wish to accept the request for,
. click on the warning icon to confirm the request.

[NOTE]
====
This final step needs to be done on the origin server (the one that initiated the handshake).
====
