include::../../variables.adoc[]
= Channels

Channels are used to organise your conversations.
A channel is a single place to share messages and upload files.
List of available channels is located on the left sidebar of the interface.

== Channel Types

There are three different types of channels:

- Public Channels
- Private Channels
- Direct Messages

**Public channels** are open to everyone who is signed up to Messaging.
They are identified with a hashtag icon (“#”).
Click on “Browse all Channels” at the bottom of the Public Channels list or press "CTRL/CMD + K" to search the full list of Public Channels available

**Private channels** are for discussions that are limited to only selected team members.
Private Channels are identified by a lock icon.

**Direct messages** are discussions between two or more people.
There is no channel name, only the names of the individuals.
The Direct Message discussion is only visible to the people involved.Direct Messages are identified by the presence icon.
If the presence icon is block green, then all members of the Direct Message discussion are online.
If the presence icon has a green perimeter only, then only one or some of the members of the discussion are online.
If the presence icon is grey, then no-one is available in the discussion.

== Dealing with Channels

.How to create a new channel:
Click on plus icon (+) next to "Public channel", "Private channel" or "Direct messages" section titles.
Fullfill the form, add members and click on "Create" button.

.How to join a channel:
Choose a channel you want to join and click on the "Join channel" button on the very bottom (covering the messaging input).

.How to hide a channel:
Any channel can be hidden from interface by hovering the cursor over the channel name and clicking on the “x” next to the channel name.
Removing the channel from the user interface does not delete the channel for you or for any other user.
