include::../../variables.adoc[]
= Video Conference

Part of {PRODUCT_NAME} is an open-source video conferencing tool https://jitsi.org/[Jitsi].

== Starting a video call

To start a call open a new tab (instructions: <<tabs>>) and select "Jitsi video" among the available applications.

Select one of the existing channels and click on "Join" button or create a new room and click on "Create" button.

To invite other members tell them which room to join or copy a direct link to the meeting from the box in the bottom right corner.

== Sharing a screen

While you're inside Jitsi video conference screen you can select an option to share a screen on the bottom left corner (screen icon).
Select if you'd like to share the entire screen, application window or Chrome Tab only.

To stop sharing a screen click on "Stop Sharing" button on the bottom.

== Shortcuts

List of available keyboard shortcuts to use during the video conference:

- F: Show or hide video thumbnails
- M: Mute or unmute your microphone
- V: Start or stop your camera
- A: Manage call quality
- D: Switch between camera and screen sharing
- S: View or exit full screen
- Space: Push to talk
