include::../../variables.adoc[]

= Script Parsing

Script parsing process is an important bit of the system and it introduces a few gotchas that you should be aware.
Script parsing is the fist operation that is performed by the automation system in order for it to function properly.

== Script parsing flow

. determine available source files (referred as a file),
. for each file:
.. convert to an AST tree,
.. find and parse the default exported object.
If it's not found or invalid, the parsing for this file is aborted with a descriptive error,
.. parse the exported object into the `Script` object:
*** determine meta data (label, description); if provided,
*** evaluate security context; if provided,
*** evaluate triggers; if provided,
*** evaluate iterators; if provided,
*** determine exec function.

[IMPORTANT]
====
Triggers and iterators can **not** be used in the same script.
If both are provided, the iterator is given priority.
====

[IMPORTANT]
====
The core of the automation script is evaluated outside of the source file, meaning any imports and other symbols defined outside of the exported object are ignored.

This prevents the use of constants and other symbols that are defined outside of the exported object.
====
