include::../../variables.adoc[]

= Security

== Automation script execution

Automation script execution is not jailed or virtualized and it is ran in the same context as the main system; either {app_automation} in the case of server scripts or any front end application in case of client scripts.

You (or whoever is responsible for automation system) is responsible for making sure that the automation scripts are audited and written in a way that they are not harmful to the system.

It is recommended to make use of security context feature described in the following sub section, and limit the permissions each automation script can use.

== Security context

Automation scripts are no exception to {product_name} permission system, meaning that any operation performed by an automation script (such as record creation) must pass all permission checks required by the resource.

By default any manual and implicit automation triggers use the current user's permission scope for the automation scripts security context.

But there are cases where this is not sufficient and the execution requires permissions that the invoker does not have.
For such cases we can specify a custom security context that the automation script will run in.

[EXAMPLE]
====
As an example where the automation script would require elevated permissions we can define a manual automation script that creates a Lead record and a new system user.
System user creation requires administrator permissions and so, a regular user could not execute the automation script.
====

The same also applies to deferred, interval and sink automation scripts, since they are executed by the system without the need of user interaction (at least we can't be sure who exactly executed it).

[IMPORTANT]
====
Due to privacy and security concerns, security context definition is **not** available for client side scripts.
====

[TIP]
====
When using custom permission context, we strongly recommend using a system user with the minimal required set of permissions to execute the required operations.
====

== Role-based access control

Role-based access control allows us to define what user can access what automation scripts based on their permissions.

[IMPORTANT]
====
This only applies to explicit and client side automation scripts; server side scripts (except explicit) ignore this.
====
