include::ROOT:partial$variables.adoc[]


= Database Connection
 
The data access layer enables you to connect your {PRODUCT_NAME} instance to multiple datasources. 
The data sources are defened in two ways:

. Primary data source(always available and is configured during system setup).
. External Data Source (EDS).

The capability to connect to different data sources helps the business integrate information from the various connections into the business.

An example would be when a sales manager wants to include sales forecast data which is available in a spreadsheet stored on a sale's officer local machine, into the actual sales data available on the primary data source.
To make this integration, he would connect the spreadsheet as a relational data source, and the sales forecast data would be viewed along with the actual sales data available.

== Data access layer configuration.

When configuring the data access layer you need to specify the following.

* Defaulty table or container name 

This is an identifier which can contain placeholders like {{module}} (replaced with module handle) and/or {{namespace}} (replace with namespace handle). When set it is used as a default for modules.

* Connection and parameter type.

This specifies the data source connection and the parameter type to be used when creating the connection. For example it can be *corteza::dal:connection:dsn*

* Connection parameters

Connection parameters are used to specify information such as database name, database server name , and the user ID. 