include::ROOT:partial$variables.adoc[]

= Pages

A *page* lets you *interact* with your application to manage the *system* and your *data*.

Each page consists of a series of *page blocks* (blocks) that let you define pages of *arbitrary complexity* while keeping it *responsive* and *mobile friendly*.

[TIP]
====
A page can be thought of as a *view* in a relational database.
====

== Page types

{PRODUCT_NAME} defines *two page types*.
The main *difference is the context*; which the system uses.
Their definition via the <<page-builder,page builder>> *remain the same*.

Record page::
    *Record pages* are used when *viewing specific records*.
    If you wish to *interact with records*, you need to create a *record page for that module*.

List page::
    *List pages* are used when viewing aggregated data *from different sources*.
    These can be used to implement *simple record lists*, or complicated *dashboards* consisting of multiple data sources.

== Create a list page

.To create a list page:
. navigate to the {PRODUCT_NAME} {APP_NAME_COMPOSE} page and enter the namespace you wish to edit,
. click on the "Admin panel" in the top right corner,
. navigate to the "Pages" subpage,
. enter the page name and press the "Create" button,
. provide the page handle, a description and save the changes.

[IMPORTANT]
====
You can only define permissions for existing pages.
====

== Create/edit a record page

.To create a record page:
. navigate to the {PRODUCT_NAME} {APP_NAME_COMPOSE} page and enter the namespace you wish to edit,
. click on the "Admin panel" in the top right corner,
. navigate to the "Modules" subpage,
. click on the "page builder" *next to the module list*, or click on the "Record page" button on the *bottom of the module editor*.

== Edit a page

.To edit an existing page:
. navigate to the {PRODUCT_NAME} {APP_NAME_COMPOSE} page and enter the namespace you wish to edit,
. click on the "Admin panel" in the top right corner,
. navigate to the "Pages" subpage,
. click on the edit icon next to the page you wish to edit,
. update the data and save the changes.

[IMPORTANT]
====
To change the structure of your page, see the <<page-builder,page builder>> section.
====

== Delete a page

.To delete an existing page:
. navigate to the {PRODUCT_NAME} {APP_NAME_COMPOSE} page and enter the namespace you wish to delete,
. click on the "Admin panel" in the top right corner,
. navigate to the "Pages" subpage,
. click on the edit icon next to the page you wish to delete,
. press the "Delete" button on the bottom of the page and confirm the operation.

[#page-builder]
== Page builder

Each page consists of a series of *page blocks* (blocks) that let you define pages of *arbitrary complexity* while keeping it *responsive* and *mobile friendly*.

The page builder *defines a grid* spanning over *12 columns*.
Add a page block by clicking on the *"Add block"* button on the *bottom toolbar*.
The page block can be *moved and resized* on the grid mentioned above.

[IMPORTANT]
====
The grid is *not limited* in height.
====

Page blocks differ by the *type* and what *page type* they can be used on (see the <<page-blocks,page blocks>> section).

.To enter the page builder:
. navigate to the {PRODUCT_NAME} {APP_NAME_COMPOSE} page and enter the namespace you wish to edit,
. click on the "Admin panel" in the top right corner,
. navigate to the "Pages" subpage,
. click on the "Page builder" *next to the page* you wish to edit, or from the *page editor screen*.

When *finished*, click on the "Save" or the "Save and close" button on the *bottom right of the toolbar*.

*Discard* your changes by clicking on the "Back (without saving changes)" on the *bottom left of the toolbar*.

[#page-blocks]
== Page blocks

include::./page-blocks/index.adoc[]

== Navigation

You can freely define your *page hierarchy* by reordering your pages in the *page tree*.
The *page order* and the *nesting* defines the *navigation structure*.

.To change the navigation:
. navigate to the {PRODUCT_NAME} {APP_NAME_COMPOSE} page and enter the namespace you wish to edit,
. click on the "Admin panel" in the top right corner,
. navigate to the "Pages" subpage,
. drag and drop your pages to define the order; the order is *automatically updated*

[TIP]
====
Create a *subpage* (nesting), by dragging the page *into another page*.
====

== Permissions for all pages

include::ROOT:partial$permissions/compose-pages.adoc[]

== Permissions for a specific page

include::ROOT:partial$permissions/compose-page-specific.adoc[]
