include::../../variables.adoc[]

[#admin-adminpanel-system-applications]
= Applications

The applications interface can be accessed by clicking on the "Applications" navigation item on the left navigation drawer under the system item group.

The interface allows you to:

* Edit permissions regarding the applications (see <<admin-adminpanel-system-applications-perms>>),
* add new applications (see <<admin-adminpanel-system-applications-add>>),
* list applications (see <<admin-adminpanel-system-applications-list>>),
* edit applications (see <<admin-adminpanel-system-applications-edit>>).

[#admin-adminpanel-system-applications-perms]
== Managing permissions

To manage permissions related to the application resource, click on the "Permissions" button on the top right corner of the page.
You can define:

Read any application::
    Determines if the given role is allowed to access any application,

Update any application::
    Determines if the given role is allowed to update any application,

Delete any application::
    Determines if the given role is allowed to delete any application,

[#admin-adminpanel-system-applications-add]
== Adding applications

To add a new application, click on the "New" button on the top right corner of the page.

This opens a new interface where you can insert the basic information regarding the application.

* Name,
* if active.

After saving the application, a new interface is provided where you can edit the newly created application.

include::./partials/application-edit.adoc[]

[#admin-adminpanel-system-applications-list]
== Listing applications

Applications can be viewed on the table in the middle of the interface.
The system supports a powerful search engine, from partial searching, finding only active applications and so on.
It also supports pagination and sorting.
Out of the box, these applications are already configured:

* {APP_NAME_MESSAGING},
* {APP_NAME_COMPOSE},
* CRM,
* Jitsi Video,
* {PRODUCT_NAME} Admin Area,
* Google Maps.

[#admin-adminpanel-system-applications-edit]
== Editing applications

Applications can be edited by pressing on the edit icon next to each row in the role list, that opens up a new interface,

include::./partials/application-edit.adoc[]
