include::../../variables.adoc[]

= Automation

The *automation* interface provides an overview of *processed automation scripts*.

The automation interface can be used to *debug* any issues *regarding invalid* or *missing automation scripts*.

[NOTE]
====
Refer to xref:ROOT:integrator-guide/extensions/index.adoc#extension-deploy[deploying extensions] for details on *how to deploy extensions*.
====

== Listing automation scripts

.To list current automation scripts:
. navigate to the {PRODUCT_NAME} {APP_NAME_ADMIN},
. click on the "Automation" in the navigation drawer,
. optionally insert the filtering parameters.

*Invalid automation scripts* provide an *error message*.

[NOTE]
====
The list is *filter(ted automatically*.
====

== Inspecting automation scripts

.To inspect specific automation scripts:
. navigate to the {PRODUCT_NAME} {APP_NAME_ADMIN},
. click on the "Automation" in the navigation drawer,
. click on the blue button next to the label.

You can inspect the automation script *triggers*, *iterators*, and *security context*.

*Invalid automation scripts* provide an *error message*.
