include::../../variables.adoc[]

= Settings

The *settings* interface allows you to configure some *core system settings*.

[IMPORTANT]
====
There is a separate view for <<settings-system,*system*>>, <<settings-messaging,*{APP_NAME_MESSAGING}*>>, <<settings-compose,*{APP_NAME_COMPOSE}*>>, and <<settings-unify,*{APP_NAME_SHELL}*>>.
====

== System settings

Authentication::
    The *authentication* section lets you control the *authentication flow*, *email notifications*, and *where to redirect* successful logins.

Email::
    The *email* section lets you define the *system email* templates.

[IMPORTANT]
====
This does *not* affect emails sent from the {APP_NAME_COMPOSE}.
====

External authentication::
    The *external authentication* section lets you configure *what authentication providers* are available (if at all).
    See <<configure-external-auth>> for configuration details.

[TIP]
====
You can disable *internal authentication* to force your users to use *external providers*.
====

== {APP_NAME_COMPOSE}

Basic::
    *Basic system configuration* such as UI tweaks and attachment constraints (size and type).

== {APP_NAME_MESSAGING}

Basic::
    *Basic system configuration* such as UI tweaks and attachment constraints (size and type).

== {APP_NAME_SHELL}

Logo::
    The *logo* section lets you replace the default {PRODUCT_NAME} logo with your own.

Panels::
    The *panels* section lets you define the *default layout* for your users.

[#configure-external-auth]
== Configuring external providers

=== Google

.To enable Google authentication, you need to create a client ID:
. Go to https://developers.google.com/identity/sign-in/web/sign-in#before_you_begin[Google Sign-in Guide] and click on "Configure a project" button.
. Select an existing project or create a new one.
. Set a product name; for example, {PRODUCT_NAME}.
. On "Configure your OAuth client" screen select "Web browser" and paste the URL where your {PRODUCT_NAME} system is running (including `https://`).
. Copy and paste both Client ID and Client Secret fields to {PRODUCT_NAME} {APP_NAME_ADMIN}.

=== Facebook

.You need to retrieve your application credentials:
. Go to https://developers.facebook.com/apps/[Facebook for developers] website, *click on "Add a new app"* or *select an existing app*.
. In the list of available products search for "Facebook Login" and click on "Set Up" button.
. Select "Web" platform and paste the URL where your {PRODUCT_NAME} system is running.
. Go to "Settings" and then "Basic" in the left sidebar.
. Copy and paste "App ID" to "Client key" inside {PRODUCT_NAME} {APP_NAME_ADMIN}.
. Copy and paste "App Secret" to "Secret" inside {PRODUCT_NAME} {APP_NAME_ADMIN}.

=== Github

.You need to retrieve your application credentials:
. Go to https://github.com/settings/applications/new[GitHub] and create a new OAuth application.
. Copy and paste both Client ID and Client Secret fields to {PRODUCT_NAME} {APP_NAME_ADMIN}.

=== LinkedIn

.You need to retrieve your application credentials:
. Go to https://www.linkedin.com/developers/apps/new[LinkedIn], fill out the form and click on "Create app".
. Go to Auth section and copy and paste both the Client ID and Client Secret fields to {PRODUCT_NAME} {APP_NAME_ADMIN}.
