include::../../variables.adoc[]

[#admin-panel-user]
= Users

[NOTE]
====
The users interface can be accessed by clicking on the "Users" navigation item on the left navigation drawer under the system item group.
====

**A user** is someone who can log in to the {PRODUCT_NAME} system.

Each user has Email, Full name and Nickname (handle).
Additionally, each user has a username (=email) and password to enable them to log in to the system (referred as credentials).

The interface allows you to:

* Edit permissions regarding the user resource (see <<admin-panel-user-permissions>>),
* add new users (see <<admin-panel-user-add>>),
* list system users (see <<admin-panel-user-list>>),
* edit users (see <<admin-panel-user-edit>>).

[#admin-panel-user-permissions]
== Managing permissions

To manage permissions related to the user resource, click on the "Permissions" button on the top right corner of the page.
You can define:

Read any user::
    Determines if the given role is allowed to access information of any user,
Update any user::
    Determines if the given role is allowed to update the information of any user,
Delete any user::
    Determines if the given role is allowed to delete any user,
Suspend any user::
    Determines if the given role is allowed to suspend any user,
Unsuspend any user::
    Determines if the given role is allowed to unsuspend any user,
Show email details for any user::
    Determines if the given role is allowed to see the email corresponding to any user,
Show name details for any user::
    Determines if the given role is allowed to see the name corresponding to any user,

[TIP]
====
The ability to manage the visibility of emails and names was introduced with the user masking privacy feature.
It allows a specific role to know about other users but they can't necessarily know of their private information.
====

[#admin-panel-user-add]
== Adding users

To add a new user, click on the "New" button on the top right corner of the page.

This opens a new interface where you can insert the basic information regarding the user.

* Email address,
* full name,
* handle (sort of like a nickname).

After saving the user, a new interface is provided where you can edit the newly created user.

include::./partials/user-edit.adoc[]

[#admin-panel-user-list]
== Listing users

Users can be viewed on the table in the middle of the interface.
The system supports a powerful search engine, from partial searching, finding only non-suspended users and so on.
It also supports pagination and sorting.

[#admin-panel-user-edit]
== Editing users

Users can be edited by pressing on the edit icon next to each row in the user list, that opens up a new interface.

include::./partials/user-edit.adoc[]
