include::ROOT:partial$variables.adoc[]

= Structure

== `/tools`

The `/tools` directory contains tools that automate some tasks, such as the API client code generator.
You should include a script to run the tool in the `/package.json` file.

== `/src/api-clients`

The `/src/api-clients` directory contains the generated REST API clients.
The API clients are generated by the `/tools/codegen` tool based on the definitions of the `corteza-server/***/rest.yaml` files.

Each API client should be provided as a separate class so that it can be on its own.

The codegen is run with the `yarn codegen:corteza-api-client` command.

== `/src/automation`

The `/src/automation` directory contains common code for the automation, such as type definitions.

== `/src/compose`

The `/src/compose` directory contains common code for compose, such as type definitions.

== `/src/corredor`

The `/src/corredor` directory contains common code for the Corredor, such as type definitions, script parsing utilities, and Corredor helper classes.

== `/src/corredor/helpers`

The `/src/corredor/helpers` directory contains the {APP_AUTOMATION} helper classes.
The helper classes implement common automation operations such as creating and updating records.

== `/src/eventbus`

The `/src/eventbus` directory contains the client-side implementation of the event bus.
The event bus handles and reacts to dispatched events.

== `/src/system`

The `/src/system` directory contains common code for the core system, such as type definitions.
