include::ROOT:partial$variables.adoc[]

= Upgrading to 2020.3
:page-aliases: upgrade-guide:202003.adoc

== After upgrade

=== {APP_AUTOMATION} scripts

{PRODUCT_NAME} 2020.3 introduces a new way of how automation scripts are stored, handled and executed.
The code, configuration and triggers are no longer stored in the {PRODUCT_NAME} database, but are defined as JavaScript files on the filesystem and accessed directly by the {PRODUCT_NAME} {APP_AUTOMATION} server.

All pre-installed scripts for the CRM and ServiceCloud have already been migrated and are ready for use.

[IMPORTANT]
====
You will need to migrate any custom automation scripts manually.
====

There are 2 available `script-migrator` commands, one for system other one for {APP_NAME_COMPOSE} service:

[source,subs="attributes"]
----
{CLI_CMD_SYSTEM} script-migrator --dst <base-location>
{CLI_CMD_COMPOSE} script-migrator --dst <base-location>
----

These two commands will create a simple structure under `<base-location>/<service>/custom`
(`system/custom/` and `compose/custom/`) containing scripts from both services.

[CAUTION]
====
The script migrator tool directly exports the script's source code and triggers without running any checks or tests.
Make sure you test each script and trigger after the migration.
====

Point script-migrator tool (base-location) to Corredor's `usr/server` directory.
This will create script source files (javascript) directly to the recommended location.

Script files names are created from the script names (with suffixing script ID in case of any duplicated).
Migrator skips all deleted scripts, deleted triggers, scripts with "test" name or without any code.

[NOTE]
====
If possible, module handle is used where a module is referenced (in Compose scripts).
====
