include::ROOT:partial$variables.adoc[]

= Upgrading {PRODUCT_NAME}
:page-aliases: 2024.9@upgrade-guide:index.adoc

This guide helps you upgrade your {PRODUCT_NAME} to the newest version in no time!

[IMPORTANT]
====
While there are internal safeguards in place that can prevent data loss or other kinds of disasters, make sure you backup your database before you upgrade.
Refer to xref:devops-guide:maintenance/backups.adoc[devops guide on backup procedure] for details.
====

[IMPORTANT]
====
If you are upgrading multiple versions at the same time; for example from 2019.12 to 2020.9; you should follow all the upgrade guides between the two versions.
====

== Recommended Steps for {PRODUCT_NAME} Upgrade

.Especially before any major version upgrade, it is recommended that before upgrading your production you either:
- upgrade your staging environment, or
- deploy a temporary environment with a copy of the production database and perform a test upgrade there.

.Steps to upgrade {PRODUCT_NAME} when deployed with *docker-compose*:
. changing image versions in your `docker-compose.yaml` (or  `.env`) file,
. pull new images from docker hub with `docker-compose pull`,
. recreate containers with `docker-compose up -d`.

[CAUTION]
====
If you are also taking over a `docker-compose.yaml` change that adds a volume to a service which previously had none, that service starts against an *empty* directory.

For the `db` service this means the database initialises a new, empty cluster on the next `docker-compose up -d`, while your existing data remains in the writable layer of the old container.
Dump your database *before* recreating the containers and restore it afterwards.

Refer to xref:devops-guide:maintenance/backups.adoc[devops guide on backup procedure] for details.
====

:leveloffset: +1

include::2024096.adoc[]

:leveloffset: -1
