include::../../variables.adoc[]

= Script execution

What operation the given script performs is determined by the execution function (referred to as the exec function).
The function conforms to the following interface:

[source,ts]
----
interface ScriptFn {
  (args: exec.Args, ctx?: exec.Ctx): unknown;
}
----

== Execution arguments

[IMPORTANT]
====
Arguments to a client-script are provided via *references* to the original objects, meaning that *any change* to the argument parameter *will reflect* to the original object.

For example, running the following code in the client script's exec function will reflect the values without the need of returning the updated record.
[source,js]
----
{
  ...
  async exec ({ $record }) {
    $record.values.Field1 = 'value1'
    $record.values.Field2 = 10
  },
}
----
====

The execution arguments provide an object containing all of the arguments related to the given operation and resource.
For example, when working with records this will contain the `$record`, `$module` and `$namespace`.

Refer to <<integrator-guide:resources-events>> for a complete list of available arguments.

== Execution context

The execution context provides an object containing things related to the given system.
It contains:

`ctx.console`::
    Used for logging.
    When running in the UA, this will be native `window.console`.
    When running in {app_automation}, this will be a `Pino` instance,

`ctx.log`::
    Shortcut for `ctx.console.log`,

`ctx.$authUser`::
    User object corresponding to the security context,

`ctx.SystemAPI`::
    API client for {PRODUCT_NAME} System interaction,

`ctx.ComposeAPI`::
    API client for {PRODUCT_NAME} {APP_NAME_COMPOSE} interaction,

`ctx.MessagingAPI`::
    API client for {PRODUCT_NAME} {APP_NAME_MESSAGING} interaction,

`ctx.System`::
    Helper class instance for the {PRODUCT_NAME} System,

`ctx.Compose`::
    Helper class instance for the {PRODUCT_NAME} {APP_NAME_COMPOSE},

`ctx.ComposeUI`::
    Helper class instance for the {PRODUCT_NAME} {APP_NAME_COMPOSE} user interface,

`ctx.Messaging`::
    Helper class instance for the {PRODUCT_NAME} {APP_NAME_MESSAGING},

`ctx.frontendBaseURL`::
    Base URL used by front-end web applications.
    This is useful when generating URL's inside server scripts.

== Execution result

Unknown Error::
    An error aborts the script's execution chain (the current script and all following scripts).

Aborted Error::
    An error with the value of `'Aborted'` stops the execution of the *current* automation script.
    Any further scripts down the chain are executed as usual.

`false`::
    Same as aborted error.
    A return value of `false` stops the execution of the *current* automation script.
    Any further scripts down the chain are executed as usual.

unknown::
    Any other return value specifies that the execution was successful and the following script (if any) can execute.

