include::../../variables.adoc[]

= TL;DR

[#integrator-guide:extensions:tl-dr:script-signature]
== Script signature

An automation script must conform to the given interface:

[source,ts]
----
export interface Script extends ScriptFile {
  label?: string;<1>

  description?: string;<2>

  security?: {<3>
    runAs?: string;
    deny: string[];
    allow: string[];
  }|string;

  triggers?: Trigger[];<4>

  iterator?: Iterator;<5>

  exec?: ScriptFn;
}
----
<1> User-friendly name for the script.
<2> Additional description if needed.
<3> Security context for the script; if defining `runAs`, you can provide a string.
<4> Script triggers; refer to <<integrator-guide:extensions:automation-triggers>> for details.
<5> Script iterator; refer to <<integrator-guide:extensions:automation-iterators>> for details.

== File structure

=== Server-scripts

include::../../../partials/extensions/fs-server.adoc[]

=== Client-scripts

include::../../../partials/extensions/fs-client.adoc[]

=== Meta

[source,text]
----
/package.json<1>
/...<2>
----
<1> Dependencies to use.
<2> Undefined file structure.
Can be used for assets, tools, common scripts, test configuration, ...

== Server-scripts

Server-scripts are executed in the {PRODUCT_NAME} {APP_AUTOMATION} server.

=== Use when

* Interaction with the user is not required,
* response latency is not as important,
* execution consistency is important,
* automation script produces a heavy load on system resources.

=== Example use case

* Insert additional record fields based on an external data source,
* send an email when a new user signs up,
* run statistic operations once a month for reporting purposes.

== Client-scripts

Client-scripts are executed in the client's browser (user agent; UA).

=== Use when

* Interaction with the user is required,
* response latency should be minimal,
* execution reliability is not important,
* we are not working with sensitive information such as authentication tokens or api credentials,
* automation script produces a light load on system resources.

=== Example use-cases

* Prompt user to confirm form submission,
* validate or modify form's data before submission,
* redirect the user to another page; either in {PRODUCT_NAME} {APP_NAME_COMPOSE} or other,
* open an external resource inside a popup window.

== Automation triggers

An automation triggers specify under what conditions an automation script should be executed execute and its execution context.

== Explicit triggers

Explicit triggers execute on a specific user invocation, such as a button press.
These include:

* Manual.

== Implicit triggers

Implicit triggers execute as a collateral to another system event such as record creation.
These triggers include any before/after event.
For a full list of events see <<integrator-guide:resources-events>>.

== Deferred triggers

[IMPORTANT]
====
The minimum time precision is 1 minute.
====

[IMPORTANT]
====
Requires explicit security context.
====

[IMPORTANT]
====
Only available inside server-scripts.
====

Deferred automation triggers are executed at a specific point in time; once or multiple times, such as a reminder.
These include:

* Scheduled,
* interval.

[NOTE]
====
Scheduled triggers use a ISO 8601 timestamp.
====

[NOTE]
====
Interval triggers use cron expressions.
====

== Sink triggers

[IMPORTANT]
====
Only available inside server-scripts.
====

[IMPORTANT]
====
Requires explicit security context.
====

Sink automation triggers are executed on a specific http request.
They can be used to implement new routes on the API, such as a web hook to some external service.

== Automation iterators

An automation iterators specify under what conditions an automation script iterator should execute and part of the execution context.

[IMPORTANT]
====
The given operation is executed over a set of resources defined by the iterator.
====

== Conventions

=== Writing triggers

include::partials/conventions-triggers.adoc[]
