include::../../variables.adoc[]
= Channels

:CHLIST_SHORTCUT: CTRL/CMD + K

Channels make your conversations *structured* and in *one place*.
It is a single place where you can *share messages*, share resources and *upload files*

[TIP]
====
You can see all of your channels on the left sidebar.
====


.There are three different *channel types*:

Public channels::
    Public channels are open and available to all members.
    They are listed under "Public channels" in the sidebar and are identified with a hashtag icon.
    You can join a public channel by clicking on the "Browse all channels" at the bottom of the channel list.

[TIP]
====
You can use the `{CHLIST_SHORTCUT}` shortcut to search through available channels quickly.
====

Private channels::
    Private channels are limited only to the invited team members.
    They can be used to discuss sensitive topics that other members should not access.
    They are listed under "Private channels" in the sidebar and are identified with a lock icon.

Direct messages::
    Direct messages are a discussion between two or more people limited to only them.

== Creating channels

. Click on the plus icon (`+`) next to "Public channel", "Private channel" or "Direct messages" section titles,
. fill in the form and optionally add members,
. click on the "Create" button.

== Joining channels

. Click the "Browse all channels" or use the `{CHLIST_SHORTCUT}` shortcut,
. find the channel you wish to join and click on it,
. if you are not already a member of the channel, press on the "Join Channel" button on the bottom of the page.

== Channel options

Hover your mouse over the navigation icon in the top right corner (the three vertical dots).
.You can:
* See channel members,
* edit the channel,
* hide or show the channel,
* pin or unpin the channel,
* ignore or follow the channel (this disables or enables notifications),
* see bookmarked and pinned messages,
* leave the channel.

[NOTE]
====
If you don't see some of the channel options, you might not have permissions to access that option.
Contact your system administrator.
====
