include::../../variables.adoc[]
= Messages

== Sending messages

. Enter a message into the message bar at the very bottom of the screen,
. Hit "Enter".

[TIP]
====
Do you want your message to span over multiple lines?
Hold the shift button and press enter.
====

== Edit messages

. Hover over the message and click on the plus (`+`) sign that appears at the end of the message.
. select "edit message".
This method works for all your messages,
. alternatively, while you're in the message bar, hit the arrow-up key and to edit your last message.

== Removing messages

. Hover over the message and click on the plus ("+") sign that appears at the end of the message,
. select "delete message".

== React to a message

. Hover over the message and click on the emoticon (smiley) icon that appears at the end of the message,
. click on the sign and choose from the emoticon menu presented.

== Bookmarking messages

[NOTE]
====
Bookmarked messages are visible only to you.
====

Bookmarked messages have a green vertical bar on the right of the message.

To bookmark a message, hover over the message and click on the bookmark icon.

To view your bookmarked messages in any channel, select the channel controls in the top right-hand corner (the three vertical dots) and select "Bookmarked Messages".

== Pinning messages

[NOTE]
====
Pinned messages are visible in the right sidebar to *every member* of the channel.
====

Pinned messages have a yellow vertical bar on the right of the message.

To pin a message, hover over the message and click on the pin icon.

To view your pinned messages in any channel, select the channel controls in the top right-hand corner (three vertical dots) and select "Pinned Messages".

== Emojis!

. Click on the smiley face icon in the bottom right corner,
. use the icons at the top to browse categories, or you can search by name,
. click on the emoji to add it to your message.

[TIP]
====
You can use `:emoji name here:` to add an emoji by name; for example `:smile:`.
====

== Mentioning teammates

[NOTE]
====
A mentioned user receives a notification about the new message.
You can use mentions to resolve urgent topics quickly.
====

. Access the available mentions by typing the `@` sign,
. continue typing to filter through the list.
You can use your arrow keys to navigate up and down the list,
. select a mention by either pressing enter or clicking on it.

== Mentioning channels

[NOTE]
====
Channel mentions allow you to reference other channels.
====

. Access the available mentions by typing the `#` sign,
. continue typing to filter through the list.
You can use your arrow keys to navigate up and down the list,
. select a mention by either pressing enter or clicking on it.

== Managing unread messages

The number of unread messages in a channel appears beside the channel name in the left sidebar.

A bubble icon instead of a number indicates you have unread messages in one of the threads inside the channel.

To mark messages as read, open the channel and click on the "Mark as read" button on the bottom right corner.
