include::../variables.adoc[]

[#maint-index]
= {PRODUCT_NAME} Management and Maintenance
:toc: left
:toclevels: 3

== {PRODUCT_NAME} Architecture overview

.Mayor component or services in {PRODUCT_NAME}
 - frontend applications (WebApps)
 - backend API (Server)
 - automation script execution engine (Corredor)

.Auxiliary services
 - log storage
 - error tracking
 - email sending
 - object storage
 - database

.Frontend applications
 - {GIT_REPO_LINK_PREFIX}[Auth] handles authentication flows, sign-up, login, password recovery, ...
 - {GIT_REPO_LINK_PREFIX}[Admin] is used for instance administration, settings, user overview, general permission management
 - {GIT_REPO_LINK_PREFIX}[{APP_NAME_COMPOSE}] is a https://en.wikipedia.org/wiki/Low-code_development_platform[low-code development platform] and allows creation of record-absed business applications
 - {GIT_REPO_LINK_PREFIX}[Messaging] collaboration platform that allows teams to collaborate more efficiently and communicate safely with other organizations or customers
 - {GIT_REPO_LINK_PREFIX}[{APP_NAME_SHELL}] is a unified workspace to access and run third-party web and {PRODUCT_NAME} applications. Centralized access management from a single console enables administrative control over who can see or access applications

:leveloffset: +1

include::requirements.adoc[]

include::install/index.adoc[]

include::setup/index.adoc[]

include::backup.adoc[]

:leveloffset: -1
