include::../../variables.adoc[]
= Basics

To access {PRODUCT_NAME} Admin Panel, click on a new tab and select it from the list of available applications.
Alternatively you can navigate to the appropriate URL.

[IMPORTANT]
====
You must have Administrator rights to access and edit this part of {PRODUCT_NAME} system.

If you do not have permissions to access the admin panel, contact your system administrator.
====

The {PRODUCT_NAME} Admin Panel provides the following sections:

Dashboard::
    The dashboard section provides a quick overview of the entire system.
    Read more in <<admin-adminpanel-dashboard>>,

System::
    The system section provides the interface to manage system level resources, such as users and roles.
    Read more in <<admin-adminpanel-system>>,

Compose::
    The compose section provides the interface to manage {{PRODUCT_NAME}} {{APP_NAME_COMPOSE}} level resources, such as access control.
    Read more in <<admin-adminpanel-compose>>,

Messaging::
    The messaging section provides the interface to manage {{PRODUCT_NAME}} {{APP_NAME_MESSAGING}} level resources, such as access control.
    Read more in <<admin-adminpanel-messaging>>,

One::
    The one section provides the interface to manage {{PRODUCT_NAME}} {{APP_NAME_SHELL}} level resources, such as access control.
    Read more in <<admin-adminpanel-shell>>.
