include::../../variables.adoc[]

= Leads

The Leads page is accessible by clicking on the "Leads" in the main navigation bar on the top of the screen.

[NOTE]
====
There are three pages dedicated to leads -- one main page and two subpages.
They all show leads but with different filtering.

* *Leads* shows all of the leads in the system,
* *All New Leads* shows only the leads that have the `New` status,
* *My Leads* shows only the leads that you are responsible for.
====

A *lead* or a prospect is an individual who *might become your customer*, but currently is not.
They are usually converted to *accounts*, *contacts* and *opportunities*.

== Add a new lead

[NOTE]
====
A new lead can be added from either one of the subpages.
====

. Click on the "+ Add" button to open up the form,
. populate the data and press the "Save" button on the bottom right corner.

[TIP]
====
The rating field is incredibly helpful as it allows you to distinguish between good leads quickly.
====

The typical process of handling a lead after it is inserted in the system is for a salesperson to follow up on the lead.

[TIP]
====
You can create notes, events and tasks are extremely helpful here.
====

== Converting the lead

A lead should be converted *after* a salesperson has made contact, and there is a sales opportunity.

You have two options:
Convert this lead into an Account::
    This creates an account and a contact for the lead.
    Use it when a lead shows some interest but its not exactly clear what their needs are.

Convert this lead into an Account and Opportunity::
    This creates an account, contact and an opportunity for the lead.
    Use it when a lead shows interest, and we already know what their needs are.

[TIP]
====
When a lead is converted, the generated Contact is set as the primary contact for the account.
====

== Tips for determining a lead rating

If a lead *shows commercial interest*, such as a request for pricing and the lead's *location matches the region your business targets*, this lead should be considered a *5 star lead*.

If a lead *performed some additional interactions*, such as going through a demo, they could be considered a *3 star lead*.

If a lead *contacted* you regarding one of your services and didn't show any explicit business intention, it can be considered a *0 star* or a *1 star* lead.
