include::../../variables.adoc[]

= Opportunities

The Opportunities page is accessible by clicking on the "Opportunities" in the main navigation bar on the top of the screen.

When you generate an opportunity for a given account, you indicate that you have uncovered a potential future sale and thus potential revenue.

An *opportunity name* should be short and descriptive to identify what the opportunity is about quickly.
For example, "300 licenses" is a good example, as it is short and straight to the point.

The close date is set to one month after the opportunity is created.
[NOTE]
====
The close date determination is configurable via the settings.
====

The "stage" field allows you to identify what stage a given opportunity is in.
When you create an opportunity, it is set to "Qualification".
Once correctly qualified, you can move it to "Proposal" (or to "Need Analysis", if more analysis is needed).
The last few steps are "Negotiation", followed by "Closed Won" or "Closed Lost".

== Tips for qualifying leads

.It is useful to figure out the following data:
* *Budget*: Check if there is actually a budget,
* *Authority*: Check if you are talking to or being able to get through to the decision-makers,
* *Need*: Check if there is an actual need for the product/service,
* *Timeline*: Check by when the product/service needs to be delivered or implemented, and if this timeline makes sense,
* *Competition*: Check whom you are competing with.
