include::ROOT:partial$variables.adoc[]

= Backups
:description: An example of how to perform data backups and restore the state based on the backup.
:keywords: dev-ops, DevOps, CLI, command-line interface, maintenance

We recommend backing up your database and uploaded files regularly.
It is also highly recommended to backup before you upgrade to a more recent {PRODUCT_NAME} version.

[TIP]
====
You can define a cron job that backups your data to external storage.
====

[NOTE]
====
*DevNote* add some example setups, as we have now with a CRON job?
====

== MySQL Database

=== Backup

We recommend you use the `mysqldump` tool.
It's builtin into the `db` container (`percona:8.0` image).

[CAUTION]
====
Do not attempt to copy raw database files to perform a backup.
It might lead to corrupted data.
====

If you want to use a different tool to create your backup, you need to connect to the container or publish MySQL ports.

If you're using a different database engine, refer to their documentation on how to perform backups.

[WARNING]
====
By default, `mysqldump` locks the tables when you run the export.
Table locks might cause issues when running in production, so do keep this in mind.
====

.Database dump command:
[source,bash]
----
# This will dump the entire database and place it in the dump.sql file.
docker-compose exec -T \
    --env MYSQL_PWD=your-password db \
    mysqldump your-db-name --add-drop-database -u your-username > dump.sql
----
//Editor's note: will dump --> dumps

[CAUTION]
====
If you've changed the database service name (`db`) inside your `docker-compose.yaml`, make sure to change it in the above command.
====

=== Restoration

[NOTE]
====
We recommend that {PRODUCT_NAME} server is shut-down until the restore procedure finishes.
====

.Database restore command:
[source,bash]
----
# This will restore the database based on the dump.sql file
docker-compose exec -T \
    --env MYSQL_PWD=your-password db \
    mysql your-db-name -u your-username < dump.sql
----
//Editor's note: will restore --> restores, add a dot at the end (after "file").

[CAUTION]
====
If you've changed the database service name (`db`) inside your `docker-compose.yaml`, make sure to change it in the above command.
====

== PostgreSQL Database

=== Backup

We recommend you use the `pg_dumpall` or `pg_dump` tool.
`pg_dumpall` is a utility for writing out ("dumping") all PostgreSQL databases of a cluster into one script file.
The script file contains SQL commands that can be used as input to psql to restore the databases.
It does this by calling `pg_dump` for each database in a cluster.

[CAUTION]
====
Do not try to copy raw database files to perform a backup.
It might lead to corrupted data.
====

If you want to use a different tool to create your backup, you need to connect ... to the container, or publish PostgreSQL ports.
//Editor's note: to connect what to the container? 

If you're using a different database engine, refer to their documentation on how to perform backups.

[WARNING]
====
By default, `pg_dump` locks the tables when you run the export.
Table locks might cause issues when running in production, so do keep this in mind.
====

.Database Dump Command:
[source,bash]
----
# This will dump all databases and place them in the dump.sql file.
docker-compose exec db \
    pg_dumpall -c -U your-username > dump.sql

# This will dump the entire database and place it in the dump.sql file.
docker-compose exec db \
    pg_dump -d your-db-name -c -U your-username > dump.sql

# To reduce the size of the sql,
# This will dump all databases and place them in the dump.gz file.
docker-compose exec db \
    pg_dumpall -c -U your-username | \
    gzip > /var/data/postgres/backups/dump.gz
----
//Editor's note: will dump --> dumps

[CAUTION]
====
If you've changed the database service name (`db`) inside your `docker-compose.yaml`, make sure to also change it in the above command.
====

=== Restoration

[NOTE]
====
It is recommended that {PRODUCT_NAME} server is shut-down until the restore procedure finishes.
====

.Database Restore Command:
[source,bash]
----
# This will restore the database based on the dump.sql file
cat dump.sql | \
    docker-compose exec db psql -U your-username

# This will restore a specific database based on the dump.sql file
cat dump.sql | \
    docker-compose exec db psql -U your-username -d your-db-name

# To restore a compressed sql,
# This will restore the database based on the dump.gz file
gzip < dump.gz | \
    docker-compose exec db psql -U your-username
----
//Editor's note: will restore --> restores

[CAUTION]
====
If you've changed the database service name (`db`) inside your `docker-compose.yaml`, make sure to change it in the above command.
====

== Files

=== Backup

Without object storage service like Min.io, uploaded files are stored directly on the filesystem.
{PRODUCT_NAME} server stores data to the `/data` directory (if not configured differently with `*_STORAGE_PATH` environmental variables).

You can use any standard file management tools to make a backup copy of the files.

.Compressing files with the `tar` command:
[source,bash]
----
# This will compress all your uploaded files into the backup.tar.bz2 archive
tar -cjf backup.tar.bz2 data/server/
----
//Editor's note: will compress --> compresses
=== Restore

.Uncompromising files from the archive with the `tar` command:
[source,bash]
----
# This will restore your backup.tar.bz2 archive
tar -xjf backup.tar.bz2
----
//Editor's note: will restore --> restores
