include::ROOT:partial$variables.adoc[]

= Troubleshooting
:description: These troubleshooting steps help you solve the most common issues we have encountered in the past.
:keywords: dev-ops, DevOps, troubleshooting

[NOTE]
====
*DevNote* update this with new discoveries regarding configurations
====

== Ports are not available

When you're running various services on your machine, it's common that the ports are already in use.
You will see something like this:

[source]
----
Cannot start service server: Ports are not available: listen tcp 127.0.0.1:18080: bind: address already in use
----

If you see this error, you can change the port number to something between `1024` and `65535`.
You can also replace the value for `services.server.ports` in `docker-compose.yaml` to `["80"]`, and Docker will pick an available port for you.

⚠️ Make sure also to change the port everywhere else.

[#ws-nginx-connection-fail]
== WebSocket connection failing with Nginx

If the WebSocket connection is failing to establish, you might need to enable Nginx WebSocket proxying.

[NOTE]
====
You can find detailed instructions and further examples in the https://nginx.org/en/docs/http/websocket.html[Nginx documentation].
====

Inside your `nginx.conf` file (by default, it is located inside the `/etc/nginx` directory), add the following lines to the `server` configuration section.

[CAUTION]
====
Make sure to adjust the location if you've defined a custom configuration that affects the base path.
====

[source]
----
location /api/websocket {
  proxy_pass http://server:80;
  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "Upgrade";
  proxy_set_header Host $host;
}
----

== Connection to {APP_AUTOMATION} server

You might see one or more connection refused errors in server container logs (`docker-compose logs -f server`):

[source]
----
{"level":"error","ts":1608125024.4714684,"logger":"corredor","caller":"corredor/service.go:427","msg":"could not load corredor server scripts","error":"rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = \"transport: Error while dialing dial tcp 172.23.0.2:80: connect: connection refused\"","stacktrace":"github.com/cortezaproject/corteza-server/pkg/corredor.(*service).loadServerScripts\n\t/drone/src/pkg/corredor/service.go:427"}
----

If there are a couple of errors when the server is starting up, that's ok.
Sometimes it takes more time to start up {APP_AUTOMATION} server, and {PRODUCT_NAME} server can not yet connect to it.

If the problem persists, and you can see {APP_AUTOMATION} state as healthy, verify the changes you might have made to the configuration.

== Network proxy declared as external

[source]
----
ERROR: Network proxy declared as external, but could not be found. Please create the network manually using `docker network create proxy` and try again.
----

Make sure your nginx-proxy service is up and running before running {PRODUCT_NAME}.

== Blank screen on /auth with "state does not match" error in the browser console

"State does not match" is an error that usually occurs in development environment or where {PRODUCT_NAME} server is frequently restarted
State that users going through authentication flow carry with them is not persistent and will perish on server restart.
If problem occurs and persists on production environment verify `AUTH_SESSION_*` settings (in case you have modified them).

== Further troubleshooting

If you're continuing to have issues with {PRODUCT_NAME}, we encourage you to contact other users on our https://latest.cortezaproject.org[community server].
You'll more than likely find someone who can help you out.
You can also open an issue on our https://github.com/cortezaproject/corteza-server[cortezaproject/corteza-server] GitHub repository.
