= Authentication

This describes the handshake process between two federated nodes; how to establish a secure connection and how to introduce access control when accessing resources.

== Handshake

The handshake consists of two parts:

Federation node identification::
    Firstly we need to identify the two federation nodes.

    . Node A generates a URL containing it's information, along with a OTT token T.
    . the administrator sends the generated URL to the maintainer of the node B,
    . node B pings node A to confirm the connection,

Secure token exchange::
    After two nodes are identified, we need to initiate secure communication between the two nodes.

    . Node A creates a system user that is responsible for serving data to node B (this allows access control),
    . node A sends a JWT token used for authentication along with the OTT token T to node B,
    . node B validates the token T and stores the JWT
    . node B creates a system user that is responsible for fetching data from node A and sends the JWT to node A,
    . node A validates the request and stores the JWT.

