[#rfc:federation:data-sync]
= Data Sync

The data sync occurs after the first two phases, node 
authentication and pairing, and structure sync are successfuly done. The orchestrator for the data sync is a federation data 
sync service that works with the compose API service and store repository methods.
The structure of the microservice works in a way as to possibly decouple the service from the main corteza server.

== Data sync (Origin)

*Schema* +
http://www.plantuml.com/plantuml/uml/TP8nRiCm34LtdO9ZE_G27ee0IRkrGt82rg8I0R8eK4pRunUM8ITMbTNKV_-J_hkiA7gTWaaewaUVC2fyigK3PVKHrNFSpDwFb7NFKOL38DdEo98KoOdasu-qcUvvIfpfU38M5Rym4voKXRQ80ohsr6-_YKL9J1CENbxRJ0ESIM4sWITqIW8vqUYT7-UFz6oQzmNHHbyW6088ZImsWsC1lA4cjjT0ZnnQtEnHjbsuRfs3Zuw1O-LXj31XIcJ1UGescoBhPxpxL4G-ddFVUpt-_xtOWLwecexBG_WeSRgmpKyQ80ab52gGXGd1PuKVhvVrBdMPUsb_fyVYVfXQZ05KC6R7CirH2iRKOT_gfg0bSy-XKwzM1knAtNh5QkewL44zlzbHjDSf_040[link to uml schema]

Diagram:
[source,uml]
----
@startuml
participant NodeDestination
participant FRestController
participant FederationService
participant ComposeRS
database Store
participant FDataService
participant Exporter
NodeDestination -> FRestController: get data (after specific date)
FRestController -> FederationService: get all records for a specific module (after specific date)
FederationService -> Store: get federation info on module and mapped fields
Store -> FederationService: Federation mappings
FederationService -> ComposeRS: get all records of the mapped compose Module
FederationService -> FDataService: prepare the record list with specific fields
FDataService -> FederationService: list with specific fields
FederationService -> Exporter: transform the list
Exporter -> FederationService: transformed list
FederationService -> FRestController: transformed list of data
FRestController -> NodeDestination: list of records
@enduml
----


.*Flow*:
1. The incoming request from Destination is parsed and the input parameters about module and 
last update time is provided to the Federation service
2. The federation service calls the Federation Data Service, which in turn first fetches all the federation info about the 
module and the fields mappings
3. Once the info is gathered from the store, the Federation Data Service fetches the compose Records from store
4. All the records are then transformed in the service to include only the necessary data (also the specific fields and the paging data)
5. Once the list is generated, it is sent to the exporter service to transform the list to the appropriate standard
6. Alongside the list, there is also the filtering info with the paging data, so any necessary requests are made again
to satisfy the length of the data (paging) and to ensure all the data is not fetched in one big chunk

== Data sync (Destination)

*Schema* +
http://www.plantuml.com/plantuml/uml/XLFDJiCm3BxtANm48LvW1pHf28aBIDiJcCOfbjguibqctfvkqz9rwSOrzlTZ-ylQ7DM7hgrwLEUQUqmE7nBeKxdXD7j-svBvHfAhj2tfl4Q159qbxKX_kAPPTIDTBqRRNHNGyGkDOEUYDATuHSSbzFi8LXy59r_m_79jPmKDEHpuuG6ZauBrL7Fa-l18ZzLL_qXHkbw1KYqQ3A8eu4JHIHXQki5Sq8pSfm5FfcAk0wSe8EdCXob0XtrF0I9J6wmwmcvucvwE84wDBMhdZQsWPNEGcCVYD9cFeXrwTMvU52qObWNpxMOxV8AuvFYYzn_D-fGRsDxJpk4gfzspVyEegz8hezDvoHboSQYzibD6kcHnSr5iA5_cKj0SVRZYAqpcjdivCNAmtrJVxIqYxuh93dUaa8SFwBWKzkdtb4TTKmf3r_u1[link to uml schema]

Diagram:
[source,uml]
----
@startuml
participant NodeOrigin
participant FRestController
participant FederationService
participant ComposeRS
database Store
participant FDataService
participant Importer
NodeOrigin -> FRestController: get data (after specific date)
FRestController -> FederationService: records for a specific module (after specific date)
FederationService -> Store: get federation info on module and mapped fields
Store -> FederationService: Federation mappings
FederationService -> Importer: list of records in specific format
Importer -> FederationService: list of records
FederationService -> FDataService: records + federation mappings
FDataService -> FederationService: list of compose Records
FederationService -> ComposeRS: list of records with appropriate fields
ComposeRS -> Store: write records to compose storage
Store -> ComposeRS: status
ComposeRS -> FederationService: status
FederationService -> Store: set sync status
FederationService -> FRestController: transformed list of data
FRestController -> NodeOrigin: list of records
@enduml
----


.*Flow*:
1. Start the data sync after a successful structure sync is done
2. Data sync service checks for the last successful sync date in store
3. The latest data changes are fetched from the Origin (depending on the last sync)
4. The list of url endpoints is provided on the Origin
5. Destination parses the list of endpoints and fetches the corresponding records per-federation module
6. Destination node gets the mapping info via Federation Service from the Store
7. The federation info and the list of records are transformed in the Federation Data Service
to accomodate the field mappings
8. The list of records are then written to the Store via compose service
9. After the successful data sync, the federation status is saved as successful for the future sync

== Endpoints

.List:
 - Origin provides data for a specific module (/records endpoint in structure sync)
 - master list of changes, depends on filtering (list of modules updated from the dropoff time)
 - info about the data sync per-module and for all (via UI)
 - add an externally requested sync (via UI)?
