= Glossary

== Pairing

[IMPORTANT]
====
This step uses node A and node B when identifying the parties involved as it is not clear which node will origin the data and which will consume the data.
At this step they are equivalent.
====

Node URI::
    The URI that identifies the node it was generated for.

Node A::
    The node that initializes the process by generating a node URI.

Node B::
    The node that initializes the handshake step by registering node A.

NodeID A::
    The nodeID generated by node A.

NodeID B::
    The nodeID generated by node B.

Token A::
    The auth token generated by node A.

Token B::
    The auth token generated by node B.

== Data exchange

Origin node::
    The node that **shares the data** to the other node.
    If node A requests data from node B, node B is origin as it contains the data.

Destination node::
    The node that **receives the data** from the origin node.
    If node A requests data from node B, node A is destination as it receives the data.
