= Pairing nodes

Node pairing is the process of establishing a federated network between two nodes in order to share their information.
The process consists of two steps:

Node identification::
    The step identifies the two nodes so they know where to access the information.

Node handshake::
    The step exchanges the authentication tokens so the two nodes can access protected resources from each other.

.Outline of the entire pairing process.
[plantuml,node-pair,svg,role=sequence]
----
@startuml
skinparam responseMessageBelowArrow true

actor "Administrator A" as AdministratorA
participant "Node A" as NodeA
participant "Node B" as NodeB
actor "Administrator B" as AdministratorB

== Node identification ==
AdministratorA->NodeA: Register federated node B
note right of AdministratorA
Administrator A sends the node URI
to administrator B via a secure channel.
end note
AdministratorA-->AdministratorB: Send node URI
...
note left of AdministratorB
Administrator B registers node A
using the node URI.
end note
AdministratorB->NodeB: Register federated node A

== Node handshake ==
AdministratorB->NodeB: Initialize the handshake
note over NodeB #FFAAAA
Prepare the node's state for a
federated network.
end note

NodeB->NodeA: Request handshake
NodeA-->AdministratorA: Notify administrator A
note right of AdministratorA #ffffff
Administrator A should manually
approve the handshake.
end note
...
AdministratorA->NodeA: Approve handshake request
note over NodeA #FFAAAA
Prepare the node's state for a
federated network.
end note
NodeA->NodeB: Complete handshake
@enduml
----

== Node identification

.Outline of the node identification step.
[plantuml,node-pair,svg,role=sequence]
----
@startuml
skinparam responseMessageBelowArrow true

actor "Administrator A" as AdministratorA
participant "Node A" as NodeA
participant "Node B" as NodeB
actor "Administrator B" as AdministratorB

AdministratorA->NodeA: Register federated node B
note right of AdministratorA
Administrator A sends the node URI
to administrator B via a secure channel.
end note
AdministratorA-->AdministratorB: Send node URI
...
note left of AdministratorB
Administrator B registers node A
using the node URI.
end note
AdministratorB->NodeB: Register federated node A
@enduml
----

[IMPORTANT]
====
No authentication tokens are exchanged in during the identification step.
====

Node A administrator registers node B and generates it's node URI::
    This step lets node A know about node B.
    The generated node URI identifies node A and is in the form of `corteza://$NODE_ID_A:$OTT@$DOMAIN_A?name=$NAME`.

[NOTE]
====
`$OTT` is a generated OTT token that allows us to perform some authentication when performing the handshake.
====

include::api/node_create_a.adoc[]

Node A administrator sends the node URI to the node B administrator::
    This step transports the node URI to the node that we wish to pair with.

[NOTE]
====
This step is *performed manually* by the node A administrator.
The two administrators should use a secure channel in order to exchange this information.
====

Node B administrator registers node A using the node URI::
    This step lets node B know about node A.
    Both nodes A and B are now identified and prepared to perform the <<rfc:federation:node-pair:node-handshake>>.

include::api/node_create_b.adoc[]

[IMPORTANT]
====
In the above response, `$NODE_URI` contains the value provided by node A.
====

[#rfc:federation:node-pair:node-handshake]
== Node handshake

.Outline of the node handshake step.
[plantuml,node-pair,svg,role=sequence]
----
@startuml
skinparam responseMessageBelowArrow true

actor "Administrator A" as AdministratorA
participant "Node A" as NodeA
participant "Node B" as NodeB
actor "Administrator B" as AdministratorB

AdministratorB->NodeB: Initialize the handshake
note over NodeB #FFAAAA
Prepare the node's state for a
federated network.
end note

NodeB->NodeA: Request handshake
NodeA-->AdministratorA: Notify administrator A
note right of AdministratorA #ffffff
Administrator A should manually
approve the handshake.
end note
...
AdministratorA->NodeA: Approve handshake request
note over NodeA #FFAAAA
Prepare the node's state for a
federated network.
end note
NodeA->NodeB: Complete handshake
@enduml
----

Node B administrator initializes the process with node A::
    This configures the state on node B and generates the `$TOKEN_B`; so node A will be able to access protected resources on node B.

include::api/node_handshake_init.adoc[]

Node B sends a handshake request to node A::
    This notifies the node A administrator that node B wishes to establish a federated network.
    This request *must* be manually confirmed by the node administrator.

[IMPORTANT]
====
This request is authenticated by the before generated `$OTT` token, outside of the standard authentication facility.
====

include::api/node_handshake_request.adoc[]

Node A administrator confirms the handshake request::
    This configures the state on node A and generates the `$TOKEN_A`; so node B will be able to access protected resources on node A.

include::api/node_handshake_confirm.adoc[]

Node A completes the handshake with node B::
    This sends the `$TOKEN_A` to node B so it will be able to access protected resources on node A.

[NOTE]
====
Notice how node A uses `$TOKEN_B` to authenticate this request.
====

include::api/node_handshake_complete.adoc[]
