[#rfc:federation:structure-sync]
= Syncing structures

The process of determining what structures on the origin node, is exposed to it's destination node.
The origin node has full control over what data the destination node is allowed to access.
This can be as simple as allowing access to only specific modules; and as complex as allowing access to only specific module fields.

[IMPORTANT]
====
The two nodes must be paired prior to this.
See <<rfc:federation:node-pair, Node pairing>>.
====

== Exposing structures

Firstly, in order to perform any data sharing, the origin node must define what structures (in our case modules and fields) the destination node can access.
This can be performed via the Corteza Low-Code administration panel, or directly via the API.

[NOTE]
====
Besides the module itself, the origin node must also specify what fields the destination node is allowed to access.
====

=== API

==== Expose module

include::api/structure_sync__add_module_to_federation.adoc[]

==== See exposed module

include::api/structure_sync__list_exposed_module.adoc[]

==== Remove exposed module

include::api/structure_sync__remove_module_federation.adoc[]

==== Change exposed module fields

include::api/structure_sync__change_sharing_fields.adoc[]

=== Store

==== Exposed modules

include::store/module_exposed.adoc[]

== Syncing structures

When the two nodes are paired and the origin node has exposed some structures, the actual structure sync can occur.

.Outline of structure sync process on the origin node.
[plantuml,structure-sync-origin,svg,role=sequence]
----
@startuml
skinparam responseMessageBelowArrow true
hide footbox
actor "Destination Node" as NodeDestination
box "Origin Node" #f7f7f7
participant "Federation Rest Controller" as FRestController
participant "Federation Service" as FederationService
participant "Compose Module Service" as ComposeMS
database Store
participant "Federation Structure Service" as FStructureService
participant Encoder
NodeDestination -> FRestController: get structure
note left : only the structure\nthat was updated after\nlast successful sync
activate FRestController
FRestController -> FederationService: get structure for all modules
activate FederationService
FederationService -> Store: get module id list
activate Store
Store -> FederationService: federated modules id list
deactivate Store
FederationService -> ComposeMS: get filtered compose Modules
activate ComposeMS
ComposeMS -> Store: get filtered list of modules
activate Store
Store -> ComposeMS: list of compose Modules
deactivate Store
ComposeMS -> FederationService: list of compose Modules
deactivate ComposeMS
FederationService -> FStructureService: module list + federated module ID list + federated field ID list
note left : omit the fields we do not wish to share
activate FStructureService
FStructureService -> FederationService: module list with specific fields
deactivate FStructureService
FederationService -> Encoder: transform the list to specific structure
activate Encoder
Encoder -> FederationService: transformed list
deactivate Encoder
FederationService -> FRestController: transformed list of modules (structure)
deactivate FederationService
FRestController -> NodeDestination: list of modules
deactivate FRestController
end box
@enduml
----

.Outline of structure sync process on the destination node.
[plantuml,structure-sync-destination,svg,role=sequence]
----
@startuml
skinparam responseMessageBelowArrow true
hide footbox
actor "Origin Node" as NodeOrigin

box "Destination Node" #f7f7f7

participant "Federation Service" as FederationService
database Store
participant "Federation Structure Service" as FStructureService
participant Decoder

FederationService -> NodeOrigin: get structure for module
activate FederationService
activate NodeOrigin
NodeOrigin -> FederationService: structure for module
deactivate NodeOrigin
note left : federated Module structure from Origin

FederationService -> Decoder: structure for module in specific format
activate Decoder
Decoder -> FederationService: structure for module
deactivate Decoder

FederationService -> FStructureService: structure for module and fields
activate FStructureService
FStructureService -> FederationService: remapped module with fields
deactivate FStructureService

FederationService -> Store: write federated modules and fields info
FederationService -> Store: structure sync OK
deactivate FederationService
end box
@enduml
----

Destination node requests changed structures::
    Origin node provides a set of endpoints that the destination node can use to fetch shared structures.

include::api/structure_sync__master_changes.adoc[]

Destination node fetches updated structures::
    The destination node requests structure definitions based on the above provided set of endpoints.
    The origin node provides the structure definition with respect to the fields that the destination node is allowed to access.

include::api/structure_sync__sync_shared_module.adoc[]

Destination node updates its store::
    Once the structure sync is finished, the destination node writes the structures to the store and updates the nodes status.

[IMPORTANT]
====
This step doesn't create any system resources, such as records, on the destination node.
This is performed later in the data sync.
====

=== Store

==== Shared modules

include::store/module_shared.adoc[]

[#rfc:federation:structure-sync:field-mapping]
== Field mapping

Field mapping allows the destination node to determine what fields from the origin node should map into what fields on the destination node.
This allows some flexibility when it comes down to datamodel definitions on both origin and destination nodes.
This can be performed via the Corteza Low-Code administration panel, or directly via the API.

=== API

==== Set field mapping for a module
include::api/structure_sync__set_module_federation_mapping.adoc[]

==== Get field mapping for a module
include::api/structure_sync__get_module_federation_mapping.adoc[]

==== Remove field mapping for a module
include::api/structure_sync__remove_module_federation_mapping.adoc[]

=== Store

==== Module mapping

include::store/module_mapping.adoc[]

== Example

=== Phase I - on Origin node

First phase is exposing the desired modules for a specific node (to the Destination), so the structure mapping on the Destination and then the data sync can be done.

*compose_module*
|===
|id|handle|name

|161250629010849793|Account|Account
|===

*compose_module_field*
|===
|id|kind|name|label|is_multi

| 161250629061509121 | String | Phone              | Phone                |        0
| 161250629027758081 | Url    | LinkedIn           | LinkedIn             |        0
| 161250629044666369 | String | Description        | Description          |        0
|===

*federation_node*
|===
|id|name

|1|Origin server
|2|Destination server
|===

*federation_module_exposed*
|===
|id|rel_node|rel_compose_module|field_mapping

|11|2|161250629010849793|[{"name":"Phone","kind":"String","is_multi":0}]
|===

=== Phase II - on Destination node

There are 2 phases in the phase II. First the module info from Origin is saved. After that we can do the mapping. The modules on the Destination need to be created beforehand.

*compose_module*
|===
|id|handle|name

|261250629010849755|Account_federated|Account (federated from Origin)
|===

*compose_module_field*
|===
|id|kind|name|label|is_multi

| 161250629061509121 | String | Mobile      | Mobile               |        0
| 161250629044666369 | String | Desc        | Description          |        0
|===

*federation_node*
|===
|id|name

|1|Our server
|2|Misc server (some other server)
|3|Origin server in this example (from phase I)
|===

==== 1. Fetch and save the module info

*federation_module_shared*

|===
|id|handle|name|rel_node|xref_module|field_mapping

|22|Account|Account|3|11|[{"name":"Phone","kind":"String","is_multi":0}]
|===

==== 2. Mapping finished, modules created

The sharing of modules info from Origin is added, that is enough information for us to handle mapping from UI. We can now pick the fields from the field_mapping column that we need and store it into the mapping table.

*federation_module_mapping*

|===
|federation_module_id|compose_module_id|fields

|22|261250629010849755|[{"origin":{"name":"Phone","kind":"String","is_multi":0},"destination":{"name":"Mobile","kind":"String","is_multi":0}}]
|===
