include::ROOT:partial$variables.adoc[]

= Settings

The settings interface allows you to configure some core system settings.

[IMPORTANT]
====
There is a separate view for <<settings-system,system>>, <<settings-compose,compose>>, and <<settings-ui,user interface>>.
====

[#settings-system]
== System settings

Authentication::
    The authentication section lets you control the authentication flow, email notifications, and where to redirect successful logins.

External authentication::
    The external authentication section lets you configure what authentication providers are available (if at all).
    Refer to the menu:Administrator Guide[Authentication providers] for details.

[TIP]
====
You can disable internal sign-up and manually add users that are allowed to access your system.
====

[#settings-compose]
== Compose

Basic::
    Basic system configuration such as UI tweaks and attachment constraints (size and type).

[#settings-ui]
== User interface

Logo::
    The logo section lets you replace main {PRODUCT_NAME} logo and icon with your own.

