include::../../variables.adoc[]

= Automation Iterator Anatomy

To better understand the power of automation iterators and their definition, we define and describe their anatomy.

Automation iterator are constructed with the following methods:

`i`::
    Defines the resource, action and the filter used for resource fetching.

Passed object must conform to the interface:

[source,typescript]
----
interface {
  resourceType: string; <1>
  eventType: 'onManual' | 'onInterval' | 'onTimestamp' = 'onManual'; <2>
  action: 'update' | 'delete' | 'clone' | '' = ''; <3>
  filter: IteratorFilter; <4>
}
----
<1> define the resource type; see <<ext-resevt>> for details.
<2> define the event type; see <<ext-resevt>> for details.
<3> define what action the script performs; see <<ext-dev-iteract>> for details,
<4> define the filter to use; standard {product_name} filter object.

`i.at`::
    Defines that the automation script is executed at a specific time,

`i.every`::
    Defines the interval in which the automation script is executed,


[#ext-dev-iteract]
== Iterator actions

update::
    The result of the automation script will be used to update the original resource,

delete::
    The result of the automation script will be used to delete the original resource,

clone::
    The result of the automation script will be used to create a new resource with updated values; original resource is left un changed,

N/A::
    The result of the automation script is ignored.

[IMPORTANT]
====
N/A indicates that the value is omitted or an empty string is provided.
====

[IMPORTANT]
====
Iterator and trigger are not compatible; you can only use one or the other within the same automation script.
====
