include::ROOT:partial$variables.adoc[]

= Low-Code Platform Developer Guide
:page-aliases: administrator-guide:index.adoc
:keywords: low-code app, low-code application, custom application, low-code config, low-code configuration, extending {PRODUCT_NAME}, {APP_NAME_COMPOSE} development
:description: Learn how to build your own custom {PRODUCT_NAME} {APP_NAME_COMPOSE} application

The low-code platform developer guide covers the process of extending {PRODUCT_NAME} to cover your business' needs.
An integration can be as simple as the modification of the login screen to include your brand graphics or as complex as the implementation of a completely custom {APP_NAME_COMPOSE} application.

In case you haven't yet setup your {PRODUCT_NAME} instance, refer to the xref:devops-guide:index.adoc[DevOps guide].

== Authentication and Security Model

For *authentication*, {PRODUCT_NAME} implements the OAuth2 protocol, where {PRODUCT_NAME} can act both as an OAuth2 client or as a server.
Refer to the xref:authentication/index.adoc[authentication] section for details.
The login screen can be completely personalized to match your brand and to give your users a piece of mind when entering their credentials.
Refer to the xref:personalization/auth.adoc[menu:personalization[authentication]] section for details.

[TIP]
====
It may be a good idea to include your brand graphics where your {PRODUCT_NAME} instance will be accessed by external users.
====

For *access control*, {PRODUCT_NAME} implements a https://en.wikipedia.org/wiki/Role-based_access_control[RBAC facility] which allows you to fine tune access permissions to your needs.
Refer to the xref:security-model/index.adoc[] section for details.

== Internationalization

{PRODUCT_NAME} allows you to fully translate most aspect of the system.

Refer to the xref:i18n/static.adoc[] page to learn how to translate the user interface.

Refer to the xref:i18n/resource.adoc[] page to learn how to translate your {PRODUCT_NAME} {APP_NAME_COMPOSE} apps.

== Access {PRODUCT_NAME} via the API

{PRODUCT_NAME} is API-centric, meaning that everything can be done via an API endpoint.
Refer to the xref:accessing-corteza/index.adoc[accessing {PRODUCT_NAME}] sections for details regarding to xref:accessing-corteza/index.adoc#authentication[authentication], xref:accessing-corteza/index.adoc#api-endpoints[API endpoints], xref:accessing-corteza/index.adoc#response-format[data format], and the xref:accessing-corteza/ql.adoc[query language].

If you wish to connect an external application with {PRODUCT_NAME} in order to exchange data, you are able to do so by using our xref:accessing-corteza/api-clients.adoc[Node.js API clients].

== Creating a Custom {APP_NAME_COMPOSE} App

Refer to the xref:compose-configuration/index.adoc[{APP_NAME_COMPOSE} configuration] page to learn how you can configure your own {APP_NAME_COMPOSE} app.
For additional details, refer to xref:compose-configuration/field-types.adoc[menu:{APP_NAME_COMPOSE} configuration[field type reference]] for a reference of available field types and xref:compose-configuration/page-blocks.adoc[menu:{APP_NAME_COMPOSE} configuration[page block reference]] for a reference of available page blocks.

Refer to the xref:api-gw/index.adoc[] page to learn how you can define custom webhook endpoints external services can use.

Refer to the xref:reporting/index.adoc[] page to learn how you can create custom reports to visualize the data of your {APP_NAME_COMPOSE}.

== Automating your process

{PRODUCT_NAME} provides a powerful automation facility that allows you to implement nearly anything!
Automation is defined either via xref:automation/workflows/index.adoc[workflows (menu:automation[workflow])] or xref:automation/automation-scripts/index.adoc[automation scripts (menu:automation[automation script])].

A *workflow* is a simplified BPMN diagram, which allows you to describe the automation in a user-friendly manner.
A workflow is the recommended way of implementing an automation.
Workflows are easier to read and maintain.

An *automation script* is a piece of JavaScript code that performs a desired operation.

[CAUTION]
====
When the automation requires multiple complex operations that are not originally supported by the workflow engine, an automation script is a better choice.
====

== {PRODUCT_NAME} {APP_NAME_DISCOVERY}

{PRODUCT_NAME} {APP_NAME_DISCOVERY} provides a powerful search engine to interact with your data.
{PRODUCT_NAME} {APP_NAME_DISCOVERY} defines an intuitive interface to search and, for some cases, visualize the data such as geographical metadata.

Refer to xref:discovery/index.adoc[] page to learn how to configure and use {PRODUCT_NAME} {APP_NAME_DISCOVERY}

== Creating custom documents

[IMPORTANT]
====
To enable PDF document rendering, you will need to run the https://thecodingmachine.github.io/gotenberg/[gotenberg] Docker container.

Refer to the xref:devops-guide:pdf-renderer.adoc[DevOps guide] for details on how to set it up.
====

{PRODUCT_NAME} defines a flexible template facility, which allows you to design custom documents (such as marketing emails and PDF quotes) that you send to your contacts.
The template facility currently supports *PDF*, *HTML*, and *plain text* formats.

Refer to the xref:templates/index.adoc[templates] section to overview the process of defining a template and rendering a document.

[TIP]
====
You can request document rendering from external applications via the REST API.

*DevNote* add a reference to the endpoint.
====

== {PRODUCT_NAME} Federation

{PRODUCT_NAME} {APP_NAME_FEDERATION} enables different {PRODUCT_NAME} instances to establish a federated network to freely and securely exchange information.

Refer to the xref:federation/index.adoc[] page to learn how to configure and use {PRODUCT_NAME} Federation.

== Troubleshooting

Get in touch with us on our https://forum.{DOMAIN}[forum].
Any feedback, questions or suggestions are always welcome!
