include::../../../variables.adoc[]

[#admin-adminpanel-messaging-permissions]
= Permissions

The permissions interface can be accessed by clicking on the "Permissions" navigation item on the left navigation drawer under the messaging item group.

The interface allows you to define permissions for core messaging resources, such as access to {PRODUCT_NAME} {APP_NAME_MESSAGING}, creating public channels, joining channels and so on.

[IMPORTANT]
====
To define fine grained access control for specific resources, such as modules and pages, see ...
====

The interface is devised to the following sections:

Messaging service::
    The section allows you to control overall access and usage of {PRODUCT_NAME} {APP_NAME_MESSAGING} (see <<admin-adminpanel-messaging-permissions-messaging>>),

Channels::
    The section allows you to control {PRODUCT_NAME} {APP_NAME_MESSAGING} channel related access (see <<admin-adminpanel-messaging-permissions-channel>>),

[#admin-adminpanel-messaging-permissions-messaging]
== Messaging service permissions

Access to messaging::
    Determines if the role is allowed to access {PRODUCT_NAME} {APP_NAME_MESSAGING},

Grant permissions on messaging service::
    Determines if the role is allowed to grant permissions on {PRODUCT_NAME} {APP_NAME_MESSAGING},

Access all settings::
    Determines if the role is allowed to access any {PRODUCT_NAME} {APP_NAME_MESSAGING} setting,

Manage all settings::
    Determines if the role is allowed to manage any {PRODUCT_NAME} {APP_NAME_MESSAGING} setting,

Create public channels::
    Determines if the role is allowed to create public {PRODUCT_NAME} {APP_NAME_MESSAGING} channels,

Create private channels::
    Determines if the role is allowed to create private {PRODUCT_NAME} {APP_NAME_MESSAGING} channels,

Create direct messages and group channels::
    Determines if the role is allowed to create direct {PRODUCT_NAME} {APP_NAME_MESSAGING} channels to a specific user or a set of,

[#admin-adminpanel-messaging-permissions-channel]
== Channels permissions

Update any channel::
    Determines if the role is allowed to update any {PRODUCT_NAME} {APP_NAME_MESSAGING} channel,

View any channel::
    Determines if the role is allowed to access any {PRODUCT_NAME} {APP_NAME_MESSAGING} channel,

Join any channel::
    Determines if the role is allowed to join any {PRODUCT_NAME} {APP_NAME_MESSAGING} channel,

Leave any channel::
    Determines if the role is allowed to leave any {PRODUCT_NAME} {APP_NAME_MESSAGING} channel,

Delete any channel::
    Determines if the role is allowed to delete any {PRODUCT_NAME} {APP_NAME_MESSAGING} channel,

Undelete any channel::
    Determines if the role is allowed to undelete (restore) any {PRODUCT_NAME} {APP_NAME_MESSAGING} channel,

Archive any channel::
    Determines if the role is allowed to archive any {PRODUCT_NAME} {APP_NAME_MESSAGING} channel,

Unarchive any channel::
    Determines if the role is allowed to unarchive any {PRODUCT_NAME} {APP_NAME_MESSAGING} channel,

Manage members on any channel::
    Determines if the role is allowed to add or remove any {PRODUCT_NAME} {APP_NAME_MESSAGING} channel members,

Manage attachments on any channel::
    Determines if the role is allowed to manage attachments of any {PRODUCT_NAME} {APP_NAME_MESSAGING} channel,

Message sending on any channel::
    Determines if the role is allowed to send massages to any {PRODUCT_NAME} {APP_NAME_MESSAGING} channel,

Reply to messages on any channel::
    Determines if the role is allowed to reply (create threads) to any {PRODUCT_NAME} {APP_NAME_MESSAGING} channel message,

Embedding in messages on any channel::
    Determines if the role is allowed to embed external resources to any {PRODUCT_NAME} {APP_NAME_MESSAGING} channel message,

File attaching on any channel::
    Determines if the role is allowed to upload files (attachments) to any {PRODUCT_NAME} {APP_NAME_MESSAGING} channel,

Update own messages on any channel::
    Determines if the role is allowed to update own messages of any {PRODUCT_NAME} {APP_NAME_MESSAGING} channel,

Update any message on any channel::
    Determines if the role is allowed to update any message or any {PRODUCT_NAME} {APP_NAME_MESSAGING} channel,

Delete own messages on any channel::
    Determines if the role is allowed to delete own messages of any {PRODUCT_NAME} {APP_NAME_MESSAGING} channel,

Delete any message on any channel::
    Determines if the role is allowed to delete any message of any {PRODUCT_NAME} {APP_NAME_MESSAGING} channel,

React on messages on any channel::
    Determines if the role is allowed to add reactions to any message of any {PRODUCT_NAME} {APP_NAME_MESSAGING} channel,
