include::../../../../variables.adoc[]

[#admin-compose-pages]
= Pages

{PRODUCT_NAME} {APP_NAME_COMPOSE} provide a graphic user interface to access the data contained within the given namespace.
Each page consists of a series of page blocks that allow you to construct pages of arbitrary complexity while assuring each page is responsive and mobile friendly.

There are two types of pages:

* <<admin-compose-page-record>>,
* <<admin-compose-page-list>>.

Pages are available under the "Pages" sub administration page.
Pages are represented in a tree view, that allows you to change their order and even their nesting.
This allows unlimited flexibility when defining your namespace.

[#admin-compose-page-record]
== Record pages

A record page is designed to show information regarding a specific record, such as it's field values and other related records.
In order for a module to be accessible to the user, it must have an associated record page.

You can define a record page for the given module by pressing the "Page builder" button next to the module you wish to use.
This will open up a new editor.
Please refer to <<admin-compose-pages-build>> for details on the page building process.

[#admin-compose-page-list]
== List pages

List pages are not related to any specific record; rather, they are designed to show multiple record lists, charts, notes, calendars and so on and so forth.
With list pages we can create a home page, a dashboard, a list of contacts, etc.

To create a List page, you need to go to the "Pages" administrative page and enter a title in the Create a new page box at the top.
When you submit this form, it opens the Edit page form, which allows you to add a page description (for internal use; the end user will not see it), and you can set the page to "Visible" so it can be accessed.

The actual page editor can be accessed via the "Page builder" button either on the page editor or on the page tree view.

[#admin-compose-page-builder]
== Page builder

Page's content is defined as a grid consisting spanning over 12 columns.
The content is defined by a series of page blocks that helps maintain responsive and mobile-friendly pages.

Page blocks can be added using the "Add block" button on the bottom toolbar.
This opens a modal window where you can select the page block type you wish to use (refer to <<admin-compose-page-blocks>> for details on page blocks).

Once added, they can be arranged, resized and moved with an intuitive drag and drop style interface.
Blocks can be edited by clicking on the edit icon or deleted by pressing the trash can icon on the bottom left corner of the page block.

Once finished, press the "Save" or the "Save and close" button on the bottom right of the toolbar.
To revert the changes, press the "Back (without saving changes) button".

[#admin-compose-page-blocks]
== Page blocks

include::./page-blocks/index.adoc[]
