:PRODUCT_NAME: Corteza
:WORKFLOW-DIR: ../../../../src/modules/integrator-guide/pages/workflows
:WORKFLOW-IMAGE-DIR: ../../../../src/modules/integrator-guide/images/workflow

=== What is workflow?

**Corteza Low Code** is the flexible and easy to use open source Low Code Development platform for custom web based business applications, with drag and drop builder features, integrated Identity, Access and Privacy Management, and powerful automation options aka **workflow**.
Corteza CRM is based on Low Code.

A workflow can help you maintain and expand on larger projects.
Here is https://docs.cortezaproject.org/corteza-docs/2021.3/integrator-guide/workflows/style-guide-best-practices.html[style guide and best practices].

=== Where do I start?

==== Tour of workflow inside https://github.com/cortezaproject/corteza-server[corteza-server]

1. `/automation`: It has workflow CRUD, core logic for workflow along with REST api.
2. `/*/automation`: It has automation functions, types for corresponding module.
3. `/pkg/wfexec`: It is execution layer for workflow, also with generic types etc.

==== Create your first workflow

To set up corteza server with workflow webapp in dev environment follow these steps:

1. Make sure you have cloned https://github.com/cortezaproject/corteza-server[corteza-server], Ignore this go to 2 point if you have already done this.
2. Now we need webapp for workflow, so open terminal and go to directory where corteza server is cloned and run `make webapp VERSION={0000.0.0}` command to in webapp inside `/webapp` directory
3. Assuming above steps are done, then you can watch corteza server using `make watch` and go to browser run `{domain}/workflow` to run webapp for workflow
4. All set, now you can create workflow by clicking on **New Workflow** button from workflow home page.
+
> Additional step to set up corteza web apps locally
5. clone https://github.com/cortezaproject/corteza-js.git[corteza-js]
* Open terminal and go to directory where corteza-vue is cloned and run `yarn install`, `yarn build`
* To use this as package run `yarn link` will return output like below, later you can use `yarn link "@cortezaproject/corteza-vue"` to link this package in other projects.
+
-----------------
yarn link v1.00.00
success Registered "@cortezaproject/corteza-js".
info You can now run `yarn link "@cortezaproject/corteza-js"` in the projects where you want to use this package and it will be used instead.
Done in 0.02s.
-----------------

6. Follow step 5 for https://github.com/cortezaproject/corteza-vue.git[corteza-vue].
* Additionally, link `corteza-js` package to `corteza-vue`.

7. Follow step 5 for https://github.com/cortezaproject/corteza-webapp-compose.git[corteza-webapp-compose].
* Make sure to link both `corteza-js` and `corteza-vue` to `corteza-webapp-compose`
* Now we must set config inside `corteza-webapp-compose/public/config.js`(for reference checkout config.example.js).
+
----------
// CortezaAuth can be autoconfigured by replacing /api with /auth in CortezaAPI or by appending /auth to the end of CortezaAPI string
// When this is not possible and your configuration is more exotic you can set it
// explicitly:
// window.CortezaAuth = '{HOST:PORT}/api'
----------

[NOTE]
====
Make sure VERSION for webapp and corteza server are same, to prevent any compatibility errors.
====

=== Concepts

==== Workflow

Workflow is graphically designed by connecting steps found in the toolbox.
It is the glue that tie together these active elements.
It allows you to implement custom business logic without the need for any programming knowledge.

Refer to xref:{WORKFLOW-DIR}/index.adoc[Workflow integration guide] for more details.

==== Trigger

A *trigger* image:{WORKFLOW-IMAGE-DIR}/trigger.svg[width=20px] defines when the workflow starts and what steps the workflow execution should perform.

[NOTE]
====
A single workflow can have multiple triggers.
Multiple triggers allow you to define fewer workflows for different events.

Refer `automation/service` inside corteza server for trigger.
====

Refer to xref:{WORKFLOW-DIR}/index.adoc#step-exec-triggers[Trigger] for more details.

==== Sessions

Sessions are a simple way to store data for individual users against unique session ID. This can be used to persist information between page request.
In workflow, whenever we define a new workflow, It will be stored into session along with respected data store so once user action either trigger the workflow exection
or any certain point of time if there is delayed execution can be performed based on session state, along with pending prompts for user.

Refer to following for more insight on session at different layer inside corteza-serve.

* `automation/service/session.go` and `automation/service/session_actions.yaml`: session implementation for workflow automation
* `store/automation_sessions.yaml`: rdbms layer for workflow session
* `pkg/wfexec/session.go`: session at execution layer for workflow automation

==== Delays
A *delay step* image:{WORKFLOW-IMAGE-DIR}/delay.svg[width=20px] allows you to explicitly pause the workflows' execution for a set period of time.

Refer to xref:{WORKFLOW-DIR}/delaying-scheduling.adoc[Delaying and scheduling] for more details.

[#prompts]
==== Prompts
The *prompt step* image:{WORKFLOW-IMAGE-DIR}/prompt.svg[width=20px] allows you to interact with the user in order to provide additional confirmation or data, such as a recipient email address or filling in any missing parameters.

An *alert prompt* displays a notification to the receiving user.
This can be used to show success or other informative notifications.

A *choice prompt* displays a notification with two buttons to either confirm or reject something to the receiving user.
This can be used to request additional confirmation before performing an operation or to optionally perform additional operations.

A *single input prompt* displays a notification with a value input box to the receiving user.
This can be used to request additional information from the receiving user, such as missing contact data or their pin code.

An *option select prompt* displays a notification with a list of available options either as a select or a list of radio buttons.
This can be used as a more verbose choice prompt, or a more constrained input prompt.

==== Step types

- Expressions:
+
An *expression step* image:{WORKFLOW-IMAGE-DIR}/expressions.svg[width=20px] initialize, modify and manipulate variables.
+
Refer to xref:{WORKFLOW-DIR}/index.adoc#expressions[Expressions] for more details.

- Functions
+
A *function step* image:{WORKFLOW-IMAGE-DIR}/function.svg[width=20px] defines what operation should be performed.
+
There are predefined function and also we can add user defined functions. In order to do that,

1. Define function along with required values like meta, label, params, results in `/*/automation/*.yaml`.
2. Run the `make codegen` then implement the function inside corresponding `*.go` file.
3. Restart the server, you can use that function by selecting it from function type dropdown.
+
Rest Endpoint to get available workflow functions is `/functions/`.

+
Refer to xref:{WORKFLOW-DIR}//index.adoc#functions[Functions] for more details.

- Iterators:
+
An *iterator step* image:{WORKFLOW-IMAGE-DIR}/iterator.svg[width=20px] allows you to sequentially process a series of items one after another.
+
Refer to xref:{WORKFLOW-DIR}//scope-in-depth.adoc#processing-multiple-items[Iterators] for more details.

* Controlling iterator execution
** Continue
+
Refer to xref:{WORKFLOW-DIR}//index.adoc#step-iterator-control-continue[Continue] for more details.

** Break
+
Refer to xref:{WORKFLOW-DIR}//index.adoc#step-iterator-control-break[Break] for more details.

- Error Handling
+
Refer to xref:{WORKFLOW-DIR}//index.adoc#working-with-errors[Error Handling] for more details.

- Gateway
+
A *gateway step* allows you to implement conditional execution based on the ongoing state of your workflow, for example, if a current user is already a subscriber, we should send a renewal request instead of a subscription request.
+
There are three kinds of gateway steps,

. An *Exclusive* image:{WORKFLOW-IMAGE-DIR}/gatewayExclusive.svg[width=20px] that can return exactly one path.
. An *Inclusive* image:{WORKFLOW-IMAGE-DIR}/gatewayInclusive.svg[width=20px] that can return one or more paths.
. A *Fork* image:{WORKFLOW-IMAGE-DIR}/gatewayParallel.svg[width=20px] determines all possible fork paths.

It is part of `pkg/wfexec` internals.

=== Interaction with clients/Frontend applications
Corteza Frontend application uses rest interface and websocket to communicate with corteza-server.
The frontend will, for example, send entered data to the backend. The backend might then again validate that data (since frontend code can be tricked) and finally store it in some database

Earlier we learned about **Prompt**, for example, we define workflow which sends prompt to user based on some user action with help of websocket connection to send pending prompt to user.

* Prompts are part of session rest interface. Rest endpoint to get list of prompts is `/sessions/prompts`.

==== Websocket implementation
When user login into any of the corteza web application, FE will authenticate user with auth server, then we will have JWT token for that particular session.
Now we will use `{HOST:PORT}/api/websocket` also open connection to websocket for that user, and will send first message to server with JWT token to authenticate websocket connection.
Once it authenticates, server will have in-memory session for the user using that session.

* Refer to `pkg/websocket` package inside corteza-server for more details on server side implementation.
* Websocket is also used for sending reminder to user. reminder are alert, will be displayed based on reminder timing set by user.

=== Testing and debugging
Refer to xref:{WORKFLOW-DIR}/testing-debugging.adoc[Testing and debugging workflows] for more details.

== Related projects
. https://github.com/cortezaproject/corteza-server[Corteza Server]
. https://github.com/cortezaproject/corteza-webapp-workflow[Workflow webapp]
. https://github.com/cortezaproject/corteza-webapp-compose[Compose webapp]
