include::ROOT:partial$variables.adoc[]

= Platform Developer Guide

The *platform developer guide* is designed for *core {PRODUCT_NAME} maintainers* and *our contributors*.
If you wish to *develop applications* using {PRODUCT_NAME}, refer to the xref:ROOT:integrator-guide/index.adoc[*low-code platform developer guide*].

Use this guide as a reference when *adding new*, or *maintaining features*.

[IMPORTANT]
====
The platform developer guide covers the _high-level_ of the low-level -- the idea behind specific features, how you can add something for example.

The documentation *compliments the source code*.
====

Build pipeline::
    Refer to the xref:ROOT:developer-guide/building.adoc[*build pipelines*] section for an overview on how we *compile our sources*.

Release cycle::
    The xref:ROOT:developer-guide/release-cycle/index.adoc[*release cycle*] covers the *process of releasing* a new {PRODUCT_NAME} version.

Documentation::
    The xref:ROOT:developer-guide/documentation/index.adoc[*documentation*] section covers documentation related bits, such as xref:ROOT:developer-guide/documentation/index.adoc#documentation-rules[*contribution rules*], xref:ROOT:developer-guide/documentation/index.adoc#documentation-conventions[*conventions*], and xref:ROOT:developer-guide/documentation/index.adoc#documentation-writing-guidelines[*guidelines*].

Features::
    Refer to the main navigation for the complete list of documented features.
