include::../variables.adoc[]

= Terminology

Extension::
    A collection of automation scripts, corresponding libraries and other assets,

Script or Automation Script::
    Combination of automation triggers, meta data and the code it self,

Client scripts::
    Automation scripts executed within a client's browser,

Server scripts::
    Automation scripts executed inside the {APP_AUTOMATION} server,

Triggers or Automation Triggers::
    A set of rules, constraints and options to define when, where and how an automation script is executed,

Resource Type::
    Defines the resource that this automation script was designed for.
    It also defines the input and output of the automation script,

Event Type::
    Defines what event causes this automation script to execute.
    For a full list of event types and availability based on the defined resource see @todo...

Trigger constraints::
    A set of constraints that must be truthy in order for the automation script to be available and executable,

Trigger weight::
    Allows us to specify the order of automation script execution for the given event,

User interface properties or UIProps::
    Determine front-end aspects of the automation script invocation component; such as placement, label and color,

Explicitly triggered or manual scripts::
    Automation scripts that are executed explicitly, such as a button press,

Implicitly triggered scripts::
    Automation scripts that are executed implicitly as a collateral to an event, such as record creation and form submission,

Deferred or scheduled scripts::
    Automation scripts that are executed at a specified time or on a configured interval,

Batch or iterator scripts::
    Automation scripts that are executed over a larger set of resources at the same time (used for batch processing).

Sink scripts::
    Automation scripts that are executed on HTTP requests and allow implementation of new endpoints,

Event bus::
    Event handling system inside client web applications and on the server,

UIHooks::
    Define a front-end components that is used to execute explicit (manual) automation scripts.
