include::../../variables.adoc[]

= Modules

Modules and fields exist inside your namespace.
(In programming terminology, they are "locally defined.")
Modules and fields define places where data is stored in your namespace.
Without modules and fields, your namespace has no memory nor anything to work with, so defining them is the next step when creating a new app.

== Enter the namespace's admin area

To enter the admin area of an namespace, you first need to open the namespace inside {PRODUCT_NAME} {APP_NAME_COMPOSE}.
Once inside, you'll see an Admin panel link on the right.
Click on it to enter the namespace's admin area. 

In the admin area there are four menu items:

* *Modules*: Create or edit modules and fields
* *Pages*: Define the visual part of your namespace
* *Charts*: Create charts to add to pages
* *Automation*: Add automation rules to automate business processes and workflows

The Public pages link takes you back to your namespace.

== Create modules and fields

Modules and fields define what data you need to store in your namespace and how that data links to other data.
If you've ever built a database before, this might feel familiar, but you don't need any database experience to work with {PRODUCT_NAME}.

=== Modules

A module is like a table in a database.
A simple namespace typically has a few modules, while bigger namespaces have many more.
{PRODUCT_NAME} CRM, for example, has over 35.
The number of modules an namespace can have is unlimited.

A new namespace does not have any modules.
You can create one by using the form on top or by importing an existing module from a different namespace using an export file. 
You can import and export individual modules or all modules at the same time.

When you create a module, best practice is to give it a descriptive name without spaces and using capital letters on different words, e.g., Lead, Account, or CaseUpdate.

=== Fields

Each module consists of a set of fields that define what data you want to store and in what format.

You can add new fields to a module by using the Add new field button.
 This adds a new row with the following fields:

* *Name*: It must be unique and cannot have spaces, e.g., "firstname." 
This is not shown to the end user.
* *Title*: This is the field's label—the field name the end users see when they view or edit a record.
It can contain any character, including spaces.
Although it's best practice to keep this title unique, it's not mandatory.
An example is "First name."
* *Type*: This is where you set the field type.
The wrench icon on the right allows you to set more detailed data for the field type.
* *Multiple values*: This checkbox is available when you want a field type to allow multiple value entries.
* *Required*: This makes the field mandatory for the end user when creating or editing a record.
* *Sensitive*: This allows you to mark data that is sensitive, such as name, email, or telephone number, so your namespace is compliant with privacy regulations such as the GDPR.

At the end of the row, you can find a Delete button (to remove a field) and a Permission button (to set read permissions and update field permissions per role).

=== Field types

You can select from the following field types.
The wrench icon beside the field type provides further options for each case.

* *Checkbox (Y/N)*: This field shows a checkbox to the end user when editing a record.
When you click on the wrench icon, you can select what checked and unchecked represent.
For example: Yes/No, Active/Inactive, etc.
* *DateTime*: This makes a date field. You can select:
** Date only
** Time only
** Past values only
** Future value only
** Output relative value (e.g., three days ago)
** Custom output format (see Moment.js for formatting options)
* *Email*: This field auto-validates whether the input is an email and turns it into a clickable email link in record-viewing mode.
You can select the Don't turn email into a link option to remove the auto-link feature.
* *Select*: When you click on the wrench icon, you can use the Add button to add as many Select options as you need.
You can also set whether the end user can select multiple values at once.
* *Number*: This field gives you the option to add a prefix (for example a $ for values in dollars), a suffix (for example % for a number that represents a percentage), and the decimal precision (e.g., zero for whole numbers or two for values like 1.13, 2.44, 3.98). 
You can use the Format Input field to create more complex formats.
* *Record*: This field allows you to link the current module to another module.
It will show as a Select to the end user.
You can select the module in the Module name field and choose the field to use to load the Select options.
In Query fields on search, you can define what fields you want the user to be able to search on.
As with the Select field type, you can set whether the user can select multiple values at once.
* *String*: By default, a String field is a single-line text-input field, but you can choose to make it multi-line or even a rich text editor.
* *URL*: The URL field automatically validates whether the field is a link to a site. You can select the following options for this field:
** Trim # from the URL
** Trim ? from the URL
** Only allow SSL (HTTPS) URLs
** Don't turn URL into a link
* *User*: This creates a Select field that loads with all users in {PRODUCT_NAME}.
You can preset the value to the current user.
* *File*: This creates a File Upload button for the end user.

