include::../../variables.adoc[]

= Resource Permissions

== All namespaces

In the main namespaces menu you can set the following permissions for all namespaces by clicking on the "lock" icon:

Read any namespace::
  Determines if the role is allowed to access any namespace,
Update any namespace::
  Determines if the role is allowed to update the parameters of any namespace,
Delete any namespace::
  Determines if the role is allowed to delete any namespace,
Manage any namespace::
  Determines if the role is allowed to access the administration section of any namespace,
Create modules under any namespace::
  Determines if the role is allowed to create modules under any namespace,
Create charts under any namespace::
  Determines if the role is allowed to create charts under any namespace,
Create pages under any namespace::
  Determines if the role is allowed to create pages under any namespace

[NOTE]
====
When setting "Manage any namespace" to deny; "Create modules under any namespace", "Create charts under any namespace" and "Create pages under any namespace" are also denied.
====

[TIP]
====
Want to remove access to all namespaces except for the one?
Set "Read any namespace" to "Deny" and set "Read namespace" for the desired namespace to "Allow".
====

== Single namespace

When you enter the edit page of a namespace (via the namespaces menu), you can click on the "lock" icon to set the permissions of a single namespace.
These settings overwrite the ones set in "All namespaces" and allow fine-grained control.

Read namespace "(namespace name)"::
  Determines if the role is allowed to access the given namespace,
Update namespace "(namespace name)"::
  Determines if the role is allowed to update the parameters of the given namespace,
Delete namespace "(namespace name)"::
  Determines if the role is allowed to delete the given namespace,
Manage namespace "(namespace name)"::
  Determines if the role is allowed to access the administration section of the given namespace,
Create modules under namespace "(namespace name)"::
  Determines if the role is allowed to create modules under the given namespace,
Create charts under namespace "(namespace name)"::
  Determines if the role is allowed to create charts under the given namespace,
Create pages under namespace "(namespace name)"::
  Determines if the role is allowed to create pages under the given namespace

== Permissions inside a namespace

After setting permission to an entire namespace, you can further define permissions inside a namespace for the following resources:

* Modules,
* Module fields,
* Pages,
* Chart.

This can be achieved by entering the adminstration area of the namespace.

=== Modules

==== All modules

On the "Modules" administration sub page, you can set permissions regarding any module in the given namespace.
Click on the "lock" icon on the top right corner.
You can set:

Read any module::
  Determines if the role is allowed to access any module,
Update any module::
  Determines if the role is allowed to update the properties of any module,
Delete any module::
  Determines if the role is allowed to delete any module,
Create record of any module::
  Determines if the role is allowed to create record entries for any module,
Read records of any module::
  Determines if the role is allowed to access the records of any module,
Update records of any module::
  Determines if the role is allowed to update the records of any module,
Delete records of any module::
  Determines if the role is allowed to delete the records of any module.

==== Single module

You can set permissions for a single module by clicking on the "lock" icon at the end of the module row.
The same interface can also be accessed inside the module editor, when pressing the "edit" icon.
The "lock" icon will be available on the top right corner.
You can set:

Read module "(module name)"::
  Determines if the role is allowed to access the given module,
Update module "(module name)"::
  Determines if the role is allowed to update the properties of the given module,
Delete module "(module name)"::
  Determines if the role is allowed to delete the given module,
Create record of module "(module name)"::
  Determines if the role is allowed to create record entries for the given module,
Read records of module "(module name)"::
  Determines if the role is allowed to access the records of the given module,
Update records of module "(module name)"::
  Determines if the role is allowed to update the records of the given module,
Delete records of module "(module name)"::
  Determines if the role is allowed to delete the records of the given module.

==== Module fields

Inside the module editor, you can define permissions for each module field.
You can set:

Read "(field name)" record fields::
  Determines if the role is allowed to access the given value inside the module.
  This will hide any data that might appear in the field,
Update "(field name)" record fields::
  Determines if the role is allowed to update the values in the given module field.
  This will prevent any data manipulation for the field.

[TIP]
====
You can implement read-only fields by setting their update permission to deny.
====

=== Pages

==== All pages

On the top you can click on the "lock" icon to set permissions for all pages.
You can set the following permissions:

Read any page::
    Determines if the role is allowed to access any page of the given namespace,
Update any page::
    Determines if the role is allowed to update any page of the given namespace,
Delete any page::
    Determines if the role is allowed to delete any page of the given namespace.

==== Single page

You can set permissions for a single page by clicking on the "lock" icon at the end of the row.
The same interface can also be accessed inside the page editor, when pressing the "edit" icon.
The "lock" icon will be available on the top right corner.
You can set:

Read any page::
    Determines if the role is allowed to access the page of the given namespace,
Update any page::
    Determines if the role is allowed to update the page of the given namespace,
Delete any page::
    Determines if the role is allowed to delete the page of the given namespace.

=== Charts

==== All charts

On the top you can click on the "lock" icon to set permissions for all charts.
You can set the following permissions:

Read any chart::
    Determines if the role is allowed to access any chart of the given namespace,
Update any chart::
    Determines if the role is allowed to update any chart of the given namespace,
Delete any chart::
    Determines if the role is allowed to delete any chart of the given namespace.

==== Single chart

You can set permissions for a single chart by clicking on the "lock" icon at the end of the row.
The same interface can also be accessed inside the chart editor, when pressing the "edit" icon.
The "lock" icon will be available on the top right corner.
You can set:

Read any chart "(chart name)"::
    Determines if the role is allowed to access the given chart,
Update any chart "(chart name)"::
    Determines if the role is allowed to update the given chart,
Delete any chart "(chart name)"::
    Determines if the role is allowed to delete the given chart.
