include::../../variables.adoc[]

[#documentation-conventions]
= Conventions

You can use all of the formatting and different components that AsciiDoc allows.
We do define some exceptions for better consistency when working with more flexible components.
The conventions listed below must be followed when contributing to any part of the documentation.

== Lists

Ordered lists::
  Ordered lists should be defined with the `.` instead of using actual numbers.
  For example:

[source,adoc]
----
. List point 1,
. list point 2.
----

Unordered lists::
  Unordered lists should be defined with the `*`.
  For example:

[source,adoc]
----
* List point 1,
* list point 2.
----

[IMPORTANT]
====
Use ordered/unordered lists only when the lines are relatively short.
If the list should provide detailed description, use the multi-line description block:

[source,adoc]
----
// Make the general outline outline the entire content of the description.
[General outline here]::
    [Description here].
----

For example:

[source,adoc]
----
== Product overview documentation

...

Product Overview::
    Describe what the product is and what it’s not...

Security::
    Provide a rough overview over the security system - users, roles, access control and so on...

Architecture::
    Outline all of the important components and what they are and/or could be used for...

...

----

====

== Code snippets

Short one-liners::
    When specifying short code snippets such as a CLI command use the single backtick (```),

Longer code snippets::
    Try to avoid long code snippets as much as possible unless when working on examples.
    Use the source code syntax `[source,{language here}]` blocked 4 dashes `----`.
    For example:

// Here, this one is an exception though
```
[source,adoc]
----
----
```

== Admonition

Use the admonition block syntax when wanting to create admonitions.
For example:

[source,adoc]
----
[IMPORTANT]
====
This is *very* important!
====
----

== Diagrams

Use the https://plantuml.com/[PlantUML] framework *for any* diagrams (unless there is an explicit reason why not).
This makes it easier on us to keep a consistent feel throughout the entire documentation.

[NOTE]
====
Move large diagrams into separate files to avoid clutter and unreadable source.
====

// Here, this one is also an exception
```
.Provide a good caption to summarize the *entire* diagram.
[plantuml,diagram-name-here,svg,role=diagram-name]
----
@startuml

... content here ...

@enduml
----
```

[TIP]
====
Larger diagrams can get a bit messy to understand what is going on, so do your best to group elements together, and use a nice comment to indicate it.
====

Diagram captions::
    A caption *must* be enough to give you enough understanding to know what is going on on the diagram.
    Make sure that the caption gives the reader enough insight to have an idea what they can expect to learn from the diagram.

[IMPORTANT]
====
We are quite strict in having 1 sentence per line to simplify history tracking.
Here, however, I am unable to figure out how/if this is possible.
You are free to inline all of your sentences when it comes to captions (for now).
====

Comments::
    A PlantUML comment starts with `'` (single line), or is enclosed between `/'`, and `'/`.
    We'll use the following notation to be consistent:

[source,adoc]
----
' ---------------
' Do a comment like this.
' Multiple lines are fine.
' ---------------
----

Diagram structure::
    You are free to use any diagram, and any component defined by the diagram.
    *Avoid* any extreme visual customization using *Skinparam*.

// @todo update this section
// 
// == Referencing

// Use this template to specify an explicit ID:
// [source,adoc]
// ----
// [#{{ documentation type }}:{{ nesting separated by ':' }}].
// ----

// For example, the Conventions section defines an explicit ID of:
// [source,adoc]
// ----
// [#developer-guide:documentation:conventions]
// ----

// To reference this ID, simply use:
// [source,adoc]
// ----
// <<{{ ID here }}>>
// ----

// for example:

// [source,adoc]
// ----
// <<developer-guide:documentation:conventions>>
// ----
