= Assigning a role

[NOTE]
When assigning a role to a user, note that both the role being assigned and the user must already exist. 

Refer to the documentation to xref:users/creating.adoc[create a user] and a xref:users/roles/assign.adoc[role] for help.

Role assignment: A subject can exercise permission only if the subject is assigned a role.

When assigning a role it is important to allocate enough access for employees to do their job.

[CAUTION]
====
In order for the role membership to reflect on the user, they need to re-login.
====

.To assign a role to an existing user:
. navigate to menu:system[users],
. click on the btn:[edit] icon next to the user you wish to edit,
. navigate to the "role membership" section and assign appropriate roles,

[NOTE]
====
Refer to xref:roles/index.adoc[Role Management] for more information regarding roles and access control.
====

[annotation,role="data-zoomable"]
----
{
  "image": {
    "rel": "access-control/user-edit.png",
    "alias": "admin-webapp-users-assign",
    "w": 1920,
    "h": 1080
  },
  "view": {
    "x": 321,
    "y": 0,
    "w": 1599,
    "h": 1080
  },
  "focus": {
    "x": 586,
    "y": 557,
    "w": 1069,
    "h": 195
  },
  "annotations": []
}
----
. press the btn:[submit] button.
